import { createHash } from 'node:crypto';
import { whiteboardImport as C } from '@repo/contracts';
import { mapImportedBoard } from '@repo/whiteboard-core';
import type { Principal } from '../../domain/principal';
import { ObjectExistsError, type ObjectStore } from '../artifact/ports';
import type { WhiteboardRepository } from './ports';
import type { WhiteboardCollaborationStore } from './collaboration-ports';
import { parseWhiteboardImport, UnsafeWhiteboardImport } from './import-parser';

export const WHITEBOARD_IMPORT_SERVICE=Symbol('WhiteboardImportService');
export type ImportStatus=ReturnType<typeof C.WhiteboardImportStatus.parse>;
export type ImportReport=ReturnType<typeof C.WhiteboardImportReport.parse>;
export interface WhiteboardImportRecord extends ImportStatus { sourceObjectKey:string; actorId:string; report:ImportReport|null; executeRequestId:string|null; executeRequestHash:string|null; completedEpoch:number|null; completedSeq:number|null; }
export interface WhiteboardImportRepository {
  create(principal:Principal,record:WhiteboardImportRecord):Promise<{record:WhiteboardImportRecord;replayed:boolean;conflict:boolean}>;
  get(principal:Principal,boardId:string,importId:string):Promise<WhiteboardImportRecord|null>;
  savePreflight(principal:Principal,record:WhiteboardImportRecord,requestId:string,report:ImportReport):Promise<WhiteboardImportRecord>;
  claimExecution(principal:Principal,record:WhiteboardImportRecord,input:{requestId:string;requestHash:string}):Promise<{record:WhiteboardImportRecord;conflict:boolean}>;
  releaseExecution(principal:Principal,record:WhiteboardImportRecord,input:{requestId:string;requestHash:string}):Promise<void>;
  complete(principal:Principal,record:WhiteboardImportRecord,input:{requestId:string;requestHash:string;epoch:number;seq:number;report:ImportReport;assetRefs:Array<{objectKey:string;contentHash:string;byteSize:number}>}):Promise<WhiteboardImportRecord>;
}
export class WhiteboardImportError extends Error { constructor(readonly code:C.WhiteboardImportFailure){super(code);this.name='WhiteboardImportError';} }
const hash=(bytes:Uint8Array|string)=>createHash('sha256').update(bytes).digest('hex');
const status=(record:WhiteboardImportRecord):ImportStatus=>C.WhiteboardImportStatus.parse({importId:record.importId,boardId:record.boardId,source:record.source,sourceBoardId:record.sourceBoardId,sourceRevision:record.sourceRevision,fileName:record.fileName,mimeType:record.mimeType,sizeBytes:record.sizeBytes,sha256:record.sha256,stage:record.stage,counts:record.counts,createdAt:record.createdAt,updatedAt:record.updatedAt});
const sourceImportId=(source:string,boardId:string,revision:string)=>{const value=hash(`${source}\0${boardId}\0${revision}`);return`${value.slice(0,8)}-${value.slice(8,12)}-5${value.slice(13,16)}-a${value.slice(17,20)}-${value.slice(20,32)}`;};

export class WhiteboardImportService {
  constructor(private readonly boards:WhiteboardRepository,private readonly imports:WhiteboardImportRepository,private readonly collaboration:WhiteboardCollaborationStore,private readonly objects:Pick<ObjectStore,'putOnce'|'get'|'head'>,private readonly now:()=>Date=()=>new Date()){}
  private async access(principal:Principal,boardId:string){const board=await this.boards.get(principal,boardId);if(!board)throw new WhiteboardImportError('NOT_FOUND');if(board.role==='viewer')throw new WhiteboardImportError('FORBIDDEN');if(board.archived)throw new WhiteboardImportError('ARCHIVED');return board;}
  private prefix(principal:Principal,boardId:string){return`whiteboards/tenants/${hash(principal.orgId).slice(0,32)}/boards/${boardId}`;}
  private decode(value:string):Uint8Array{if(!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value))throw new WhiteboardImportError('INVALID_UPLOAD');return new Uint8Array(Buffer.from(value,'base64'));}
  private async putVerified(key:string,bytes:Uint8Array,mime:string){try{await this.objects.putOnce(key,bytes,mime);}catch(error){if(!(error instanceof ObjectExistsError))throw new WhiteboardImportError('DEPENDENCY_UNAVAILABLE');}let body:Uint8Array|null,head:{sizeBytes:number;mime:string}|null;try{[body,head]=await Promise.all([this.objects.get(key),this.objects.head(key)]);}catch{throw new WhiteboardImportError('DEPENDENCY_UNAVAILABLE');}if(!body||!head||body.byteLength!==bytes.byteLength||head.sizeBytes!==bytes.byteLength||hash(body)!==hash(bytes))throw new WhiteboardImportError('INTEGRITY_FAILED');}
  private async source(principal:Principal,record:WhiteboardImportRecord){if(!record.sourceObjectKey.startsWith(`${this.prefix(principal,record.boardId)}/imports/${record.importId}/`))throw new WhiteboardImportError('INTEGRITY_FAILED');let bytes:Uint8Array|null;try{bytes=await this.objects.get(record.sourceObjectKey);}catch{throw new WhiteboardImportError('DEPENDENCY_UNAVAILABLE');}if(!bytes||bytes.byteLength!==record.sizeBytes||hash(bytes)!==record.sha256)throw new WhiteboardImportError('INTEGRITY_FAILED');return bytes;}
  async upload(principal:Principal,boardId:string,input:unknown):Promise<ImportStatus>{await this.access(principal,boardId);const parsed=C.UploadWhiteboardImport.parse(input),bytes=this.decode(parsed.contentBase64);if(bytes.byteLength!==parsed.sizeBytes||hash(bytes)!==parsed.sha256)throw new WhiteboardImportError('INVALID_UPLOAD');const importId=sourceImportId(parsed.source,parsed.sourceBoardId,parsed.sourceRevision),key=`${this.prefix(principal,boardId)}/imports/${importId}/source/${parsed.sha256}`;await this.putVerified(key,bytes,parsed.mimeType);const now=this.now().toISOString(),record:WhiteboardImportRecord={importId,boardId,source:parsed.source,sourceBoardId:parsed.sourceBoardId,sourceRevision:parsed.sourceRevision,fileName:parsed.fileName,mimeType:parsed.mimeType,sizeBytes:parsed.sizeBytes,sha256:parsed.sha256,stage:'uploaded',counts:null,createdAt:now,updatedAt:now,sourceObjectKey:key,actorId:principal.userId,report:null,executeRequestId:null,executeRequestHash:null,completedEpoch:null,completedSeq:null};const saved=await this.imports.create(principal,record);if(saved.conflict)throw new WhiteboardImportError('IDEMPOTENCY_CONFLICT');return status(saved.record);}
  private report(record:WhiteboardImportRecord,mapped:ReturnType<typeof mapImportedBoard>,skipped:string[]):ImportReport{return C.WhiteboardImportReport.parse({importId:record.importId,counts:{discovered:mapped.discovered,accepted:mapped.accepted,unsupported:mapped.unsupported,assets:mapped.assets},issues:[...mapped.issues,...skipped.slice(0,Math.max(0,C.WHITEBOARD_IMPORT_LIMITS.issues-mapped.issues.length)).map(path=>({code:'FILE_SKIPPED' as const,sourceId:null,sourceType:null,detail:`Unsupported archive entry ${path}`}))],items:mapped.outcomes,exportFormat:'workspacex.whiteboard-import-report.v1',executable:mapped.commands.length>0});}
  private async prepare(principal:Principal,record:WhiteboardImportRecord,storeAssets:boolean){const bytes=await this.source(principal,record);let parsed;try{parsed=await parseWhiteboardImport(bytes,record.mimeType,record.source);}catch(error){if(error instanceof UnsafeWhiteboardImport)throw new WhiteboardImportError(error.code);throw error;}const assetRefs:Array<{objectKey:string;contentHash:string;byteSize:number}>=[];if(storeAssets){const refs=new Map<string,string>();for(const asset of parsed.assets){const digest=hash(asset.bytes),key=`${this.prefix(principal,record.boardId)}/imports/${record.importId}/assets/${digest}`;await this.putVerified(key,asset.bytes,asset.mime);refs.set(asset.path,key);assetRefs.push({objectKey:key,contentHash:digest,byteSize:asset.bytes.byteLength});}for(const item of parsed.items)if(item.assetRef)item.assetRef=refs.get(item.assetRef)??null;}const mapped=mapImportedBoard(record.source,record.importId,parsed.items,C.WHITEBOARD_IMPORT_LIMITS.objects);return{mapped,assetRefs,report:this.report(record,mapped,parsed.skipped)};}
  async preflight(principal:Principal,boardId:string,importId:string,input:unknown):Promise<ImportReport>{await this.access(principal,boardId);const action=C.WhiteboardImportAction.parse(input),record=await this.imports.get(principal,boardId,importId);if(!record)throw new WhiteboardImportError('NOT_FOUND');if(record.report&&record.stage!=='uploaded')return record.report;const prepared=await this.prepare(principal,record,false);await this.imports.savePreflight(principal,record,action.requestId,prepared.report);return prepared.report;}
  async execute(principal:Principal,boardId:string,importId:string,input:unknown){await this.access(principal,boardId);const action=C.ExecuteWhiteboardImport.parse(input);let record=await this.imports.get(principal,boardId,importId);if(!record)throw new WhiteboardImportError('NOT_FOUND');const requestHash=hash(JSON.stringify({importId,expectedEpoch:action.expectedEpoch}));if(record.executeRequestId){if(record.executeRequestId!==action.requestId||record.executeRequestHash!==requestHash)throw new WhiteboardImportError('IDEMPOTENCY_CONFLICT');if(record.completedEpoch!==null&&record.completedSeq!==null&&record.report)return{status:status(record),report:record.report,epoch:record.completedEpoch,seq:record.completedSeq,replayed:true};}else{const claimed=await this.imports.claimExecution(principal,record,{requestId:action.requestId,requestHash});if(claimed.conflict)throw new WhiteboardImportError('IDEMPOTENCY_CONFLICT');record=claimed.record;}const prepared=await this.prepare(principal,record,true);if(!prepared.report.executable)throw new WhiteboardImportError('UNSUPPORTED_FORMAT');let ack;try{ack=await this.collaboration.writeCommands(principal,boardId,{epoch:action.expectedEpoch,requestId:action.requestId,commands:prepared.mapped.commands});}catch(error){const code=(error as{code?:string}).code;if(code==='STALE_EPOCH'){await this.imports.releaseExecution(principal,record,{requestId:action.requestId,requestHash});throw new WhiteboardImportError('STALE_HEAD');}if(code==='IDEMPOTENCY_CONFLICT')throw new WhiteboardImportError('IDEMPOTENCY_CONFLICT');throw error;}const completed=await this.imports.complete(principal,record,{requestId:action.requestId,requestHash,epoch:ack.epoch,seq:ack.seq,report:prepared.report,assetRefs:prepared.assetRefs});return{status:status(completed),report:prepared.report,epoch:ack.epoch,seq:ack.seq,replayed:ack.replayed};}
  async getStatus(principal:Principal,boardId:string,importId:string){await this.access(principal,boardId);const record=await this.imports.get(principal,boardId,importId);if(!record)throw new WhiteboardImportError('NOT_FOUND');return status(record);}
  async getReport(principal:Principal,boardId:string,importId:string){await this.access(principal,boardId);const record=await this.imports.get(principal,boardId,importId);if(!record||!record.report)throw new WhiteboardImportError('NOT_FOUND');return record.report;}
}
