import type {PublishedAgentReader} from '../chat/message-command-ports';
import {createHash,randomUUID} from 'node:crypto';import * as Y from 'yjs';
import type {WhiteboardCommand,WhiteboardObject} from '@repo/contracts/whiteboard-document';
import {WhiteboardAIProposal,WhiteboardAIProposalCreate,WhiteboardAIProposalDecision,type WhiteboardAIProposal as Proposal} from '@repo/contracts/whiteboard-operation';
import {digestWhiteboardObject,readObjects} from '@repo/whiteboard-core';
import type {Principal} from '../../domain/principal';import type {DatabasePort,TenantSession} from '../ports/database.port';import type {WhiteboardCollaborationStore} from './collaboration-ports';import type {WhiteboardOperationAuditRepository} from './operation-ports';import type {WhiteboardProposalRepository} from './proposal-ports';import {WhiteboardOperationError,WhiteboardOperationService} from './operation-service';
export const WHITEBOARD_PROPOSAL_SERVICE=Symbol('WhiteboardProposalService');
const canonical=(v:unknown):string=>Array.isArray(v)?`[${v.map(canonical)}]`:v&&typeof v==='object'?`{${Object.entries(v as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`)}}`:JSON.stringify(v);const hash=(v:unknown)=>createHash('sha256').update(canonical(v)).digest('hex');
export function inverse(commands:readonly WhiteboardCommand[],objects:Map<string,WhiteboardObject>):WhiteboardCommand[]{return[...commands].reverse().map(command=>{if(command.type==='create')return{type:'delete',id:command.object.id};if(command.type==='restore')return{type:'delete',id:command.id};const prior=objects.get(command.id);if(!prior)throw new WhiteboardOperationError('NOT_FOUND');if(command.type==='delete')return{type:'restore',id:command.id};if(command.type==='geometry')return{type:'geometry',id:command.id,geometry:prior.geometry};if(command.type==='style')return{type:'style',id:command.id,style:prior.style};if(command.type==='parent')return{type:'parent',id:command.id,parentId:prior.parentId,orderKey:prior.orderKey};if(command.type==='state')return{type:'state',id:command.id,locked:prior.locked,zIndex:prior.zIndex};if(command.type==='extension')return{type:'extension',id:command.id,extensionData:prior.extensionData??null};if(command.type==='connector')return{type:'connector',id:command.id,connector:prior.connector!};return{type:'text',id:command.id,index:command.index,deleteCount:command.insert.length,insert:prior.text.slice(command.index,command.index+command.deleteCount)};});}
export class WhiteboardProposalService{
 constructor(private db:DatabasePort,private collaboration:WhiteboardCollaborationStore,private audit:WhiteboardOperationAuditRepository,private proposals:WhiteboardProposalRepository,private operations:WhiteboardOperationService,private now=()=>new Date(),private agents?:PublishedAgentReader){}
 async create(principal:Principal,boardId:string,input:unknown,runtimePin?:Proposal['runtimePin']){const request=WhiteboardAIProposalCreate.parse(input),requestHash=hash({principal:principal.userId,request,...(runtimePin?{runtimePin}:{})});const replay=await this.db.withTenant(principal.orgId,async session=>{if(!await this.audit.lockHead(session,principal,boardId))throw new WhiteboardOperationError('NOT_FOUND');return this.proposals.lock(session,principal,boardId,request.proposalId);});if(replay){if(replay.ownerUserId!==principal.userId||replay.requestHash!==requestHash)throw new WhiteboardOperationError('IDEMPOTENCY_CONFLICT');return replay.proposal;}const snapshot=await this.collaboration.load(principal,boardId);if(snapshot.epoch!==request.baseRevision.epoch||snapshot.seq!==request.baseRevision.seq)throw new WhiteboardOperationError('STALE_REVISION');const doc=new Y.Doc();Y.applyUpdate(doc,snapshot.update);const refs=new Set<string>();for(const command of request.action.commands)if(command.type!=='create')refs.add(command.id);if('objectIds'in request.action)request.action.objectIds.forEach(id=>refs.add(id));const objects=readObjects(doc).filter(object=>refs.has(object.id));doc.destroy();if(objects.length!==refs.size)throw new WhiteboardOperationError('NOT_FOUND');return this.db.withTenant(principal.orgId,async session=>{const head=await this.audit.lockHead(session,principal,boardId);if(!head||head.epoch!==request.baseRevision.epoch||head.seq!==request.baseRevision.seq)throw new WhiteboardOperationError('STALE_REVISION');const registered=await this.audit.resolveActor(session,principal,boardId,request.actorId);if(!registered||registered.kind!=='ai'||!registered.model||!registered.skill||!registered.scopes.includes('board:write'))throw new WhiteboardOperationError('FORBIDDEN');if(runtimePin)await this.verifyRuntime(session,principal,boardId,request.actorId,runtimePin);const actor={kind:'ai' as const,actorId:registered.actorId,orgId:principal.orgId,role:head.actorRole,scopes:registered.scopes,delegatedBy:registered.delegatedBy};const created=this.now(),proposal=WhiteboardAIProposal.parse({... (runtimePin?{runtimePin}:{}),proposalId:request.proposalId,boardId,createdBy:actor,baseRevision:request.baseRevision,baseObjectDigests:Object.fromEntries(objects.map(object=>[object.id,digestWhiteboardObject(object)])),action:request.action,provenance:{...request.provenance,source:'ai-proposal',model:registered.model,skill:registered.skill,inputObjectIds:[...refs]},status:'preview',createdAt:created.toISOString(),expiresAt:new Date(created.getTime()+300000).toISOString()});return this.proposals.create(session,principal,proposal,requestHash);});}
 async read(principal:Principal,boardId:string,proposalId:string){return this.db.withTenant(principal.orgId,async session=>(await this.required(session,principal,boardId,proposalId)).proposal);}
 async cancel(principal:Principal,boardId:string,proposalId:string,input:unknown){WhiteboardAIProposalDecision.parse(input);return this.db.withTenant(principal.orgId,async session=>{const stored=await this.required(session,principal,boardId,proposalId);if(stored.proposal.status!=='preview')throw new WhiteboardOperationError('IDEMPOTENCY_CONFLICT');await this.proposals.setStatus(session,principal,boardId,proposalId,'cancelled');return WhiteboardAIProposal.parse({...stored.proposal,status:'cancelled'});});}
 async confirm(principal:Principal,boardId:string,proposalId:string,input:unknown){const decision=WhiteboardAIProposalDecision.parse(input);return this.db.withTenant(principal.orgId,async session=>{const head=await this.audit.lockHead(session,principal,boardId);if(!head)throw new WhiteboardOperationError('NOT_FOUND');const stored=await this.required(session,principal,boardId,proposalId),proposal=stored.proposal;if(proposal.runtimePin)await this.verifyRuntime(session,principal,boardId,proposal.createdBy.actorId,proposal.runtimePin);if(proposal.status!=='preview'&&proposal.status!=='confirmed')throw new WhiteboardOperationError('IDEMPOTENCY_CONFLICT');if(proposal.status==='confirmed')return this.operations.executeInTransaction(session,principal,boardId,{apiVersion:'2026-09-01',requestId:decision.requestId,boardId,expectedRevision:proposal.baseRevision,actor:proposal.createdBy,commands:proposal.action.commands,provenance:proposal.provenance},proposal.runtimePin);if(Date.parse(proposal.expiresAt)<=this.now().getTime())throw new WhiteboardOperationError('STALE_REVISION');if(decision.expectedRevision.epoch!==proposal.baseRevision.epoch||decision.expectedRevision.seq!==proposal.baseRevision.seq||head.epoch!==proposal.baseRevision.epoch||head.seq!==proposal.baseRevision.seq)throw new WhiteboardOperationError('STALE_REVISION');const snapshot=await this.collaboration.loadInTransaction(session,principal,boardId),doc=new Y.Doc();Y.applyUpdate(doc,snapshot.update);const current=new Map(readObjects(doc).map(object=>[object.id,digestWhiteboardObject(object)]));doc.destroy();if(Object.entries(proposal.baseObjectDigests).some(([id,digest])=>current.get(id)!==digest))throw new WhiteboardOperationError('STALE_REVISION');const receipt=await this.operations.executeInTransaction(session,principal,boardId,{apiVersion:'2026-09-01',requestId:decision.requestId,boardId,expectedRevision:proposal.baseRevision,actor:proposal.createdBy,commands:proposal.action.commands,provenance:proposal.provenance},proposal.runtimePin);await this.proposals.setStatus(session,principal,boardId,proposalId,'confirmed');return receipt;});}
 async confirmWithUndo(principal:Principal,boardId:string,proposalId:string,input:unknown){const decision=WhiteboardAIProposalDecision.parse(input);return this.db.withTenant(principal.orgId,async session=>{const head=await this.audit.lockHead(session,principal,boardId);if(!head)throw new WhiteboardOperationError('NOT_FOUND');const stored=await this.required(session,principal,boardId,proposalId),proposal=stored.proposal;if(proposal.runtimePin)await this.verifyRuntime(session,principal,boardId,proposal.createdBy.actorId,proposal.runtimePin);if(proposal.status==='confirmed'&&proposal.undoReceipt){const receipt=await this.operations.executeInTransaction(session,principal,boardId,{apiVersion:'2026-09-01',requestId:decision.requestId,boardId,expectedRevision:proposal.baseRevision,actor:proposal.createdBy,commands:proposal.action.commands,provenance:proposal.provenance},proposal.runtimePin);return{...receipt,undoReceipt:proposal.undoReceipt};}if(proposal.status!=='preview'||Date.parse(proposal.expiresAt)<=this.now().getTime()||decision.expectedRevision.epoch!==proposal.baseRevision.epoch||decision.expectedRevision.seq!==proposal.baseRevision.seq||head.epoch!==proposal.baseRevision.epoch||head.seq!==proposal.baseRevision.seq)throw new WhiteboardOperationError('STALE_REVISION');const snapshot=await this.collaboration.loadInTransaction(session,principal,boardId),doc=new Y.Doc();Y.applyUpdate(doc,snapshot.update);const objects=new Map(readObjects(doc).map(object=>[object.id,object]));doc.destroy();if(Object.entries(proposal.baseObjectDigests).some(([id,digest])=>!objects.has(id)||digestWhiteboardObject(objects.get(id)!)!==digest))throw new WhiteboardOperationError('STALE_REVISION');const receipt=await this.operations.executeInTransaction(session,principal,boardId,{apiVersion:'2026-09-01',requestId:decision.requestId,boardId,expectedRevision:proposal.baseRevision,actor:proposal.createdBy,commands:proposal.action.commands,provenance:proposal.provenance},proposal.runtimePin),undoReceipt={undoId:randomUUID(),operationId:receipt.operationId,boardId,expectedRevision:receipt.revision,commands:inverse(proposal.action.commands,objects),createdAt:this.now().toISOString()};await this.proposals.setConfirmation(session,principal,boardId,proposalId,undoReceipt);return{...receipt,undoReceipt};});}
 async undo(principal:Principal,boardId:string,proposalId:string,input:unknown){
  const decision=WhiteboardAIProposalDecision.parse(input);
  return this.db.withTenant(principal.orgId,async session=>{
   const stored=await this.required(session,principal,boardId,proposalId),proposal=stored.proposal,undo=proposal.undoReceipt;
   if(proposal.status!=='confirmed'||!undo)throw new WhiteboardOperationError('NOT_FOUND');
   if(decision.expectedRevision.epoch!==undo.expectedRevision.epoch||decision.expectedRevision.seq!==undo.expectedRevision.seq)throw new WhiteboardOperationError('STALE_REVISION');
   // Commands and idempotency key come from the server's immutable receipt, never
   // from caller-supplied inverse JSON. Any intervening edit rejects via head CAS.
   return this.operations.executeInTransaction(session,principal,boardId,{apiVersion:'2026-09-01',requestId:undo.undoId,boardId,expectedRevision:undo.expectedRevision,
    actor:{kind:'human',actorId:principal.userId,orgId:principal.orgId,role:'owner',scopes:['board:read','board:write'],delegatedBy:null},commands:undo.commands,
    provenance:{source:'human',model:null,skill:null,sourceArtifactId:null,sourceRevision:null,layoutHash:null,inputObjectIds:proposal.provenance.inputObjectIds}});
  });
 }
 private async verifyRuntime(session:TenantSession,principal:Principal,boardId:string,actorId:string,pin:NonNullable<Proposal['runtimePin']>){
  const registered=await this.audit.resolveActor(session,principal,boardId,actorId),snapshot=await this.agents?.resolvePublished(principal.orgId,actorId);
  if(!registered||registered.model!==pin.model||registered.skill!==pin.skill||!snapshot||snapshot.agentVersionId!==pin.agentVersionId||`${snapshot.modelProvider}/${snapshot.modelId}`!==pin.model||!snapshot.skillVersionIds.includes(pin.skill))throw new WhiteboardOperationError('STALE_REVISION');
 }
 private async required(session:TenantSession,principal:Principal,boardId:string,proposalId:string){if(!await this.audit.lockHead(session,principal,boardId))throw new WhiteboardOperationError('NOT_FOUND');const stored=await this.proposals.lock(session,principal,boardId,proposalId);if(!stored||stored.ownerUserId!==principal.userId)throw new WhiteboardOperationError('NOT_FOUND');return stored;}
}
