const {chromium}=require('../../node_modules/playwright-core');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const out=process.env.MENU_AUDIT_OUT||'/private/tmp/board-all-menu-audit';fs.mkdirSync(out,{recursive:true});
const root=path.resolve(__dirname,'../../../..');
const {hashes}=require('./audit-source.cjs');
const scenes=[{name:'desktop-center',width:1440,height:1000,edge:'center'},{name:'desktop-left-top',width:1440,height:1000,edge:'left'},{name:'desktop-right-bottom',width:1440,height:1000,edge:'right'},{name:'narrow-center',width:390,height:844,edge:'center'},{name:'narrow-left-top',width:390,height:844,edge:'left'},{name:'narrow-right-bottom',width:390,height:844,edge:'right'}];
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage();page.setDefaultTimeout(5000);const errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));
const board='22222222-2222-4222-8222-222222222222';await page.route(`**/whiteboards/${board}/comments`,r=>r.fulfill({json:{items:[]}}));await page.route(`**/v1/whiteboards/${board}/ai-organize/actors`,r=>r.fulfill({json:[]}));await page.route(`**/whiteboards/${board}/mentionable-members`,r=>r.fulfill({json:{items:[]}}));
const manifest=hashes();const snapshot=()=>page.evaluate(()=>window.feedbackSnapshot());const raf=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const key=s=>s.replace(/[^a-zA-Z0-9_-]/g,'_');let sequence=0;
const capture=async name=>{if(!name.includes('FAILED')&&!name.startsWith('desktop-center')&&!name.startsWith('narrow-center'))return null;const file=`${String(++sequence).padStart(3,'0')}-${key(name)}.png`;await page.screenshot({path:path.join(out,file)});return file;};
const run=async(name,fn)=>{const row={name};try{Object.assign(row,await fn());row.ok=true;}catch(e){row.ok=false;row.error=e.stack;row.screenshot=await capture(name+'-FAILED');}results.push(row);fs.writeFileSync(path.join(out,'partial-report.json'),JSON.stringify(results,null,2));return row;};
const fresh=async(scene,kind='sticky')=>{await page.setViewportSize({width:scene.width,height:scene.height});await page.goto(`http://127.0.0.1:33755/audit.html?kind=${kind}&edge=${scene.edge}`);await page.getByTestId('board-tool-select').waitFor();await raf();};
const select=async kind=>{const select=page.getByTestId('board-tool-select');await select.click();if(kind==='multi'){await select.focus();await page.keyboard.press('ControlOrMeta+a');await page.getByTestId('board-selection-layout-toolbar').waitFor();}else{const row=page.getByTestId('board-a11y-object-target');await row.focus();await row.press('Enter');if(['sticky','shape','text'].includes(kind)){const edit=page.getByTestId('board-thinking-editor');await edit.waitFor();await edit.press('Escape');await edit.waitFor({state:'hidden'});}await page.getByTestId('board-context-toolbar').waitFor();}await raf();};
const settled=async locator=>{await locator.evaluate(async e=>{await Promise.all(e.getAnimations({subtree:true}).filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})));});await raf();};
const rect=async locator=>{const b=await locator.boundingBox();assert(b,'Visible bounds required');return b;};
function boundary(p,s){assert(p.x>=15&&p.x+p.width<=s.width-15,JSON.stringify({p,s}));assert(p.y>=0&&p.y+p.height<=s.height-15,JSON.stringify({p,s}));}
function proximity(p,t){const dx=Math.max(t.x-p.x-p.width,p.x-t.x-t.width,0),dy=Math.max(t.y-p.y-p.height,p.y-t.y-t.height,0);assert(Math.hypot(dx,dy)<=25,JSON.stringify({p,t,dx,dy}));return{dx,dy};}
const descriptor=button=>({id:button.id,name:button.name});
const visibleTriggers=async host=>host.locator('button[aria-haspopup="dialog"]').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().width&&e.getBoundingClientRect().height&&getComputedStyle(e).visibility!=='hidden').map(e=>({id:e.getAttribute('data-testid'),name:e.getAttribute('aria-label')||e.textContent.trim()})));
const triggerFor=(host,d)=>d.id?host.getByTestId(d.id).filter({visible:true}).first():host.getByRole('button',{name:d.name,exact:true}).filter({visible:true}).first();
async function option(pop,id,kind){const before=await snapshot();let checked=false;
 if(id==='board-sticky-style-open'){await pop.getByTestId('sticky-quick-color-pink').click();await raf();assert.notDeepEqual(await snapshot(),before);checked=true;}
 else if(id==='board-sticky-text-open'){await pop.getByRole('button',{name:'切换粗体',exact:true}).click();await raf();assert.notDeepEqual(await snapshot(),before);checked=true;}
 else if(id==='board-connector-path-open'){await pop.getByTestId('board-connector-curve').click();await raf();assert.equal((await snapshot())[0].connector.type,'curve');checked=true;}
 else if(id==='board-connector-color-open'){await pop.getByRole('button',{name:'连接线颜色 #EF4444',exact:true}).click();await raf();assert.equal((await snapshot())[0].style.stroke,'#EF4444');checked=true;}
 else if(id==='board-connector-width-open'){await pop.getByTestId('board-connector-width-8').click();await raf();assert.equal((await snapshot())[0].connector.strokeWidth,8);checked=true;}
 else if(id==='board-connector-pattern-open'){await pop.getByTestId('board-connector-pattern-dashed').click();await raf();assert.equal((await snapshot())[0].connector.lineStyle,'dashed');checked=true;}
 else if(id==='board-connector-endpoints-open'){await pop.getByTestId('board-connector-end-circle').click();await raf();assert.equal((await snapshot())[0].connector.endStyle,'circle');checked=true;}
 else if(id==='board-connector-label-open'){await pop.getByTestId('board-connector-label').fill('Menu audit label');await pop.getByTestId('board-connector-label-save').click();await raf();assert.equal((await snapshot())[0].connector.label,'Menu audit label');checked=true;}
 else if(id==='board-inspector-metadata'){await pop.getByLabel('新标签',{exact:true}).fill('audit');await pop.getByRole('button',{name:'添加标签',exact:true}).click();await raf();assert((await snapshot())[0].extensionData.objectExperience.tags.includes('audit'));checked=true;}
 else if(id==='board-inspector-text'){await pop.getByRole('button',{name:'粗体',exact:true}).click();await raf();assert.notDeepEqual(await snapshot(),before);checked=true;}
 else if(id==='board-inspector-layout'){await pop.getByTestId('board-layout-row').click();await raf();assert.notDeepEqual(await snapshot(),before);checked=true;}
 else if(id==='board-inspector-actions'){await pop.getByTestId('board-properties-open').click();await pop.getByTestId('board-shared-properties').waitFor();checked=true;}
 else if(kind==='shape'){const fills=pop.getByRole('button',{name:'对象填充颜色 #FBC9DF',exact:true});if(await fills.count()){await fills.click();await raf();assert.notDeepEqual(await snapshot(),before);checked=true;}}
 return{canonicalOrControlOptionChecked:checked,before,after:await snapshot()};}
async function popup(scene,kind,phase,d){const host=kind==='multi'?page.getByTestId('board-selection-layout-toolbar'):page.getByTestId('board-context-toolbar');const button=triggerFor(host,d);await button.scrollIntoViewIfNeeded();await button.click();const pop=page.getByTestId('board-tool-popover').filter({visible:true});await pop.waitFor();await settled(pop);const p=await rect(pop),t=await rect(button);boundary(p,scene);const distance=proximity(p,t);if(['board-connector-path-open','board-connector-width-open','board-connector-pattern-open'].includes(d.id))assert(p.width<=210,`Compact ${d.id} width ${p.width}`);const screenshot=await capture(`${scene.name}-${kind}-${phase}-${d.id||d.name}`);const behavior=await option(pop,d.id,kind);await pop.press('Escape');await pop.waitFor({state:'hidden'});await raf();const focusReturned=await button.evaluate(e=>document.activeElement===e);assert(focusReturned,'Escape must return focus to mother trigger');return{kind,phase,trigger:d,panel:p,mother:t,distance,screenshot,...behavior,focusReturned};}
for(const scene of scenes){
 await fresh(scene);for(const [id,label]of [['board-add-sticky','sticky'],['board-add-text','text'],['board-add-shape','shape'],['board-add-connector','connector'],['board-add-more','widgets']])await run(`${scene.name}-creation-${label}`,async()=>{await fresh(scene);const button=page.getByTestId(id);await button.scrollIntoViewIfNeeded();await button.click();const panel=page.getByTestId('board-tool-picker');await panel.waitFor();await settled(panel);const p=await rect(panel),t=await rect(button),mother=await rect(page.getByTestId('board-creation-dock'));boundary(p,scene);proximity(p,t);assert(mother.y-p.y-p.height>=7&&mother.y-p.y-p.height<=17);if(label==='connector')assert(p.width<=210);const screenshot=await capture(`${scene.name}-creation-${label}`);const choice=label==='sticky'?'board-sticky-circle':label==='text'?'board-text-heading':label==='shape'?'board-shape-triangle':label==='connector'?'board-connector-curve':'board-content-icon';const item=panel.getByTestId(choice);await item.click();await raf();if(label!=='widgets')assert.equal(await item.getAttribute('aria-pressed'),'true');else assert((await snapshot()).some(o=>o.extensionData?.contentObject?.type==='icon'));await page.getByTestId('board-tool-select').click();await panel.waitFor({state:'hidden'});return{trigger:id,panel:p,mother,t,screenshot,option:choice,optionChecked:true};});
 await run(`${scene.name}-creation-draw`,async()=>{await fresh(scene);const button=page.getByTestId('board-add-draw');await button.scrollIntoViewIfNeeded();await button.click();const panel=page.getByTestId('board-draw-tool-panel');await panel.waitFor();await settled(panel);const p=await rect(panel),mother=await rect(page.getByTestId('board-creation-dock'));boundary(p,scene);assert(mother.y-p.y-p.height>=7&&mother.y-p.y-p.height<=10);await panel.getByTestId('board-draw-marker').click();assert.equal(await panel.getByTestId('board-draw-marker').getAttribute('aria-pressed'),'true');const screenshot=await capture(`${scene.name}-creation-draw`);await panel.getByRole('button',{name:'Close draw tools',exact:true}).click();await panel.waitFor({state:'hidden'});return{panel:p,mother,screenshot,optionChecked:true};});
 for(const kind of ['sticky','shape','text','connector','drawing','image','frame','multi']){await run(`${scene.name}-${kind}-selection`,async()=>{await fresh(scene,kind);await select(kind);return{selected:kind,screenshot:await capture(`${scene.name}-${kind}-selection`)};});let host=kind==='multi'?page.getByTestId('board-selection-layout-toolbar'):page.getByTestId('board-context-toolbar');if(!await host.isVisible())continue;const compact=await visibleTriggers(host);for(const d of compact)await run(`${scene.name}-${kind}-compact-${d.id||d.name}`,async()=>{await fresh(scene,kind);await select(kind);return popup(scene,kind,'compact',d);});
 if(kind!=='multi'){await run(`${scene.name}-${kind}-expanded`,async()=>{await fresh(scene,kind);await select(kind);await page.getByTestId('board-inspector-expand').click();await page.getByTestId('board-inspector-scroll-content').waitFor();const p=await rect(host);boundary(p,scene);return{panel:p,screenshot:await capture(`${scene.name}-${kind}-expanded`)};});if(!await page.getByTestId('board-inspector-scroll-content').isVisible())continue;const advanced=page.getByTestId('board-widget-advanced-format');if(await advanced.count())await advanced.locator('summary').click();const triggers=await visibleTriggers(host);for(const d of triggers)await run(`${scene.name}-${kind}-expanded-${d.id||d.name}`,async()=>{await fresh(scene,kind);await select(kind);await page.getByTestId('board-inspector-expand').click();const advanced=page.getByTestId('board-widget-advanced-format');if(await advanced.count())await advanced.locator('summary').click();return popup(scene,kind,'expanded',d);});}
 }
 // Header and zoom are actual product chrome. Desktop-only hidden controls are recorded explicitly.
 for(const [id,name]of [['board-title-menu','title'],['board-help-open','help'],['board-zoom-menu','zoom']])await run(`${scene.name}-chrome-${name}`,async()=>{await fresh(scene);const b=page.getByTestId(id);if(!await b.isVisible())return{reachable:false,reason:'Responsive product hides this entry at this viewport'};await b.click();const panel=name==='help'?page.getByTestId('board-tool-popover'):page.getByRole('menu');await panel.waitFor();await settled(panel);const p=await rect(panel),t=await rect(b);boundary(p,scene);proximity(p,t);const screenshot=await capture(`${scene.name}-chrome-${name}`);if(name==='zoom'){await page.getByTestId('board-zoom-in').click();assert.equal(await page.getByTestId('board-zoom-value').innerText(),'110%');}else{if(name==='title'){await panel.getByLabel('白板名称',{exact:true}).fill('Renamed audit');assert.equal(await page.getByTestId('board-title-menu').innerText(),'Renamed audit');}await panel.press('Escape');await panel.waitFor({state:'hidden'});}return{panel:p,mother:t,screenshot,reachable:true};});
 await run(`${scene.name}-chrome-actions`,async()=>{await fresh(scene);const b=page.getByRole('button',{name:'更多白板操作',exact:true});await b.click();const panel=page.getByTestId('board-tool-popover');await panel.waitFor();await settled(panel);const p=await rect(panel),t=await rect(b);boundary(p,scene);proximity(p,t);const screenshot=await capture(`${scene.name}-chrome-actions`);await panel.press('Escape');await panel.waitFor({state:'hidden'});return{panel:p,mother:t,screenshot};});
 for(const [id,panelId,name]of [['board-add-image','board-image-upload-dialog','image-upload'],['board-share-open','board-share-dialog','share']])await run(`${scene.name}-modal-${name}`,async()=>{await fresh(scene);const b=page.getByTestId(id);if(!await b.isVisible())return{reachable:false,reason:'Responsive product hides entry'};await b.scrollIntoViewIfNeeded();await b.click();const dialog=page.getByTestId(panelId);await dialog.waitFor();await settled(dialog);const p=await rect(dialog);boundary(p,scene);const screenshot=await capture(`${scene.name}-modal-${name}`);await dialog.press('Escape');await dialog.waitFor({state:'hidden'});return{modal:true,panel:p,screenshot,reachable:true};});
}
await run('source-freeze',async()=>{assert.deepEqual(hashes(),manifest);return{files:manifest.length};});await run('no-page-errors',async()=>{assert.equal(errors.length,0,JSON.stringify(errors));return{errors};});fs.writeFileSync(path.join(out,'source-manifest.json'),JSON.stringify(manifest,null,2));const report={scope:'Production menu components with canonical in-memory Yjs. Comments/AI actor lists mocked; no API durability/auth/model proof.',scenes,results,unreachable:[{name:'Frame creation',reason:'No product dock button invokes panel creation'},{name:'Minimap menu',reason:'Overview icon is fit-board action, not a menu'}],ok:results.every(r=>r.ok)};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({ok:report.ok,total:results.length,failed:results.filter(r=>!r.ok).map(r=>({name:r.name,error:r.error})),out},null,2));process.exitCode=report.ok?0:1;
})().catch(e=>{console.error(e);process.exitCode=1;});
