const {chromium}=require('../../node_modules/playwright-core');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const{hashes:sourceManifest}=require('./audit-source.cjs');
const manifestBefore=sourceManifest();
const out=process.env.FEEDBACK_OUT||'/private/tmp/board-feedback-browser';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(8000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks=[];await page.route('**/whiteboards/22222222-2222-4222-8222-222222222222/comments',route=>route.fulfill({json:{items:[{id:'11111111-1111-4111-8111-111111111111',boardId:'22222222-2222-4222-8222-222222222222',objectId:'shape',worldPosition:null,status:'open',revision:1,resolvedBy:null,resolvedAt:null,archivedAt:null,comments:[]}]}}));const snapshot=()=>page.evaluate(()=>window.feedbackSnapshot());
const wait=async()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const shot=async name=>page.screenshot({path:path.join(out,name+'.png')});
const fresh=async()=>{await page.goto('http://127.0.0.1:33755');await page.getByTestId('board-add-sticky').waitFor();await wait();};
const check=async(name,fn)=>{try{await fn();checks.push({name,ok:true});}catch(e){checks.push({name,ok:false,error:e.stack});await shot(name+'-failed');}};
await fresh();
await check('dock-icons-and-right-chevrons',async()=>{for(const id of ['board-add-sticky','board-add-text','board-add-shape','board-add-draw','board-add-more']){const b=page.getByTestId(id),cue=page.getByTestId(id+'-submenu');assert.equal(await b.locator('.sr-only').count(),1);const svg=await b.locator('[data-board-drag-preview]').boundingBox(),c=await cue.boundingBox();assert(c.x+c.width/2>svg.x+svg.width/2);assert(Math.abs(c.y+c.height/2-svg.y-svg.height/2)<2,JSON.stringify({id,svg,c}));}await shot('desktop-dock');});
await check('sticky-native-drag-single-object',async()=>{const before=await snapshot();const b=await page.getByTestId('board-add-sticky').boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(1000,350,{steps:25});await page.mouse.up();await page.waitForTimeout(300);assert.equal((await snapshot()).length,before.length+1);await page.keyboard.press('Escape');await shot('sticky-native-drag');});
for(const width of [1440,390])await check('submenu-adjacency-'+width,async()=>{await page.setViewportSize({width,height:1000});await fresh();await page.getByTestId('board-a11y-object-a').focus();await page.getByTestId('board-a11y-object-a').press('Enter');await page.getByTestId('board-thinking-editor').waitFor({state:'visible'});await page.getByTestId('board-thinking-editor').press('Escape');await page.getByTestId('board-thinking-editor').waitFor({state:'hidden'});const trigger=page.getByTestId('board-sticky-style-open');await trigger.click();const pop=page.getByTestId('board-tool-popover');await pop.waitFor();await wait();const p=await pop.boundingBox(),t=await trigger.boundingBox();assert(p.x>=15&&p.x+p.width<=width-15);assert(p.y>=0&&p.y+p.height<=1000);const gap=Math.min(Math.abs(p.x-t.x-t.width),Math.abs(t.x-p.x-p.width),Math.abs(p.y-t.y-t.height),Math.abs(t.y-p.y-p.height));assert(gap<=10,JSON.stringify({p,t,gap}));await shot('sticky-submenu-'+width);await page.keyboard.press('Escape');});
await page.setViewportSize({width:1440,height:1000});await fresh();
await check('drawing-live-eraser-cancel-undo',async()=>{await page.getByTestId('board-add-draw').click();await page.getByTestId('board-draw-stroke-8').click();await page.mouse.move(920,220);await page.mouse.down();await page.mouse.move(1120,220,{steps:20});await page.mouse.up();await page.getByTestId('board-draw-select').click();await page.mouse.click(100,550);await page.getByTestId('board-add-draw').click();await page.getByTestId('board-draw-eraser').click();const baseline=await snapshot();const pixel=()=>page.getByTestId('board-fabric-surface').evaluate(el=>{const c=el.querySelector('canvas.lower-canvas'),r=c.getBoundingClientRect(),d=c.getContext('2d').getImageData(Math.round((1000-r.x)*c.width/r.width),Math.round((220-r.y)*c.height/r.height),1,1).data;return [...d];});const original=await pixel();assert(original[0]<100&&original[3]>200,JSON.stringify(original));await page.mouse.move(995,220);await page.mouse.down();await page.mouse.move(1010,220,{steps:10});await wait();const held=await pixel();assert(held[3]===0,JSON.stringify(held));const cursor=await page.getByTestId('board-eraser-cursor').boundingBox();assert(cursor.width>=47&&cursor.height>=47);assert.deepEqual(await snapshot(),baseline);await shot('eraser-held-live');await page.getByTestId('board-fabric-surface').locator('canvas.upper-canvas').dispatchEvent('pointercancel',{bubbles:true,pointerId:1,pointerType:'mouse'});await page.mouse.up();await wait();assert.deepEqual(await snapshot(),baseline);assert((await pixel())[3]>200);await page.mouse.move(995,220);await page.mouse.down();await page.mouse.move(1010,220,{steps:10});await page.mouse.up();await wait();assert((await pixel())[3]===0);assert.notDeepEqual(await snapshot(),baseline);await page.getByRole('button',{name:'撤销',exact:true}).click();await wait();assert.deepEqual(await snapshot(),baseline);assert((await pixel())[3]>200);await shot('eraser-undo');await page.getByRole('button',{name:'重做',exact:true}).click();await wait();assert((await pixel())[3]===0);await shot('eraser-redo');});
await fresh();
await check('connector-repeated-drag',async()=>{for(let i=0;i<10;i++){await page.mouse.click(390,350);await page.keyboard.press('Escape');const handle=page.getByTestId('connector-handle-a-right');await handle.waitFor();const h=await handle.boundingBox();await page.mouse.move(h.x+h.width/2,h.y+h.height/2);await page.mouse.down();await page.mouse.move(600,350,{steps:12});await page.mouse.up();await wait();const rows=await snapshot();assert.equal(rows.filter(r=>r.kind==='connector').length,i+1);}await shot('repeated-connectors');});

await check('shape-comment-and-appearance',async()=>{await page.goto('http://127.0.0.1:33755/?shape');await page.getByTestId('board-comment-indicator-shape').waitFor();const badge=page.getByTestId('board-comment-indicator-shape');assert.equal(await badge.locator('svg').count(),1);assert.equal(await badge.locator('img').count(),0);await page.mouse.click(990,370);await page.keyboard.press('Escape');await page.getByTestId('board-inspector-expand').click();await page.getByTestId('board-shape-properties').waitFor();await page.getByRole('button',{name:'形状边框粗细 4px',exact:true}).click();await page.getByRole('button',{name:'形状圆角 20px',exact:true}).click();await page.getByRole('button',{name:'形状边框样式 dashed',exact:true}).click();await wait();const content=(await snapshot()).find(r=>r.id==='shape').extensionData.contentObject;assert.equal(content.borderWidth,4);assert.equal(content.radius,20);assert.equal(content.borderStyle,'dashed');assert.equal(await page.getByTestId('board-shape-properties').locator('input[type=number]').count(),0);const slider=page.getByTestId('board-shape-properties').locator('input[type=range]');const accent=await slider.evaluate(e=>getComputedStyle(e).accentColor);const primary=await page.getByTestId('board-tool-select').evaluate(e=>getComputedStyle(e).backgroundColor);assert.equal(accent,primary);await slider.scrollIntoViewIfNeeded();await shot('shape-opacity-neutral');const scroll=await page.getByTestId('board-context-toolbar').evaluate(e=>({asideScroll:e.scrollTop,bodyScrollable:e.querySelector('[data-testid=board-inspector-scroll-content]').scrollHeight>e.querySelector('[data-testid=board-inspector-scroll-content]').clientHeight,headerHeight:e.firstElementChild.getBoundingClientRect().height,headerTop:e.firstElementChild.getBoundingClientRect().top,asideTop:e.getBoundingClientRect().top,accent:getComputedStyle(e.querySelector('input[type=range]')).accentColor}));assert.equal(scroll.asideScroll,0);assert(scroll.headerTop>=scroll.asideTop&&scroll.headerHeight>30);assert.equal(scroll.bodyScrollable,true);fs.writeFileSync(path.join(out,'inspector-scroll.json'),JSON.stringify(scroll,null,2));await page.getByTestId('board-inspector-scroll-content').evaluate(e=>e.scrollTop=0);await wait();await shot('shape-appearance-and-comment');});
for(const viewport of [{width:1440,height:1000},{width:390,height:1000},{width:1536,height:1024},{width:1672,height:941}])await check('drawing-panel-adjacent-'+viewport.width,async()=>{const {width,height}=viewport;await page.setViewportSize(viewport);await fresh();const button=page.getByTestId('board-add-draw');await button.scrollIntoViewIfNeeded();await button.click();await wait();const panel=await page.getByTestId('board-draw-tool-panel').boundingBox(),t=await button.boundingBox(),dock=await page.getByTestId('board-creation-dock').boundingBox();const dockGap=dock.y-panel.y-panel.height;fs.writeFileSync(path.join(out,'draw-panel-metrics-'+width+'.json'),JSON.stringify({viewport,dock,button:t,panel,dockGap,compactCiCondition:panel.y+panel.height<=dock.y-2},null,2));assert(panel.x>=15&&panel.x+panel.width<=width-15);assert(panel.y>=64&&panel.y+panel.height<=height);assert(dockGap>=8&&dockGap<=10,JSON.stringify({dock,panel,dockGap}));assert(panel.y+panel.height<=dock.y-2);await shot('draw-panel-'+width);});

await check('spacing-held-gap-midpoints',async()=>{await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:33755/?spacing');await page.getByTestId('board-add-sticky').waitFor();const before=await snapshot();await page.mouse.move(690,350);await page.mouse.down();await page.mouse.move(694,350,{steps:4});await wait();const labels=await page.getByTestId('board-spacing-measurement').evaluateAll(es=>es.map(e=>{const b=e.getBoundingClientRect();return{text:e.textContent,center:b.x+b.width/2,bottom:b.bottom};}));assert.equal(labels.length,2);assert.deepEqual(labels.map(l=>l.center).sort((a,b)=>a-b),[540,840]);assert(labels.every(l=>l.text==='120 px'&&l.bottom===260));assert.deepEqual(await snapshot(),before);await shot('spacing-held-gap-midpoints');await page.mouse.up();fs.writeFileSync(path.join(out,'spacing-receipt.json'),JSON.stringify({labels,canonicalBefore:before,heldPointer:true},null,2));});
await check('source-freeze',async()=>assert.deepEqual(sourceManifest(),manifestBefore,'Application source changed during browser run; rerun required'));fs.writeFileSync(path.join(out,'source-manifest.json'),JSON.stringify(manifestBefore,null,2));await check('no-page-errors',async()=>assert.equal(errors.length,0,JSON.stringify(errors)));const report={scope:'Production CollaborativeThinkingEditor and Fabric in a browser, in-memory canonical Yjs. No API durability, auth, websocket or reload persistence claim.',checks,errors,ok:checks.every(c=>c.ok)};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report,null,2));process.exitCode=report.ok?0:1;
})().catch(e=>{console.error(e);process.exitCode=1;});
