/** Actual testbench component, substituted API, no app/API/DB server or paid call. */
const fs=require('node:fs');const path=require('node:path');const {createRequire}=require('node:module');const {pathToFileURL}=require('node:url');const {spawnSync}=require('node:child_process');
const root=path.resolve(__dirname,'../..'),web=path.join(root,'apps/web'),fromWeb=createRequire(path.join(web,'package.json'));
const fromVitest=createRequire(fromWeb.resolve('vitest/package.json')),fromVite=createRequire(fromVitest.resolve('vite')),esbuild=fromVite('esbuild');
const {chromium}=fromWeb('playwright-core');const fromAxe=createRequire(fromWeb.resolve('@axe-core/playwright'));
const output=path.resolve(process.argv[2]||'/tmp/wsx-model-testbench-ui');fs.mkdirSync(output,{recursive:true});
const entry=path.join(output,'entry.tsx');fs.writeFileSync(entry,`
import * as React from 'react';import {createRoot} from 'react-dom/client';import {PlatformModelTestbench} from ${JSON.stringify(path.join(web,'components/admin/platform-model-testbench'))};
createRoot(document.getElementById('root')!).render(<main className="mx-auto max-w-7xl p-4"><p className="mb-4 rounded border p-3 text-14">组件验收：真实测试台组件，API 为测试替代响应；未登录组织后台，未调用供应商，未产生费用。</p><PlatformModelTestbench/></main>);
`);
const fixtures=`
const abilities=['text','image-generation','text-to-speech','speech-to-text','embedding','rerank'];let current;
export async function getModelTestCandidates(){return abilities.map(capability=>({modelId:'fixture-'+capability,displayName:'组件测试模型',capability,available:true,reason:null,modelProvider:'fixture',runtimeModelId:'fixture-id',currency:'CNY',maximumOutputTokens:64,nativeUnit:'request',maximumQuantity:'5'})).concat([{modelId:'fixture-unsupported',displayName:'未适配示例',capability:'image-generation',available:false,reason:'adapter-unavailable',modelProvider:null,runtimeModelId:null,currency:null,maximumOutputTokens:null,nativeUnit:null,maximumQuantity:null}]);}
export async function startModelTest(input){current={testId:input.testId,orgId:input.orgId,modelId:input.modelId,capability:input.capability,state:'unknown',settlementState:'held',result:null,failureReason:'provider-unconfirmed',usage:null};return current;}
export async function getModelTest(){return current;}
export async function cancelModelTest(){return current={...current,state:'cancelled'};}
`;
(async()=>{
await esbuild.build({entryPoints:[entry],outfile:path.join(output,'app.js'),bundle:true,platform:'browser',jsx:'automatic',alias:{'@':web},nodePaths:[path.join(web,'node_modules'),path.join(root,'node_modules')],define:{'process.env':'{}','process.env.NODE_ENV':'"production"'},minify:true,plugins:[{name:'explicit-component-fixture',setup(build){
 build.onLoad({filter:/live-platform-model-test\.ts$/},()=>({contents:fixtures,loader:'ts'}));
 build.onLoad({filter:/live-platform-organizations\.ts$/},()=>({contents:`export async function listPlatformOrganizations(){return {organizations:[{orgId:'fixture-org',name:'组件验收组织'}],nextCursor:null}}`,loader:'ts'}));
 build.onLoad({filter:/admin-screen\.tsx$/},()=>({contents:`import * as React from 'react';export function AdminScreen({children,title,intro}){return <><h1 className="mb-3 text-24 font-semibold">{title}</h1><p className="mb-6 text-14">{intro}</p>{children}</>}`,loader:'tsx'}));
}}]});
const css=spawnSync(path.join(web,'node_modules/.bin/tailwindcss'),['-c','tailwind.config.ts','-i','app/globals.css','-o',path.join(output,'style.css'),'--content',`./components/admin/platform-model-testbench.tsx,./components/ui/*.tsx,${entry}`],{cwd:web,encoding:'utf8'});fs.writeFileSync(path.join(output,'css.txt'),css.stdout+css.stderr);if(css.status!==0)throw new Error('CSS failed');
fs.writeFileSync(path.join(output,'index.html'),'<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>测试台组件验收</title><link rel="stylesheet" href="style.css"></head><body><div id="root"></div><script src="app.js"></script></body></html>');
const browser=await chromium.launch({headless:true});try{const page=await browser.newPage();const pageErrors=[];page.on('pageerror',error=>pageErrors.push(error.message));const checks=[];
 for(const width of [375,768,1280]){await page.setViewportSize({width,height:900});await page.goto(pathToFileURL(path.join(output,'index.html')).href);await page.getByRole('button',{name:'测试所属组织'}).click();await page.getByRole('menuitemradio',{name:'组件验收组织'}).click();await page.getByRole('button',{name:'组件测试模型 · 文字对话'}).click();
 await page.getByLabel('测试提示词').fill('非机密组件测试输入');await page.getByLabel(/最大费用/).fill('0.10');await page.getByLabel(/超时上限/).fill('1000');await page.getByLabel('最大输出 Token').fill('16');await page.getByLabel('确认非机密输入与费用上限').check();
 await page.addScriptTag({path:fromAxe.resolve('axe-core/axe.min.js')});const accessibilityViolations=await page.evaluate(async()=>(await window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa']}})).violations.map(row=>({id:row.id,nodes:row.nodes.length})));
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);if(overflow||accessibilityViolations.length)throw new Error(JSON.stringify({width,overflow,accessibilityViolations}));await page.screenshot({path:path.join(output,`prepare-${width}.png`),fullPage:true});
 await page.getByRole('button',{name:'发起一次真实测试'}).click();await page.getByText('供应商结果未确认',{exact:true}).waitFor();const heldOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);const heldAccessibilityViolations=await page.evaluate(async()=>(await window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa']}})).violations.map(row=>({id:row.id,nodes:row.nodes.length})));if(heldOverflow||heldAccessibilityViolations.length)throw new Error(JSON.stringify({width,heldOverflow,heldAccessibilityViolations}));await page.screenshot({path:path.join(output,`held-${width}.png`),fullPage:true});
 const originalTestId=(await page.getByText(/^测试 ID：/).innerText()).replace('测试 ID：','').trim();await page.getByLabel('确认旧测试预留仍保留').check();await page.getByRole('button',{name:'准备新测试'}).click();await page.getByRole('region',{name:'之前测试'}).waitFor();const heldHistoryOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);if(heldHistoryOverflow)throw new Error('History overflow');if(width===1280){await page.screenshot({path:path.join(output,'history-1280.png'),fullPage:true});await page.getByLabel('已有测试 UUID').fill(originalTestId);await page.getByRole('button',{name:'恢复原测试（仅查询）'}).click();await page.getByText('供应商结果未确认',{exact:true}).waitFor();await page.screenshot({path:path.join(output,'recovery-1280.png'),fullPage:true});}checks.push({width,overflow,heldOverflow,heldHistoryOverflow,accessibilityViolations,heldAccessibilityViolations});
 }
 if(pageErrors.length)throw new Error(pageErrors.join('\n'));const result={scope:'actual-testbench-component-with-explicit-substituted-API-not-authenticated-not-provider-acceptance',checks,pageErrors};fs.writeFileSync(path.join(output,'results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({output,...result}));
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
