import test from 'node:test';
import { runMaintenanceRelease, type MaintenanceOperations } from '../cn-maintenance-release';
import assert from 'node:assert/strict';
import { runARouteMaintenanceRelease, type ARouteOperations } from './a_route';
const request={sourceRevision:'9'.repeat(40),baselineRevision:'b'.repeat(40),migrationPlanSha256:'a'.repeat(64),attemptId:'fixture',maintenanceOptIn:'stop-all-writes-and-require-database-recovery' as const};
const names=['prepareOffline','verifyPreholdRecoveryCapability','verifyIsolatedCandidateAcceptance','persistMaintenanceHold','verifyMaintenanceHoldPresent','blockAllWrites','verifyWritesBlocked','captureAndVerifyCurrentEpochRecovery','verifyCurrentEpochIsolatedCandidateAcceptance','migrateExactPlan','verifyHeldCandidateReadback','stageCandidateRuntime','verifyCandidateRuntimeIdentity','persistCandidateResumeIntent','resumeExactCandidateWriters','verifyCandidateWritersResumed','verifyPublicAcceptance','observeOpenedCandidate','blockCandidateWriters','verifyNoMigrationCommitted','resumeUnchangedBaselineCancellation','verifyBaselineCancellation','clearAndVerifyMaintenanceHold','recordRecoveryRequired','recordReconciliationRequired'] as const;
function fixture(fail?:string){const calls:string[]=[];const ops:any={acquireReleaseLock:async()=>{calls.push('lock');return async()=>{calls.push('unlock');};}};for(const name of names)ops[name]=async()=>{calls.push(name);if(name===fail)throw Error('fixture failure');};return {calls,ops:ops as ARouteOperations};}
test('A route separates prehold proof/current epoch and verifies new runtime before new writers/public acceptance',async()=>{const f=fixture();await runARouteMaintenanceRelease(request,f.ops);const c=f.calls;for(const [before,after] of [['verifyPreholdRecoveryCapability','persistMaintenanceHold'],['verifyWritesBlocked','captureAndVerifyCurrentEpochRecovery'],['captureAndVerifyCurrentEpochRecovery','verifyCurrentEpochIsolatedCandidateAcceptance'],['verifyCurrentEpochIsolatedCandidateAcceptance','migrateExactPlan'],['verifyCandidateRuntimeIdentity','persistCandidateResumeIntent'],['persistCandidateResumeIntent','resumeExactCandidateWriters'],['verifyCandidateWritersResumed','verifyPublicAcceptance'],['verifyPublicAcceptance','clearAndVerifyMaintenanceHold']] as const)assert.ok(c.indexOf(before)<c.indexOf(after));assert.equal(c.includes('resumeUnchangedBaselineCancellation'),false);assert.equal(c.at(-1),'unlock');});
test('before DDL cancellation requires fresh no-commit proof and verified unchanged baseline',async()=>{const f=fixture('captureAndVerifyCurrentEpochRecovery');await assert.rejects(runARouteMaintenanceRelease(request,f.ops),/fixture failure/);assert.deepEqual(f.calls.slice(-5),['verifyNoMigrationCommitted','resumeUnchangedBaselineCancellation','verifyBaselineCancellation','clearAndVerifyMaintenanceHold','unlock']);assert.equal(f.calls.includes('migrateExactPlan'),false);});
test('partially committed SQL failure never cancels to old runtime or releases lock',async()=>{const f=fixture('migrateExactPlan');await assert.rejects(runARouteMaintenanceRelease(request,f.ops),/DATABASE_RECOVERY_REQUIRED/);assert.equal(f.calls.includes('resumeUnchangedBaselineCancellation'),false);assert.equal(f.calls.includes('unlock'),false);assert.equal(f.calls.at(-1),'recordRecoveryRequired');});
test('failure after resume intent reblocks candidate before recovery disposition',async()=>{const f=fixture('resumeExactCandidateWriters');await assert.rejects(runARouteMaintenanceRelease(request,f.ops),/DATABASE_RECOVERY_REQUIRED/);assert.deepEqual(f.calls.slice(-4),['verifyMaintenanceHoldPresent','blockCandidateWriters','verifyWritesBlocked','recordRecoveryRequired']);assert.equal(f.calls.includes('unlock'),false);assert.equal(f.calls.includes('resumeUnchangedBaselineCancellation'),false);});
test('lost candidate reblock response retains lock and requires reconciliation',async()=>{const f=fixture('verifyPublicAcceptance');f.ops.blockCandidateWriters=async()=>{throw Error('lost reply');};await assert.rejects(runARouteMaintenanceRelease(request,f.ops),/WRITE_STATE_RECONCILIATION/);assert.equal(f.calls.at(-1),'recordReconciliationRequired');assert.equal(f.calls.includes('unlock'),false);});

test('canonical coordinator dispatches the source-owned A route without legacy acceptance/prior resume',async()=>{const f=fixture();await runMaintenanceRelease(request,{aRoute:f.ops} as MaintenanceOperations);assert.ok(f.calls.includes('resumeExactCandidateWriters'));assert.equal(f.calls.includes('resumeUnchangedBaselineCancellation'),false);});

test('historical isolated acceptance cannot authorize DDL when same-epoch candidate journeys fail',async()=>{const f=fixture('verifyCurrentEpochIsolatedCandidateAcceptance');await assert.rejects(runARouteMaintenanceRelease(request,f.ops),/fixture failure/);assert.ok(f.calls.includes('verifyIsolatedCandidateAcceptance'));assert.equal(f.calls.includes('migrateExactPlan'),false);assert.ok(f.calls.includes('verifyNoMigrationCommitted'));});

test('post-open observation failure reholds and reblocks candidate without releasing lock',async()=>{const f=fixture('observeOpenedCandidate');await assert.rejects(runARouteMaintenanceRelease(request,f.ops),/DATABASE_RECOVERY_REQUIRED/);assert.deepEqual(f.calls.slice(-5),['persistMaintenanceHold','verifyMaintenanceHoldPresent','blockCandidateWriters','verifyWritesBlocked','recordRecoveryRequired']);assert.equal(f.calls.includes('unlock'),false);assert.equal(f.calls.includes('resumeUnchangedBaselineCancellation'),false);});
test('post-open failure with lost rehold response retains lock for reconciliation',async()=>{const f=fixture('observeOpenedCandidate');let holds=0;f.ops.persistMaintenanceHold=async()=>{if(++holds>1)throw Error('lost hold');};await assert.rejects(runARouteMaintenanceRelease(request,f.ops),/WRITE_STATE_RECONCILIATION/);assert.equal(f.calls.at(-1),'recordReconciliationRequired');assert.equal(f.calls.includes('unlock'),false);});
