import {test}from 'node:test';import assert from 'node:assert/strict';import{createHash}from 'node:crypto';import {createMigrationTransport,type MigrationHostBinding}from './migration_transport';
import {gzipSync}from 'node:zlib';
import {sourceEvidence as baseEvidence}from '../../test/cn-migration-snapshot.fixture';
import {providerIdentityDigest}from '../cn-migration-source-identity';
import {migrationLedgerDigest}from '../cn-migration-snapshot';
import type {ExactMigrationInputs}from './reused_actions';
const canonical=(v:any):string=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
function fixture(){
 const identity={sourceRevision:'9b25bfa65662b96c0826fe67506b562ea46aa6d0',baselineRevision:'ba6343199f3c834d6a198f83d0c771614292c82b',migrationPlanSha256:'c'.repeat(64),attemptId:'one'};
 const cfg={host:'private.rds.example',port:5432,database:'workspacex',user:'migration_owner',password:'fixture-password',ssl:{rejectUnauthorized:true,ca:'fixture-ca'},connectionTimeoutMillis:1000,statement_timeout:1000};const raw=JSON.stringify(cfg);const root=`/etc/workspacex-cn/maintenance-migration/${identity.sourceRevision}/one`;
 const binding:MigrationHostBinding={identity,toolRevision:'f'.repeat(40),ddlSource:undefined,ddlSourceEvidence:undefined,configPath:root+'/config.json',configSha256:hash(raw),completionPath:`/etc/workspacex-cn/migration-completion-inputs/${identity.sourceRevision}/one.json`,collector:{path:'/usr/local/lib/workspacex-cn/collect-cn-migration-snapshot.py',sha256:'d'.repeat(64)},writerPlanPath:root+'/writer.json',writerPlanSha256:'e'.repeat(64),writerPlanCanonicalSha256:'9'.repeat(64),writerFence:{path:'/usr/local/lib/workspacex-cn/host_transport.py',sha256:'f'.repeat(64)},lockTimeoutMs:1000};
 const source={accountId:'account',regionId:'cn-shanghai',dbInstanceId:'pgm-uf6rg214cp381l49',database:cfg.database,user:cfg.user,endpointSha256:hash(cfg.host+':'+cfg.port),serverAddressSha256:null,port:null,identityLane:'aliyun-private-endpoint',clientPeerAddressSha256:'a'.repeat(64),clientPeerPort:5432,configurationSha256:'b'.repeat(64),providerEvidenceSha256:'c'.repeat(64),sslMode:'verify-full',clientEncrypted:true,clientTlsAuthorized:true};
 const evidence=structuredClone(baseEvidence);Object.assign(evidence.request,{regionId:source.regionId,dbInstanceId:source.dbInstanceId});Object.assign(evidence.configuration,{regionId:source.regionId,rdsInstanceId:source.dbInstanceId,sha256:source.configurationSha256,host:cfg.host,port:cfg.port,database:cfg.database,user:cfg.user,endpointSha256:source.endpointSha256});evidence.stsResponse.AccountId=source.accountId;Object.assign(evidence.attributeResponse.Items.DBInstanceAttribute[0]!,{DBInstanceId:source.dbInstanceId,RegionId:source.regionId,ConnectionString:cfg.host,Port:String(cfg.port)});Object.assign(evidence.netInfoResponse.DBInstanceNetInfos.DBInstanceNetInfo[0]!,{ConnectionString:cfg.host,Port:String(cfg.port)});source.clientPeerAddressSha256=hash('10.0.0.8');source.providerEvidenceSha256=providerIdentityDigest(evidence);
 binding.ddlSource=structuredClone(source);binding.ddlSourceEvidence=structuredClone(evidence);source.user='maintenance_diag_ro';evidence.configuration.user=source.user;
 const inputs={checkout:'/var/lib/workspacex-cn/releases/'+identity.sourceRevision,plan:{ledger:[{name:'base.sql',checksum:'b'.repeat(64)}]},expectedCompletion:{productionSource:source}}as unknown as ExactMigrationInputs;
 let now=Date.now();let migrated=0;const calls:string[]=[];let captured=now;
 const barrier=async()=>({stdout:JSON.stringify({schemaVersion:1,kind:'maintenance-writers-held',ready:false,identity,planSha256:binding.writerPlanCanonicalSha256,observedAt:now/1000,databaseSessionsSha256:'d'.repeat(64),families:['http','socket','queue','background','agent','checkpoint','memory','privileged']})});
 const overrides={verifyCompletion:(async()=>({fixture:true})) as any,persist:async()=>{},now:()=>now,read:(path:string)=>Buffer.from(path===binding.configPath?raw:JSON.stringify({expected:inputs.expectedCompletion,snapshotInput:{capturedAt:new Date(captured).toISOString()},bindingInput:{},sourceEvidence:evidence})),verifyExecutable:()=>{},runBash:async(_command:any,args:readonly string[])=>{if(args[0]==='--preflight-completion')return{stdout:JSON.stringify({schemaVersion:1,kind:'migration-collector-preflight',identity,toolRevision:'f'.repeat(40),querySha256:hash('/usr/bin/node /usr/local/lib/workspacex-cn/cn-migration-snapshot-query.cjs --readonly-ledger '+identity.sourceRevision+' '+identity.attemptId+'\n'),ready:false})};calls.push(...args);const ledger=[{name:'base.sql',checksum:'b'.repeat(64)},{name:'one.sql',checksum:'a'.repeat(64)}];const cloud={ecsInstanceId:'ecs',invokeId:'inv',commandId:'cmd',querySha256:'d'.repeat(64)};const sql={schemaVersion:2,kind:'cn-migration-ledger-output',querySha256:cloud.querySha256,readOnly:true,transactionIsolation:'repeatable read',source,independentSqlCount:2,ledger,ledgerSha256:migrationLedgerDigest(ledger)};const provider={RequestId:'fixture',Invocation:{TotalCount:1,InvocationResults:{InvocationResult:[{InstanceId:cloud.ecsInstanceId,InvokeId:cloud.invokeId,CommandId:cloud.commandId,Dropped:0,InvocationStatus:'Success',ExitCode:0,FinishedTime:new Date(captured).toISOString(),Output:Buffer.from('WSX_CN_MIGRATION_SNAPSHOT_V2='+gzipSync(JSON.stringify(sql)).toString('base64')+'\n').toString('base64')}]}}};const bytes=JSON.stringify(provider);return{stdout:JSON.stringify({schemaVersion:1,providerResponseBase64:Buffer.from(bytes).toString('base64'),providerResponseSha256:hash(bytes),cloud})};}};
 const admission:any={schemaVersion:2,phase:'prebuild',buildStarted:false,sourceSha:identity.sourceRevision,baselineSha:identity.baselineRevision,attemptId:identity.attemptId,release:'2026.10.3-cn.1',issuedAt:new Date(now-1000).toISOString(),expiresAt:new Date(now+60000).toISOString(),checks:{'bootstrap.compatibility':{status:'passed',evidenceSha256:'a'.repeat(64),metadata:{evidenceMode:'source-static',baselineSha:identity.baselineRevision,migrationPlanSha256:identity.migrationPlanSha256,baselineSchemaSha256:'d'.repeat(64),baselineLedgerContract:true,baselineSchemaContract:true,baselinePermissionContract:true,candidateSchemaContract:false,buildAdmissionOnly:true,productionWriteStatements:0}}}};
 const validatedAdmission=()=>({...Object.fromEntries(['sourceSha','baselineSha','attemptId','release','issuedAt','expiresAt'].map(k=>[k,admission[k]])),schemaVersion:2,phase:'prebuild',ready:true,blockers:[],receiptSha256:hash(canonical(admission))});
 const originalRead=overrides.read;overrides.read=(path:string)=>path.endsWith('/prebuild.json')?Buffer.from(JSON.stringify(admission)):path.endsWith('/prebuild.validated.json')?Buffer.from(JSON.stringify(validatedAdmission())):originalRead(path);
 const lifecycle={recordMigrationCompletion:async()=>{},migrateExactPlan:async()=>{migrated++;return{applied:['one.sql'],skipped:['base.sql']};},readDiagnosticLedger:async()=>({ledger:migrated?[{name:'base.sql',checksum:'b'.repeat(64)},{name:'one.sql',checksum:'a'.repeat(64)}]:[{name:'base.sql',checksum:'b'.repeat(64)}],rowCount:migrated?2:1,connection:{role:source.user,peer:{database:source.database,serverAddr:null,serverPort:5432},socket:{remoteAddress:'10.0.0.8',remotePort:5432,encrypted:true,authorized:true,localAddress:'10.0.1.5'}}})};
 return{identity,binding,inputs,overrides,lifecycle,barrier,calls,admission,count:()=>migrated,setCaptured:(value:number)=>{captured=value;},now};
}
test('actual pinned migrator call receives explicit directory and no force/provision',async()=>{const f=fixture();const t=createMigrationTransport(f.inputs,f.binding,f.barrier,f.lifecycle,f.overrides);assert.deepEqual(await t.migrate(),{applied:['one.sql'],skipped:['base.sql']});await t.readFreshCompletion();assert.equal(f.count(),1);assert.deepEqual(f.calls,['--maintenance-completion',f.identity.sourceRevision,'one',f.identity.migrationPlanSha256]);});
test('missing trusted collector prevents DDL',async()=>{const f=fixture();const t=createMigrationTransport(f.inputs,f.binding,f.barrier,f.lifecycle,{...f.overrides,verifyExecutable:()=>{throw new Error('collector-missing');}});await assert.rejects(t.migrate(),/collector-missing/);assert.equal(f.count(),0);});
test('stale writer guard prevents migration',async()=>{const f=fixture();const stale=async()=>({stdout:JSON.stringify({schemaVersion:1,kind:'maintenance-writers-held',ready:false,identity:f.identity,planSha256:f.binding.writerPlanCanonicalSha256,observedAt:(f.now-31000)/1000,databaseSessionsSha256:'d'.repeat(64),families:['http','socket','queue','background','agent','checkpoint','memory','privileged']})});const t=createMigrationTransport(f.inputs,f.binding,stale,f.lifecycle,f.overrides);await assert.rejects(t.migrate(),/LIVE_WRITER_BARRIER_INVALID/);assert.equal(f.count(),0);});
test('preexisting completion cannot prove current migration',async()=>{const f=fixture();f.setCaptured(f.now-1);const t=createMigrationTransport(f.inputs,f.binding,f.barrier,f.lifecycle,f.overrides);await t.migrate();await assert.rejects(t.readFreshCompletion(),/NOT_FROM_THIS_EXECUTION/);});
test('completion before migration is rejected without collector invocation',async()=>{const f=fixture();const t=createMigrationTransport(f.inputs,f.binding,f.barrier,f.lifecycle,f.overrides);await assert.rejects(t.readFreshCompletion(),/BEFORE_MIGRATION/);assert.equal(f.calls.length,0);});
test('configuration endpoint mismatch rejects before DDL',async()=>{const f=fixture();(f.binding.ddlSource as any).endpointSha256='0'.repeat(64);assert.throws(()=>createMigrationTransport(f.inputs,f.binding,f.barrier,f.lifecycle,f.overrides),/DDL_DIAGNOSTIC_TARGET_MISMATCH/);assert.equal(f.count(),0);});
test('reentry rejects repeated migration',async()=>{const f=fixture();const t=createMigrationTransport(f.inputs,f.binding,f.barrier,f.lifecycle,f.overrides);await t.migrate();await assert.rejects(t.migrate(),/REENTRY_FORBIDDEN/);assert.equal(f.count(),1);});

import {verifyMigrationPeer}from './pinned-app-9b/migration-pg';
test('SQL/socket/TLS mismatch rejected before migrator writes',()=>{const f=fixture();const source=f.inputs.expectedCompletion.productionSource as any;const observed={database:'workspacex',user:source.user,serverAddress:null,serverPort:5432,remoteAddress:'10.0.0.1',remotePort:5432,encrypted:true,authorized:true};source.clientPeerAddressSha256=hash(observed.remoteAddress);assert.doesNotThrow(()=>verifyMigrationPeer(source,observed));for(const patch of [{database:'other'},{user:'app_rw'},{encrypted:false},{authorized:false},{remoteAddress:'10.0.0.2'}])assert.throws(()=>verifyMigrationPeer(source,{...observed,...patch}),/LIVE_DATABASE_PEER_MISMATCH/);});
test('existing noTLS exception requires exact provider evidence approval and actual source CIDR',async()=>{
 const {verifyMigrationPeer}=await import('./pinned-app-9b/migration-pg');const evidence=structuredClone(baseEvidence) as any;const exception={kind:'aliyun-postgresql-serverless-no-tls',allowedCidrs:['10.0.0.0/8']};evidence.configuration.sslMode='disable';evidence.configuration.rdsTlsException=exception;
 const original=(await import('../../test/cn-migration-snapshot.fixture')).binding.source;const source={...original,sslMode:'disable' as const,clientEncrypted:false,clientTlsAuthorized:false,providerEvidenceSha256:providerIdentityDigest(evidence)};
 const observed={database:source.database,user:source.user,serverAddress:'fixture-server',serverPort:5432,remoteAddress:'10.0.0.8',remotePort:5432,encrypted:false,authorized:false,localAddress:'10.0.1.5'};source.serverAddressSha256=hash(observed.serverAddress);
 assert.doesNotThrow(()=>verifyMigrationPeer(source,observed,{sourceEvidence:evidence,approvedRdsTlsException:exception}));
 assert.throws(()=>verifyMigrationPeer(source,observed));
 assert.throws(()=>verifyMigrationPeer(source,observed,{sourceEvidence:evidence,approvedRdsTlsException:{...exception,allowedCidrs:['192.168.0.0/16']}}));
 assert.throws(()=>verifyMigrationPeer(source,{...observed,localAddress:'192.168.0.1'},{sourceEvidence:evidence,approvedRdsTlsException:exception}),/SOURCE_CIDR_MISMATCH/);
 assert.throws(()=>verifyMigrationPeer({...source,sslMode:'verify-full',clientEncrypted:true,clientTlsAuthorized:true},observed,{sourceEvidence:evidence,approvedRdsTlsException:exception}),/LIVE_DATABASE_PEER_MISMATCH/);
});
import shim,{withExistingMigrationPeer}from './pinned-app-9b/migration-pg';
import{mkdtempSync,chmodSync,readFileSync,lstatSync,rmSync}from 'node:fs';import{tmpdir}from 'node:os';import{join}from 'node:path';import{publishMigrationReceipt}from './migration_transport';
test('borrowed persistent Client never reconnects or closes real NOLOGIN session',async()=>{const f=fixture();const source=f.binding.ddlSource as any;let connects=0,ends=0,queries=0;const client={connect:async()=>{connects++;throw new Error('must not reconnect');},end:async()=>{ends++;},connection:{stream:{remoteAddress:'10.0.0.8',remotePort:5432,localAddress:'10.0.1.5',encrypted:true,authorized:true}},query:async(sql:string)=>{queries++;return{rows:sql.startsWith('SELECT current_database')?[{database:source.database,user:source.user,serverAddress:null,serverPort:5432}]:[]};}};
 await withExistingMigrationPeer(client as any,source,async()=>{const borrowed=new shim.Client({});await borrowed.connect();await borrowed.query('SELECT 1');await borrowed.end();});assert.equal(connects,0);assert.equal(ends,0);assert.equal(queries,2);
});
test('completed receipt atomically publishes private unique file and never overwrites',()=>{const directory=mkdtempSync(join(tmpdir(),'wsx-completed-receipt-'));chmodSync(directory,0o700);const path=join(directory,'one.completed.json');const owner={uid:process.getuid!(),gid:process.getgid!(),boundary:directory};try{publishMigrationReceipt(path,Buffer.from('{"one":1}\n'),owner);assert.equal(lstatSync(path).nlink,1);assert.equal(lstatSync(path).mode&0o777,0o600);assert.throws(()=>publishMigrationReceipt(path,Buffer.from('replacement'),owner));assert.equal(readFileSync(path,'utf8'),'{"one":1}\n');}finally{rmSync(directory,{recursive:true});}});
test('full completion verifier rejection never journals or publishes success receipt',async()=>{const f=fixture();const events:string[]=[];const lifecycle={...f.lifecycle,recordMigrationCompletion:async(_id:any,stage:string)=>{events.push(stage);}};const t=createMigrationTransport(f.inputs,f.binding,f.barrier,lifecycle,{...f.overrides,verifyCompletion:async()=>{throw new Error('real-verifier-rejected');},persist:async()=>{events.push('publish');}});await t.migrate();await assert.rejects(t.readFreshCompletion(),/real-verifier-rejected/);assert.deepEqual(events,[]);});
test('journal intent precedes publish and durable follows actual receipt',async()=>{const f=fixture();const events:string[]=[];const lifecycle={...f.lifecycle,recordMigrationCompletion:async(_id:any,stage:string)=>{events.push(stage);}};const t=createMigrationTransport(f.inputs,f.binding,f.barrier,lifecycle,{...f.overrides,persist:async()=>{events.push('publish');}});await t.migrate();await t.readFreshCompletion();assert.deepEqual(events,['intent','publish','durable']);});

for(const [name,change] of Object.entries({artifact:(v:any)=>{v.phase='artifact-build';},expired:(v:any)=>{v.expiresAt=v.issuedAt;},wrongPlan:(v:any)=>{v.checks['bootstrap.compatibility'].metadata.migrationPlanSha256='0'.repeat(64);},wrongSource:(v:any)=>{v.sourceSha='0'.repeat(40);},wrongBaseline:(v:any)=>{v.baselineSha='0'.repeat(40);},wrongAttempt:(v:any)=>{v.attemptId='other';},missingSchema:(v:any)=>{delete v.checks['bootstrap.compatibility'].metadata.baselineSchemaSha256;},missingLedger:(v:any)=>{v.checks['bootstrap.compatibility'].metadata.baselineLedgerContract=false;}}))test('baseline admission rejects '+name+' before any DDL',async()=>{const f=fixture();change(f.admission);const t=createMigrationTransport(f.inputs,f.binding,f.barrier,f.lifecycle,f.overrides);await assert.rejects(t.migrate(),/BASELINE_ADMISSION_INVALID/);assert.equal(f.count(),0);});
test('missing protected baseline receipt and tampered validated hash reject before DDL',async()=>{for(const missing of [true,false]){const f=fixture(),read=f.overrides.read;const overrides={...f.overrides,read:(p:string)=>{if(p.endsWith('/prebuild.validated.json')){if(missing)throw Error('baseline-receipt-missing');const v=JSON.parse(read(p).toString());v.receiptSha256='0'.repeat(64);return Buffer.from(JSON.stringify(v));}return read(p);}};const t=createMigrationTransport(f.inputs,f.binding,f.barrier,f.lifecycle,overrides);await assert.rejects(t.migrate(),/baseline-receipt-missing|BASELINE_ADMISSION_INVALID/);assert.equal(f.count(),0);}});
