import {test} from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {verifyOfflineManifest,localImageInspectionArgs} from './offline_artifacts';
const id={sourceRevision:'a'.repeat(40),baselineRevision:'b'.repeat(40),migrationPlanSha256:'c'.repeat(64),attemptId:'one'};const services=['web','api','agent','sandbox','postgres','redis'];const image='example.test/wsx@sha256:'+'d'.repeat(64);const bytes=Buffer.from(JSON.stringify({schemaVersion:1,release:'1.0.0',sourceRevision:id.sourceRevision,platform:'linux/amd64',images:Object.fromEntries(services.map(s=>[s,{image}]))}));const hash=createHash('sha256').update(bytes).digest('hex'),runtime={path:'/usr/bin/docker' as const,sha256:'e'.repeat(64)};
function output(revision=id.sourceRevision){return JSON.stringify([{Os:'linux',Architecture:'amd64',RepoDigests:[image],Config:{Labels:{'org.opencontainers.image.revision':revision}}}]);}
test('offline verification independently inspects six local immutable images',async()=>{const calls:string[]=[];await verifyOfflineManifest(id,bytes,hash,runtime,async(_,i)=>{calls.push(i);return output();})();assert.equal(calls.length,6);});
test('artifact bytes changed stops before image inspection',async()=>{let calls=0;await assert.rejects(verifyOfflineManifest(id,Buffer.concat([bytes,Buffer.from(' ')]),hash,runtime,async()=>{calls++;return output();})(),/MANIFEST_HASH/);assert.equal(calls,0);});
test('foreign application image fails actual existing image validator',async()=>{await assert.rejects(verifyOfflineManifest(id,bytes,hash,runtime,async()=>output('f'.repeat(40)))(),/REVISION_MISMATCH/);});
test('wrong manifest source stops without invoking transport',async()=>{await assert.rejects(verifyOfflineManifest({...id,sourceRevision:'f'.repeat(40)},bytes,hash,runtime,async()=>{throw Error('called');})(),/APPLICATION_IDENTITY/);});

test('production argv binds local Unix daemon and empty protected config',()=>{assert.deepEqual(localImageInspectionArgs(image),['--config','/etc/workspacex-cn/docker-offline','--host','unix:///run/docker.sock','image','inspect',image]);assert.throws(()=>localImageInspectionArgs('--context remote'),/REFERENCE/);});
