import {test}from 'node:test';import assert from 'node:assert/strict';import {createProductionConsumers,type ConsumerRuntime}from './production_consumers';import type {EntryPlan}from './entry';
const id={sourceRevision:'a'.repeat(40),baselineRevision:'b'.repeat(40),migrationPlanSha256:'c'.repeat(64),attemptId:'one'},h='d'.repeat(64),tool='e'.repeat(40);
const command=(name:string)=>({path:'/usr/local/lib/workspacex-cn/'+name,sha256:h});
function fixture(){
 const events:string[]=[];let resumed=false;const host={identity:id,writerPlanPath:'/etc/workspacex-cn/writer.json',writerPlanSha256:h,writerPlanCanonicalSha256:h,hold:command('hold.py'),writerFence:command('host_transport.py')};
 const migrationBinding={identity:id,collector:command('collect.py'),writerFence:host.writerFence};const activationBinding={identity:id,toolRevision:tool,activationCommand:command('activation.py'),recoveryCommand:command('recovery.py')};
 const data={schemaVersion:1,identity:id,toolRevision:tool,prepared:{receipt:{path:'/etc/workspacex-cn/receipt.json',sha256:h},manifest:{path:'/etc/workspacex-cn/manifest.json',sha256:h}},migration:{inputs:{path:'/etc/workspacex-cn/migration.json',sha256:h},binding:migrationBinding},activation:activationBinding,recoveryAudit:{verifier:command('cn-maintenance-recovery-evidence-verifier.py'),evidenceSha256:h},dockerRuntime:{path:'/usr/bin/docker',sha256:h},dynamic:{collector:command('collect-cn-release-preflight.sh'),verifier:command('verify-cn-release-preflight.sh'),release:'1.0.0'},writerModules:{writer_fence:command('writer_fence.py'),fixed_probes:command('fixed_probes.py'),control_connection:command('control_connection.py')}};
 const plan={identity:id,host,production:{toolRevision:tool},consumerInputsPath:'/etc/workspacex-cn/consumers.json',consumerInputsSha256:h} as EntryPlan;
 const profile={installedFilesSha256:Object.fromEntries([host.writerFence,...Object.values(data.writerModules),data.recoveryAudit.verifier,data.dynamic.collector,data.dynamic.verifier,migrationBinding.collector,activationBinding.activationCommand,activationBinding.recoveryCommand].map(c=>[c.path,c.sha256]))};
 const io:Partial<ConsumerRuntime>={assertActivationCapability:()=>{},readJson:path=>path===plan.consumerInputsPath?data:{},readBytes:()=>Buffer.from('{}'),verifyExecutable:()=>{},acquireLock:async()=>async()=>{events.push('unlock');},migration:(_i,b)=>{return {migrate:async()=>({applied:[],skipped:[]}),readFreshCompletion:async()=>({snapshot:{},binding:{}}),verifyLiveWriterBarrier:async()=>{assert.equal(b.writerPlanSha256,'f'.repeat(64));}};},activation:()=>({} as any),lifecycle:()=>({readRunDrain:async()=>({queued:0,running:0,writebackPending:0}),recordMigrationCompletion:async()=>{},migrateExactPlan:async()=>({applied:[],skipped:[]}),readDiagnosticLedger:async()=>({ledger:[],rowCount:0,connection:{},observedAt:0}),start:async()=>{events.push('start');return {...host,writerPlanPath:'/var/lib/workspacex-cn/runtime/one/seal.json',writerPlanSha256:'f'.repeat(64)};},invoke:async cb=>{events.push(cb);if(cb==='verifyWritesResumed')resumed=true;return {stdout:'{}'};},closeAfterAccepted:async()=>{if(!resumed)throw Error('unknown');events.push('close');},retainUnknown:()=>{events.push('retain');}})};
 return {events,plan,profile,io,host};
}
test('prehold failure releases inherited lock without starting database lifecycle',async()=>{const f=fixture(),c=await createProductionConsumers(f.plan,f.profile,f.io);const release=await c.acquireLock();await release();assert.deepEqual(f.events,['unlock']);});
test('first writer callback starts once, seals host/migration and closes before unlock',async()=>{const f=fixture(),c=await createProductionConsumers(f.plan,f.profile,f.io);await c.run(c.host.writerFence,['--apply-reviewed-fence',c.host.writerPlanPath,c.host.writerPlanSha256,'blockAllWrites']);assert.equal(c.host.writerPlanSha256,'f'.repeat(64));await c.inputs.migrationTransport.verifyLiveWriterBarrier();await c.run(c.host.writerFence,['--apply-reviewed-fence',c.host.writerPlanPath,c.host.writerPlanSha256,'verifyWritesResumed']);await(await c.acquireLock())();assert.deepEqual(f.events,['start','blockAllWrites','verifyWritesResumed','close','unlock']);});
test('unknown writer lifecycle retains lock and never unlocks',async()=>{const f=fixture(),c=await createProductionConsumers(f.plan,f.profile,f.io);await c.run(c.host.writerFence,['--apply-reviewed-fence',c.host.writerPlanPath,c.host.writerPlanSha256,'blockAllWrites']);await assert.rejects((await c.acquireLock())(),/unknown/);assert.equal(f.events.includes('unlock'),false);});
test('foreign installed hash rejects before any lifecycle start',async()=>{const f=fixture();f.profile.installedFilesSha256[f.host.writerFence.path]='0'.repeat(64);await assert.rejects(createProductionConsumers(f.plan,f.profile,f.io),/PROFILE_BINDING/);assert.deepEqual(f.events,[]);});

test('unresolved acceptance writer contract rejects default startup before commands/lock',async()=>{const f=fixture();delete f.io.assertActivationCapability;await assert.rejects(createProductionConsumers(f.plan,f.profile,f.io),/ACCEPTANCE_WRITER_LANE_NOT_IMPLEMENTED/);assert.deepEqual(f.events,[]);});
