import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {validateApiWsObjectstoreCiEvidence,validateCapturedVendorCiEvidence,validateIntegratedLaneArtifact} from './board-integrated-ci-policy.mjs';

const sha='a'.repeat(40),hash='b'.repeat(64),context={runtimeMarker:'11111111-1111-4111-8111-111111111111',startedAt:'2026-09-28T00:00:00.000Z',endedAt:'2026-09-28T00:01:00.000Z'};
const runtime={sha,buildSha:sha,dirty:false,method:'fresh-server-marker-and-built-chunk-hashes',deploymentMarker:context.runtimeMarker,runStartedAt:context.startedAt,buildCreatedAt:context.startedAt,buildId:'build',chunks:[{url:'/chunk.js',sha256:hash,localSha256:hash}]};
function fixture(values){const root=mkdtempSync(join(tmpdir(),'board-integrated-')),rows=[];for(const group of values){const attachments=[];for(const [name,value] of Object.entries(group)){const bytes=Buffer.from(JSON.stringify(value)),path=join(root,`${rows.length}-${name.replaceAll('/','_')}`);writeFileSync(path,bytes);attachments.push({name,path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});}rows.push({results:[{attachments}]});}return{root,report:{suites:[{specs:[{tests:rows}]}]}};}
let fixtureIndex=0;const captured=()=>{const index=fixtureIndex++;return{source:index===1?'mural':'miro',name:`board-${index}`,sourceHash:crypto.randomUUID().replaceAll('-','').padEnd(64,'0'),classification:'captured-account-export',realBoardAcceptance:'requires-source-evidence-review',sourceEvidence:['reviewed-redaction'],accepted:{seq:3,report:{counts:{accepted:1}}},replay:{seq:3,replayed:true},report:{counts:{accepted:1}},localEvidence:{initialHash:hash,reloadedHash:hash,peerHash:hash},portableEvidence:{bundleSha256:hash,accepted:{seq:2},replay:{seq:2,replayed:true},ownerLocalHash:hash,peerLocalHash:hash}};};

test('captured vendor policy requires three persisted fixtures and exact runtime',()=>{const f=fixture([{'captured-vendor-evidence.json':{version:1,kind:'captured-vendor-import',fixtures:[captured(),captured(),captured()]},'captured-vendor-runtime.json':{scenario:'captured-vendor-import',runtimeIdentity:runtime}}]);try{assert.equal(validateCapturedVendorCiEvidence(f.report,sha,context,f.root).valid,true);f.report.suites[0].specs[0].tests[0].results[0].attachments.pop();assert.equal(validateCapturedVendorCiEvidence(f.report,sha,context,f.root).valid,false);}finally{rmSync(f.root,{recursive:true,force:true});}});

test('API websocket objectstore policy requires all four independent producers and observed AI behavior',()=>{const names=['Create','Update','Move','Arrange','Connect','Delete','Post-recovery event','Parent','Undo','Redo'],agent={kind:'board-agent-api',sha,runtime:{deploymentMarker:context.runtimeMarker},steps:names.map(name=>({name})),eventCount:12},ai={version:1,kind:'board-ai-api',proposal:{id:'00000000-0000-4000-8000-000000000111',previewStatus:'preview',confirmedStatus:'confirmed'},artifact:{artifactId:'artifact-board-layout-fixture',sourceRevision:'artifact-v1:1',layoutHash:`layout-v1:${hash}`,expectedRevision:{epoch:1,seq:2},committedRevision:{epoch:1,seq:3}},events:{types:['ObjectCreated','AIOrganized','ObjectCreated'],nextSeq:3,artifactLayoutHash:`layout-v1:${hash}`},meetingRoom:{roomId:'e2e-room',joinedActorId:'room:e2e-room:meeting-room-display',handoffActorId:'room:e2e-room:meeting-room-display'},follower:{enteredFollowMode:true,leftFollowMode:true}},outbox={status:'passed',transport:{dropped:0},revisions:{before:0,after:8},afterReloadSeq:8,http:[{status:200}]},portable={canonicalEquivalent:true,replay:{replayed:true,seq:2},accepted:{seq:2},images:[{hash,pixelHash:hash,width:4,height:4}]},race={blockedBeforeRevocationCommit:true,status:404,metadataUnchanged:true},rows=[{'agent-api-evidence':agent},{'ai-api-evidence':ai},{'same-browser-outbox-evidence':outbox},{'portable-roundtrip':portable,'portable-revocation-race':race,'api-ws-objectstore-runtime.json':{scenario:'api-ws-objectstore',runtimeIdentity:runtime}}],f=fixture(rows),bad=fixture([rows[0],{'ai-api-evidence':{...ai,follower:{...ai.follower,leftFollowMode:false}}},rows[2],rows[3]]);try{assert.equal(validateApiWsObjectstoreCiEvidence(f.report,sha,context,f.root).valid,true);assert.equal(validateApiWsObjectstoreCiEvidence(bad.report,sha,context,bad.root).valid,false);f.report.suites[0].specs[0].tests[3].results[0].attachments=f.report.suites[0].specs[0].tests[3].results[0].attachments.filter(row=>row.name!=='portable-revocation-race');assert.equal(validateApiWsObjectstoreCiEvidence(f.report,sha,context,f.root).valid,false);}finally{rmSync(f.root,{recursive:true,force:true});rmSync(bad.root,{recursive:true,force:true});}});

test('unified artifact stays closed for failures, pending review or runtime mismatch',()=>{const report={version:1,kind:'board-integrated-lane',lane:'storage',sha,...context,status:'engineering-checks-passed',counterproof:true,runtimeIdentity:runtime,failures:[],pending:[]};assert.equal(validateIntegratedLaneArtifact(report,'storage',sha,context).valid,true);report.pending=['operator-review'];assert.equal(validateIntegratedLaneArtifact(report,'storage',sha,context).valid,false);report.pending=[];report.runtimeIdentity={...runtime,buildSha:'c'.repeat(40)};assert.equal(validateIntegratedLaneArtifact(report,'storage',sha,context).valid,false);});
