import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {validateApiWsObjectstoreCiEvidence,validateCapturedVendorCiEvidence,validateIntegratedLaneArtifact} from './board-integrated-ci-policy.mjs';

const sha='a'.repeat(40),hash='b'.repeat(64),context={runtimeMarker:'11111111-1111-4111-8111-111111111111',startedAt:'2026-09-28T00:00:00.000Z',endedAt:'2026-09-28T00:01:00.000Z'};
const runtime={sha,buildSha:sha,dirty:false,method:'fresh-server-marker-and-built-chunk-hashes',deploymentMarker:context.runtimeMarker,runStartedAt:context.startedAt,buildCreatedAt:context.startedAt,buildId:'build',chunks:[{url:'/chunk.js',sha256:hash,localSha256:hash}]};
function fixture(values){const root=mkdtempSync(join(tmpdir(),'board-integrated-')),rows=[];for(const group of values){const attachments=[];for(const [name,value] of Object.entries(group)){const bytes=Buffer.from(JSON.stringify(value)),path=join(root,`${rows.length}-${name.replaceAll('/','_')}`);writeFileSync(path,bytes);attachments.push({name,path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});}rows.push({results:[{attachments}]});}return{root,report:{suites:[{specs:[{tests:rows}]}]}};}
const captured=()=>({sourceHash:crypto.randomUUID().replaceAll('-','').padEnd(64,'0'),classification:'captured-account-export',realBoardAcceptance:'requires-source-evidence-review',sourceEvidence:['reviewed-redaction'],accepted:{seq:3,report:{counts:{accepted:1}}},replay:{seq:3,replayed:true},report:{counts:{accepted:1}},localEvidence:{initialHash:hash,reloadedHash:hash,peerHash:hash},portableEvidence:{bundleSha256:hash,accepted:{seq:2},replay:{seq:2,replayed:true},ownerLocalHash:hash,peerLocalHash:hash}});

test('captured vendor policy requires three persisted fixtures and exact runtime',()=>{const f=fixture([{'captured-vendor-evidence.json':{version:1,kind:'captured-vendor-import',fixtures:[captured(),captured(),captured()]},'captured-vendor-runtime.json':{scenario:'captured-vendor-import',runtimeIdentity:runtime}}]);try{assert.equal(validateCapturedVendorCiEvidence(f.report,sha,context,f.root).valid,true);f.report.suites[0].specs[0].tests[0].results[0].attachments.pop();assert.equal(validateCapturedVendorCiEvidence(f.report,sha,context,f.root).valid,false);}finally{rmSync(f.root,{recursive:true,force:true});}});

test('API websocket objectstore policy requires all three independent producers',()=>{const agent={kind:'board-agent-api',sha,runtime:{deploymentMarker:context.runtimeMarker},steps:Array.from({length:10},(_,i)=>({name:String(i)})),eventCount:12},outbox={status:'passed',transport:{dropped:0},revisions:{before:0,after:8},afterReloadSeq:8,http:[{status:200}]},portable={canonicalEquivalent:true,replay:{replayed:true,seq:2},accepted:{seq:2},images:[{hash,pixelHash:hash,width:4,height:4}]},race={blockedBeforeRevocationCommit:true,status:404,metadataUnchanged:true};const f=fixture([{'agent-api-evidence':agent},{'same-browser-outbox-evidence':outbox},{'portable-roundtrip':portable,'portable-revocation-race':race,'api-ws-objectstore-runtime.json':{scenario:'api-ws-objectstore',runtimeIdentity:runtime}}]);try{assert.equal(validateApiWsObjectstoreCiEvidence(f.report,sha,context,f.root).valid,true);f.report.suites[0].specs[0].tests[2].results[0].attachments=f.report.suites[0].specs[0].tests[2].results[0].attachments.filter(row=>row.name!=='portable-revocation-race');assert.equal(validateApiWsObjectstoreCiEvidence(f.report,sha,context,f.root).valid,false);}finally{rmSync(f.root,{recursive:true,force:true});}});

test('unified artifact stays closed for failures, pending review or runtime mismatch',()=>{const report={version:1,kind:'board-integrated-lane',lane:'storage',sha,...context,status:'engineering-checks-passed',counterproof:true,runtimeIdentity:runtime,failures:[],pending:[]};assert.equal(validateIntegratedLaneArtifact(report,'storage',sha,context).valid,true);report.pending=['operator-review'];assert.equal(validateIntegratedLaneArtifact(report,'storage',sha,context).valid,false);report.pending=[];report.runtimeIdentity={...runtime,buildSha:'c'.repeat(40)};assert.equal(validateIntegratedLaneArtifact(report,'storage',sha,context).valid,false);});
