import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import {tsImport} from 'tsx/esm/api';import {validateStorageCiEvidence} from './board-storage-ci-policy.mjs';
const sha='a'.repeat(40),hash='b'.repeat(64),context={runtimeMarker:'marker',startedAt:'2026-09-27T00:00:00Z',endedAt:'2026-09-27T01:00:00Z'},runtime={sha,buildSha:sha,dirty:false,method:'fresh-server-marker-and-built-chunk-hashes',buildId:'build',deploymentMarker:'marker',runStartedAt:context.startedAt,buildCreatedAt:context.startedAt,chunks:[{url:'/chunk.js',sha256:hash,localSha256:hash}]};
async function fixture(dir){
 const {loadVendorSchemaFixture}=await tsImport(new URL('../e2e/support/board-vendor-schema-fixtures.ts',import.meta.url).href,import.meta.url);const rows=[];
 const row=(scenario,entries)=>{const attachments=Object.entries({'storage-runtime.json':{scenario,runtimeIdentity:runtime,assetId:'asset',targetBoardId:'target'},...entries}).map(([name,value],i)=>{const bytes=Buffer.isBuffer(value)?value:Buffer.from(JSON.stringify(value)),path=join(dir,`${scenario}-${i}`);writeFileSync(path,bytes);return{name,path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};});rows.push({results:[{attachments}]});};
 const pg=ids=>({assets:ids.map(boardId=>({boardId,key:`/boards/${boardId}/assets/x`,metadata:{assetId:'asset',persistence:'durable'},active:true})),documents:ids.map(boardId=>({boardId,key:`/boards/${boardId}/snapshot`,hash,size:3,bodyIsNull:true})),inlineUpdates:0,binaryAssetColumns:0});
 row('durable-images',{'canonical-upload':{objects:[{kind:'image',extensionData:{contentObject:{assetId:'asset'}}}]},'pg-independent-pointers':pg(['source','target']),'pg-target-after-source-delete':pg(['target'])});
 for(const name of ['miro-workshop','mural-diagram','miro-media']){const f=await loadVendorSchemaFixture(name),report={executable:true,items:f.expected.map(i=>({sourceId:i.sourceId,outcome:i.outcome,reasonCode:i.reasonCode}))};row(name,{'migration-evidence.json':{boardId:name,roundtripBoardId:name+'-copy',sourceHash:f.sha256,classification:'schema-derived-synthetic',realBoardAcceptance:'diagnostic-only',report,accepted:{seq:1,report},replay:{seq:1,replayed:true},images:f.media.map(m=>({sha256:m.sha256,pixelHash:hash})),localEvidence:{objectCount:f.expected.filter(i=>['success','downgraded'].includes(i.outcome)).length,initialHash:hash,reloadedHash:hash,peerHash:hash},portableEvidence:{bundleSha256:hash,accepted:{seq:1,epoch:1},replay:{seq:1,epoch:1,replayed:true},ownerLocalHash:hash,peerLocalHash:hash,media:f.media.map(m=>({sourceId:m.sourceId,sha256:m.sha256,sizeBytes:1}))}},...Object.fromEntries(['owner-after-refresh.png','independent-peer.png','roundtrip-owner-after-refresh.png','roundtrip-independent-peer.png'].map(n=>[n,Buffer.from([137,80,78,71,13,10,26,10,0])]))});}
 return{suites:[{specs:[{tests:rows}]}]};
}
for(const mutation of ['valid','missing','tampered','runtime','duplicate-fixture','missing-pg','missing-screenshot'])test(`storage persisted evidence ${mutation}`,async()=>{const dir=mkdtempSync(join(tmpdir(),'storage-policy-'));try{const report=await fixture(dir),rows=report.suites[0].specs[0].tests;if(mutation==='missing')rows.pop();if(mutation==='tampered')writeFileSync(rows[0].results[0].attachments[0].path,'{}');if(mutation==='runtime')context.runtimeMarker='wrong';if(mutation==='duplicate-fixture')rows[3]=rows[2];if(mutation==='missing-pg')rows[0].results[0].attachments.pop();if(mutation==='missing-screenshot')rows[1].results[0].attachments.pop();const result=await validateStorageCiEvidence(report,sha,context,dir);assert.equal(result.valid,mutation==='valid',JSON.stringify(result));}finally{context.runtimeMarker='marker';rmSync(dir,{recursive:true,force:true});}});
test('miro media fixture bytes stay identical across producer and verifier processes',()=>{const root=resolve(import.meta.dirname,'../../..'),script="import {loadVendorSchemaFixture} from './apps/web/e2e/support/board-vendor-schema-fixtures.ts'; void loadVendorSchemaFixture('miro-media').then(value=>console.log(value.sha256));",run=()=>execFileSync(process.execPath,['--import','tsx','--input-type=module','-e',script],{cwd:root,encoding:'utf8'}).trim();assert.equal(run(),run());});
