import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {exportConnectorLoginDiagnostics as run,safeConnectorLoginExport as safe} from './connector-login-safe-export.mjs';
function fixture(){const root=mkdtempSync(join(tmpdir(),'c06-safe-')),artifacts=join(root,'artifacts');mkdirSync(artifacts);const head='a'.repeat(40),path=join(artifacts,'attachments','c06-login-fixed-diagnostic-'+ 'a'.repeat(40)+'.json'),row={stage:'C06_LOGIN',sourceHead:head,version:1,httpStatus:200,jsonParsed:true,objectSchema:true,actorString:true,tokenString:true,actorMatches:false,tokenMatches:true};const attachment={name:'c06-login-fixed-diagnostic',contentType:'application/json',path};const spec={file:'board-connector-authority.spec.ts',title:'C06 valid Connector permissions and held gesture authority lifecycle',tests:[{results:[{attachments:[attachment]}]}]};mkdirSync(join(artifacts,'attachments'));writeFileSync(path,JSON.stringify(row));return {root,artifacts,head,path,row,attachment,spec,report:{specs:[spec]}};}
test('exports only fixed fields without claiming success',()=>{const f=fixture();try{const value=run(f.report,f.artifacts,f.head);assert.equal(value.diagnostics[0].actorMatches,false);assert(!('passed' in value));assert(!JSON.stringify(value).includes(f.root));}finally{rmSync(f.root,{recursive:true});}});
test('missing extra foreign and oversized inputs fail closed',()=>{for(const mutate of [f=>f.spec.tests[0].results[0].attachments=[],f=>f.spec.file='foreign.spec.ts',f=>f.row.sourceHead='b'.repeat(40),f=>f.row.secret='PRIVATE_TOKEN',f=>delete f.row.tokenMatches,f=>f.row.actorMatches='PRIVATE_ID',f=>f.row.jsonParsed=false,f=>f.row.padding='x'.repeat(5000),f=>f.report.padding='x'.repeat(8*1024*1024)]){const f=fixture();try{mutate(f);writeFileSync(f.path,JSON.stringify(f.row));assert.throws(()=>run(f.report,f.artifacts,f.head));}finally{rmSync(f.root,{recursive:true});}}});
test('owned path and duplicate receipt fences reject foreign data',()=>{for(const duplicate of [false,true]){const f=fixture();try{if(duplicate)f.spec.tests[0].results[0].attachments.push(f.attachment);else{const foreign=join(f.root,'c06-login-0.json');writeFileSync(foreign,JSON.stringify(f.row));f.attachment.path=foreign;}assert.throws(()=>run(f.report,f.artifacts,f.head));}finally{rmSync(f.root,{recursive:true});}}});

test('safe export distinguishes missing evidence, invalid schema and unknown identity',()=>{const f=fixture();try{f.row.jsonParsed=false;f.row.objectSchema=false;f.row.actorString=false;f.row.tokenString=false;f.row.actorMatches=false;f.row.tokenMatches=false;writeFileSync(f.path,JSON.stringify(f.row));assert.equal(safe(f.report,f.artifacts,f.head).diagnostics[0].code,'C06_LOGIN_JSON_PARSE');f.row.secret='PRIVATE_BODY';writeFileSync(f.path,JSON.stringify(f.row));const invalid=safe(f.report,f.artifacts,f.head);assert.equal(invalid.status,'EXPORT_INVALID');assert(!JSON.stringify(invalid).includes('PRIVATE'));f.spec.tests[0].results[0].attachments=[];assert.equal(safe(f.report,f.artifacts,f.head).status,'NOT_AVAILABLE');}finally{rmSync(f.root,{recursive:true});}});

test('pinned Playwright attach-copy basename is accepted while direct original and foreign prefix are rejected',()=>{const f=fixture();try{assert.equal(safe(f.report,f.artifacts,f.head).status,'EXPORTED');for(const name of ['c06-login-0.json','foreign-'+ 'a'.repeat(40)+'.json','c06-login-fixed-diagnostic-bad.json']){const path=join(f.artifacts,'attachments',name);writeFileSync(path,JSON.stringify(f.row));f.attachment.path=path;const value=safe(f.report,f.artifacts,f.head);assert.equal(value.status,'EXPORT_INVALID');assert.equal(value.reasonCode,'C06_RECEIPT_BASENAME');}}finally{rmSync(f.root,{recursive:true});}});

test('safe export never reads an error code getter',()=>{let reads=0;const error=Object.defineProperty(new Error('PRIVATE_CAUSE'),'code',{get(){reads++;throw new Error('PRIVATE_GETTER');}});const report={toJSON(){throw error;}};const value=safe(report,'unused','a'.repeat(40));assert.equal(reads,0);assert.equal(value.status,'EXPORT_INVALID');assert.equal(value.reasonCode,'C06_EXPORT_UNKNOWN');assert(!JSON.stringify(value).includes('PRIVATE'));});
