import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {BoardOrganizeControls} from '@/components/whiteboard/board-organize-controls';
const calls=vi.hoisted(()=>({actors:vi.fn(async()=>[{actorId:'agent',model:'configured/model',skill:'skill'}]),organize:vi.fn(),undo:vi.fn()}));
vi.mock('@/lib/whiteboard-operation-client',()=>({boardOrganizeActors:calls.actors,organizeBoard:calls.organize,undoAIProposal:calls.undo}));
afterEach(()=>{cleanup();vi.clearAllMocks();});
it('submits selected identities rather than authored cluster commands and emits proposal',async()=>{const onProposal=vi.fn(),proposal={proposalId:'p'};calls.organize.mockResolvedValue(proposal);render(<BoardOrganizeControls boardId="b" selectedIds={['one','two']} readOnly={false} onProposal={onProposal} undo={null} onUndone={()=>{}}/>);await waitFor(()=>expect(screen.getByTestId('board-ai-organize')).toBeEnabled());fireEvent.click(screen.getByTestId('board-ai-organize'));await waitFor(()=>expect(calls.organize).toHaveBeenCalledWith('b','agent',['one','two']));expect(onProposal).toHaveBeenCalledWith(proposal);});
it('shows stale undo honestly and does not clear receipt on rejected inverse',async()=>{calls.undo.mockRejectedValue(new Error('BOARD_OPERATION_CONFLICT'));const onUndone=vi.fn();render(<BoardOrganizeControls boardId="b" selectedIds={[]} readOnly={false} onProposal={()=>{}} undo={{proposal:{proposalId:'p'} as never,revision:{epoch:1,seq:2}}} onUndone={onUndone}/>);fireEvent.click(screen.getByTestId('board-ai-undo'));await screen.findByText('白板已被修改，不能覆盖这些修改；AI 撤销未执行。');expect(onUndone).not.toHaveBeenCalled();});
it('does not expose mutation controls to read-only members',()=>{render(<BoardOrganizeControls boardId="b" selectedIds={['one','two']} readOnly onProposal={()=>{}} undo={null} onUndone={()=>{}}/>);expect(screen.queryByTestId('board-ai-organize')).toBeNull();expect(calls.actors).not.toHaveBeenCalled();});
