import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { HistoryPanel } from '@/components/whiteboard/history-panel';
import * as api from '@/lib/live-whiteboard';

const push=vi.fn();
vi.mock('next/navigation',()=>({useRouter:()=>({push})}));
vi.mock('@/lib/live-whiteboard',()=>({listBoardCheckpoints:vi.fn(),getBoardHistoryHead:vi.fn(),createBoardCheckpoint:vi.fn(),previewBoardCheckpoint:vi.fn(),compareBoardCheckpoint:vi.fn(),restoreBoardCheckpoint:vi.fn()}));
const digest='a'.repeat(64),boardId='11111111-1111-4111-8111-111111111111',checkpointId='22222222-2222-4222-8222-222222222222';
const checkpoint:api.BoardCheckpoint={id:checkpointId,boardId,epoch:1,seq:3,headDigest:digest,contentDigest:digest,byteLength:100,objectCount:1,blobVersion:1,createdAt:'2026-09-24T00:00:00.000Z',creatorId:'facilitator',label:'会后定稿',reason:'工作坊主持人确认',retentionUntil:'2027-09-24T00:00:00.000Z',retentionState:'active',sourceBoardId:null,sourceCheckpointId:null};
beforeEach(()=>{vi.resetAllMocks();vi.mocked(api.listBoardCheckpoints).mockResolvedValue([checkpoint]);vi.mocked(api.getBoardHistoryHead).mockResolvedValue({epoch:1,seq:3,digest});vi.mocked(api.createBoardCheckpoint).mockResolvedValue(checkpoint);vi.mocked(api.previewBoardCheckpoint).mockResolvedValue({checkpoint,objects:[]});vi.mocked(api.compareBoardCheckpoint).mockResolvedValue({from:{checkpointId,contentDigest:digest},to:{kind:'current',head:{epoch:1,seq:4,digest}},added:1,modified:2,deleted:3,changes:[]});vi.mocked(api.restoreBoardCheckpoint).mockResolvedValue({restoreId:'33333333-3333-4333-8333-333333333333',sourceBoardId:boardId,sourceCheckpointId:checkpointId,restoredBoardId:'44444444-4444-4444-8444-444444444444',restoredCheckpointId:'55555555-5555-4555-8555-555555555555',actorId:'facilitator',reason:'恢复副本',createdAt:'2026-09-24T00:00:00.000Z',replayed:false});});
afterEach(cleanup);
describe('Board history panel',()=>{
  it('shows audit metadata and object-level comparison without snapshot bytes',async()=>{render(<HistoryPanel boardId={boardId} boardName="Workshop" canEdit onClose={()=>{}}/>);expect(await screen.findByText('会后定稿')).toBeTruthy();expect(screen.getByText(/facilitator/)).toBeTruthy();expect(screen.getByText(/工作坊主持人确认/)).toBeTruthy();fireEvent.click(screen.getByText('与当前比较'));expect(await screen.findByText(/新增 1 · 修改 2 · 删除 3/)).toBeTruthy();expect(api.previewBoardCheckpoint).not.toHaveBeenCalled();});
  it('renders the complete preview object model including long extension content',async()=>{const text=`${'长'.repeat(500)}尾部`;vi.mocked(api.previewBoardCheckpoint).mockResolvedValue({checkpoint,objects:[{object:{id:'rich',schemaVersion:1,kind:'extension',geometry:{x:0,y:0,width:200,height:100,rotation:0},text,style:{},parentId:null,orderKey:'z',restoredFrom:'source',extensionData:{mermaid:{source:'graph TD; A-->B'},image:{assetId:'asset-1'},drawing:{points:[[0,0],[1,1]]}}},deleted:false,parentMissing:false,parentDeleted:false,connector:null}]});render(<HistoryPanel boardId={boardId} boardName="Workshop" canEdit onClose={()=>{}}/>);fireEvent.click(await screen.findByText('预览'));expect(await screen.findByTestId('board-object-rich')).toHaveTextContent('尾部');expect(screen.getByText(/完整对象模型只读渲染/)).toBeTruthy();});
  it('restores into a new Board and navigates to it',async()=>{render(<HistoryPanel boardId={boardId} boardName="Workshop" canEdit onClose={()=>{}}/>);fireEvent.click(await screen.findByText('创建恢复副本'));await waitFor(()=>expect(api.restoreBoardCheckpoint).toHaveBeenCalledWith(boardId,checkpointId,expect.objectContaining({sourceContentDigest:digest,boardName:'Workshop · 恢复副本'})));expect(push).toHaveBeenCalledWith('/studio/board/44444444-4444-4444-8444-444444444444');});
  it('reuses the same create intent after response loss',async()=>{vi.mocked(api.createBoardCheckpoint).mockRejectedValueOnce(new Error('response lost')).mockResolvedValueOnce(checkpoint);render(<HistoryPanel boardId={boardId} boardName="Workshop" canEdit onClose={()=>{}}/>);await screen.findByText('会后定稿');fireEvent.change(screen.getByLabelText('版本名称'),{target:{value:'Intent'}});fireEvent.change(screen.getByLabelText('保存原因'),{target:{value:'Network retry'}});fireEvent.click(screen.getByText('保存当前版本'));await screen.findByText(/复用同一保存请求/);fireEvent.click(screen.getByText('保存当前版本'));await screen.findByText('已保存不可变版本。');const calls=vi.mocked(api.createBoardCheckpoint).mock.calls;expect(calls).toHaveLength(2);expect(calls[0]![1].requestId).toBe(calls[1]![1].requestId);});
  it('does not resubmit after commit succeeded but list reload failed',async()=>{vi.mocked(api.listBoardCheckpoints).mockResolvedValueOnce([checkpoint]).mockRejectedValueOnce(new Error('reload lost'));render(<HistoryPanel boardId={boardId} boardName="Workshop" canEdit onClose={()=>{}}/>);await screen.findByText('会后定稿');fireEvent.change(screen.getByLabelText('版本名称'),{target:{value:'Committed'}});fireEvent.change(screen.getByLabelText('保存原因'),{target:{value:'Reload loss'}});fireEvent.click(screen.getByText('保存当前版本'));expect(await screen.findByText(/版本已保存，但历史列表刷新失败/)).toBeTruthy();expect(api.createBoardCheckpoint).toHaveBeenCalledTimes(1);expect(screen.getByText('保存当前版本')).toBeDisabled();});
  it('reuses the same restore intent after response loss',async()=>{vi.mocked(api.restoreBoardCheckpoint).mockRejectedValueOnce(new Error('response lost'));render(<HistoryPanel boardId={boardId} boardName="Workshop" canEdit onClose={()=>{}}/>);const button=await screen.findByText('创建恢复副本');fireEvent.click(button);await screen.findByText(/复用同一恢复请求/);fireEvent.click(button);await waitFor(()=>expect(api.restoreBoardCheckpoint).toHaveBeenCalledTimes(2));const calls=vi.mocked(api.restoreBoardCheckpoint).mock.calls;expect(calls[0]![2].requestId).toBe(calls[1]![2].requestId);expect(push).toHaveBeenCalledTimes(1);});
});
