import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { zodToJsonSchema } from "zod-to-json-schema";
import { schemas, limits, endpoints } from "../src/sandbox-session";

describe("sandbox session contract", () => {
  it("generated service artifact exactly matches the source", () => {
    const generated = JSON.parse(readFileSync(new URL("../../../apps/skill-sandbox/src/generated/sandbox-session-schema.json", import.meta.url), "utf8"));
    expect(generated).toEqual({ limits, endpoints, schemas: Object.fromEntries(Object.entries(schemas).map(([name, schema]) =>
      [name, zodToJsonSchema(schema, { target: "jsonSchema7", $refStrategy: "none" })])) });
  });
  it("Python and sandbox consume identical generated bytes", () => {
    const sandbox = readFileSync(new URL("../../../apps/skill-sandbox/src/generated/sandbox-session-schema.json", import.meta.url), "utf8");
    const python = readFileSync(new URL("../../../apps/deep-agent-service/src/deep_agent_service/generated/sandbox_session_schema.json", import.meta.url), "utf8");
    expect(python).toBe(sandbox);
  });
  it("rejects caller-selected credentials and malformed execution control", () => {
    expect(schemas.create.safeParse({ sessionId: "chosen", token: "chosen" }).success).toBe(false);
    expect(schemas.execute.safeParse({ executionId: "x", command: "echo ok", timeoutMs: Infinity }).success).toBe(false);
    expect(schemas.execute.safeParse({ executionId: "11111111-1111-4111-8111-111111111111", command: "echo ok", timeoutMs: 300001 }).success).toBe(false);
  });
});
