import * as React from "react";
import { describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { GuidedResearchSources } from "@/components/research-studio/guided-research-sources";
import { GuidedResearchLive } from "@/components/research-studio/guided-research-live";
import { runtimeFixture } from "../guided-runtime-fixture";
import { executeResearchRuntime, getResearchRuntime } from "@/lib/guided-research-api";
vi.mock("@/lib/guided-research-api", () => ({ getResearchRuntime: vi.fn(), executeResearchRuntime: vi.fn() }));
const source = runtimeFixture("research").sources[0]!;
describe("compact research sources", () => {
  it("includes pending sources, hides removed ones, and exposes complete descriptions on hover/focus/touch", () => {
    const content = "完整描述。".repeat(1000);
    render(<GuidedResearchSources sources={[{ ...source, content, decision: "pending" }, { ...source, id: "removed", title: "Removed", decision: "excluded" }]} disabled={false} onAdd={vi.fn()} onRemove={vi.fn()} />);
    const link = screen.getByRole("link", { name: source.title });
    expect(screen.queryByRole("link", { name: "Removed" })).not.toBeInTheDocument();
    expect(screen.queryByRole("combobox")).not.toBeInTheDocument();
    expect(screen.queryByText(content)).not.toBeInTheDocument();
    fireEvent.mouseEnter(link);
    expect(screen.getByRole("tooltip")).toHaveTextContent(content);
    fireEvent.keyDown(link, { key: "Escape" });
    expect(screen.queryByRole("tooltip")).not.toBeInTheDocument();
    fireEvent.focus(link);
    expect(screen.getByRole("tooltip")).toHaveTextContent(content);
    fireEvent.blur(link);
    expect(screen.queryByRole("tooltip")).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: `查看描述 ${source.title}` }));
    expect(screen.getByRole("tooltip")).toHaveTextContent(content);
  });
  it("keeps failed additions editable, prevents unsafe protocols and clears only on success", async () => {
    const add = vi.fn().mockResolvedValueOnce(false).mockResolvedValueOnce(true);
    render(<GuidedResearchSources sources={[]} disabled={false} onAdd={add} onRemove={vi.fn()} />);
    fireEvent.click(screen.getByRole("button", { name: "添加来源" }));
    const input = screen.getByLabelText("来源链接");
    fireEvent.change(input, { target: { value: "javascript:alert(1)" } });
    expect(screen.getByRole("button", { name: "添加" })).toBeDisabled();
    fireEvent.change(input, { target: { value: "https://example.org/new" } });
    fireEvent.click(screen.getByRole("button", { name: "添加" }));
    await waitFor(() => expect(screen.getByRole("button", { name: "添加" })).toBeEnabled());
    expect(input).toHaveValue("https://example.org/new");
    fireEvent.click(screen.getByRole("button", { name: "添加" }));
    await waitFor(() => expect(screen.queryByLabelText("来源链接")).not.toBeInTheDocument());
    expect(add).toHaveBeenCalledTimes(2);
  });
  it("adds through the versioned runtime and keeps legacy pending sources included on completion", async () => {
    vi.mocked(executeResearchRuntime).mockReset();
    const state = runtimeFixture("research"); state.sources[0]!.decision = "pending";
    vi.mocked(getResearchRuntime).mockResolvedValue(state);
    const next = { ...state, version: state.version + 1, sources: [...state.sources, { ...source, id: "new", url: "https://example.org/new", title: "New source", decision: "accepted" as const }] };
    vi.mocked(executeResearchRuntime).mockResolvedValue(next);
    render(<GuidedResearchLive sessionId={state.sessionId} onBack={vi.fn()} />);
    await screen.findByRole("link", { name: source.title });
    fireEvent.click(screen.getByRole("button", { name: "添加来源" }));
    fireEvent.change(screen.getByLabelText("来源链接"), { target: { value: "https://example.org/new" } });
    fireEvent.click(screen.getByRole("button", { name: "添加" }));
    await screen.findByRole("link", { name: "New source" });
    expect(executeResearchRuntime).toHaveBeenCalledWith(expect.objectContaining({ action: "add_source", sourceUrl: "https://example.org/new", expectedVersion: state.version }));
    fireEvent.click(screen.getByRole("button", { name: "确认并继续" }));
    await waitFor(() => expect(executeResearchRuntime).toHaveBeenLastCalledWith(expect.objectContaining({ action: "complete", expectedVersion: next.version, draft: { node: "research", value: [{ id: source.id, decision: "accepted" }, { id: "new", decision: "accepted" }] } })));
  });
});
