import { randomUUID } from 'node:crypto';
import { describe,expect,it } from 'vitest';
import { mapImportedBoard,type ImportedBoardItem } from '../src/import-mapping';
import { WhiteboardCommandBatch } from '@repo/contracts/whiteboard-document';
const item=(value:Partial<ImportedBoardItem>&Pick<ImportedBoardItem,'sourceId'|'sourceType'|'type'>):ImportedBoardItem=>({x:0,y:0,width:180,height:120,rotation:0,text:'',color:null,shape:null,parentSourceId:null,fromSourceId:null,toSourceId:null,zIndex:0,assetRef:null,assetMime:null,metadata:{},...value});
describe('canonical Miro/Mural mapping',()=>{
  it('preserves provenance, hierarchy, visual values and semantic connector relations',()=>{const result=mapImportedBoard('mural',randomUUID(),[item({sourceId:'panel',sourceType:'area',type:'panel',text:'Workshop'}),item({sourceId:'note',sourceType:'sticky note',type:'sticky',text:'Pain',color:'#fecaca',parentSourceId:'panel'}),item({sourceId:'shape',sourceType:'diamond',type:'shape',shape:'diamond',text:'Decide'}),item({sourceId:'edge',sourceType:'arrow',type:'connector',fromSourceId:'note',toSourceId:'shape',text:'causes',metadata:{semanticRelation:'causes'}})]);expect(()=>WhiteboardCommandBatch.parse(result.commands)).not.toThrow();expect(result.accepted).toBe(4);const objects=result.commands.map(command=>command.type==='create'?command.object:null).filter(Boolean);expect(objects[1]).toMatchObject({text:'Pain',parentId:objects[0]?.id,style:{fill:'#FECACA'},extensionData:{import:{source:'mural',sourceId:'note'}}});expect(objects[3]).toMatchObject({connector:{from:objects[1]?.id,to:objects[2]?.id,label:'causes',semanticRelation:'causes'}});});
  it('reports unsupported items and enforces one atomic batch',()=>{const input=Array.from({length:205},(_,index)=>item({sourceId:`s${index}`,sourceType:index===0?'unknown':'sticker',type:index===0?'unsupported':'sticky'}));const result=mapImportedBoard('miro',randomUUID(),input);expect(result.commands).toHaveLength(0);expect(result.accepted).toBe(0);expect(result.unsupported).toBe(205);expect(result.issues.map(issue=>issue.code)).toContain('OBJECT_LIMIT');expect(result.outcomes).toEqual([]);});
  it('keeps image bytes out of canonical data and stores only an asset ref',()=>{const result=mapImportedBoard('miro',randomUUID(),[item({sourceId:'img',sourceType:'image',type:'image',assetRef:'board-image-'+ 'a'.repeat(64),assetMetadata:{assetId:'board-image-'+ 'a'.repeat(64),mimeType:'image/png',magicMimeType:'image/png',byteSize:100,contentDigest:'sha256:'+ 'a'.repeat(64),intrinsicWidth:32,intrinsicHeight:24,persistence:'durable'}})]);const body=JSON.stringify(result.commands);expect(body).toContain('assetId');expect(body).toContain('board-image-');expect(body).not.toContain('base64');});
  it('builds hierarchy and connectors only from objects that were actually emitted',()=>{const result=mapImportedBoard('mural',randomUUID(),[
    item({sourceId:'missing-image',sourceType:'image',type:'image'}),
    item({sourceId:'child',sourceType:'sticker',type:'sticky',parentSourceId:'missing-image'}),
    item({sourceId:'bad-parent',sourceType:'sticker',type:'sticky',parentSourceId:'child'}),
    item({sourceId:'edge',sourceType:'arrow',type:'connector',fromSourceId:'child',toSourceId:'missing-image'}),
  ]);expect(()=>WhiteboardCommandBatch.parse(result.commands)).not.toThrow();expect(result.commands).toHaveLength(2);expect(result.commands.every(command=>command.type==='create'&&command.object.parentId===null)).toBe(true);expect(result.issues.filter(issue=>issue.code==='INVALID_REFERENCE')).toHaveLength(3);expect(result.issues.map(issue=>issue.code)).toContain('ASSET_MISSING');});
  it('maps Mural circles and reports every unknown shape downgrade',()=>{const result=mapImportedBoard('mural',randomUUID(),[item({sourceId:'circle',sourceType:'circle',type:'shape',shape:'circle'}),item({sourceId:'mystery',sourceType:'shape',type:'shape',shape:'starburst'})]);const objects=result.commands.map(command=>command.type==='create'?command.object:null);expect(objects[0]).toMatchObject({kind:'ellipse',extensionData:{contentObject:{variant:'circle'}}});expect(objects[1]).toMatchObject({kind:'rectangle',extensionData:{contentObject:{variant:'rectangle'}}});expect(result.issues).toContainEqual(expect.objectContaining({code:'VALUE_NORMALIZED',sourceId:'mystery'}));});
  it('preserves source groups as structural parents',()=>{const result=mapImportedBoard('miro',randomUUID(),[item({sourceId:'group',sourceType:'group',type:'group'}),item({sourceId:'note',sourceType:'sticker',type:'sticky',parentSourceId:'group'})]);const objects=result.commands.flatMap(command=>command.type==='create'?[command.object]:[]);expect(objects[0]).toMatchObject({kind:'group'});expect(objects[1]).toMatchObject({kind:'sticky',parentId:objects[0]?.id});});
});

it('reports duplicate records as skipped and broken parents as downgraded',()=>{
 const result=mapImportedBoard('miro',randomUUID(),[item({sourceId:'a',sourceType:'text',type:'text',parentSourceId:'missing'}),item({sourceId:'a',sourceType:'text',type:'text'})]);
 expect(result.commands).toHaveLength(1);expect(result.outcomes.map(item=>item.outcome)).toEqual(['downgraded','skipped']);
 expect(result.outcomes[0]?.reasonCode).toBe('INVALID_REFERENCE');
});
it('retains parser loss explanations per emitted item',()=>{
 const result=mapImportedBoard('miro',randomUUID(),[item({sourceId:'a',sourceType:'text',type:'text',losses:['Text-only source was arranged in a grid.']})]);
 expect(result.outcomes[0]).toMatchObject({outcome:'downgraded',detail:'Text-only source was arranged in a grid.'});
});
