"use client";
import { useState } from "react";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AppShell } from "@/components/shell/app-shell";
import { mockIdentity } from "@/lib/identity";
import { ResearchIntake } from "./research-intake";
import { ResearchHistoryCard } from "./research-history-card";
import { ResearchTopicInformation } from "./research-topic-information";
import { ResearchChaptersWorkspace } from "./research-chapters-workspace";
import { ResearchPrototypeReport } from "./research-prototype-report";
import { GuidedResearchPlanPanel } from "./guided-research-plan-panel";
import { GuidedResearchReportWorkspace } from "./guided-research-report-workspace";
import { GuidedResearchSixStepShell } from "./guided-research-six-step-shell";
import { GuidedResearchSourceWorkspace } from "./guided-research-source-workspace";
import { GuidedResearchTopicPanel } from "./guided-research-topic-panel";
import { GuidedResearchTrustConsole } from "./guided-research-trust-console";
import { ResearchChapterTasks } from "./guided-research-runtime-progress";
import { prototypeRuntime } from "./research-prototype-fixture";
import { researchReportDocument } from "@/lib/research-report-document";
import type { GuidedResearchVisualStage } from "@/lib/guided-research-six-step";
const stages = ["import", "topic", "plan", "research", "chapters", "report"] as const;
const noop = () => undefined;
const route = (stage: string) => `/research?preview=prototype-fidelity&stage=${stage}`;
const List = ({ items }: { items: string[] }) => <ul className="list-inside list-disc space-y-1 text-lg leading-relaxed text-muted-foreground">{items.map((item) => <li key={item}>{item}</li>)}</ul>;
/** Development-only visual samples. No backend/model verification is implied. */
export function GuidedResearchPrototypePreview({ stage }: { stage?: string }) {
  const current = stages.includes(stage as GuidedResearchVisualStage) ? stage as GuidedResearchVisualStage : null;
  const [runtime, setRuntime] = useState(prototypeRuntime);
  const document = researchReportDocument(runtime.report!, runtime.sources, runtime.outline);
  const actions = (previous: string, next: string, label: string) => <div className="flex justify-between gap-4"><Button asChild variant="outline" className="h-12 px-6 text-lg"><a href={route(previous)}>上一步</a></Button><Button asChild variant="primary" className="h-12 px-6 text-lg"><a href={route(next)}>{label}<ArrowRight className="size-5" /></a></Button></div>;
  const note = <p role="note" className="px-10 py-2 text-sm text-muted-foreground">视觉对照样本：固定示例数据，不代表真实检索、模型生成或后端验证。</p>;
  if (!current) return <AppShell identity={mockIdentity("org-yuanyang", null)} previewRole={null} hideRoleSwitcher><div data-testid="guided-research-prototype-preview"><section data-testid="guided-research-prototype-home" className="mx-auto max-w-screen-2xl space-y-6 px-10 py-8"><header className="flex items-center justify-between"><div><h1 className="text-5xl font-bold">研究列表</h1><p className="mt-3 text-2xl text-muted-foreground">从问题出发，深入研究，获得可执行的洞察。</p></div><Button asChild className="h-14 px-6 text-xl"><a href={route("import")}>新建研究</a></Button></header><div className="grid gap-6 md:grid-cols-2">{["中国新能源汽车市场的发展趋势", "全球储能产业发展与竞争格局", "东南亚电商市场的增长潜力", "AI 大模型在金融行业的应用前景"].map((title, index) => <ResearchHistoryCard key={title} testId={`prototype-card-${index}`} title={title} status={null} description="分析市场规模、竞争格局、政策环境及未来发展趋势，识别关键机遇与挑战。" tags={index === 0 ? ["行业", "市场", "政策", "新能源"] : index === 1 ? ["储能", "行业", "出海"] : index === 2 ? ["市场", "出海", "电商"] : ["AI", "金融", "行业"]} metadata={<time>更新于 2024-03-{15 - index}</time>} management={null} primaryAction={<Button asChild className="h-11 px-5 text-base"><a href={route("plan")}>继续研究 <ArrowRight className="size-5" /></a></Button>}><p className="text-base">研究进度 {3 - index % 3} / 6 步</p><progress aria-label={`${title}进度`} className="h-2 w-full appearance-none overflow-hidden rounded-full bg-muted [&::-webkit-progress-bar]:bg-muted [&::-webkit-progress-value]:bg-primary [&::-moz-progress-bar]:bg-primary" value={3 - index % 3} max={6} /></ResearchHistoryCard>)}</div></section>{note}</div></AppShell>;
  let main;
  if (current === "import") main = <ResearchIntake session={null} workflow={null} onSession={noop} onWorkflow={noop} onPending={noop} onNavigate={noop} renderAssistant={() => null} onConfirmBrief={(brief) => { setRuntime({ ...runtime, brief }); window.location.assign(route("topic")); }} />;
  else if (current === "topic") main = <GuidedResearchTopicPanel workspace={<><h2 className="text-3xl font-bold">完善研究信息</h2><ResearchTopicInformation brief={runtime.brief} disabled={false} onSave={(brief) => setRuntime({ ...runtime, brief })} /></>} actions={actions("import", "plan", "下一步：研究计划")} />;
  else if (current === "plan") main = <GuidedResearchPlanPanel plan={<div className="rounded-lg border bg-muted/20 p-5"><p className="text-lg text-muted-foreground">研究主题（示例）</p><h3 className="mt-2 text-xl font-bold">{runtime.brief.topic}</h3><p className="mt-3 text-lg leading-relaxed text-muted-foreground">{runtime.brief.goal}</p></div>} questions={<List items={runtime.outline.flatMap((item) => item.questions)} />} successCriteria={<List items={runtime.intent!.successCriteria} />} materials={<List items={["行业报告、市场研究报告、咨询机构研究数据", "政府政策文件、行业标准、监管公告", "企业财报、招股书、官方发布信息", "学术论文、专业期刊、行业媒体报道"]} />} sourceScope={<List items={["政府机构官网及国际组织", "权威咨询机构与行业媒体", "学术数据库与公开披露信息"]} />} disabled={false} onEdit={noop} onBack={() => window.location.assign(route("topic"))} onConfirm={() => window.location.assign(route("research"))} />;
  else if (current === "research") main = <GuidedResearchSourceWorkspace progress={<ResearchChapterTasks state={runtime} />} activity={<GuidedResearchTrustConsole compact runtime={runtime} pending={false} onSteer={noop} onResolveConflict={noop} />} evidence={<List items={runtime.sources.map((source) => source.title)} />} sourcePreview={<List items={runtime.sources.map((source) => source.title)} />} insights={<List items={["市场增长与政策环境需要交叉验证", "进入路径取决于本地合作与准入约束", "不同国家的投资与并网条件存在差异"]} />} risk={<List items={["统计口径可能存在差异", "部分公开资料的覆盖范围有限", "结论的时效性需要进一步验证"]} />} actions={<><Button className="h-12 px-6 text-lg">继续搜索</Button><Button variant="outline" className="h-12 px-6 text-lg">重试失败任务</Button></>} />;
  else if (current === "chapters") main = <ResearchChaptersWorkspace runtime={runtime} disabled={false} onSave={(outline) => setRuntime({ ...runtime, outline })} onOptimize={noop} onBack={() => window.location.assign(route("research"))} onNext={() => window.location.assign(route("report"))} />;
  else main = <GuidedResearchReportWorkspace actions={null} metrics={null} limitation={null} contents={<ol className="space-y-4">{["执行摘要", ...document.sections.map((item) => item.title), "参考文献"].map((title, index) => <li key={title}><a className="block rounded px-3 py-2 transition-colors hover:bg-muted" href={index === 0 ? "#research-report-summary" : index === document.sections.length + 1 ? "#research-report-references" : `#research-report-section-${index - 1}`}>{index + 1}. {title}</a></li>)}</ol>} document={<ResearchPrototypeReport document={document} sources={runtime.sources.length} disabled={false} onRegenerate={noop} />} />;
  return <div data-testid="guided-research-prototype-preview"><div data-testid={`guided-research-prototype-${current}`}><GuidedResearchSixStepShell current={current} available={[...stages]} onBack={() => window.location.assign(route("home"))} onNavigate={(next) => window.location.assign(route(next))} main={<>{main}{note}</>} /></div></div>;
}
