import { beforeAll, afterAll, expect, it } from 'vitest';
import { migrateOnce, resetOrgs, seedOrg } from '../support/db';
import { PgDatabase } from '../../src/infrastructure/db/pg-database';
import { appConfig } from '../../src/infrastructure/db/pg-config';
import { PgSurveyRepository } from '../../src/infrastructure/survey/pg-survey-repository';
import { SurveyService } from '../../src/application/survey/survey-service';
import { toOrgId } from '../../src/domain/org-id';
import { SurveyDraftInputSchema, SurveyRuntimeSchema, SurveySubmissionInputSchema } from '@repo/contracts/survey-runtime';
const org=toOrgId('org-survey-persist-3754');const other=toOrgId('org-survey-other-3754');let db:PgDatabase;
beforeAll(async()=>{await migrateOnce();await resetOrgs(org,other);await seedOrg({orgId:org,projectId:'project-survey-3754',teamNames:[]});await seedOrg({orgId:other,projectId:'project-survey-other-3754',teamNames:[]});db=new PgDatabase(appConfig());});
afterAll(async()=>{await db?.close();await resetOrgs(org,other);});
it('persists across service recreation, forces RLS, serializes concurrent receipts, and preserves report snapshots',async()=>{
  const s=new SurveyService(new PgSurveyRepository(db));
  const draft=SurveyDraftInputSchema.parse({title:'持久化',questions:[{id:'q1',order:1,chapterId:'s',title:'满意度',type:'scale',required:true,options:['1','2','3','4','5','6','7','8','9','10']}],template:{id:'t',title:'报告',sections:[{id:'section',title:'分析',blocks:[{id:'b',title:'得分',type:'metric',questionIds:['q1'],statistic:'mean'}]}]}});
  let m=await s.create(org,'owner',draft);m=await s.publish(org,'owner',m.id,m.version);const token=m.publication!.token;
  const answer=SurveySubmissionInputSchema.parse({submissionId:'same-request-3754',answers:[{questionId:'q1',value:'8'}]});
  const submissions=await Promise.all([s.submit(token,answer),s.submit(token,answer)]);expect(new Set(submissions.map(r=>r.responseId)).size).toBe(1);expect(submissions.filter(r=>r.replayed)).toHaveLength(1);
  const reloaded=new SurveyService(new PgSurveyRepository(db));m=await reloaded.get(org,'owner',m.id);expect(m.responses).toHaveLength(1);expect(SurveyRuntimeSchema.safeParse(m).success).toBe(true);
  const wrong=await db.withTenant(other,s=>s.query('SELECT id FROM survey_workspaces WHERE id=$1',[m.id]));expect(wrong.rows).toEqual([]);
  await expect(reloaded.get(org,'intruder',m.id)).rejects.toThrow('not_found');
  const competing=await Promise.allSettled([reloaded.save(org,'owner',m.id,m.version,draft),reloaded.save(org,'owner',m.id,m.version,draft)]);expect(competing.filter(r=>r.status==='fulfilled')).toHaveLength(1);
  m=await reloaded.get(org,'owner',m.id);m=await reloaded.report(org,'owner',m.id,m.version);expect(m.report!.sections[0]!.blocks[0]!.rows[0]!.value).toBe(8);const snapshot=structuredClone(m.report);
  m=await reloaded.save(org,'owner',m.id,m.version,{...draft,template:{...draft.template,title:'新报告草稿'}});expect(m.report).toEqual(snapshot);expect(m.reportBasisVersion).toBeLessThan(m.version-1);
  m=await reloaded.review(org,'owner',m.id,m.version,m.responses[0]!.id,'review');
  await expect(reloaded.report(org,'owner',m.id,m.version)).rejects.toThrow('invalid_report');
  const allTemplate=structuredClone(draft.template);allTemplate.sections[0]!.blocks[0]!.samplePolicy='all';
  m=await reloaded.save(org,'owner',m.id,m.version,{...draft,template:allTemplate});m=await reloaded.report(org,'owner',m.id,m.version);
  expect(m.report!.sections[0]!.blocks[0]!.rows[0]!.value).toBe(8);expect(m.reportBasisVersion).toBe(m.version-1);expect(m.reportGeneratedAt).not.toBeNull();
});
