import { createHash, randomUUID } from 'node:crypto';
import { deflateSync } from 'node:zlib';
import { expect, test, type Page, type APIRequestContext } from '@playwright/test';
import { FULLSTACK_E2E as F } from './fullstack-smoke-fixture';
import { SESSION_TOKEN_STORAGE_KEY } from '../lib/api-client';
import { produceImageStorageEvidence } from './support/board-durable-images-storage';
function pngFixture(){const chunk=(name:string,data:Buffer)=>{const body=Buffer.concat([Buffer.from(name),data]);let crc=0xffffffff;for(const byte of body){crc^=byte;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}const size=Buffer.alloc(4),sum=Buffer.alloc(4);size.writeUInt32BE(data.length);sum.writeUInt32BE((crc^0xffffffff)>>>0);return Buffer.concat([size,body,sum]);};const header=Buffer.alloc(13);header.writeUInt32BE(64,0);header.writeUInt32BE(48,4);header[8]=8;header[9]=2;const pixels=Buffer.alloc(48*193);for(let y=0;y<48;y++)for(let x=0;x<64;x++){const p=y*193+1+x*3;pixels[p]=231;pixels[p+1]=29;pixels[p+2]=73;}return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);}
function origin(){const value=process.env.WHITEBOARD_API_URL??(process.env.WORKSPACEX_API_PORT?`http://127.0.0.1:${process.env.WORKSPACEX_API_PORT}`:undefined);if(!value)throw new Error('WHITEBOARD_API_URL required');return value;}
async function call(api:APIRequestContext,token:string,method:string,path:string,data?:unknown){const r=await api.fetch(`${origin()}${path}`,{method,headers:{Authorization:`Bearer ${token}`},data});expect(r.ok(),`${method} ${path}: ${r.status()}`).toBe(true);return r;}
async function login(page:Page,peer=false){await page.goto('/login');await page.getByTestId('login-email').fill(peer?F.leadEmail:F.adminEmail);await page.getByTestId('login-password').fill(peer?F.leadPassword:F.adminPassword);await page.getByTestId('login-submit').click();await expect(page).toHaveURL(/\/projects$/);return(await page.evaluate(key=>localStorage.getItem(key),SESSION_TOKEN_STORAGE_KEY))!;}
async function canonical(api:APIRequestContext,token:string,id:string){const result=await(await call(api,token,'POST',`/whiteboards/${id}/imports/standard-export`,{requestId:randomUUID()})).json();const downloaded=await(await call(api,token,'GET',result.downloadPath)).json();const bytes=Buffer.from(downloaded.contentBase64,'base64');expect(createHash('sha256').update(bytes).digest('hex')).toBe(downloaded.sha256);return JSON.parse(bytes.toString()) as {board:{epoch:number;seq:number};objects:Array<{kind:string;extensionData?:{contentObject?:Record<string,unknown>}}>};}
type Evidence={created:string[];revoked:string[];loaded:Array<{url:string;width:number;height:number}>};
async function observe(page:Page){await page.addInitScript(()=>{const state={created:[] as string[],revoked:[] as string[],loaded:[] as Array<{url:string;width:number;height:number}>};(window as unknown as {__images:typeof state}).__images=state;const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=blob=>{const url=create(blob);state.created.push(url);return url;};URL.revokeObjectURL=url=>{state.revoked.push(url);revoke(url);};const descriptor=Object.getOwnPropertyDescriptor(HTMLImageElement.prototype,'src')!;Object.defineProperty(HTMLImageElement.prototype,'src',{...descriptor,set(value:string){if(value.startsWith('blob:'))this.addEventListener('load',()=>state.loaded.push({url:value,width:this.naturalWidth,height:this.naturalHeight}),{once:true});descriptor.set!.call(this,value);}});});}
async function painted(page:Page){await expect.poll(()=>page.evaluate(()=>(window as unknown as {__images:Evidence}).__images.loaded.some(image=>image.width===64&&image.height===48))).toBe(true);await expect.poll(()=>page.locator('canvas.lower-canvas').evaluateAll(canvases=>canvases.some(element=>{const canvas=element as HTMLCanvasElement,ctx=canvas.getContext('2d');if(!ctx)return false;const bytes=ctx.getImageData(0,0,canvas.width,canvas.height).data;let matching=0;for(let i=0;i<bytes.length;i+=4)if(bytes[i]===231&&bytes[i+1]===29&&bytes[i+2]===73&&bytes[i+3]===255)matching++;return matching>100;}))).toBe(true);}

test('durable image bytes survive refresh, independent peer, revoke and source deletion',async({browser,request:api,baseURL},info)=>{
 expect(baseURL,'WHITEBOARD_WEB_URL or isolated WORKSPACEX_WEB_PORT required').toBeTruthy();
 const ownerContext=await browser.newContext({baseURL}),peerContext=await browser.newContext({baseURL}),owner=await ownerContext.newPage(),peer=await peerContext.newPage();await observe(owner);await observe(peer);
 let token:string|undefined,source:string|undefined,target:string|undefined;
 const archive=async(id:string)=>{const b=await(await call(api,token!,'GET',`/whiteboards/${id}`)).json();return b.archived?b:(await call(api,token!,'PATCH',`/whiteboards/${id}`,{archived:true,expectedLifecycleRevision:b.lifecycleRevision})).json();};
 try{
  token=await login(owner);const peerToken=await login(peer,true);source=(await(await call(api,token,'POST','/whiteboards',{requestId:randomUUID(),name:`Durable images ${randomUUID()}`})).json()).id as string;
  await call(api,token,'PUT',`/whiteboards/${source}/members`,{userId:F.leadUserId,role:'editor'});await owner.goto(`/studio/board/${source}`);await expect(owner.getByTestId('collaborative-editor')).toBeVisible();await expect(owner.getByText(/^已同步/)).toBeVisible();
  const png=pngFixture(),digest=`sha256:${createHash('sha256').update(png).digest('hex')}`;
  const uploaded=owner.waitForResponse(r=>r.url().endsWith(`/whiteboards/${source}/assets`)&&r.request().method()==='POST'),readback=owner.waitForResponse(r=>r.url().includes(`/whiteboards/${source}/assets/`)&&r.url().endsWith('/content'));
  await owner.getByTestId('board-image-input').setInputFiles({name:'durable-evidence.png',mimeType:'image/png',buffer:png});const upload=await uploaded;expect(upload.ok()).toBe(true);const metadata=await upload.json();expect(metadata).toMatchObject({contentDigest:digest,intrinsicWidth:64,intrinsicHeight:48,persistence:'durable',byteSize:png.length});
  const read=await readback;expect(read.status()).toBe(200);expect(read.headers()['cache-control']).toBe('private, no-store');expect(await read.body()).toEqual(png);expect(read.request().headers()['authorization']).toBe(`Bearer ${token}`);await painted(owner);
  let snapshot:Awaited<ReturnType<typeof canonical>>|undefined;await expect.poll(async()=>{snapshot=await canonical(api,token!,source!);return JSON.stringify(snapshot.objects);}).toContain(metadata.assetId);
  const canonicalImage=snapshot!.objects.find(object=>object.kind==='image')?.extensionData?.contentObject;expect(canonicalImage).toMatchObject({...metadata,type:'image',status:'ready',sourceUrl:null,failureCode:null});
  expect(JSON.stringify(snapshot!.objects)).toContain('durable');expect(JSON.stringify(snapshot!.objects)).not.toMatch(/blob:|data:image|local-session-/);await info.attach('canonical-upload',{body:JSON.stringify(snapshot),contentType:'application/json'});
  await owner.reload();await painted(owner);const peerRead=peer.waitForResponse(r=>r.url().includes(`/whiteboards/${source}/assets/`)&&r.url().endsWith('/content'));await peer.goto(`/studio/board/${source}`);expect((await peerRead).status()).toBe(200);await painted(peer);
  const peerUrls=await peer.evaluate(()=>(window as unknown as {__images:Evidence}).__images.loaded.map(image=>image.url));expect(peerUrls.length).toBeGreaterThan(0);
  const duplicate=await(await call(api,token,'POST',`/whiteboards/${source}/duplicates`,{requestId:randomUUID(),targetName:`Image copy ${randomUUID()}`,expectedSource:{epoch:snapshot!.board.epoch,seq:snapshot!.board.seq}})).json();target=duplicate.board.id;expect(duplicate.receipt.assetCount).toBe(1);
  await info.attach('pg-independent-pointers',{body:JSON.stringify(await produceImageStorageEvidence(F.orgId,[source,target!],metadata.assetId)),contentType:'application/json'});
  await call(api,token,'DELETE',`/whiteboards/${source}/members/${F.leadUserId}`);// Revoked board membership hides resource existence: read is precisely 404, not 403.
  const denied=await api.get(`${origin()}/whiteboards/${source}/assets/${metadata.assetId}/content`,{headers:{Authorization:`Bearer ${peerToken}`}});expect(denied.status()).toBe(404);expect(await denied.body()).not.toEqual(png);expect(denied.headers()['content-type']).not.toContain('image/');
  const deniedCanonical=await api.post(`${origin()}/whiteboards/${source}/imports/standard-export`,{headers:{Authorization:`Bearer ${peerToken}`},data:{requestId:randomUUID()}});expect(deniedCanonical.status()).toBe(404);expect(await deniedCanonical.text()).not.toContain(metadata.assetId);
  await expect(peer.getByTestId('denied')).toBeVisible();await expect(peer.getByTestId('board-fabric-surface')).toHaveCount(0);
  await expect.poll(()=>peer.evaluate(urls=>urls.every(url=>(window as unknown as {__images:Evidence}).__images.revoked.includes(url)),peerUrls)).toBe(true);
  expect(await peer.evaluate(async urls=>Promise.all(urls.map(async url=>{try{await fetch(url);return false;}catch{return true;}})),peerUrls)).toEqual(peerUrls.map(()=>true));
  const targetBytes=async()=>expect(await(await call(api,token!,'GET',`/whiteboards/${target}/assets/${metadata.assetId}/content`)).body()).toEqual(png);
  const archived=await archive(source);await targetBytes();await call(api,token,'DELETE',`/whiteboards/${source}`,{requestId:randomUUID(),confirmation:'PERMANENTLY_DELETE',expectedLifecycleRevision:archived.lifecycleRevision});source=undefined;
  await targetBytes();await owner.goto(`/studio/board/${target}`);await painted(owner);await owner.reload();await painted(owner);
  await info.attach('pg-target-after-source-delete',{body:JSON.stringify(await produceImageStorageEvidence(F.orgId,[target!],metadata.assetId)),contentType:'application/json'});
 }finally{await ownerContext.close();await peerContext.close();if(token){if(source)await archive(source);if(target)await archive(target);}}
});
