import {test,expect} from '@playwright/test';
import {createHash,randomUUID} from 'node:crypto';
import {writeFile} from 'node:fs/promises';
import {DuplicateBoardResult} from '@repo/contracts/whiteboard';
import {FULLSTACK_E2E as F} from './fullstack-smoke-fixture';
import {boardLogin,boardApi,canonicalBoardSnapshot,createAcceptanceBoard,object,createCommands,operate,selectAll} from './board-acceptance-support';
import {runtimeSourceIdentity,observeRuntimeChunks,verifyRuntimeIdentity,sha256} from './board-runtime-evidence';
import {deleteOwnedConnectorFixture} from './support/connector-acceptance-fixture';
import {exactInterchangeObjects} from './support/connector-c08-oracle.mjs';
import {copiedSubgraphProof} from './support/connector-copy-oracle.mjs';
import {verifyConnectorRuntimeManifest} from './support/connector-runtime-manifest';

for(const viewport of [{width:1440,height:900},{width:390,height:844}])test(`C08 real UI copy/paste, board duplicate and old Connector defaults at ${viewport.width}px`,async({page,request:api},info)=>{
 test.setTimeout(180_000);await page.setViewportSize(viewport);const source=runtimeSourceIdentity(),chunks=observeRuntimeChunks(page),owned:Array<{id:string;title:string}>=[],records:unknown[]=[],screenshots:unknown[]=[],cleanupErrors:unknown[]=[];let token='',failure:unknown;
 const make=async(title:string)=>{const id=await createAcceptanceBoard(api,token,title);owned.push({id,title});return id;};
 const synced=async()=>{await expect(page.getByTestId('board-sync-status')).toHaveAttribute('data-sync-phase','synced');};
 const capture=async(phase:string)=>{const path=info.outputPath(`${phase}.png`),bytes=await page.screenshot({path});screenshots.push({phase,path,sha256:sha256(bytes)});};
 let manifestBefore:Awaited<ReturnType<typeof verifyConnectorRuntimeManifest>>|undefined;
 try{
  manifestBefore=await verifyConnectorRuntimeManifest();records.push({phase:'runtime-manifest-before',...manifestBefore});
  const loginResponse=page.waitForResponse(response=>new URL(response.url()).pathname.endsWith('/auth/login')&&response.request().method()==='POST');token=await boardLogin(page);const login=await (await loginResponse).json();expect(login.userId).toBe(F.userId);expect(login.sessionToken).toBe(token);
  const boardId=await make(`C08 UI copy ${viewport.width}`),seed=[object('c08-copy-a','sticky',120,180,'A',140,100),object('c08-copy-b','sticky',600,400,'B',140,100)];
  for(const type of ['straight','elbow','curve'] as const){const route=type==='curve'?{kind:'curve' as const,startOffset:{x:100,y:-70},endOffset:{x:-80,y:25}}:type==='elbow'?{kind:'elbow' as const,waypoints:[{x:420,y:230},{x:420,y:450}]}:undefined;seed.push({...object(`c08-copy-${type}`,'connector',260,230,`C08 ${type}`,340,220),style:{stroke:'#E11D48'},connector:{from:'c08-copy-a',to:'c08-copy-b',fromAnchor:'right',toAnchor:'left',type,route,strokeWidth:12,label:`C08 ${type}`,semanticRelation:'depends_on',labelPosition:{t:.73,normalOffset:-29},startStyle:'circle',endStyle:'diamond',lineStyle:'dotted'}});}
  seed.push({...object('c08-copy-free','connector',200,620,'free',500,0),style:{stroke:'#E11D48'},connector:{fromPoint:{x:200,y:620},toPoint:{x:700,y:620},fromAnchor:'right',toAnchor:'left',type:'elbow',route:{kind:'elbow',waypoints:[{x:420,y:650}]},strokeWidth:7,label:'C08 free',semanticRelation:'supports',labelPosition:{t:.3,normalOffset:40},startStyle:'diamond',endStyle:'circle',lineStyle:'dashed'}});
  await operate(api,token,boardId,createCommands(seed));await page.goto(`/studio/board/${boardId}`);await synced();const runtimeBefore=await verifyRuntimeIdentity(api,source,await chunks()),original=await canonicalBoardSnapshot(api,token,boardId);
  await selectAll(page,original.objects.length);await page.getByRole('button',{name:'更多白板操作',exact:true}).click();await page.getByRole('button',{name:'复制',exact:true}).click();const unchanged=await canonicalBoardSnapshot(api,token,boardId);expect(unchanged).toEqual(original);await page.getByRole('button',{name:'粘贴',exact:true}).click();
  await expect.poll(async()=> (await canonicalBoardSnapshot(api,token,boardId)).objects.length).toBe(original.objects.length*2);await synced();const pasted=await canonicalBoardSnapshot(api,token,boardId);expect(pasted.revision).toEqual({epoch:original.revision.epoch,seq:original.revision.seq+1});
  const originalIds=new Set(original.objects.map(item=>item.id)),copies=pasted.objects.filter(item=>!originalIds.has(item.id)),expectedCopies=copiedSubgraphProof(original.objects,copies);
  exactInterchangeObjects([...original.objects,...expectedCopies],pasted.objects);await capture('UI-pasted-full-subgraph');await page.reload();await synced();exactInterchangeObjects([...original.objects,...expectedCopies],(await canonicalBoardSnapshot(api,token,boardId)).objects);
  const requestId=randomUUID(),targetName=`C08 duplicated ${viewport.width}`,duplicated=DuplicateBoardResult.parse(await (await boardApi(api,token,'POST',`/whiteboards/${boardId}/duplicates`,{requestId,targetName,expectedSource:pasted.revision})).json());owned.push({id:duplicated.board.id,title:targetName});expect(duplicated.receipt).toEqual({requestId,sourceBoardId:boardId,sourceEpoch:pasted.revision.epoch,sourceSeq:pasted.revision.seq,objectCount:12,connectorCount:8,assetCount:0});
  const duplicateId=(id:string)=>`copy_${createHash('sha256').update(requestId).update('\0').update(id).digest('hex')}`;
  const expectedBoard=pasted.objects.map(item=>({...structuredClone(item),id:duplicateId(item.id),parentId:item.parentId===null?null:duplicateId(item.parentId),...(item.connector?{connector:{...structuredClone(item.connector),...(item.connector.from?{from:duplicateId(item.connector.from)}:{}),...(item.connector.to?{to:duplicateId(item.connector.to)}:{})}}:{})}));
  exactInterchangeObjects(expectedBoard,(await canonicalBoardSnapshot(api,token,duplicated.board.id)).objects);await page.goto(`/studio/board/${duplicated.board.id}`);await synced();await capture('board-duplicated-full-canonical');await page.reload();await synced();exactInterchangeObjects(expectedBoard,(await canonicalBoardSnapshot(api,token,duplicated.board.id)).objects);expect(await canonicalBoardSnapshot(api,token,boardId)).toEqual(pasted);
  const oldId=await make(`C08 old record ${viewport.width}`),oldEdge={...object('c08-old','connector',100,240,'Old record',500,0),style:{stroke:'#E11D48'},connector:{fromPoint:{x:100,y:240},toPoint:{x:600,y:240},fromAnchor:'right' as const,toAnchor:'left' as const,label:'Old record'}};await operate(api,token,oldId,createCommands([oldEdge]));const oldBefore=await canonicalBoardSnapshot(api,token,oldId);expect(oldBefore.objects[0]!.connector!.strokeWidth).toBeUndefined();expect(oldBefore.objects[0]!.connector!.route).toBeUndefined();expect(oldBefore.objects[0]!.connector!.labelPosition).toBeUndefined();
  await page.goto(`/studio/board/${oldId}`);await synced();const row=page.getByTestId('board-a11y-object-c08-old');await row.focus();await row.press('Enter');await expect(row).toHaveAttribute('aria-pressed','true');await expect(page.getByTestId('board-connector-width-open')).toHaveText('2');await page.getByTestId('board-connector-path-open').click();await expect(page.getByTestId('board-connector-straight')).toHaveAttribute('aria-pressed','true');await page.keyboard.press('Escape');
  const surface=await page.getByTestId('board-fabric-surface').boundingBox(),zoom=Number(await page.getByTestId('board-fabric-surface').getAttribute('data-viewport-zoom')),panX=Number(await page.getByTestId('board-fabric-surface').getAttribute('data-viewport-pan-x')),panY=Number(await page.getByTestId('board-fabric-surface').getAttribute('data-viewport-pan-y')),handle=await page.getByTestId('board-connector-handle-label').boundingBox();expect(surface).not.toBeNull();expect(handle).not.toBeNull();expect([zoom,panX,panY,surface!.x,surface!.y,surface!.width,surface!.height,handle!.x,handle!.y,handle!.width,handle!.height].every(Number.isFinite)).toBe(true);expect(zoom).toBeGreaterThan(0);expect(surface!.width).toBeGreaterThan(0);expect(surface!.height).toBeGreaterThan(0);expect(handle!.width).toBeGreaterThan(0);expect(handle!.height).toBeGreaterThan(0);expect(Math.abs(handle!.x+handle!.width/2-surface!.x-panX-350*zoom)).toBeLessThan(1);expect(Math.abs(handle!.y+handle!.height/2-surface!.y-panY-240*zoom)).toBeLessThan(1);await capture('old-record-default-width-path-label');expect(await canonicalBoardSnapshot(api,token,oldId)).toEqual(oldBefore);await page.reload();await synced();expect(await canonicalBoardSnapshot(api,token,oldId)).toEqual(oldBefore);
  records.push({runtimeBefore,runtimeAfter:await verifyRuntimeIdentity(api,source,await chunks()),copyRevision:pasted.revision,duplicateReceipt:duplicated.receipt,oldRecordUnchanged:true});
 }catch(error){failure=error;}
 finally{
  for(const board of owned){try{records.push({phase:'cleanup',...await deleteOwnedConnectorFixture(api,token,board.id,F.userId,board.title)});}catch(error){cleanupErrors.push(error);}}
  try{expect(manifestBefore).toBeTruthy();records.push({phase:'runtime-manifest-after',...await verifyConnectorRuntimeManifest(manifestBefore)});}catch(error){cleanupErrors.push(error);}
  if(cleanupErrors.length)failure=new AggregateError([...(failure?[failure]:[]),...cleanupErrors],'Connector copy/default execution/cleanup failures');const path=info.outputPath('connector-copy-defaults-result.json');await writeFile(path,JSON.stringify({source,viewport,status:failure?'failed':'C08-UI-copy-default-subcases-passed',requiredC08Complete:false,records,screenshots,pending:['actual runtime and independent screenshots','portable interchange at mobile viewport']},null,2),{mode:0o600});await info.attach('connector-copy-defaults-result',{path,contentType:'application/json'});
 }
 if(failure)throw failure;
});
