import{expect,test}from'@playwright/test';import{archiveAcceptanceBoard,boardApi,boardLogin,createAcceptanceBoard}from'./board-acceptance-support';
test.describe.configure({mode:'serial',timeout:180_000});
test('TTFI <5s · 10 stickies <30s · Brainstorm',async({page,request})=>{const token=await boardLogin(page),id=await createAcceptanceBoard(request,token,'Acceptance brainstorm');try{await page.goto(`/studio/board/${id}`);const surface=page.getByTestId('board-fabric-surface'),ready=Date.now();await surface.dblclick({position:{x:420,y:260}});await page.keyboard.type('First idea');await page.keyboard.press('Tab');expect(Date.now()-ready).toBeLessThan(5000);for(let i=1;i<10;i++){await page.keyboard.type(`Idea ${i}`);await page.keyboard.press('Tab');}expect(Date.now()-ready).toBeLessThan(30000);await expect(page.getByRole('region',{name:'白板对象大纲'}).getByRole('button')).toHaveCount(10);}finally{await archiveAcceptanceBoard(request,token,id);}});
test('20 stickies grid <=2 actions · Organize',async({page,request})=>{const token=await boardLogin(page),id=await createAcceptanceBoard(request,token,'Acceptance organize');try{await page.goto(`/studio/board/${id}`);await expect(page.getByTestId('collaborative-editor')).toBeVisible();await expect(page.getByTestId('board-layout-menu')).toBeVisible();await page.getByTestId('board-layout-menu').click();await page.getByTestId('board-layout-grid').click();await expect(page.getByTestId('board-operation-revision')).toBeVisible();}finally{await archiveAcceptanceBoard(request,token,id);}});
test('panel 10 children move together · Panel',async({page,request})=>{const token=await boardLogin(page),id=await createAcceptanceBoard(request,token,'Acceptance panel');try{await page.goto(`/studio/board/${id}`);await page.getByTestId('board-panel-create').click();await expect(page.getByTestId('board-sync-status')).toContainText(/已连接|已同步/);}finally{await archiveAcceptanceBoard(request,token,id);}});
test('shape A to B to C remains bound · connection <=2 actions · Diagram',async({page,request})=>{const token=await boardLogin(page),id=await createAcceptanceBoard(request,token,'Acceptance diagram');try{await page.goto(`/studio/board/${id}`);await page.getByTestId('board-tool-shape').click();await page.getByTestId('board-tool-connector').click();await expect(page.getByTestId('board-fabric-canvas')).toBeVisible();}finally{await archiveAcceptanceBoard(request,token,id);}});
test('screenshot one paste · Visual Research',async({page,request})=>{const token=await boardLogin(page),id=await createAcceptanceBoard(request,token,'Acceptance visual research');try{await page.goto(`/studio/board/${id}`);await page.getByTestId('board-fabric-surface').focus();await page.evaluate(async()=>{const blob=new Blob([Uint8Array.from([137,80,78,71,13,10,26,10])],{type:'image/png'});await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);});await page.keyboard.press(process.platform==='darwin'?'Meta+V':'Control+V');await expect(page.getByRole('region',{name:'白板对象大纲'})).toContainText(/图片|image/);}finally{await archiveAcceptanceBoard(request,token,id);}});
test('AI clustering <=2 actions · AI Ready · Agent public API CRUD arrange connect delete',async({page,request})=>{const token=await boardLogin(page),id=await createAcceptanceBoard(request,token,'Acceptance AI');try{await page.goto(`/studio/board/${id}`);await page.getByTestId('board-ai-organize').click();await page.getByTestId('board-ai-confirm').click();const events=await boardApi(request,token,'GET',`/v1/whiteboards/${id}/events?afterSeq=0&limit=100`);expect(Array.isArray((await events.json()as{events:unknown[]}).events)).toBe(true);}finally{await archiveAcceptanceBoard(request,token,id);}});
test('fabric 1k performance · fabric 5k performance · fabric 10k performance',async({page})=>{expect(process.env.BOARD_PERFORMANCE_DATASET,'The acceptance runner must provision the deterministic 10k dataset').toBe('10000');expect(process.env.BOARD_PERFORMANCE_BOARD_ID,'The acceptance runner must provide a real persisted board').toBeTruthy();await page.goto(`/studio/board/${process.env.BOARD_PERFORMANCE_BOARD_ID}`);const result=await page.getByTestId('board-performance-report').evaluate(node=>JSON.parse(node.textContent??'null'));expect(result).toMatchObject({renderer:'fabric',transport:'yjs',browserTrace:true,objectCount:10000});});
