import { randomUUID } from 'node:crypto';
import { expect, test, type APIRequestContext, type Page } from '@playwright/test';
import { computeRenderedLayoutHash } from '@repo/whiteboard-core';
import { SESSION_TOKEN_STORAGE_KEY } from '../lib/api-client';
import { FULLSTACK_E2E } from './fullstack-smoke-fixture';

test.describe.configure({mode:'serial',timeout:120_000});
const apiOrigin=()=>`http://127.0.0.1:${process.env.WORKSPACEX_API_PORT}`;
async function login(page:Page,email:string=FULLSTACK_E2E.email,password:string=FULLSTACK_E2E.password){await page.goto('/login');await page.getByTestId('login-email').fill(email);await page.getByTestId('login-password').fill(password);await page.getByTestId('login-submit').click();await expect(page).toHaveURL(/\/projects$/);const token=await page.evaluate(key=>localStorage.getItem(key),SESSION_TOKEN_STORAGE_KEY);expect(token).toBeTruthy();return token!;}
async function call(api:APIRequestContext,token:string,method:string,path:string,data?:unknown){const response=await api.fetch(`${apiOrigin()}${path}`,{method,headers:{Authorization:`Bearer ${token}`},data});expect(response.ok(),`${method} ${path}: ${response.status()} ${await response.text()}`).toBe(true);return response;}
const geometry=(index:number)=>({x:100+(index%6)*230,y:100+Math.floor(index/6)*190,width:200,height:160,rotation:0});

test('AI clustering <=2 actions · chat fabric layout handoff · meeting room follow',async({browser,request:api,baseURL})=>{
  const context=await browser.newContext({baseURL}),page=await context.newPage();let followerContext:Awaited<ReturnType<typeof browser.newContext>>|undefined,displayContext:Awaited<ReturnType<typeof browser.newContext>>|undefined,boardId:string|undefined,token:string|undefined;
  try{token=await login(page);const created=await call(api,token,'POST','/whiteboards',{requestId:randomUUID(),name:`AI API ${randomUUID()}`});boardId=(await created.json() as{id:string}).id;
    const notes=Array.from({length:30},(_,index)=>({type:'create',object:{id:`ai-note-${index}`,schemaVersion:1,kind:'sticky',geometry:geometry(index),text:`Customer theme ${index%3}`,style:{fill:'#FFF2A8'},parentId:null,orderKey:String(index).padStart(3,'0')}}));
    const humanActor={kind:'human' as const,actorId:FULLSTACK_E2E.userId,orgId:FULLSTACK_E2E.orgId,role:'owner' as const,scopes:['board:read' as const,'board:write' as const],delegatedBy:null};
    const first=await call(api,token,'POST',`/v1/whiteboards/${boardId}/operations`,{apiVersion:'2026-09-01',requestId:randomUUID(),boardId,expectedRevision:{epoch:1,seq:0},actor:humanActor,commands:notes,provenance:{source:'human',model:null,skill:null,sourceArtifactId:null,sourceRevision:null,layoutHash:null,inputObjectIds:[]}});const receipt=await first.json() as{revision:{seq:number}};
    const proposalId=randomUUID(),aiActor={kind:'ai' as const,actorId:FULLSTACK_E2E.agentId,orgId:FULLSTACK_E2E.orgId,role:'owner' as const,scopes:['board:write' as const],delegatedBy:FULLSTACK_E2E.userId};const proposalResponse=await call(api,token,'POST',`/v1/whiteboards/${boardId}/ai-proposals`,{proposalId,actorId:aiActor.actorId,baseRevision:{epoch:1,seq:receipt.revision.seq},action:{type:'arrange',objectIds:notes.map((_,index)=>`ai-note-${index}`),layout:'grid',commands:notes.map((_,index)=>({type:'geometry',id:`ai-note-${index}`,geometry:geometry(index)}))},provenance:{source:'ai-proposal',model:'ignored-client',skill:'ignored-client',sourceArtifactId:null,sourceRevision:null,layoutHash:null,inputObjectIds:[]}});expect((await proposalResponse.json()as{status:string}).status).toBe('preview');
    await page.goto(`/studio/board/${boardId}?proposal=${proposalId}`);await expect(page.getByTestId('board-ai-proposal')).toBeVisible();await page.getByTestId('board-ai-confirm').click();await expect(page.getByTestId('board-ai-proposal')).toHaveCount(0);
    const head=await(await call(api,token,'GET',`/v1/whiteboards/${boardId}/head`)).json()as{epoch:number;seq:number;role:string};const expectedRevision={epoch:head.epoch,seq:head.seq};const artifactId=FULLSTACK_E2E.boardArtifactId,layoutBody={schemaVersion:1 as const,artifactId,orgId:FULLSTACK_E2E.orgId,sourceRevision:'artifact-v1:1',diagramKind:'flowchart' as const,objects:[{sourceId:'artifact-node',kind:'node' as const,geometry:{x:1600,y:100,width:220,height:120,rotation:0},text:'Chat Mermaid node',style:{fill:'#FFFFFF',shape:'rect',direction:'TD'},fromSourceId:null,toSourceId:null}],selectedSourceIds:[]};
    const layout={...layoutBody,layoutHash:computeRenderedLayoutHash(layoutBody)};
    const artifact=await call(api,token,'POST',`/v1/whiteboards/${boardId}/artifact-handoffs`,{requestId:randomUUID(),expectedRevision,layout,offset:{x:24,y:24}});
    const artifactReceipt=await artifact.json() as{revision:{seq:number}};
    const events=await call(api,token,'GET',`/v1/whiteboards/${boardId}/events?afterSeq=0&limit=100`);const pageOfEvents=await events.json() as{events:{type:string;provenance:{layoutHash:string|null}}[];nextSeq:number};expect(pageOfEvents.events.map(event=>event.type)).toEqual(['ObjectCreated','AIOrganized','ObjectCreated']);expect(pageOfEvents.events[2]?.provenance.layoutHash).toBe(layout.layoutHash);expect(pageOfEvents.nextSeq).toBe(artifactReceipt.revision.seq);
    await call(api,token,'PUT',`/whiteboards/${boardId}/members`,{userId:FULLSTACK_E2E.memberUserId,role:'viewer'});await call(api,token,'PUT',`/whiteboards/${boardId}/members`,{userId:FULLSTACK_E2E.adminUserId,role:'editor'});displayContext=await browser.newContext({baseURL});const display=await displayContext.newPage(),displayToken=await login(display,FULLSTACK_E2E.adminEmail,FULLSTACK_E2E.adminPassword);const joined=await(await call(api,displayToken,'POST',`/v1/whiteboards/${boardId}/rooms/join`,{roomId:'e2e-room',deviceId:'meeting-room-display',deviceKind:'meeting-display'})).json()as{actorId:string;reconnectToken:string};expect(joined.actorId).toBe('room:e2e-room:meeting-room-display');expect(joined.reconnectToken.length).toBeGreaterThan(16);
    await call(api,token,'POST',`/v1/whiteboards/${boardId}/presentation`,{roomId:'e2e-room',command:{type:'claim-presenter',actorId:FULLSTACK_E2E.userId,expectedRevision:0}});await page.goto(`/studio/board/${boardId}?room=e2e-room`);await expect(page.getByRole('button',{name:'结束演示'})).toBeVisible();await expect(page.getByRole('button',{name:'图形：Customer theme 0',exact:true}).first()).toBeVisible({timeout:30_000});await expect(page.getByRole('button',{name:'图形：Chat Mermaid node',exact:true})).toBeVisible();await page.getByRole('button',{name:'交给会议室'}).click();await expect.poll(async()=>((await(await call(api,token!,'GET',`/v1/whiteboards/${boardId}/presentation?roomId=e2e-room`)).json())as{presenterId:string|null}).presenterId).toBe(joined.actorId);
    followerContext=await browser.newContext({baseURL});const follower=await followerContext.newPage();await login(follower,FULLSTACK_E2E.memberEmail,FULLSTACK_E2E.memberPassword);await follower.goto(`/studio/board/${boardId}?room=e2e-room`);await follower.getByRole('button',{name:'跟随演示者'}).click();await expect(follower.getByRole('button',{name:'自由浏览'})).toBeVisible();await follower.getByRole('button',{name:'自由浏览'}).click();await expect(follower.getByRole('button',{name:'跟随演示者'})).toBeVisible();
  }finally{try{if(boardId&&token){const board=await(await call(api,token,'GET',`/whiteboards/${boardId}`)).json()as{archived:boolean;lifecycleRevision:number};if(!board.archived)await call(api,token,'PATCH',`/whiteboards/${boardId}`,{archived:true,expectedLifecycleRevision:board.lifecycleRevision});}}finally{if(followerContext)await followerContext.close();if(displayContext)await displayContext.close();await context.close();}}
});
