import { randomUUID } from 'node:crypto';
import { expect,test,type Page,type APIRequestContext } from '@playwright/test';
import { SESSION_TOKEN_STORAGE_KEY } from '../lib/api-client';
import { FULLSTACK_E2E } from './fullstack-smoke-fixture';

/** Real API + PostgreSQL + object-store chain. Route interception is forbidden in this spec. */
test.describe.configure({mode:'serial',timeout:120_000});
const apiUrl=()=>process.env.WHITEBOARD_API_URL??(process.env.WORKSPACEX_API_PORT?`http://127.0.0.1:${process.env.WORKSPACEX_API_PORT}`:undefined);
async function login(page:Page){const email=process.env.WHITEBOARD_OWNER_EMAIL??FULLSTACK_E2E.adminEmail,password=process.env.WHITEBOARD_OWNER_PASSWORD??FULLSTACK_E2E.adminPassword;if(!email||!password)throw new Error('Missing real Board owner fixture');await page.goto('/login');await page.getByTestId('login-email').fill(email);await page.getByTestId('login-password').fill(password);await page.getByTestId('login-submit').click();await expect(page).toHaveURL(/\/projects$/);const token=await page.evaluate(key=>localStorage.getItem(key),SESSION_TOKEN_STORAGE_KEY);if(!token)throw new Error('Login did not issue session token');return token;}
async function call(api:APIRequestContext,token:string,method:string,path:string,data?:unknown){const base=apiUrl();if(!base)throw new Error('Missing WHITEBOARD_API_URL');const response=await api.fetch(`${base.replace(/\/$/,'')}${path}`,{method,headers:{Authorization:`Bearer ${token}`},data});expect(response.ok(),`${method} ${path}: ${response.status()}`).toBe(true);return response;}

test('Miro Mural import report',async({page,request:api})=>{const token=await login(page),created=await call(api,token,'POST','/whiteboards',{requestId:randomUUID(),name:`Import ${randomUUID()}`}),boardId=(await created.json() as{id:string}).id;try{await page.goto(`/studio/board/${boardId}`);await expect(page.getByTestId('collaborative-editor')).toBeVisible({timeout:30_000});await page.getByTestId('board-import-open').click();await page.getByTestId('board-import-file').setInputFiles({name:'board.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({board:{id:'source-1'},version:'rev-7',widgets:[{id:'note',type:'sticker',text:'Imported idea'},{id:'video',type:'video'}]}))});await page.getByTestId('board-import-submit').click();await expect(page.getByTestId('board-import-progress')).toContainText('导入完成',{timeout:30_000});await expect(page.getByTestId('board-import-report')).toContainText('成功 1 · 降级 0 · 跳过 1 · 失败 0');await expect(page.getByTestId('board-import-report')).toContainText('UNSUPPORTED_ITEM');const download=page.waitForEvent('download');await page.getByTestId('board-import-report-download').click();expect((await download).suggestedFilename()).toMatch(/^whiteboard-import-[0-9a-f-]+\.json$/);await page.reload();await expect(page.getByRole('button',{name:'图形：Imported idea',exact:true})).toBeVisible({timeout:30_000});}finally{await call(api,token,'PATCH',`/whiteboards/${boardId}`,{archived:true});}});
