import { describe,it,expect } from 'vitest';
import { fixedMaintenanceActivationActions,maintenanceActivationAction,assertMaintenanceActivationCapability } from '../src/cn-maintenance-host/activation_transport';
import type { CommandRunner } from '../src/cn-maintenance-host/fixed_transport';
const identity={sourceRevision:'9'.repeat(40),baselineRevision:'b'.repeat(40),migrationPlanSha256:'c'.repeat(64),attemptId:'attempt'};
const binding={identity,toolRevision:'d'.repeat(40),activationCommand:{path:'/usr/local/lib/workspacex-cn/cn-maintenance-activation.py',sha256:'e'.repeat(64)},recoveryCommand:{path:'/usr/local/lib/workspacex-cn/cn-production-recovery-executor.py',sha256:'f'.repeat(64)},plan:{path:`/etc/workspacex-cn/maintenance-activation/${identity.sourceRevision}/attempt/activation-plan.json`,sha256:'a'.repeat(64)},recoveryPlan:{path:`/etc/workspacex-cn/maintenance-recovery/${identity.sourceRevision}/attempt/recovery-plan.json`,sha256:'1'.repeat(64)}};
const wrapped=(action:string,result:unknown)=>JSON.stringify({schemaVersion:1,kind:'maintenance-activation-operation',identity,toolRevision:binding.toolRevision,planSha256:binding.plan.sha256,action,writesHeld:true,result});
describe('fixed maintenance activation consumer',()=>{
 it('startup rejects absent controlled acceptance writer lane before mutation',()=>expect(()=>assertMaintenanceActivationCapability()).toThrow('MAINTENANCE_ACCEPTANCE_WRITER_LANE_NOT_IMPLEMENTED'));
 it('rejects ordinary deploy/container rollback command binding',()=>{expect(()=>fixedMaintenanceActivationActions({...binding,recoveryCommand:{...binding.recoveryCommand,path:'/usr/local/bin/workspacex-cn-deploy'}})).toThrow('COMMAND_BINDING');});
 it('uses exact fixed command and pinned plan argv',async()=>{const calls:unknown[]=[];const run:CommandRunner=async(c,args)=>{calls.push([c.path,args]);return {stdout:wrapped(args[3]!,{baselineSha256:'2'.repeat(64)})};};expect(await fixedMaintenanceActivationActions(binding,run).readBaselineFingerprint()).toBe('2'.repeat(64));expect(calls).toEqual([[binding.activationCommand.path,['--maintenance-activation-operation',binding.plan.path,binding.plan.sha256,'read-baseline-fingerprint']]]);});
 it('rejects response attempt drift',async()=>{const run:CommandRunner=async()=>({stdout:JSON.stringify({...JSON.parse(wrapped('read-baseline-fingerprint',{baselineSha256:'2'.repeat(64)})),identity:{...identity,attemptId:'other'}})});await expect(fixedMaintenanceActivationActions(binding,run).readBaselineFingerprint()).rejects.toThrow('RESPONSE_BINDING');});
 it('cannot accept health-only or missing browser journeys',async()=>{const run:CommandRunner=async()=>({stdout:wrapped('browser-acceptance',{login:true})});await expect(fixedMaintenanceActivationActions(binding,run).runBrowserSmoke()).rejects.toThrow();});
 it('refuses unheld canonical verification',async()=>{const run:CommandRunner=async()=>({stdout:wrapped('verify-canonical',{status:'passed',lockRetained:false,passedStages:8})});await expect(fixedMaintenanceActivationActions(binding,run).verifyCanonical()).rejects.toThrow();});
 it('runs retained triple-DB recovery before baseline runtime/pointer',async()=>{const calls:string[]=[];const run:CommandRunner=async(c,args)=>{if(c.path===binding.recoveryCommand.path){calls.push('three-db');return {stdout:JSON.stringify({schemaVersion:1,kind:'production-recovery-completed',identity,receiptSha256:'3'.repeat(64),writesHeld:true,ready:false})};}calls.push(args[3]!);return {stdout:wrapped(args[3]!,args[3]==='verify-recovery-plan'?{recoveryPlanSha256:binding.recoveryPlan.sha256}:{baselineRuntimeRecovered:true,databaseRecoveryReceiptSha256:'3'.repeat(64)})};};const recover=async(actual:typeof identity,plan:typeof binding.recoveryPlan)=>{expect(actual).toEqual(identity);expect(plan).toEqual(binding.recoveryPlan);calls.push('three-db');return {schemaVersion:1,kind:'production-recovery-completed',identity,receiptSha256:'3'.repeat(64),writesHeld:true,ready:false};};await fixedMaintenanceActivationActions(binding,run,recover).restoreBaseline();expect(calls).toEqual(['verify-recovery-plan','three-db','restore-baseline-runtime']);});
 it('never restores runtime when triple-DB recovery fails',async()=>{const calls:string[]=[];const run:CommandRunner=async(c,args)=>{if(c.path===binding.recoveryCommand.path)throw Error('failed');calls.push(args[3]!);return {stdout:wrapped(args[3]!,{recoveryPlanSha256:binding.recoveryPlan.sha256})};};await expect(fixedMaintenanceActivationActions(binding,run,async()=>{throw Error('failed');}).restoreBaseline()).rejects.toThrow('failed');expect(calls).toEqual(['verify-recovery-plan']);});
 it('rejects absent retained recovery before any command',async()=>{const calls:string[]=[];const run:CommandRunner=async()=>{calls.push('unexpected');throw Error('unexpected');};await expect(fixedMaintenanceActivationActions(binding,run).restoreBaseline()).rejects.toThrow('PERSISTENT_RECOVERY_REQUIRED');expect(calls).toEqual([]);});
 it('cannot use private plan from another attempt',()=>expect(()=>fixedMaintenanceActivationActions({...binding,recoveryPlan:{...binding.recoveryPlan,path:binding.recoveryPlan.path.replace('/attempt/','/other/')}})).toThrow('PLAN_BINDING'));
 it('does not interpret ordinary fast receipt as destructive maintenance authorization',async()=>{await expect(maintenanceActivationAction({},{} as never)(identity)).rejects.toThrow();});
});
