import {mkdtemp,mkdir,rm,writeFile} from "node:fs/promises";import {tmpdir} from "node:os";import {join} from "node:path";
import {describe,expect,it} from "vitest";
import {executeInitialSyncStage,initialProductionSyncPlan,validateInitialSyncAcceptance,verifyOssInventory,writeInitialSyncReceipt} from "../src/initial-production-sync";
const id="123e4567-e89b-42d3-a456-426614174000",sha="a".repeat(40),digest="b".repeat(64);
const config={schemaVersion:1,migrationId:id,sourceDatabase:{mode:"secret-ref",secretRef:"env:SOURCE_DB"},targetDatabaseSecretRef:"file:/etc/workspacex-cn/target-db.json",sourceObjects:{mode:"oss",bucket:"devapp-files",prefix:"objects/dev"},targetOss:{bucket:"workspacex-cn-files",prefix:"objects/prod"},workDirectory:"/var/lib/workspacex-sync",schemaRevision:sha,keyMigration:{mode:"rotate-required"}};
describe("initial production sync",()=>{
 it("creates a dry-run plan without credentials",()=>{const plan=initialProductionSyncPlan(config);expect(plan.dryRun).toBe(true);expect(JSON.stringify(plan)).not.toContain("password");expect(plan.commands.map(c=>c[0])).toEqual(["pg_dump","pg_restore","oss-sync","oss-sync","verify-initial-production-sync"]);const dockerPlan=initialProductionSyncPlan({...config,sourceDatabase:{mode:"devapp-docker",container:"workspacex-postgres-1",database:"workspacex",user:"postgres"}});expect(dockerPlan.commands[0]?.slice(0,4)).toEqual(["docker","exec","-i","workspacex-postgres-1"]);expect(dockerPlan.secretRefs).toEqual([config.targetDatabaseSecretRef]);});
 it.each([
  {...config,targetDatabaseSecretRef:"env:SOURCE_DB"},
  {...config,targetOss:{bucket:"devapp-files",prefix:"objects/dev"}},
  {...config,workDirectory:"relative"},
  {...config,sourceDatabase:{mode:"devapp-docker",container:"--privileged",database:"workspacex",user:"postgres"}},
  {...config,sourceObjects:{mode:"filesystem",root:"relative"}},
  {...config,keyMigration:{mode:"same-key-confirmed",confirmedBy:"",keyId:"key"}},
 ])("rejects unsafe parameters",value=>expect(()=>initialProductionSyncPlan(value)).toThrow());
 it("compares OSS key, size and digest exactly",()=>{const inventory={schemaVersion:1,bucket:"devapp-files",prefix:"objects/dev",objects:[{key:"a",size:3,sha256:digest}]};expect(verifyOssInventory(inventory,{...inventory,bucket:"workspacex-cn-files"}).verified).toBe(true);expect(verifyOssInventory(inventory,{...inventory,objects:[{key:"a",size:4,sha256:digest}]}).verified).toBe(false);});
 it("requires rotation when ciphertext was detected",()=>{const receipt={schemaVersion:1,migrationId:id,schemaRevision:sha,dumpSha256:digest,sourceSnapshot:"00000001/00000002",databaseRestored:true,foreignKeysValid:true,criticalReferencesValid:true,ossBaselineComplete:true,ossDeltaComplete:true,ossInventoryVerified:true,secretCiphertextsDetected:true,keyDecision:"same-key-confirmed",completedAt:"2026-09-12T00:00:00.000Z"};expect(()=>validateInitialSyncAcceptance(config,receipt)).toThrow("ROTATION_REQUIRED");expect(validateInitialSyncAcceptance(config,{...receipt,keyDecision:"rotated"}).accepted).toBe(true);});
 it("publishes a receipt once and rejects replay",async()=>{const root=await mkdtemp(join(tmpdir(),"initial-sync-"));try{const receipt={schemaVersion:1,migrationId:id,schemaRevision:sha,dumpSha256:digest,sourceSnapshot:"00000001/00000002",databaseRestored:true,foreignKeysValid:true,criticalReferencesValid:true,ossBaselineComplete:true,ossDeltaComplete:true,ossInventoryVerified:true,secretCiphertextsDetected:true,keyDecision:"rotated",completedAt:"2026-09-12T00:00:00.000Z"};const path=join(root,"receipt.json");await writeInitialSyncReceipt(config,receipt,path);await expect(writeInitialSyncReceipt(config,receipt,path)).rejects.toThrow("ALREADY_RECORDED");}finally{await rm(root,{recursive:true,force:true});}});
 it("executes dump without credentials in argv and resumes completed stages",async()=>{const root=await mkdtemp(join(tmpdir(),"initial-run-"));try{const value={...config,workDirectory:root};await mkdir(join(root,id));const calls:string[][]=[];const run=async(exe:string,args:readonly string[],options:{env?:NodeJS.ProcessEnv;stdoutFile?:string})=>{calls.push([exe,...args]);expect(args.join(" ")).not.toContain("private-password");expect(options.env?.PGPASSWORD).toBe("private-password-123");expect(options.stdoutFile).toBe(join(root,id,"database.dump"));await writeFile(join(root,id,"database.dump"),"dump",{mode:0o600});return "";};const state={schemaVersion:1 as const,migrationId:id,schemaRevision:sha,completed:[]};const next=await executeInitialSyncStage(value,state,"database-dump",run,{SOURCE_DB:JSON.stringify({host:"source.internal",database:"workspacex",user:"owner",password:"private-password-123",sslmode:"verify-full"})});expect(next.completed).toEqual(["database-dump"]);const resumed=await executeInitialSyncStage(value,next,"database-dump",run,{});expect("resumed" in resumed&&resumed.resumed).toBe(true);expect(calls).toHaveLength(1);}finally{await rm(root,{recursive:true,force:true});}});
 it("dumps directly from Devapp Docker without a secret or shell",async()=>{const root=await mkdtemp(join(tmpdir(),"initial-docker-"));try{const value={...config,workDirectory:root,sourceDatabase:{mode:"devapp-docker",container:"workspacex-postgres-1",database:"workspacex",user:"postgres"}};await mkdir(join(root,id));const calls:Array<{exe:string;args:readonly string[];env?:NodeJS.ProcessEnv;stdoutFile?:string}>=[];const run=async(exe:string,args:readonly string[],options:{env?:NodeJS.ProcessEnv;stdoutFile?:string})=>{calls.push({exe,args,env:options.env,stdoutFile:options.stdoutFile});await writeFile(options.stdoutFile!,"docker-dump",{mode:0o600});return "";};const state={schemaVersion:1 as const,migrationId:id,schemaRevision:sha,completed:[]};const next=await executeInitialSyncStage(value,state,"database-dump",run,{});expect(calls).toEqual([{exe:"docker",args:["exec","-i","workspacex-postgres-1","pg_dump","--format=custom","--serializable-deferrable","--lock-wait-timeout=10000","--username","postgres","--dbname","workspacex"],env:undefined,stdoutFile:join(root,id,"database.dump")}]);expect(next.dumpSha256).toMatch(/^[a-f0-9]{64}$/);}finally{await rm(root,{recursive:true,force:true});}});
 it("syncs a Devapp filesystem baseline and frozen delta to OSS",async()=>{const value={...config,sourceObjects:{mode:"filesystem",root:"/opt/workspacex/objects"}};const calls:string[][]=[];const run=async(exe:string,args:readonly string[])=>{calls.push([exe,...args]);return "";};const baseline={schemaVersion:1 as const,migrationId:id,schemaRevision:sha,completed:["database-dump","database-restore"] as ("database-dump"|"database-restore")[],dumpSha256:digest};const afterBaseline=await executeInitialSyncStage(value,baseline,"oss-baseline",run,{});await executeInitialSyncStage(value,afterBaseline,"oss-delta",run,{}, {writeFreezeConfirmed:true});expect(calls).toEqual([["ossutil","sync","/opt/workspacex/objects","oss://workspacex-cn-files/objects/prod","--delete"],["ossutil","sync","/opt/workspacex/objects","oss://workspacex-cn-files/objects/prod","--delete"]]);});
 it("protects stage order, nonempty targets and unfrozen delta",async()=>{const state={schemaVersion:1 as const,migrationId:id,schemaRevision:sha,completed:["database-dump"] as ("database-dump")[],dumpSha256:digest};const run=async()=>"1";await expect(executeInitialSyncStage(config,state,"database-restore",run,{})).rejects.toThrow();await expect(executeInitialSyncStage(config,{...state,completed:["database-dump","database-restore","oss-baseline"]},"oss-delta",run,{})).rejects.toThrow("WRITE_FREEZE_REQUIRED");});
});
