import { BadRequestException, Body, ConflictException, Controller, ForbiddenException, Get, HttpException, HttpStatus, Inject, NotFoundException, Param, ParseUUIDPipe, Post, Query, ServiceUnavailableException } from '@nestjs/common';
import type { Principal } from '../../domain/principal';
import { assertPrincipal } from '../../domain/principal';
import { WHITEBOARD_OPERATION_SERVICE, WhiteboardOperationError, type WhiteboardOperationService, type WhiteboardRateLimitedEntry } from '../../application/whiteboard/operation-service';
import { WHITEBOARD_PROPOSAL_SERVICE, type WhiteboardProposalService } from '../../application/whiteboard/proposal-service';
import { WHITEBOARD_PRESENTATION_SERVICE, type WhiteboardPresentationService } from '../../application/whiteboard/presentation-service';
import { CurrentPrincipal } from '../current-principal.decorator';
import {DATABASE_PORT,type DatabasePort} from '../../application/ports/database.port';

/** Versioned public Board API. Service/API/AI callers use the same actor-bound operation envelope. */
@Controller('v1/whiteboards/:boardId')
export class WhiteboardOperationController {
  constructor(@Inject(WHITEBOARD_OPERATION_SERVICE)private readonly service:WhiteboardOperationService,@Inject(WHITEBOARD_PROPOSAL_SERVICE)private readonly proposals:WhiteboardProposalService,@Inject(WHITEBOARD_PRESENTATION_SERVICE)private readonly presentation:WhiteboardPresentationService,@Inject(DATABASE_PORT)private readonly db:DatabasePort){}
  @Post('operations')
  async execute(@CurrentPrincipal()principal:Principal,@Param('boardId',new ParseUUIDPipe())boardId:string,@Body()body:unknown){assertPrincipal(principal);try{await this.limit(principal,boardId,'operation');return await this.service.execute(principal,boardId,body);}catch(error){this.rethrow(error);}}
  @Post('artifact-handoffs') async artifactHandoff(@CurrentPrincipal()p:Principal,@Param('boardId',new ParseUUIDPipe())b:string,@Body()body:unknown){try{await this.limit(p,b,'artifact-handoff');return await this.service.handoff(p,b,body);}catch(error){this.rethrow(error);}}
  @Get('events')
  async events(@CurrentPrincipal()principal:Principal,@Param('boardId',new ParseUUIDPipe())boardId:string,@Query('afterSeq')afterSeq?:string,@Query('limit')limit?:string){assertPrincipal(principal);try{await this.limit(principal,boardId,'events');return await this.service.events(principal,boardId,{afterSeq:afterSeq===undefined?0:Number(afterSeq),limit:limit===undefined?100:Number(limit)});}catch(error){this.rethrow(error);}}
  @Get('head') async head(@CurrentPrincipal()p:Principal,@Param('boardId',new ParseUUIDPipe())b:string){try{await this.limit(p,b,'head');return await this.service.head(p,b);}catch(error){this.rethrow(error);}}
  @Post('ai-proposals') async createProposal(@CurrentPrincipal()p:Principal,@Param('boardId',new ParseUUIDPipe())b:string,@Body()body:unknown){try{await this.limit(p,b,'proposal-create');return await this.proposals.create(p,b,body);}catch(error){this.rethrow(error);}}
  @Get('ai-proposals/:proposalId') async readProposal(@CurrentPrincipal()p:Principal,@Param('boardId',new ParseUUIDPipe())b:string,@Param('proposalId',new ParseUUIDPipe())id:string){try{await this.limit(p,b,'proposal-read');return await this.proposals.read(p,b,id);}catch(error){this.rethrow(error);}}
  @Post('ai-proposals/:proposalId/cancel') async cancelProposal(@CurrentPrincipal()p:Principal,@Param('boardId',new ParseUUIDPipe())b:string,@Param('proposalId',new ParseUUIDPipe())id:string,@Body()body:unknown){try{await this.limit(p,b,'proposal-cancel');return await this.proposals.cancel(p,b,id,body);}catch(error){this.rethrow(error);}}
  @Post('ai-proposals/:proposalId/confirm') async confirmProposal(@CurrentPrincipal()p:Principal,@Param('boardId',new ParseUUIDPipe())b:string,@Param('proposalId',new ParseUUIDPipe())id:string,@Body()body:unknown){try{await this.limit(p,b,'proposal-confirm');return await this.proposals.confirmWithUndo(p,b,id,body);}catch(error){this.rethrow(error);}}
  @Post('rooms/join') async joinRoom(@CurrentPrincipal()p:Principal,@Param('boardId',new ParseUUIDPipe())b:string,@Body()body:unknown){try{await this.limit(p,b,'room-join');return await this.presentation.join(p,b,body);}catch(error){this.rethrow(error);}}
  @Get('presentation') async readPresentation(@CurrentPrincipal()p:Principal,@Param('boardId',new ParseUUIDPipe())b:string,@Query('roomId')roomId:string){try{await this.limit(p,b,'presentation-read');return await this.presentation.read(p,b,roomId);}catch(error){this.rethrow(error);}}
  @Post('presentation') async updatePresentation(@CurrentPrincipal()p:Principal,@Param('boardId',new ParseUUIDPipe())b:string,@Body()body:unknown){try{await this.limit(p,b,'presentation-command');return await this.presentation.dispatch(p,b,body);}catch(error){this.rethrow(error);}}
  private async limit(principal:Principal,boardId:string,_entry:WhiteboardRateLimitedEntry){const allowed=await this.db.withTenant(principal.orgId,async session=>{const result=await session.query<{allowed:boolean}>(`INSERT INTO whiteboard_api_rate_limits(org_id,board_id,principal_id,window_started,count) VALUES($1,$2,$3,date_trunc('minute',clock_timestamp()),1) ON CONFLICT(org_id,board_id,principal_id) DO UPDATE SET window_started=CASE WHEN whiteboard_api_rate_limits.window_started<date_trunc('minute',clock_timestamp()) THEN date_trunc('minute',clock_timestamp()) ELSE whiteboard_api_rate_limits.window_started END,count=CASE WHEN whiteboard_api_rate_limits.window_started<date_trunc('minute',clock_timestamp()) THEN 1 ELSE whiteboard_api_rate_limits.count+1 END RETURNING count<=120 AS allowed`,[principal.orgId,boardId,principal.userId]);return result.rows[0]?.allowed===true;});if(!allowed)throw new WhiteboardOperationError('RATE_LIMITED');}
  private rethrow(error:unknown):never{if(error instanceof WhiteboardOperationError){if(error.code==='FORBIDDEN')throw new ForbiddenException();if(error.code==='NOT_FOUND')throw new NotFoundException();if(error.code==='DEPENDENCY_UNAVAILABLE')throw new ServiceUnavailableException();if(error.code==='RATE_LIMITED')throw new HttpException('RATE_LIMITED',HttpStatus.TOO_MANY_REQUESTS);if(error.code==='STALE_REVISION'||error.code==='IDEMPOTENCY_CONFLICT'||error.code==='ARCHIVED')throw new ConflictException(error.code);throw new BadRequestException();}if(error instanceof Error&&error.name==='ZodError')throw new BadRequestException();throw error;}
}
