'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { compareBoardCheckpoint, createBoardCheckpoint, getBoardHistoryHead, listBoardCheckpoints, previewBoardCheckpoint, restoreBoardCheckpoint, type BoardCheckpoint } from '@/lib/live-whiteboard';

export function HistoryPanel({ boardId, boardName, canEdit, onClose }: { boardId: string; boardName: string; canEdit: boolean; onClose: () => void }) {
  const router=useRouter(),[items,setItems]=useState<BoardCheckpoint[]>([]),[label,setLabel]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const [preview,setPreview]=useState<Awaited<ReturnType<typeof previewBoardCheckpoint>>|null>(null),[comparison,setComparison]=useState<Awaited<ReturnType<typeof compareBoardCheckpoint>>|null>(null);
  const reload=async()=>setItems(await listBoardCheckpoints(boardId));
  useEffect(()=>{let active=true;void listBoardCheckpoints(boardId).then(value=>{if(active)setItems(value);}).catch(()=>{if(active)setNotice('无法读取历史记录。');});return()=>{active=false;};},[boardId]);
  async function create(){if(!label.trim()||!reason.trim()||busy)return;setBusy(true);setNotice('');try{const expectedHead=await getBoardHistoryHead(boardId);await createBoardCheckpoint(boardId,{label,reason,retentionDays:365,expectedHead});setLabel('');setReason('');await reload();setNotice('已保存不可变版本。');}catch{setNotice('保存失败；白板已变化、权限或存储状态可能已更新。');}finally{setBusy(false);}}
  async function inspect(item:BoardCheckpoint){setBusy(true);try{setPreview(await previewBoardCheckpoint(boardId,item.id));setComparison(null);}catch{setNotice('无法读取该版本。');}finally{setBusy(false);}}
  async function compare(item:BoardCheckpoint){setBusy(true);try{setComparison(await compareBoardCheckpoint(boardId,{fromCheckpointId:item.id,to:'current'}));setPreview(null);}catch{setNotice('无法比较版本。');}finally{setBusy(false);}}
  async function restore(item:BoardCheckpoint){if(!canEdit||busy)return;const why=reason.trim()||`从版本 ${item.label} 恢复`;setBusy(true);try{const receipt=await restoreBoardCheckpoint(boardId,item.id,{sourceContentDigest:item.contentDigest,boardName:`${boardName} · 恢复副本`,reason:why,retentionDays:365});setNotice(`恢复副本已创建，操作者 ${receipt.actorId}`);router.push(`/studio/board/${receipt.restoredBoardId}`);}catch{setNotice('恢复失败；源白板和当前白板均未改变。');}finally{setBusy(false);}}
  return <aside data-testid="board-history-panel" className="w-96 shrink-0 overflow-y-auto border-l border-border bg-card p-3 text-card-foreground">
    <div className="flex items-center justify-between"><h2 className="text-16 font-semibold">版本历史</h2><Button onClick={onClose}>关闭</Button></div>
    <p className="my-2 text-12 text-muted-foreground">版本内容保存在加密对象存储。恢复会创建新白板，源白板与当前白板保持不变。</p>
    {canEdit&&<div className="space-y-2"><Input aria-label="版本名称" maxLength={100} value={label} onChange={event=>setLabel(event.target.value)} placeholder="例如：会后定稿"/><Input aria-label="保存原因" maxLength={500} value={reason} onChange={event=>setReason(event.target.value)} placeholder="记录保存或恢复原因"/><Button disabled={busy||!label.trim()||!reason.trim()} onClick={create}>保存当前版本</Button></div>}
    <p role="status" className="my-2 min-h-5 text-12">{notice}</p>
    <ul className="space-y-2">{items.map(item=><li key={item.id} className="rounded-control border border-border p-2"><strong className="block text-13">{item.label}</strong><span className="block text-11 text-muted-foreground">{item.creatorId} · seq {item.seq} · {item.objectCount} 个对象</span><span className="block text-11 text-muted-foreground">{item.reason} · 保留至 {new Date(item.retentionUntil).toLocaleDateString()}</span><div className="mt-2 flex flex-wrap gap-1"><Button disabled={busy} onClick={()=>inspect(item)}>预览</Button><Button disabled={busy} onClick={()=>compare(item)}>与当前比较</Button>{canEdit&&item.retentionState!=='expired'&&<Button disabled={busy} onClick={()=>restore(item)}>创建恢复副本</Button>}</div></li>)}</ul>
    {!items.length&&<p className="text-13 text-muted-foreground">还没有保存版本。</p>}
    {preview&&<Preview value={preview} onClose={()=>setPreview(null)}/>} {comparison&&<Comparison value={comparison} onClose={()=>setComparison(null)}/>}
  </aside>;
}
function Preview({value,onClose}:{value:Awaited<ReturnType<typeof previewBoardCheckpoint>>;onClose:()=>void}) { return <section data-testid="board-history-preview" className="mt-3 rounded-control border border-border bg-panel-alt p-2"><div className="flex justify-between"><h3 className="text-13 font-semibold">只读预览：{value.checkpoint.label}</h3><Button onClick={onClose}>收起</Button></div><div className="relative mt-2 h-56 overflow-hidden rounded bg-background">{value.objects.slice(0,300).map(object=><div key={object.id} title={`${object.kind}: ${object.text}`} className="absolute overflow-hidden border border-border bg-warning-tint p-1 text-[8px]" style={{left:`${Math.max(0,Math.min(90,(object.geometry.x+1000)/40))}%`,top:`${Math.max(0,Math.min(90,(object.geometry.y+1000)/40))}%`,width:Math.max(12,Math.min(60,object.geometry.width/8)),height:Math.max(10,Math.min(50,object.geometry.height/8))}}>{object.text||object.kind}</div>)}</div><p className="mt-1 text-11 text-muted-foreground">显示 {Math.min(value.objects.length,300)} / {value.objects.length}；缺失父级或连接端点会在对象详情中保留。</p></section>; }
function Comparison({value,onClose}:{value:Awaited<ReturnType<typeof compareBoardCheckpoint>>;onClose:()=>void}) { return <section data-testid="board-history-comparison" className="mt-3 rounded-control border border-border bg-panel-alt p-2"><div className="flex justify-between"><h3 className="text-13 font-semibold">对象级差异</h3><Button onClick={onClose}>收起</Button></div><p className="text-12">新增 {value.added} · 修改 {value.modified} · 删除 {value.deleted}</p><ul className="mt-2 max-h-48 overflow-y-auto text-11">{value.changes.map(change=><li key={`${change.change}-${change.id}`}>{change.change} · {change.after?.kind??change.before?.kind} · {change.after?.text||change.before?.text||change.id}</li>)}</ul></section>;}
