'use client';
import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { compareBoardCheckpoint, createBoardCheckpoint, getBoardHistoryHead, listBoardCheckpoints, previewBoardCheckpoint, restoreBoardCheckpoint, type BoardCheckpoint } from '@/lib/live-whiteboard';
import { WhiteboardRenderer } from './whiteboard-renderer';

export function HistoryPanel({ boardId, boardName, canEdit, onClose }: { boardId: string; boardName: string; canEdit: boolean; onClose: () => void }) {
  const router=useRouter(),[items,setItems]=useState<BoardCheckpoint[]>([]),[label,setLabel]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const createIntent=useRef<{key:string;requestId:string}|null>(null),restoreIntent=useRef<{key:string;requestId:string}|null>(null);
  const [preview,setPreview]=useState<Awaited<ReturnType<typeof previewBoardCheckpoint>>|null>(null),[comparison,setComparison]=useState<Awaited<ReturnType<typeof compareBoardCheckpoint>>|null>(null);
  const reload=async()=>setItems(await listBoardCheckpoints(boardId));
  useEffect(()=>{let active=true;void listBoardCheckpoints(boardId).then(value=>{if(active)setItems(value);}).catch(()=>{if(active)setNotice('无法读取历史记录。');});return()=>{active=false;};},[boardId]);
  async function create(){if(!label.trim()||!reason.trim()||busy)return;setBusy(true);setNotice('');try{const expectedHead=await getBoardHistoryHead(boardId),key=JSON.stringify({boardId,label:label.trim(),reason:reason.trim(),expectedHead});if(createIntent.current?.key!==key)createIntent.current={key,requestId:crypto.randomUUID()};await createBoardCheckpoint(boardId,{requestId:createIntent.current.requestId,label,reason,retentionDays:365,expectedHead});createIntent.current=null;setLabel('');setReason('');try{await reload();setNotice('已保存不可变版本。');}catch{setNotice('版本已保存，但历史列表刷新失败；重新打开版本历史即可查看。');}}catch{setNotice('保存失败；可直接重试，系统会复用同一保存请求。');}finally{setBusy(false);}}
  async function inspect(item:BoardCheckpoint){setBusy(true);try{setPreview(await previewBoardCheckpoint(boardId,item.id));setComparison(null);}catch{setNotice('无法读取该版本。');}finally{setBusy(false);}}
  async function compare(item:BoardCheckpoint){setBusy(true);try{setComparison(await compareBoardCheckpoint(boardId,{fromCheckpointId:item.id,to:'current'}));setPreview(null);}catch{setNotice('无法比较版本。');}finally{setBusy(false);}}
  async function restore(item:BoardCheckpoint){if(!canEdit||busy)return;const why=reason.trim()||`从版本 ${item.label} 恢复`,boardNameInput=`${boardName} · 恢复副本`,key=JSON.stringify({boardId,checkpointId:item.id,contentDigest:item.contentDigest,boardName:boardNameInput,reason:why});if(restoreIntent.current?.key!==key)restoreIntent.current={key,requestId:crypto.randomUUID()};setBusy(true);try{const receipt=await restoreBoardCheckpoint(boardId,item.id,{requestId:restoreIntent.current.requestId,sourceContentDigest:item.contentDigest,boardName:boardNameInput,reason:why,retentionDays:365});restoreIntent.current=null;setNotice(`恢复副本已创建，操作者 ${receipt.actorId}`);router.push(`/studio/board/${receipt.restoredBoardId}`);}catch{setNotice('恢复失败；可直接重试，系统会复用同一恢复请求。');}finally{setBusy(false);}}
  return <aside data-testid="board-history-panel" className="w-96 shrink-0 overflow-y-auto border-l border-border bg-card p-3 text-card-foreground">
    <div className="flex items-center justify-between"><h2 className="text-16 font-semibold">版本历史</h2><Button onClick={onClose}>关闭</Button></div>
    <p className="my-2 text-12 text-muted-foreground">版本内容保存在加密对象存储。恢复会创建新白板，源白板与当前白板保持不变。</p>
    {canEdit&&<div className="space-y-2"><Input aria-label="版本名称" maxLength={100} value={label} onChange={event=>setLabel(event.target.value)} placeholder="例如：会后定稿"/><Input aria-label="保存原因" maxLength={500} value={reason} onChange={event=>setReason(event.target.value)} placeholder="记录保存或恢复原因"/><Button disabled={busy||!label.trim()||!reason.trim()} onClick={create}>保存当前版本</Button></div>}
    <p role="status" className="my-2 min-h-5 text-12">{notice}</p>
    <ul className="space-y-2">{items.map(item=><li key={item.id} className="rounded-control border border-border p-2"><strong className="block text-13">{item.label}</strong><span className="block text-11 text-muted-foreground">{item.creatorId} · seq {item.seq} · {item.objectCount} 个对象</span><span className="block text-11 text-muted-foreground">{item.reason} · 保留至 {new Date(item.retentionUntil).toLocaleDateString()}</span><div className="mt-2 flex flex-wrap gap-1"><Button disabled={busy} onClick={()=>inspect(item)}>预览</Button><Button disabled={busy} onClick={()=>compare(item)}>与当前比较</Button>{canEdit&&item.retentionState!=='expired'&&<Button disabled={busy} onClick={()=>restore(item)}>创建恢复副本</Button>}</div></li>)}</ul>
    {!items.length&&<p className="text-13 text-muted-foreground">还没有保存版本。</p>}
    {preview&&<Preview value={preview} onClose={()=>setPreview(null)}/>} {comparison&&<Comparison value={comparison} onClose={()=>setComparison(null)}/>}
  </aside>;
}
function Preview({value,onClose}:{value:Awaited<ReturnType<typeof previewBoardCheckpoint>>;onClose:()=>void}) { const visible=value.objects.filter(item=>!item.deleted).map(item=>item.object);return <section data-testid="board-history-preview" className="mt-3 rounded-control border border-border bg-panel-alt p-2"><div className="flex justify-between"><h3 className="text-13 font-semibold">只读预览：{value.checkpoint.label}</h3><Button onClick={onClose}>收起</Button></div><div className="relative mt-2 h-56 overflow-auto rounded bg-background" data-testid="board-history-renderer"><div className="relative min-h-full min-w-full"><WhiteboardRenderer objects={visible} selected={[]} onPointerDown={()=>{}}/></div></div><p className="mt-1 text-11 text-muted-foreground">完整对象模型只读渲染，共 {visible.length} 个可见对象、{value.objects.length-visible.length} 个删除上下文；包含 Mermaid、图片、画笔与扩展数据。</p></section>; }
function Comparison({value,onClose}:{value:Awaited<ReturnType<typeof compareBoardCheckpoint>>;onClose:()=>void}) { return <section data-testid="board-history-comparison" className="mt-3 rounded-control border border-border bg-panel-alt p-2"><div className="flex justify-between"><h3 className="text-13 font-semibold">对象级差异</h3><Button onClick={onClose}>收起</Button></div><p className="text-12">新增 {value.added} · 修改 {value.modified} · 删除 {value.deleted}</p><ul className="mt-2 max-h-48 overflow-y-auto text-11">{value.changes.map(change=><li key={`${change.change}-${change.id}`}>{change.change} · {change.after?.kind??change.before?.kind} · {change.after?.text||change.before?.text||change.id}</li>)}</ul></section>;}
