'use client';
import type {BoardOrganizeFitRequest} from './use-board-organize-fit';
import {BoardOrganizeControls} from './board-organize-controls';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useRouter,useSearchParams } from 'next/navigation';
import type {WhiteboardAIProposal,WhiteboardPresentationState} from '@repo/contracts/whiteboard-operation';
import type * as Y from 'yjs';
import { createWhiteboardDocument } from '@repo/whiteboard-core';
import { getBoard, type Board } from '@/lib/live-whiteboard';
import { WhiteboardProvider, type WhiteboardConnectionState } from '@/lib/whiteboard-provider';
import { CollaborativeEditor } from './collaborative-editor';
import { useOptionalSession } from '@/components/session/session-provider';
import { Button } from '@/components/ui/button';
import {BoardAIProposalPanel} from './board-ai-proposal-panel';import{BoardPresentationControls}from'./board-presentation-controls';import{cancelAIProposal,clearBoardUndoReceipt,confirmAIProposal,joinBoardRoom,readAIProposal,readBoardUndoReceipt,readPresentation,recordBoardUndoReceipt,updatePresentation,type BoardAIUndoTarget}from'@/lib/whiteboard-operation-client';
import { BoardImportPanel } from './board-import-panel';
const initial: WhiteboardConnectionState = { phase: 'connecting', pending: 0, role: 'viewer', archived: false, epoch: null, peers: [], reason: null, retryAttempt: 0, duplicateAcks: 0, lastAckSequence: null, lastAckReceipt:null };
export function LiveBoard({ boardId, onSelectionChange }: { boardId: string; onSelectionChange?: (ids: string[]) => void }) {
  const router = useRouter();
  const search=useSearchParams();
  const session = useOptionalSession();
  const providerRef = useRef<WhiteboardProvider | null>(null);
  const awareness = useCallback((cursor: {x:number;y:number}|null, selected:string[], editingObjectId: string | null,collaboration:{viewport:{centerX:number;centerY:number;zoom:number;revision:number};presenting:boolean;followingActorId:string|null},pointer?:Parameters<WhiteboardProvider["awareness"]>[4]) => providerRef.current?.awareness(cursor,selected,editingObjectId,collaboration,pointer), []);
  const [organizeFitRequest,setOrganizeFitRequest]=useState<BoardOrganizeFitRequest|null>(null);
  const [importOpen,setImportOpen]=useState(false);
  const [followSuppressed,setFollowSuppressed]=useState(false);
  const [proposalError,setProposalError]=useState('');
  const [selectedIds,setSelectedIds]=useState<string[]>([]),[aiUndo,setAIUndo]=useState<BoardAIUndoTarget|null>(null);
  const [board, setBoard] = useState<Board | null>(null), [doc, setDoc] = useState<Y.Doc | null>(null);
  const [state, setState] = useState(initial), [failed, setFailed] = useState(false);
  const [proposal,setProposal]=useState<WhiteboardAIProposal|null>(null),[proposalBusy,setProposalBusy]=useState(false),[presentation,setPresentation]=useState<WhiteboardPresentationState|null>(null),[roomActorId,setRoomActorId]=useState<string|null>(null),[roomReconnectToken,setRoomReconnectToken]=useState<string|null>(null);
  const presentationRef=useRef<WhiteboardPresentationState|null>(null),dispatchTail=useRef(Promise.resolve()),viewportTimer=useRef<ReturnType<typeof setTimeout>|null>(null),pendingViewport=useRef<{x:number;y:number;zoom:number}|null>(null);
  const roomId=search.get('room')??'default',proposalId=search.get('proposal'),deviceId=search.get('device');
  useEffect(()=>{let active=true;if(proposalId)void readAIProposal(boardId,proposalId).then(value=>{if(active)setProposal(value)}).catch(()=>{});return()=>{active=false};},[boardId,proposalId]);
  useEffect(()=>{let active=true;const refresh=()=>void readPresentation(boardId,roomId).then(value=>{if(active)setPresentation(value)}).catch(()=>{});refresh();const timer=setInterval(refresh,2000);return()=>{active=false;clearInterval(timer)};},[boardId,roomId]);
  useEffect(()=>{let active=true;if(!deviceId){setRoomReconnectToken(null);return;}const key=`board-room:${boardId}:${roomId}:${deviceId}`,reconnectToken=sessionStorage.getItem(key)??undefined;void joinBoardRoom(boardId,{roomId,deviceId,deviceKind:'meeting-display',...(reconnectToken?{reconnectToken}:{})}).then(identity=>{if(!active)return;sessionStorage.setItem(key,identity.reconnectToken);setRoomActorId(identity.actorId);setRoomReconnectToken(identity.reconnectToken)}).catch(()=>{if(active){setRoomActorId(null);setRoomReconnectToken(null)}});return()=>{active=false};},[boardId,roomId,deviceId]);
  useEffect(() => {
    let active = true; const document = createWhiteboardDocument(); let provider: WhiteboardProvider | undefined;
    setOrganizeFitRequest(null); setDoc(null); setBoard(null); setFailed(false); setState(initial); setAIUndo(readBoardUndoReceipt(boardId)); setSelectedIds([]); setProposal(null); setProposalError('');setImportOpen(false);setFollowSuppressed(false);
    void getBoard(boardId).then(resource => {
      if (!active) return; setBoard(resource); setDoc(document);
      provider = new WhiteboardProvider(document, boardId, value => { if (active) setState(value); });
      providerRef.current = provider;
    }).catch(() => { if (active) setFailed(true); });
    return () => { active = false; provider?.close(); if(providerRef.current===provider)providerRef.current=null; document.destroy(); };
  }, [boardId]);
  const back = () => router.push('/studio/board');
  const status = state.phase === 'connecting' ? '正在连接' : state.phase === 'offline' ? `连接中断 · 第 ${state.retryAttempt} 次重连 · ${state.pending} 项修改待确认` : state.pending ? `${state.pending} 项修改等待服务器确认` : `已同步${state.lastAckSequence === null ? '' : ` · 序列 ${state.lastAckSequence}`}`;
  useEffect(()=>{presentationRef.current=presentation;},[presentation]);
  const actorId=roomActorId??session?.session?.userId??'',displayActorId=`room:${roomId}:meeting-room-display`;
  const dispatchPresentation=useCallback((command:Record<string,unknown>)=>{dispatchTail.current=dispatchTail.current.then(async()=>{let current=presentationRef.current;if(!current||!actorId)return;try{const next=await updatePresentation(boardId,roomId,{...command,actorId,expectedRevision:current.revision},roomReconnectToken);presentationRef.current=next;setPresentation(next);}catch{current=await readPresentation(boardId,roomId);presentationRef.current=current;setPresentation(current);const next=await updatePresentation(boardId,roomId,{...command,actorId,expectedRevision:current.revision},roomReconnectToken);presentationRef.current=next;setPresentation(next);}}).catch(()=>undefined);},[actorId,boardId,roomId,roomReconnectToken]);
  const leaveRoomFollow=useCallback(()=>{if(presentationRef.current?.followers.includes(actorId)){setFollowSuppressed(true);dispatchPresentation({type:'leave-follow'});}},[actorId,dispatchPresentation]);
  const observeViewport=useCallback((viewport:{x:number;y:number;zoom:number})=>{if(presentationRef.current?.presenterId!==actorId)return;pendingViewport.current=viewport;if(viewportTimer.current)return;viewportTimer.current=setTimeout(()=>{viewportTimer.current=null;const next=pendingViewport.current;pendingViewport.current=null;if(next)dispatchPresentation({type:'viewport',viewport:next});},100);},[actorId,dispatchPresentation]);
  useEffect(()=>()=>{if(viewportTimer.current)clearTimeout(viewportTimer.current);},[]);
  const applyProposal=async()=>{if(!proposal)return;setProposalBusy(true);try{const receipt=await confirmAIProposal(proposal,crypto.randomUUID()),undo=recordBoardUndoReceipt(proposal,receipt);setOrganizeFitRequest({id:crypto.randomUUID(),proposal});setAIUndo(undo);setProposal(null);setProposalError('');}catch(error){setProposalError(error instanceof Error&&error.message==='BOARD_OPERATION_CONFLICT'?'白板已变化，未应用 AI 修改，请重新生成。':'AI 修改尚未确认，请重试。');}finally{setProposalBusy(false);}};const rejectProposal=async()=>{if(!proposal)return;setProposalBusy(true);try{await cancelAIProposal(proposal);setProposal(null);setProposalError('');}catch{setProposalError('取消尚未确认，请重试。');}finally{setProposalBusy(false);}};
  if (failed || state.phase === 'blocked') return <section data-testid="denied" className="p-6"><h1 className="text-20 font-semibold">无法继续访问白板</h1><p className="my-3 text-14">权限、会话或同步状态已改变。请返回列表确认后重新打开。未确认的修改不能视为已保存。</p><Button onClick={back}>返回白板列表</Button></section>;
  if (!doc || !board) return <p data-testid="loading" role="status" className="p-6">正在读取白板…</p>;
  return <div className="flex h-full min-h-0 flex-col"><div data-testid="board-sync-banner" className="relative z-30 flex shrink-0 flex-wrap items-center gap-3 border-b border-border bg-warning-tint px-3 py-1 text-12 text-warning-tint-foreground"><span>未确认修改会加密保存在此浏览器，并在刷新、关闭或重连后按原操作 ID 重放。在线成员 {state.peers.length}</span>{state.duplicateAcks ? <span data-testid="board-duplicate-ack">已忽略 {state.duplicateAcks} 个重复确认</span> : null}{state.phase === 'offline' ? <Button data-testid="board-retry-sync" onClick={() => providerRef.current?.retryNow()}>立即重连</Button> : null}</div>{importOpen&&<div className="fixed inset-0 z-[70] pointer-events-none [&>aside]:pointer-events-auto"><BoardImportPanel boardId={boardId} expectedEpoch={state.epoch??1} onClose={()=>setImportOpen(false)}/></div>}<div data-testid="board-editor-region" className="relative min-h-0 flex-1 overflow-hidden"><CollaborativeEditor presentationControls={presentation?<BoardPresentationControls inline state={presentation} actorId={actorId} canPresent={!state.archived&&['owner','editor'].includes(state.role)} handoffTargetActorId={deviceId?undefined:displayActorId} onClaim={()=>void dispatchPresentation({type:'claim-presenter'})} onRelease={()=>void dispatchPresentation({type:'release-presenter'})} onFollow={()=>{setFollowSuppressed(false);dispatchPresentation({type:'follow'});}} onLeave={leaveRoomFollow} onHandoff={toActorId=>void dispatchPresentation({type:'handoff',toActorId})}/>:null} organizeFitRequest={organizeFitRequest} dockExtension={<BoardOrganizeControls boardId={boardId} selectedIds={selectedIds} readOnly={state.phase!=='online' || !['owner','editor'].includes(state.role) || state.archived} onProposal={setProposal} undo={aiUndo} onUndone={()=>{if(aiUndo)clearBoardUndoReceipt(boardId,aiUndo.operationId);setAIUndo(null);setOrganizeFitRequest(null);}}/>} boardId={boardId} clientId={`yjs-${doc.clientID.toString(36)}`} doc={doc} onSelectionChange={ids=>{setSelectedIds(ids);onSelectionChange?.(ids);}} title={board.name} status={status} lastAckSequence={state.lastAckSequence} lastAckReceipt={state.lastAckReceipt} role={state.role} commentsReadOnly={state.phase!=='online'||state.role==='viewer'||state.archived} readOnly={state.phase === 'connecting' || !['owner','editor'].includes(state.role) || state.archived} onBack={back} onImport={()=>setImportOpen(true)} currentUserId={session?.session?.userId} peers={state.peers} onAwareness={awareness} followViewport={!followSuppressed&&presentation?.followers.includes(actorId)?presentation.viewport:null} onViewportObserved={observeViewport} onManualViewportChange={leaveRoomFollow}/></div>{proposalError?<p role="alert" className="fixed right-4 top-12 z-50 rounded-lg bg-card p-2">{proposalError}</p>:null}{proposal?<BoardAIProposalPanel proposal={proposal} busy={proposalBusy} onConfirm={()=>void applyProposal()} onCancel={()=>void rejectProposal()}/>:null}</div>;
}
