'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { MonitorUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog,DialogContent,DialogDescription,DialogTitle } from '@/components/ui/dialog';
import { createRoomPairing,readPairingStatus,revokeRoom,type RoomPairing } from '@/lib/live-whiteboard-room';
import {clearPresenterSession,isAuthoritativeRoomEnd,persistPresenterSession,restorePresenterSession,type PresenterScope} from '@/lib/whiteboard-room-session';

const MAX_PAIRING_TTL_MS=5*60*1_000;
type ActivePairing=RoomPairing&{deadlineAt:number};
function activatePairing(pairing:RoomPairing):ActivePairing{const requested=Date.parse(pairing.expiresAt)-Date.now(),ttl=Number.isFinite(requested)?Math.max(0,Math.min(MAX_PAIRING_TTL_MS,requested)):0;return {...pairing,deadlineAt:performance.now()+ttl};}

export function RoomPresenterControls({boardId,orgId,userId,disabled,onSession}:{boardId:string;orgId:string|null;userId:string|null;disabled:boolean;onSession:(sessionId:string|null)=>void}){
  const scope=useMemo<PresenterScope|null>(()=>!disabled&&orgId&&userId?{boardId,orgId,userId}:null,[boardId,disabled,orgId,userId]);
  const scopeKey=scope?`${scope.orgId}:${scope.userId}:${scope.boardId}`:null;
  const renderedScopeKey=useRef(scopeKey),generation=useRef(0),beginOperation=useRef(0),stopOperation=useRef(0),sessionEpoch=useRef(0),owned=useRef<{scope:PresenterScope;scopeKey:string;sessionId:string}|null>(null);
  if(renderedScopeKey.current!==scopeKey){renderedScopeKey.current=scopeKey;generation.current+=1;beginOperation.current+=1;stopOperation.current+=1;}
  const [open,setOpen]=useState(false),[pairing,setPairing]=useState<ActivePairing|null>(null),[session,setSession]=useState<{scopeKey:string;id:string;epoch:number}|null>(null),[error,setError]=useState(''),[beginPending,setBeginPending]=useState(false);
  const sessionId=session?.scopeKey===scopeKey?session.id:null;
  const currentSession=useRef<typeof session>(null);currentSession.current=session?.scopeKey===scopeKey?session:null;
  useEffect(()=>()=>{generation.current+=1;beginOperation.current+=1;stopOperation.current+=1;},[]);
  useEffect(()=>{const previous=owned.current;if(previous&&previous.scopeKey!==scopeKey){clearPresenterSession(previous.scope,previous.sessionId);owned.current=null;}setOpen(false);setPairing(null);setError('');setBeginPending(false);const restored=scope?restorePresenterSession(scope):null;if(restored&&scope&&scopeKey){const next={scopeKey,id:restored,epoch:++sessionEpoch.current};owned.current={scope,scopeKey,sessionId:restored};currentSession.current=next;setSession(next);}else{currentSession.current=null;setSession(null);}},[scope,scopeKey]);
  useEffect(()=>{onSession(sessionId);},[onSession,sessionId]);
  useEffect(()=>{if(!pairing||sessionId||!scope||!scopeKey)return;let active=true,settled=false,timer:number|undefined,deadline:number|undefined,failures=0;const controller=new AbortController(),capturedGeneration=generation.current,remaining=()=>Math.max(0,pairing.deadlineAt-performance.now()),isCurrent=()=>active&&!settled&&generation.current===capturedGeneration&&renderedScopeKey.current===scopeKey;const terminate=()=>{if(!isCurrent())return;settled=true;controller.abort();setPairing(null);currentSession.current=null;setSession(null);setError('配对已过期，请重新创建。');};const wake=()=>{if(document.visibilityState==='visible'&&remaining()<=0)terminate();};deadline=window.setTimeout(terminate,remaining());document.addEventListener('visibilitychange',wake);const poll=async()=>{if(remaining()<=0){terminate();return;}try{const status=await readPairingStatus(boardId,pairing.id,controller.signal);if(!isCurrent())return;if(remaining()<=0){terminate();return;}failures=0;setError('');if(status.sessionId){settled=true;if(deadline)window.clearTimeout(deadline);persistPresenterSession(scope,status.sessionId);owned.current={scope,scopeKey,sessionId:status.sessionId};const next={scopeKey,id:status.sessionId,epoch:++sessionEpoch.current};currentSession.current=next;setSession(next);return;}}catch(cause){if(!isCurrent())return;if(isAuthoritativeRoomEnd(cause)){terminate();return;}failures+=1;setError('连接暂时中断，正在恢复配对…');}if(isCurrent()){timer=window.setTimeout(()=>void poll(),Math.min(5_000,1_500*Math.max(1,failures),remaining()));}};void poll();return()=>{active=false;settled=true;controller.abort();document.removeEventListener('visibilitychange',wake);if(deadline)window.clearTimeout(deadline);if(timer)window.clearTimeout(timer);};},[boardId,pairing,scope,scopeKey,sessionId]);
  async function begin(){if(!scope||!scopeKey)return;const capturedGeneration=generation.current,operation=++beginOperation.current;setBeginPending(true);setError('');try{const next=await createRoomPairing(boardId,crypto.randomUUID());if(generation.current!==capturedGeneration||renderedScopeKey.current!==scopeKey||beginOperation.current!==operation)return;setPairing(activatePairing(next));setOpen(true);}catch{if(generation.current!==capturedGeneration||renderedScopeKey.current!==scopeKey||beginOperation.current!==operation)return;setError('无法创建会议室连接，请确认你仍有编辑权限。');setOpen(true);}finally{if(generation.current===capturedGeneration&&renderedScopeKey.current===scopeKey&&beginOperation.current===operation)setBeginPending(false);}}
  async function stop(){if(!scope||!scopeKey||!sessionId||!currentSession.current)return;const capturedGeneration=generation.current,operation=++stopOperation.current,capturedSessionId=sessionId,capturedEpoch=currentSession.current.epoch,isCurrent=()=>generation.current===capturedGeneration&&renderedScopeKey.current===scopeKey&&stopOperation.current===operation&&currentSession.current?.id===capturedSessionId&&currentSession.current.epoch===capturedEpoch;try{await revokeRoom(boardId,capturedSessionId);}catch(cause){if(!isCurrent())return;if(!isAuthoritativeRoomEnd(cause)){setError('暂时无法断开会议室，请稍后重试。');return;}}if(!isCurrent())return;clearPresenterSession(scope,capturedSessionId);owned.current=null;currentSession.current=null;setSession(null);setPairing(null);setOpen(false);}
  return <><Button data-testid="room-present-open" variant="outline" disabled={disabled||beginPending} onClick={()=>sessionId?setOpen(true):void begin()}><MonitorUp className="h-4 w-4"/>连接会议室</Button><Dialog open={open} onOpenChange={value=>{setOpen(value);if(!value&&!sessionId)setPairing(null);}}><DialogContent><DialogTitle>在会议室大屏打开白板</DialogTitle>{error&&<p role="alert">{error}</p>}{sessionId?<><DialogDescription>大屏已只读连接。移动或缩放画布时，大屏会跟随；大屏也可以随时退出跟随。</DialogDescription><p data-testid="room-connected" className="rounded-control bg-success-tint p-3 text-success-tint-foreground">会议室已连接</p><Button variant="destructive" onClick={()=>void stop()}>断开会议室</Button></>:pairing?<><DialogDescription>在大屏打开“会议室模式”，粘贴配对载荷。配对码 5 分钟内有效且只能使用一次。</DialogDescription><p data-testid="room-pairing-code" className="select-all text-center font-mono text-28 tracking-[0.3em]">{pairing.code}</p><label className="text-12">配对载荷<textarea data-testid="room-pairing-payload" className="mt-1 h-20 w-full rounded-control border border-border bg-background p-2 font-mono text-11" readOnly value={pairing.payload}/></label><p role="status" className="text-12 text-muted-foreground">等待大屏连接… 不要在公开频道分享此载荷。</p></>:!error&&<p role="status">正在创建短时配对码…</p>}</DialogContent></Dialog></>;
}
