'use client';
import { useEffect, useMemo, useState } from 'react';
import { MonitorUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog,DialogContent,DialogDescription,DialogTitle } from '@/components/ui/dialog';
import { createRoomPairing,readPairingStatus,revokeRoom,type RoomPairing } from '@/lib/live-whiteboard-room';
import {isAuthoritativeRoomEnd,persistPresenterSession,restorePresenterSession,type PresenterScope} from '@/lib/whiteboard-room-session';

export function RoomPresenterControls({boardId,orgId,userId,disabled,onSession}:{boardId:string;orgId:string|null;userId:string|null;disabled:boolean;onSession:(sessionId:string|null)=>void}){
  const scope=useMemo<PresenterScope|null>(()=>!disabled&&orgId&&userId?{boardId,orgId,userId}:null,[boardId,disabled,orgId,userId]);
  const scopeKey=scope?`${scope.orgId}:${scope.userId}:${scope.boardId}`:null;
  const [open,setOpen]=useState(false),[pairing,setPairing]=useState<RoomPairing|null>(null),[session,setSession]=useState<{scopeKey:string;id:string}|null>(null),[error,setError]=useState('');
  const sessionId=session?.scopeKey===scopeKey?session.id:null;
  useEffect(()=>{setOpen(false);setPairing(null);setError('');const restored=scope?restorePresenterSession(scope):null;setSession(restored&&scopeKey?{scopeKey,id:restored}:null);},[scope,scopeKey]);
  useEffect(()=>{onSession(sessionId);},[onSession,sessionId]);
  useEffect(()=>{if(!pairing||sessionId||!scope||!scopeKey)return;let active=true,timer:number|undefined,failures=0;const terminate=()=>{persistPresenterSession(scope,null);setPairing(null);setSession(null);setError('配对已过期，请重新创建。');};const poll=async()=>{try{const status=await readPairingStatus(boardId,pairing.id);if(!active)return;failures=0;setError('');if(Date.parse(status.expiresAt)<=Date.now()){terminate();return;}if(status.sessionId){persistPresenterSession(scope,status.sessionId);setSession({scopeKey,id:status.sessionId});return;}}catch(cause){if(!active)return;if(isAuthoritativeRoomEnd(cause)){terminate();return;}failures+=1;setError('连接暂时中断，正在恢复配对…');}if(active)timer=window.setTimeout(()=>void poll(),Math.min(5_000,1_500*Math.max(1,failures)));};void poll();return()=>{active=false;if(timer)window.clearTimeout(timer);};},[boardId,pairing,scope,scopeKey,sessionId]);
  async function begin(){if(!scope)return;setError('');try{const next=await createRoomPairing(boardId,crypto.randomUUID());setPairing(next);setOpen(true);}catch{setError('无法创建会议室连接，请确认你仍有编辑权限。');setOpen(true);}}
  async function stop(){if(!scope||!sessionId)return;if(sessionId)try{await revokeRoom(boardId,sessionId);}catch(cause){if(!isAuthoritativeRoomEnd(cause)){setError('暂时无法断开会议室，请稍后重试。');return;}}persistPresenterSession(scope,null);setSession(null);setPairing(null);setOpen(false);}
  return <><Button data-testid="room-present-open" variant="outline" disabled={disabled} onClick={()=>sessionId?setOpen(true):void begin()}><MonitorUp className="h-4 w-4"/>连接会议室</Button><Dialog open={open} onOpenChange={value=>{setOpen(value);if(!value&&!sessionId)setPairing(null);}}><DialogContent><DialogTitle>在会议室大屏打开白板</DialogTitle>{error&&<p role="alert">{error}</p>}{sessionId?<><DialogDescription>大屏已只读连接。移动或缩放画布时，大屏会跟随；大屏也可以随时退出跟随。</DialogDescription><p data-testid="room-connected" className="rounded-control bg-success-tint p-3 text-success-tint-foreground">会议室已连接</p><Button variant="destructive" onClick={()=>void stop()}>断开会议室</Button></>:pairing?<><DialogDescription>在大屏打开“会议室模式”，粘贴配对载荷。配对码 5 分钟内有效且只能使用一次。</DialogDescription><p data-testid="room-pairing-code" className="select-all text-center font-mono text-28 tracking-[0.3em]">{pairing.code}</p><label className="text-12">配对载荷<textarea data-testid="room-pairing-payload" className="mt-1 h-20 w-full rounded-control border border-border bg-background p-2 font-mono text-11" readOnly value={pairing.payload}/></label><p role="status" className="text-12 text-muted-foreground">等待大屏连接… 不要在公开频道分享此载荷。</p></>:!error&&<p role="status">正在创建短时配对码…</p>}</DialogContent></Dialog></>;
}
