import { whiteboardImport as C } from '@repo/contracts';
import type { Principal } from '../../domain/principal';
import type { DatabasePort, TenantSession } from '../../application/ports/database.port';
import type { ImportReport, WhiteboardImportRecord, WhiteboardImportRepository } from '../../application/whiteboard/import-service';

type Row={id:string;board_id:string;actor_id:string;source:string;source_board_id:string;source_revision:string;file_name:string;mime_type:string;size_bytes:string;sha256:string;source_object_key:string;stage:string;counts:unknown;report:unknown;execute_request_id:string|null;execute_request_hash:string|null;completed_epoch:number|null;completed_seq:string|null;created_at:Date|string;updated_at:Date|string};
const iso=(value:Date|string)=>value instanceof Date?value.toISOString():new Date(value).toISOString();
function project(row:Row):WhiteboardImportRecord{return{...C.WhiteboardImportStatus.parse({importId:row.id,boardId:row.board_id,source:row.source,sourceBoardId:row.source_board_id,sourceRevision:row.source_revision,fileName:row.file_name,mimeType:row.mime_type,sizeBytes:Number(row.size_bytes),sha256:row.sha256,stage:row.stage,counts:row.counts,createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)}),sourceObjectKey:row.source_object_key,actorId:row.actor_id,report:row.report?C.WhiteboardImportReport.parse(row.report):null,executeRequestId:row.execute_request_id,executeRequestHash:row.execute_request_hash,completedEpoch:row.completed_epoch,completedSeq:row.completed_seq===null?null:Number(row.completed_seq)};}
const select=`SELECT id,board_id,actor_id,source,source_board_id,source_revision,file_name,mime_type,size_bytes::text,sha256,source_object_key,stage,counts,report,execute_request_id,execute_request_hash,completed_epoch,completed_seq::text,created_at,updated_at FROM whiteboard_imports`;
async function locked(session:TenantSession,p:Principal,boardId:string,id:string){const result=await session.query<Row>(`${select} WHERE org_id=$1 AND board_id=$2 AND id=$3 FOR UPDATE`,[p.orgId,boardId,id]);return result.rows[0]??null;}
export class PgWhiteboardImportRepository implements WhiteboardImportRepository{
  constructor(private readonly db:DatabasePort){}
  async create(p:Principal,record:WhiteboardImportRecord){return this.db.withTenant(p.orgId,async session=>{await session.query(`INSERT INTO whiteboard_imports(org_id,board_id,id,actor_id,source,source_board_id,source_revision,file_name,mime_type,size_bytes,sha256,source_object_key,stage,counts,report,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$16) ON CONFLICT(org_id,board_id,id) DO NOTHING`,[p.orgId,record.boardId,record.importId,p.userId,record.source,record.sourceBoardId,record.sourceRevision,record.fileName,record.mimeType,record.sizeBytes,record.sha256,record.sourceObjectKey,record.stage,record.counts,record.report,record.createdAt]);const row=await locked(session,p,record.boardId,record.importId);if(!row)throw new Error('WHITEBOARD_IMPORT_INSERT_FAILED');const existing=project(row),conflict=existing.actorId!==p.userId||existing.source!==record.source||existing.sourceBoardId!==record.sourceBoardId||existing.sourceRevision!==record.sourceRevision||existing.mimeType!==record.mimeType||existing.sizeBytes!==record.sizeBytes||existing.sha256!==record.sha256||existing.sourceObjectKey!==record.sourceObjectKey;return{record:existing,replayed:!conflict&&existing.createdAt!==record.createdAt,conflict};});}
  async get(p:Principal,boardId:string,id:string){return this.db.withTenant(p.orgId,async session=>{const result=await session.query<Row>(`${select} WHERE org_id=$1 AND board_id=$2 AND id=$3`,[p.orgId,boardId,id]);return result.rows[0]?project(result.rows[0]):null;});}
  async savePreflight(p:Principal,record:WhiteboardImportRecord,requestId:string,report:ImportReport){return this.db.withTenant(p.orgId,async session=>{const row=await locked(session,p,record.boardId,record.importId);if(!row)throw new Error('WHITEBOARD_IMPORT_NOT_FOUND');if(row.stage==='completed')return project(row);await session.query(`UPDATE whiteboard_imports SET stage='preflighted',counts=$4::jsonb,report=$5::jsonb,preflight_request_id=$6,updated_at=now() WHERE org_id=$1 AND board_id=$2 AND id=$3`,[p.orgId,record.boardId,record.importId,JSON.stringify(report.counts),JSON.stringify(report),requestId]);const saved=await locked(session,p,record.boardId,record.importId);if(!saved)throw new Error('WHITEBOARD_IMPORT_NOT_FOUND');return project(saved);});}
  async claimExecution(p:Principal,record:WhiteboardImportRecord,input:{requestId:string;requestHash:string}){return this.db.withTenant(p.orgId,async session=>{const row=await locked(session,p,record.boardId,record.importId);if(!row)throw new Error('WHITEBOARD_IMPORT_NOT_FOUND');if(row.execute_request_id){const conflict=row.execute_request_id!==input.requestId||row.execute_request_hash!==input.requestHash;return{record:project(row),conflict};}await session.query(`UPDATE whiteboard_imports SET execute_request_id=$4,execute_request_hash=$5,updated_at=now() WHERE org_id=$1 AND board_id=$2 AND id=$3`,[p.orgId,record.boardId,record.importId,input.requestId,input.requestHash]);const saved=await locked(session,p,record.boardId,record.importId);if(!saved)throw new Error('WHITEBOARD_IMPORT_NOT_FOUND');return{record:project(saved),conflict:false};});}
  async releaseExecution(p:Principal,record:WhiteboardImportRecord,input:{requestId:string;requestHash:string}){await this.db.withTenant(p.orgId,async session=>{await session.query(`UPDATE whiteboard_imports SET execute_request_id=NULL,execute_request_hash=NULL,updated_at=now() WHERE org_id=$1 AND board_id=$2 AND id=$3 AND execute_request_id=$4 AND execute_request_hash=$5 AND completed_seq IS NULL`,[p.orgId,record.boardId,record.importId,input.requestId,input.requestHash]);});}
  async reserveAssets(p:Principal,record:WhiteboardImportRecord,assets:Array<{objectKey:string;contentHash:string;byteSize:number}>){await this.db.withTenant(p.orgId,async session=>{for(const asset of assets)await session.query(`INSERT INTO whiteboard_asset_refs(org_id,board_id,import_id,object_key,content_hash,byte_size,state,lease_expires_at) VALUES($1,$2,$3,$4,$5,$6,'pending',now()+interval '24 hours') ON CONFLICT(org_id,board_id,object_key) DO UPDATE SET import_id=EXCLUDED.import_id,lease_expires_at=EXCLUDED.lease_expires_at,released_at=NULL WHERE whiteboard_asset_refs.state='pending' AND whiteboard_asset_refs.content_hash=EXCLUDED.content_hash AND whiteboard_asset_refs.byte_size=EXCLUDED.byte_size`,[p.orgId,record.boardId,record.importId,asset.objectKey,asset.contentHash,asset.byteSize]);});}
  async releaseExpiredAssets(p:Principal,now:Date){return this.db.withTenant(p.orgId,async session=>{const result=await session.query(`UPDATE whiteboard_asset_refs a SET released_at=$2 WHERE a.org_id=$1 AND a.state='pending' AND a.released_at IS NULL AND a.lease_expires_at<$2 AND NOT EXISTS(SELECT 1 FROM whiteboard_imports i WHERE i.org_id=a.org_id AND i.board_id=a.board_id AND i.id=a.import_id AND i.stage='completed') RETURNING object_key`,[p.orgId,now]);return result.rows.length;});}
  async complete(p:Principal,record:WhiteboardImportRecord,input:{requestId:string;requestHash:string;epoch:number;seq:number;report:ImportReport;assetRefs:Array<{objectKey:string;contentHash:string;byteSize:number}>}){return this.db.withTenant(p.orgId,async session=>{const row=await locked(session,p,record.boardId,record.importId);if(!row)throw new Error('WHITEBOARD_IMPORT_NOT_FOUND');if(row.execute_request_id!==input.requestId||row.execute_request_hash!==input.requestHash)throw new Error('WHITEBOARD_IMPORT_IDEMPOTENCY_CONFLICT');if(row.completed_seq!==null)return project(row);await session.query(`UPDATE whiteboard_asset_refs SET state='active',activated_at=now(),lease_expires_at=NULL,released_at=NULL WHERE org_id=$1 AND board_id=$2 AND import_id=$3 AND object_key=ANY($4::text[])`,[p.orgId,record.boardId,record.importId,input.assetRefs.map(asset=>asset.objectKey)]);await session.query(`UPDATE whiteboard_imports SET stage='completed',counts=$4::jsonb,report=$5::jsonb,completed_epoch=$6,completed_seq=$7,updated_at=now() WHERE org_id=$1 AND board_id=$2 AND id=$3`,[p.orgId,record.boardId,record.importId,JSON.stringify(input.report.counts),JSON.stringify(input.report),input.epoch,input.seq]);const saved=await locked(session,p,record.boardId,record.importId);if(!saved)throw new Error('WHITEBOARD_IMPORT_NOT_FOUND');return project(saved);});}
}
