import type { DatabasePort } from '../../application/ports/database.port';
import { randomUUID } from 'node:crypto';
import type { WhiteboardGcResult,WhiteboardObjectRetentionRepository,WhiteboardObjectRoot,WhiteboardStoredObject,WhiteboardObjectSweepRepository,WhiteboardPurgeClaim } from '../../application/whiteboard/object-retention';
type RootRow={object_key:string;kind:WhiteboardObjectRoot['kind']};
export class PgWhiteboardObjectRetentionRepository implements WhiteboardObjectRetentionRepository{
  constructor(private readonly db:DatabasePort){}
  async roots(orgId:string){return this.db.withTenant(orgId as never,async session=>(await session.query<RootRow>(`SELECT object_key,'document'::text AS kind FROM whiteboard_documents WHERE org_id=$1 AND object_key IS NOT NULL UNION SELECT update_object_key,'update' FROM whiteboard_updates WHERE org_id=$1 AND update_object_key IS NOT NULL UNION SELECT object_key,'checkpoint' FROM whiteboard_checkpoints WHERE org_id=$1 UNION SELECT source_object_key,'import' FROM whiteboard_imports WHERE org_id=$1 UNION SELECT object_key,'asset' FROM whiteboard_asset_refs WHERE org_id=$1 AND released_at IS NULL`,[orgId])).rows.map(row=>({key:row.object_key,kind:row.kind})))}
  async tombstones(orgId:string){return this.db.withTenant(orgId as never,async session=>new Map((await session.query<{object_key:string;marked_at:Date|string}>(`SELECT object_key,marked_at FROM whiteboard_object_tombstones WHERE org_id=$1 AND swept_at IS NULL AND rescued_at IS NULL`,[orgId])).rows.map(row=>[row.object_key,row.marked_at instanceof Date?row.marked_at:new Date(row.marked_at)])))}
  async mark(orgId:string,object:WhiteboardStoredObject,markedAt:Date){await this.db.withTenant(orgId as never,session=>session.query(`INSERT INTO whiteboard_object_tombstones(org_id,object_key,size_bytes,object_last_modified,version_tag,marked_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(org_id,object_key) DO UPDATE SET size_bytes=EXCLUDED.size_bytes,object_last_modified=EXCLUDED.object_last_modified,version_tag=EXCLUDED.version_tag,marked_at=EXCLUDED.marked_at,rescued_at=NULL,generation=whiteboard_object_tombstones.generation+1 WHERE whiteboard_object_tombstones.rescued_at IS NOT NULL`,[orgId,object.key,object.sizeBytes,object.lastModified,object.versionTag,markedAt]).then(()=>undefined))}
  async unmark(orgId:string,keys:readonly string[]){if(keys.length)await this.db.withTenant(orgId as never,session=>session.query(`UPDATE whiteboard_object_tombstones SET rescued_at=now() WHERE org_id=$1 AND object_key=ANY($2::text[]) AND swept_at IS NULL`,[orgId,keys]).then(()=>undefined))}
  async sweep(orgId:string,object:WhiteboardStoredObject,sweptAt:Date){await this.db.withTenant(orgId as never,session=>session.query(`UPDATE whiteboard_object_tombstones SET swept_at=$3 WHERE org_id=$1 AND object_key=$2 AND swept_at IS NULL`,[orgId,object.key,sweptAt]).then(()=>undefined))}
  async audit(orgId:string,runId:string,result:WhiteboardGcResult){await this.db.withTenant(orgId as never,session=>session.query(`INSERT INTO whiteboard_object_gc_runs(org_id,run_id,roots,scanned,marked,swept,retained,candidate_bytes,result) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) ON CONFLICT(org_id,run_id) DO NOTHING`,[orgId,runId,result.roots,result.scanned,result.marked,result.swept,result.retained,result.candidateBytes,JSON.stringify(result)]).then(()=>undefined))}
}

const rootExists=`EXISTS(SELECT 1 FROM whiteboard_documents WHERE org_id=$1 AND object_key=$2) OR EXISTS(SELECT 1 FROM whiteboard_updates WHERE org_id=$1 AND update_object_key=$2) OR EXISTS(SELECT 1 FROM whiteboard_checkpoints WHERE org_id=$1 AND object_key=$2) OR EXISTS(SELECT 1 FROM whiteboard_imports WHERE org_id=$1 AND source_object_key=$2) OR EXISTS(SELECT 1 FROM whiteboard_asset_refs WHERE org_id=$1 AND object_key=$2 AND released_at IS NULL)`;
export class PgWhiteboardObjectSweepRepository implements WhiteboardObjectSweepRepository{
  constructor(private readonly db:DatabasePort){}
  async retryable(orgId:string,limit:number){return this.db.withTenant(orgId as never,async session=>(await session.query<{object_key:string;object_last_modified:Date|string}>(`SELECT t.object_key,t.object_last_modified FROM whiteboard_object_tombstones t LEFT JOIN whiteboard_object_purge_receipts r ON r.org_id=t.org_id AND r.object_key=t.object_key AND r.generation=t.generation WHERE t.org_id=$1 AND t.swept_at IS NOT NULL AND t.rescued_at IS NULL AND (r.status IS NULL OR r.status='failed') ORDER BY t.swept_at LIMIT $2`,[orgId,limit])).rows.map(row=>({objectKey:row.object_key,objectLastModified:row.object_last_modified instanceof Date?row.object_last_modified:new Date(row.object_last_modified)})))}
  async claim(orgId:string,objectKey:string,expectedLastModified:Date){return this.db.withTenant(orgId as never,async session=>{const locked=await session.query<{object_key:string;size_bytes:string;object_last_modified:Date|string;generation:number;version_tag:string}>(`SELECT object_key,size_bytes::text,object_last_modified,generation,version_tag FROM whiteboard_object_tombstones WHERE org_id=$1 AND object_key=$2 AND swept_at IS NOT NULL AND rescued_at IS NULL AND version_tag IS NOT NULL FOR UPDATE`,[orgId,objectKey]);const row=locked.rows[0];if(!row||new Date(row.object_last_modified).getTime()!==expectedLastModified.getTime())return null;const rooted=await session.query<{rooted:boolean}>(`SELECT (${rootExists}) AS rooted`,[orgId,objectKey]);if(rooted.rows[0]?.rooted){await session.query(`UPDATE whiteboard_object_tombstones SET rescued_at=now(),generation=generation+1 WHERE org_id=$1 AND object_key=$2`,[orgId,objectKey]);return null;}const receiptId=randomUUID();const receipt=await session.query<{receipt_id:string}>(`INSERT INTO whiteboard_object_purge_receipts(org_id,object_key,generation,receipt_id,status,attempts) VALUES($1,$2,$3,$4,'purging',1) ON CONFLICT(org_id,object_key,generation) DO UPDATE SET status='purging',attempts=whiteboard_object_purge_receipts.attempts+1,last_error=NULL,updated_at=now() WHERE whiteboard_object_purge_receipts.status<>'deleted' RETURNING receipt_id`,[orgId,objectKey,row.generation,receiptId]);if(!receipt.rows[0])return null;return{objectKey,generation:row.generation,sizeBytes:Number(row.size_bytes),objectLastModified:new Date(row.object_last_modified),versionTag:row.version_tag,receiptId:receipt.rows[0].receipt_id};});}
  async confirm(orgId:string,claim:WhiteboardPurgeClaim){return this.db.withTenant(orgId as never,async session=>{const check=await session.query<{valid:boolean}>(`SELECT EXISTS(SELECT 1 FROM whiteboard_object_tombstones WHERE org_id=$1 AND object_key=$2 AND generation=$3 AND swept_at IS NOT NULL AND rescued_at IS NULL) AND NOT (${rootExists}) AS valid`,[orgId,claim.objectKey,claim.generation]);return check.rows[0]?.valid===true;});}
  async finish(orgId:string,claim:WhiteboardPurgeClaim,outcome:{deleted:boolean;error?:string}){await this.db.withTenant(orgId as never,async session=>{const locked=await session.query<{generation:number;rooted:boolean}>(`SELECT t.generation,(${rootExists}) AS rooted FROM whiteboard_object_tombstones t WHERE t.org_id=$1 AND t.object_key=$2 FOR UPDATE`,[orgId,claim.objectKey]);const row=locked.rows[0];const valid=row&&row.generation===claim.generation&&!row.rooted;const status=outcome.deleted&&valid?'deleted':'failed',error=valid?outcome.error:'ROOT_OR_GENERATION_CHANGED';await session.query(`UPDATE whiteboard_object_purge_receipts SET status=$5,last_error=$6,deleted_at=CASE WHEN $5='deleted' THEN now() ELSE deleted_at END,updated_at=now() WHERE org_id=$1 AND object_key=$2 AND generation=$3 AND receipt_id=$4`,[orgId,claim.objectKey,claim.generation,claim.receiptId,status,error??null]);await session.query(`INSERT INTO whiteboard_object_gc_audit(org_id,object_key,generation,receipt_id,event,detail) VALUES($1,$2,$3,$4,$5,$6::jsonb)`,[orgId,claim.objectKey,claim.generation,claim.receiptId,status,JSON.stringify({error:error??null,sizeBytes:claim.sizeBytes})]);});}
}
