import type { DatabasePort } from '../../application/ports/database.port';
import type { WhiteboardGcResult,WhiteboardObjectRetentionRepository,WhiteboardObjectRoot,WhiteboardStoredObject } from '../../application/whiteboard/object-retention';
type RootRow={object_key:string;kind:WhiteboardObjectRoot['kind']};
export class PgWhiteboardObjectRetentionRepository implements WhiteboardObjectRetentionRepository{
  constructor(private readonly db:DatabasePort){}
  async roots(orgId:string){return this.db.withTenant(orgId as never,async session=>(await session.query<RootRow>(`SELECT object_key,'document'::text AS kind FROM whiteboard_documents WHERE org_id=$1 AND object_key IS NOT NULL UNION SELECT update_object_key,'update' FROM whiteboard_updates WHERE org_id=$1 AND update_object_key IS NOT NULL UNION SELECT object_key,'checkpoint' FROM whiteboard_checkpoints WHERE org_id=$1 UNION SELECT source_object_key,'import' FROM whiteboard_imports WHERE org_id=$1 UNION SELECT object_key,'asset' FROM whiteboard_asset_refs WHERE org_id=$1 AND released_at IS NULL`,[orgId])).rows.map(row=>({key:row.object_key,kind:row.kind})))}
  async tombstones(orgId:string){return this.db.withTenant(orgId as never,async session=>new Map((await session.query<{object_key:string;marked_at:Date|string}>(`SELECT object_key,marked_at FROM whiteboard_object_tombstones WHERE org_id=$1 AND swept_at IS NULL AND rescued_at IS NULL`,[orgId])).rows.map(row=>[row.object_key,row.marked_at instanceof Date?row.marked_at:new Date(row.marked_at)])))}
  async mark(orgId:string,object:WhiteboardStoredObject,markedAt:Date){await this.db.withTenant(orgId as never,session=>session.query(`INSERT INTO whiteboard_object_tombstones(org_id,object_key,size_bytes,object_last_modified,marked_at) VALUES($1,$2,$3,$4,$5) ON CONFLICT(org_id,object_key) DO UPDATE SET size_bytes=EXCLUDED.size_bytes,object_last_modified=EXCLUDED.object_last_modified,marked_at=EXCLUDED.marked_at,rescued_at=NULL WHERE whiteboard_object_tombstones.rescued_at IS NOT NULL`,[orgId,object.key,object.sizeBytes,object.lastModified,markedAt]).then(()=>undefined))}
  async unmark(orgId:string,keys:readonly string[]){if(keys.length)await this.db.withTenant(orgId as never,session=>session.query(`UPDATE whiteboard_object_tombstones SET rescued_at=now() WHERE org_id=$1 AND object_key=ANY($2::text[]) AND swept_at IS NULL`,[orgId,keys]).then(()=>undefined))}
  async sweep(orgId:string,object:WhiteboardStoredObject,sweptAt:Date){await this.db.withTenant(orgId as never,session=>session.query(`UPDATE whiteboard_object_tombstones SET swept_at=$3 WHERE org_id=$1 AND object_key=$2 AND swept_at IS NULL`,[orgId,object.key,sweptAt]).then(()=>undefined))}
  async audit(orgId:string,runId:string,result:WhiteboardGcResult){await this.db.withTenant(orgId as never,session=>session.query(`INSERT INTO whiteboard_object_gc_runs(org_id,run_id,roots,scanned,marked,swept,retained,candidate_bytes,result) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) ON CONFLICT(org_id,run_id) DO NOTHING`,[orgId,runId,result.roots,result.scanned,result.marked,result.swept,result.retained,result.candidateBytes,JSON.stringify(result)]).then(()=>undefined))}
}
