import { WhiteboardAIProposal } from '@repo/contracts/whiteboard-operation';
import type { WhiteboardProposalRepository } from '../../application/whiteboard/proposal-ports';
import type {TenantSession} from '../../application/ports/database.port';
import type {Principal} from '../../domain/principal';
export class PgWhiteboardProposalRepository implements WhiteboardProposalRepository {
  async create(session:TenantSession,principal:Principal,proposal:WhiteboardAIProposal,requestHash:string){const existing=await this.lock(session,principal,proposal.boardId,proposal.proposalId);if(existing){if(existing.ownerUserId!==principal.userId||existing.requestHash!==requestHash)throw new Error('BOARD_AI_PROPOSAL_IDEMPOTENCY_CONFLICT');return existing.proposal;}await session.query(`INSERT INTO whiteboard_ai_proposals(org_id,board_id,proposal_id,owner_user_id,actor_id,request_hash,status,payload,expires_at) VALUES($1,$2,$3,$4,$5,$6,'preview',$7::jsonb,$8)`,[principal.orgId,proposal.boardId,proposal.proposalId,principal.userId,proposal.createdBy.actorId,requestHash,JSON.stringify(proposal),proposal.expiresAt]);return proposal;}
  async lock(session:TenantSession,principal:Principal,boardId:string,proposalId:string){const row=await session.query<{owner_user_id:string;request_hash:string;payload:unknown}>(`SELECT owner_user_id,request_hash,payload FROM whiteboard_ai_proposals WHERE org_id=$1 AND board_id=$2 AND proposal_id=$3 FOR UPDATE`,[principal.orgId,boardId,proposalId]);const found=row.rows[0];return found?{proposal:WhiteboardAIProposal.parse(found.payload),ownerUserId:found.owner_user_id,requestHash:found.request_hash}:null;}
  async setStatus(session:TenantSession,principal:Principal,boardId:string,proposalId:string,status:'cancelled'|'confirmed'|'stale'){await session.query(`UPDATE whiteboard_ai_proposals SET status=$4,payload=jsonb_set(payload,'{status}',to_jsonb($4::text)),updated_at=now() WHERE org_id=$1 AND board_id=$2 AND proposal_id=$3`,[principal.orgId,boardId,proposalId,status]);}
}
