import { createHash } from 'node:crypto';
import { WhiteboardCheckpointManifest,type WhiteboardCollaborationEvent } from '@repo/contracts/whiteboard-collaboration';
import type { Principal } from '../../domain/principal';
import type { DatabasePort,TenantSession } from '../../application/ports/database.port';
import { WhiteboardRecoveryError,type WhiteboardRecoveryMetadata,type WhiteboardSnapshotSource } from '../../application/whiteboard/recovery-service';
import type { WhiteboardCollaborationStore } from '../../application/whiteboard/collaboration-ports';
type Access={owner_id:string;archived:boolean};
type CheckpointRow={checkpoint_id:string;board_id:string;version:number;epoch:number;seq:string;object_key:string;content_hash:string;byte_size:string;created_by:string;created_at:Date|string};
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
const manifest=(row:CheckpointRow)=>WhiteboardCheckpointManifest.parse({checkpointId:row.checkpoint_id,boardId:row.board_id,version:row.version,epoch:row.epoch,seq:Number(row.seq),objectKey:row.object_key,contentHash:row.content_hash,byteSize:Number(row.byte_size),createdBy:row.created_by,createdAt:row.created_at instanceof Date?row.created_at.toISOString():new Date(row.created_at).toISOString()});
async function access(session:TenantSession,p:Principal,boardId:string,lock=false){const board=await session.query<Access>(`SELECT owner_id,archived FROM whiteboards WHERE org_id=$1 AND id=$2${lock?' FOR UPDATE':''}`,[p.orgId,boardId]),row=board.rows[0];if(!row)throw new WhiteboardRecoveryError('NOT_FOUND');if(row.owner_id===p.userId)return{role:'owner' as const,archived:row.archived};const member=await session.query<{role:'editor'|'viewer'}>(`SELECT role FROM whiteboard_members WHERE org_id=$1 AND board_id=$2 AND user_id=$3`,[p.orgId,boardId,p.userId]);if(!member.rows[0])throw new WhiteboardRecoveryError('NOT_FOUND');return{role:member.rows[0].role,archived:row.archived};}
const checkpointSelect=`SELECT checkpoint_id,board_id,version,epoch,seq::text,object_key,content_hash,byte_size::text,created_by,created_at FROM whiteboard_checkpoints`;
export class PgWhiteboardRecoveryMetadata implements WhiteboardRecoveryMetadata{
  constructor(private readonly db:DatabasePort){}
  async head(p:Principal,boardId:string){return this.db.withTenant(p.orgId,async session=>{const rights=await access(session,p,boardId);const result=await session.query<{epoch:number;seq:string}>(`SELECT epoch,seq::text FROM whiteboard_documents WHERE org_id=$1 AND board_id=$2`,[p.orgId,boardId]);return{...rights,epoch:result.rows[0]?.epoch??1,seq:Number(result.rows[0]?.seq??0)};});}
  async saveCheckpoint(p:Principal,value:ReturnType<typeof WhiteboardCheckpointManifest.parse>,requestId:string){return this.db.withTenant(p.orgId,async session=>{const rights=await access(session,p,value.boardId,true);if(rights.role==='viewer'||rights.archived)throw new WhiteboardRecoveryError('FORBIDDEN');const before=await session.query<CheckpointRow>(`${checkpointSelect} WHERE org_id=$1 AND board_id=$2 AND checkpoint_id=$3`,[p.orgId,value.boardId,requestId]);const replayed=Boolean(before.rows[0]);if(!replayed)await session.query(`INSERT INTO whiteboard_checkpoints(org_id,board_id,checkpoint_id,version,epoch,seq,object_key,content_hash,byte_size,created_by,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[p.orgId,value.boardId,value.checkpointId,value.version,value.epoch,value.seq,value.objectKey,value.contentHash,value.byteSize,value.createdBy,value.createdAt]);const result=replayed?before:await session.query<CheckpointRow>(`${checkpointSelect} WHERE org_id=$1 AND board_id=$2 AND checkpoint_id=$3`,[p.orgId,value.boardId,requestId]),row=result.rows[0];if(!row)throw new WhiteboardRecoveryError('DEPENDENCY_UNAVAILABLE');const existing=manifest(row);if(JSON.stringify(existing)!==JSON.stringify(value))throw new WhiteboardRecoveryError('CHECKPOINT_INVALID');const event:WhiteboardCollaborationEvent={type:'CheckpointCreated',eventId:value.checkpointId,operationId:value.checkpointId,boardId:value.boardId,checkpointId:value.checkpointId,epoch:value.epoch,seq:value.seq,actorId:p.userId,occurredAt:value.createdAt};await session.query(`INSERT INTO whiteboard_recovery_events(org_id,board_id,event_id,event_type,actor_id,epoch,checkpoint_id,event,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9) ON CONFLICT DO NOTHING`,[p.orgId,value.boardId,value.checkpointId,event.type,p.userId,value.epoch,value.checkpointId,JSON.stringify(event),value.createdAt]);return{manifest:existing,replayed};});}
  async getCheckpoint(p:Principal,boardId:string,checkpointId:string){return this.db.withTenant(p.orgId,async session=>{await access(session,p,boardId);const result=await session.query<CheckpointRow>(`${checkpointSelect} WHERE org_id=$1 AND board_id=$2 AND checkpoint_id=$3`,[p.orgId,boardId,checkpointId]);return result.rows[0]?manifest(result.rows[0]):null;});}
  async commitRestore(p:Principal,input:{boardId:string;checkpoint:ReturnType<typeof WhiteboardCheckpointManifest.parse>;newEpoch:number;expectedEpoch:number;expectedSeq:number;requestId:string;event:WhiteboardCollaborationEvent}){return this.db.withTenant(p.orgId,async session=>{const rights=await access(session,p,input.boardId,true);if(rights.role!=='owner'||rights.archived)throw new WhiteboardRecoveryError('FORBIDDEN');const requestHash=hash(JSON.stringify({checkpointId:input.checkpoint.checkpointId,newEpoch:input.newEpoch,expectedEpoch:input.expectedEpoch,expectedSeq:input.expectedSeq}));const receipt=await session.query<{request_hash:string;new_epoch:number}>(`SELECT request_hash,new_epoch FROM whiteboard_restore_receipts WHERE org_id=$1 AND board_id=$2 AND request_id=$3`,[p.orgId,input.boardId,input.requestId]);if(receipt.rows[0]){if(receipt.rows[0].request_hash!==requestHash)throw new WhiteboardRecoveryError('CHECKPOINT_INVALID');return{epoch:receipt.rows[0].new_epoch,seq:0 as const,replayed:true};}const doc=await session.query<{epoch:number;seq:string}>(`SELECT epoch,seq::text FROM whiteboard_documents WHERE org_id=$1 AND board_id=$2 FOR UPDATE`,[p.orgId,input.boardId]),head=doc.rows[0];if(!head||head.epoch!==input.expectedEpoch||Number(head.seq)!==input.expectedSeq)throw new WhiteboardRecoveryError('STALE_HEAD');await session.query(`UPDATE whiteboard_documents SET epoch=$3,seq=0,snapshot=NULL,manifest_version=1,object_key=$4,content_hash=$5,byte_size=$6,updated_at=now() WHERE org_id=$1 AND board_id=$2`,[p.orgId,input.boardId,input.newEpoch,input.checkpoint.objectKey,input.checkpoint.contentHash.slice(7),input.checkpoint.byteSize]);await session.query(`INSERT INTO whiteboard_restore_receipts(org_id,board_id,request_id,request_hash,checkpoint_id,previous_epoch,new_epoch) VALUES($1,$2,$3,$4,$5,$6,$7)`,[p.orgId,input.boardId,input.requestId,requestHash,input.checkpoint.checkpointId,input.expectedEpoch,input.newEpoch]);await session.query(`INSERT INTO whiteboard_recovery_events(org_id,board_id,event_id,event_type,actor_id,epoch,checkpoint_id,event,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9)`,[p.orgId,input.boardId,input.event.eventId,input.event.type,p.userId,input.newEpoch,input.checkpoint.checkpointId,JSON.stringify(input.event),input.event.occurredAt]);return{epoch:input.newEpoch,seq:0 as const,replayed:false};});}
}
export class CollaborationSnapshotSource implements WhiteboardSnapshotSource{
  constructor(private readonly collaboration:WhiteboardCollaborationStore){}
  async snapshot(p:Principal,boardId:string,epoch:number,seq:number){const current=await this.collaboration.load(p,boardId);if(current.epoch!==epoch||current.seq!==seq)throw new WhiteboardRecoveryError('STALE_HEAD');return current.update;}
}
