import { randomUUID } from 'node:crypto';
import { whiteboardDiscussion as C } from '@repo/contracts';
import type { DatabasePort, TenantSession } from '../../application/ports/database.port';
import type { Principal } from '../../domain/principal';
import type { WhiteboardDiscussion, CreateThread, Reply, EditComment, ResolveThread, UpsertTask, UpdateTask } from '../../application/whiteboard/discussion-ports';
import type { Guarded } from '../../application/security/permission-filter';

// Board ACLs are membership rows rather than generic acl_bindings. Keeping the permission-filter
// boundary in this type makes raw tenant rows impossible to return from the public port.
type Access = { role: 'owner'|'editor'|'viewer'; archived: boolean; readonly guarded?: Guarded<never> };
type ThreadRow = { id:string; board_id:string; anchor_kind:'object'|'point'; anchor_object_id:string|null; anchor_label:string|null; anchor_x:number|null; anchor_y:number|null; resolved_at:Date|null; created_at:Date; updated_at:Date };
type CommentRow = { id:string; author_id:string; body:string; created_at:Date; updated_at:Date; edited_at:Date|null; deleted_at:Date|null; mentions:string[]|null };
type TaskRow = { id:string; source_comment_id:string; assignee_id:string|null; due_at:Date|null; status:'open'|'done'; created_at:Date; updated_at:Date };
const iso=(v:Date|null)=>v?new Date(v).toISOString():null;

export class PgWhiteboardDiscussion implements WhiteboardDiscussion {
 constructor(private readonly db: DatabasePort) {}
 private async access(s:TenantSession,p:Principal,boardId:string,write=false):Promise<Access|null>{
  const r=await s.query<Access>(`SELECT CASE WHEN b.owner_id=$2 THEN 'owner' ELSE m.role END role,b.archived
   FROM whiteboards b LEFT JOIN whiteboard_members m ON m.org_id=b.org_id AND m.board_id=b.id AND m.user_id=$2
   WHERE b.org_id=$1 AND b.id=$3 AND (b.owner_id=$2 OR m.user_id IS NOT NULL) ${write?'FOR UPDATE OF b':''}`,[p.orgId,p.userId,boardId]);
  const a=r.rows[0]; return !a || (write && (a.role==='viewer'||a.archived)) ? null : a;
 }
 private async validUsers(s:TenantSession,p:Principal,boardId:string,ids:string[]):Promise<boolean>{
  const unique=[...new Set(ids)]; if(unique.length!==ids.length||unique.length>C.WHITEBOARD_DISCUSSION_LIMITS.mentions)return false;
  if(!unique.length)return true;
  const r=await s.query<{user_id:string}>(`SELECT u.user_id FROM (SELECT owner_id user_id FROM whiteboards WHERE org_id=$1 AND id=$2 UNION SELECT user_id FROM whiteboard_members WHERE org_id=$1 AND board_id=$2) u JOIN org_memberships om ON om.org_id=$1 AND om.user_id=u.user_id WHERE u.user_id=ANY($3::text[])`,[p.orgId,boardId,unique]);
  return r.rows.length===unique.length;
 }
 private async replaceMentions(s:TenantSession,p:Principal,boardId:string,commentId:string,ids:string[],body:string){
  if(!await this.validUsers(s,p,boardId,ids))return false;
  await s.query(`DELETE FROM whiteboard_comment_mentions WHERE org_id=$1 AND comment_id=$2`,[p.orgId,commentId]);
  if(ids.length) await s.query(`INSERT INTO whiteboard_comment_mentions(org_id,board_id,comment_id,user_id) SELECT $1,$2,$3,x FROM unnest($4::text[]) x ON CONFLICT DO NOTHING`,[p.orgId,boardId,commentId,ids]);
  for(const userId of ids) if(userId!==p.userId) await s.query(`INSERT INTO user_notifications(org_id,user_id,kind,title,body,source_key,actionable) VALUES($1,$2,'task','你在白板评论中被提及',$3,$4,true) ON CONFLICT DO NOTHING`,[p.orgId,userId,body.slice(0,4000),`whiteboard-comment:${commentId}:${userId}`]);
  return true;
 }
 private async load(s:TenantSession,p:Principal,boardId:string,threadId:string):Promise<C.Thread|null>{
  const tr=await s.query<ThreadRow>(`SELECT * FROM whiteboard_threads WHERE org_id=$1 AND board_id=$2 AND id=$3`,[p.orgId,boardId,threadId]); const t=tr.rows[0]; if(!t)return null;
  const cr=await s.query<CommentRow>(`SELECT c.*,COALESCE(array_agg(m.user_id ORDER BY m.user_id) FILTER(WHERE m.user_id IS NOT NULL),'{}') mentions FROM whiteboard_comments c LEFT JOIN whiteboard_comment_mentions m ON m.org_id=c.org_id AND m.comment_id=c.id WHERE c.org_id=$1 AND c.thread_id=$2 GROUP BY c.id ORDER BY c.created_at,c.id LIMIT $3`,[p.orgId,threadId,C.WHITEBOARD_DISCUSSION_LIMITS.commentsPerThread]);
  const qr=await s.query<TaskRow>(`SELECT * FROM whiteboard_comment_tasks WHERE org_id=$1 AND thread_id=$2`,[p.orgId,threadId]); const q=qr.rows[0];
  return C.Thread.parse({id:t.id,boardId:t.board_id,anchor:t.anchor_kind==='object'?{kind:'object',objectId:t.anchor_object_id,label:t.anchor_label}:{kind:'point',x:t.anchor_x,y:t.anchor_y},resolvedAt:iso(t.resolved_at),createdAt:iso(t.created_at),updatedAt:iso(t.updated_at),comments:cr.rows.map(c=>({id:c.id,authorId:c.author_id,body:c.deleted_at?'':c.body,mentionUserIds:c.mentions??[],createdAt:iso(c.created_at),updatedAt:iso(c.updated_at),editedAt:iso(c.edited_at),deletedAt:iso(c.deleted_at)})),task:q?{id:q.id,sourceCommentId:q.source_comment_id,assigneeId:q.assignee_id,dueAt:iso(q.due_at),status:q.status,createdAt:iso(q.created_at),updatedAt:iso(q.updated_at)}:null});
 }
 async list(p:Principal,boardId:string,cursor?:string){return this.db.withTenant(p.orgId,async s=>{if(!await this.access(s,p,boardId))return null;const r=await s.query<{id:string}>(`SELECT id FROM whiteboard_threads WHERE org_id=$1 AND board_id=$2 AND ($3::uuid IS NULL OR (updated_at,id)<(SELECT updated_at,id FROM whiteboard_threads WHERE org_id=$1 AND id=$3)) ORDER BY updated_at DESC,id DESC LIMIT $4`,[p.orgId,boardId,cursor??null,C.WHITEBOARD_DISCUSSION_LIMITS.pageSize+1]);const ids=r.rows.slice(0,C.WHITEBOARD_DISCUSSION_LIMITS.pageSize).map(x=>x.id);const items=[];for(const id of ids){const t=await this.load(s,p,boardId,id);if(t)items.push(t);}return C.ThreadPage.parse({items,nextCursor:r.rows.length>C.WHITEBOARD_DISCUSSION_LIMITS.pageSize?ids.at(-1):null});});}
 async create(p:Principal,boardId:string,input:CreateThread){return this.db.withTenant(p.orgId,async s=>{if(!await this.access(s,p,boardId,true)||!await this.validUsers(s,p,boardId,input.mentionUserIds))return null;const id=randomUUID(),commentId=randomUUID(),a=input.anchor;const inserted=await s.query<{id:string}>(`INSERT INTO whiteboard_threads(id,org_id,board_id,request_id,anchor_kind,anchor_object_id,anchor_label,anchor_x,anchor_y,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(org_id,board_id,created_by,request_id) DO NOTHING RETURNING id`,[id,p.orgId,boardId,input.requestId,a.kind,a.kind==='object'?a.objectId:null,a.kind==='object'?a.label:null,a.kind==='point'?a.x:null,a.kind==='point'?a.y:null,p.userId]);const tr=await s.query<{id:string}>(`SELECT id FROM whiteboard_threads WHERE org_id=$1 AND board_id=$2 AND created_by=$3 AND request_id=$4`,[p.orgId,boardId,p.userId,input.requestId]);const actual=tr.rows[0]!.id;if(!inserted.rows.length)return this.load(s,p,boardId,actual);await s.query(`INSERT INTO whiteboard_comments(id,org_id,board_id,thread_id,request_id,author_id,body) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT DO NOTHING`,[commentId,p.orgId,boardId,actual,input.requestId,p.userId,input.body]);const comment=await s.query<{id:string}>(`SELECT id FROM whiteboard_comments WHERE org_id=$1 AND thread_id=$2 AND author_id=$3 AND request_id=$4`,[p.orgId,actual,p.userId,input.requestId]);if(!await this.replaceMentions(s,p,boardId,comment.rows[0]!.id,input.mentionUserIds,input.body))return null;return this.load(s,p,boardId,actual);});}
 async reply(p:Principal,boardId:string,threadId:string,input:Reply){return this.db.withTenant(p.orgId,async s=>{if(!await this.access(s,p,boardId,true)||!await this.validUsers(s,p,boardId,input.mentionUserIds))return null;const replay=await s.query<{id:string}>(`SELECT id FROM whiteboard_comments WHERE org_id=$1 AND thread_id=$2 AND author_id=$3 AND request_id=$4`,[p.orgId,threadId,p.userId,input.requestId]);if(replay.rows[0])return this.load(s,p,boardId,threadId);const count=await s.query<{n:string}>(`SELECT count(*)::text n FROM whiteboard_comments WHERE org_id=$1 AND thread_id=$2`,[p.orgId,threadId]);if(Number(count.rows[0]?.n)>=C.WHITEBOARD_DISCUSSION_LIMITS.commentsPerThread)return null;const id=randomUUID();const inserted=await s.query<{id:string}>(`INSERT INTO whiteboard_comments(id,org_id,board_id,thread_id,request_id,author_id,body) SELECT $1,$2,$3,t.id,$4,$5,$6 FROM whiteboard_threads t WHERE t.org_id=$2 AND t.board_id=$3 AND t.id=$7 ON CONFLICT DO NOTHING RETURNING id`,[id,p.orgId,boardId,input.requestId,p.userId,input.body,threadId]);const c=await s.query<{id:string}>(`SELECT id FROM whiteboard_comments WHERE org_id=$1 AND thread_id=$2 AND author_id=$3 AND request_id=$4`,[p.orgId,threadId,p.userId,input.requestId]);if(!c.rows[0])return null;if(!inserted.rows.length)return this.load(s,p,boardId,threadId);if(!await this.replaceMentions(s,p,boardId,c.rows[0].id,input.mentionUserIds,input.body))return null;await s.query(`UPDATE whiteboard_threads SET updated_at=now() WHERE org_id=$1 AND id=$2`,[p.orgId,threadId]);return this.load(s,p,boardId,threadId);});}
 async edit(p:Principal,boardId:string,commentId:string,input:EditComment){return this.db.withTenant(p.orgId,async s=>{if(!await this.access(s,p,boardId,true)||!await this.validUsers(s,p,boardId,input.mentionUserIds))return null;const before=await s.query<{thread_id:string;body:string}>(`SELECT thread_id,body FROM whiteboard_comments WHERE org_id=$1 AND board_id=$2 AND id=$3 AND author_id=$4 AND deleted_at IS NULL FOR UPDATE`,[p.orgId,boardId,commentId,p.userId]);if(!before.rows[0])return null;await s.query(`UPDATE whiteboard_comments SET body=$4,updated_at=now(),edited_at=now() WHERE org_id=$1 AND board_id=$2 AND id=$3`,[p.orgId,boardId,commentId,input.body]);await s.query(`INSERT INTO whiteboard_discussion_audit(org_id,board_id,actor_id,entity_kind,entity_id,action,before_value,after_value) VALUES($1,$2,$3,'comment',$4,'edit',jsonb_build_object('body',$5),jsonb_build_object('body',$6))`,[p.orgId,boardId,p.userId,commentId,before.rows[0].body,input.body]);if(!await this.replaceMentions(s,p,boardId,commentId,input.mentionUserIds,input.body))return null;return this.load(s,p,boardId,before.rows[0].thread_id);});}
 async delete(p:Principal,boardId:string,commentId:string){return this.db.withTenant(p.orgId,async s=>{const a=await this.access(s,p,boardId,true);if(!a)return null;const r=await s.query<{thread_id:string}>(`UPDATE whiteboard_comments SET deleted_at=now(),updated_at=now() WHERE org_id=$1 AND board_id=$2 AND id=$3 AND deleted_at IS NULL AND (author_id=$4 OR $5='owner') RETURNING thread_id`,[p.orgId,boardId,commentId,p.userId,a.role]);if(!r.rows[0])return null;await s.query(`DELETE FROM whiteboard_comment_mentions WHERE org_id=$1 AND comment_id=$2`,[p.orgId,commentId]);await s.query(`INSERT INTO whiteboard_discussion_audit(org_id,board_id,actor_id,entity_kind,entity_id,action) VALUES($1,$2,$3,'comment',$4,'delete')`,[p.orgId,boardId,p.userId,commentId]);return this.load(s,p,boardId,r.rows[0].thread_id);});}
 async resolve(p:Principal,boardId:string,threadId:string,input:ResolveThread){return this.db.withTenant(p.orgId,async s=>{if(!await this.access(s,p,boardId,true))return null;const r=await s.query<{id:string}>(`UPDATE whiteboard_threads SET resolved_at=CASE WHEN $4 THEN now() ELSE NULL END,updated_at=now() WHERE org_id=$1 AND board_id=$2 AND id=$3 RETURNING id`,[p.orgId,boardId,threadId,input.resolved]);if(!r.rows[0])return null;await s.query(`INSERT INTO whiteboard_discussion_audit(org_id,board_id,actor_id,entity_kind,entity_id,action) VALUES($1,$2,$3,'thread',$4,$5)`,[p.orgId,boardId,p.userId,threadId,input.resolved?'resolve':'reopen']);return this.load(s,p,boardId,threadId);});}
 async createTask(p:Principal,boardId:string,threadId:string,input:UpsertTask){return this.db.withTenant(p.orgId,async s=>{if(!await this.access(s,p,boardId,true)||input.assigneeId&&!await this.validUsers(s,p,boardId,[input.assigneeId]))return null;await s.query(`INSERT INTO whiteboard_comment_tasks(id,org_id,board_id,thread_id,source_comment_id,request_id,assignee_id,due_at,created_by) SELECT $1,$2,$3,t.id,(SELECT c.id FROM whiteboard_comments c WHERE c.org_id=$2 AND c.thread_id=t.id ORDER BY c.created_at,c.id LIMIT 1),$4,$5,$6,$7 FROM whiteboard_threads t WHERE t.org_id=$2 AND t.board_id=$3 AND t.id=$8 ON CONFLICT DO NOTHING`,[randomUUID(),p.orgId,boardId,input.requestId,input.assigneeId,input.dueAt,p.userId,threadId]);const task=await s.query<{thread_id:string}>(`SELECT thread_id FROM whiteboard_comment_tasks WHERE org_id=$1 AND board_id=$2 AND created_by=$3 AND request_id=$4`,[p.orgId,boardId,p.userId,input.requestId]);return task.rows[0]?this.load(s,p,boardId,task.rows[0].thread_id):null;});}
 async updateTask(p:Principal,boardId:string,taskId:string,input:UpdateTask){return this.db.withTenant(p.orgId,async s=>{if(!await this.access(s,p,boardId,true)||input.assigneeId&&!await this.validUsers(s,p,boardId,[input.assigneeId]))return null;const r=await s.query<{thread_id:string}>(`UPDATE whiteboard_comment_tasks SET assignee_id=CASE WHEN $4 THEN $5 ELSE assignee_id END,due_at=CASE WHEN $6 THEN $7 ELSE due_at END,status=COALESCE($8,status),updated_at=now() WHERE org_id=$1 AND board_id=$2 AND id=$3 RETURNING thread_id`,[p.orgId,boardId,taskId,'assigneeId' in input,input.assigneeId??null,'dueAt' in input,input.dueAt??null,input.status??null]);if(!r.rows[0])return null;await s.query(`INSERT INTO whiteboard_discussion_audit(org_id,board_id,actor_id,entity_kind,entity_id,action,after_value) VALUES($1,$2,$3,'task',$4,$5,$6::jsonb)`,[p.orgId,boardId,p.userId,taskId,input.status?'status':input.assigneeId!==undefined?'assign':'due',JSON.stringify(input)]);return this.load(s,p,boardId,r.rows[0].thread_id);});}
}
