import { whiteboardFileExport as C } from '@repo/contracts';
import { BOARD_FILE_EXPORT_LIMITS } from '@repo/contracts/whiteboard-file-export';
import type { Principal } from '../../domain/principal';
import { toOrgId } from '../../domain/org-id';
import type { DatabasePort, TenantSession } from '../../application/ports/database.port';
import { WhiteboardFileExportError as Fault, type WhiteboardFileExportClaim, type WhiteboardFileExportCleanup, type WhiteboardFileExportRecord, type WhiteboardFileExportRepository } from '../../application/whiteboard/file-export-ports';

type Row={id:string;org_id?:string;actor_id?:string;board_id:string;format:C.BoardFileExportFormat;background?:string;status:C.BoardFileExportStatus['status'];progress:number;filename:string;mime_type:string;object_count:number;page_order:unknown;losses:unknown;size_bytes:string|null;error_code:C.BoardFileExportStatus['errorCode'];object_key:string|null;sha256:string|null;lease_owner?:string};
function record(row:Row):WhiteboardFileExportRecord{return{status:C.BoardFileExportStatus.parse({jobId:row.id,boardId:row.board_id,format:row.format,status:row.status,progress:row.progress,filename:row.filename,mimeType:row.mime_type,objectCount:row.object_count,pageOrder:row.page_order,losses:row.losses,sizeBytes:row.size_bytes===null?null:Number(row.size_bytes),errorCode:row.error_code}),objectKey:row.object_key,sha256:row.sha256};}
const columns=`j.id,j.board_id,j.format,j.status,j.progress,j.filename,j.mime_type,j.object_count,j.page_order,j.losses,j.size_bytes,j.error_code,j.object_key,j.sha256`;
const extension=(format:C.BoardFileExportFormat)=>format==='sticky-csv'?'csv':format;

export class PgWhiteboardFileExportRepository implements WhiteboardFileExportRepository {
  constructor(private readonly db:DatabasePort){}
  async create(p:Principal,status:C.BoardFileExportStatus,input:C.BoardFileExportInput):Promise<void>{await this.db.withTenant(p.orgId,async session=>{const allowed=await session.query(`SELECT b.id FROM whiteboards b LEFT JOIN whiteboard_members m ON m.org_id=b.org_id AND m.board_id=b.id AND m.user_id=$3 WHERE b.org_id=$1 AND b.id=$2 AND (b.owner_id=$3 OR m.user_id IS NOT NULL) FOR UPDATE OF b`,[p.orgId,status.boardId,p.userId]);if(!allowed.rows[0])throw new Fault('NOT_FOUND');await session.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[`${p.orgId}\u001f${p.userId}`]);let retained=Number((await session.query<{count:string}>(`SELECT count(*)::text count FROM whiteboard_file_export_jobs WHERE org_id=$1 AND actor_id=$2 AND NOT retention_evicted`,[p.orgId,p.userId])).rows[0]?.count);while(retained>=BOARD_FILE_EXPORT_LIMITS.retainedJobs){const evicted=await session.query<{id:string}>(`SELECT id FROM whiteboard_file_export_jobs WHERE org_id=$1 AND actor_id=$2 AND NOT retention_evicted AND status IN ('done','failed','cancelled') ORDER BY created_at,id LIMIT 1 FOR UPDATE`,[p.orgId,p.userId]),candidate=evicted.rows[0];if(!candidate)throw new Fault('BOUNDS_EXCEEDED');await session.query(`UPDATE whiteboard_file_export_jobs SET retention_evicted=true,artifact_state='cleanup_pending',cleanup_after=clock_timestamp(),updated_at=clock_timestamp() WHERE org_id=$1 AND actor_id=$2 AND id=$3`,[p.orgId,p.userId,candidate.id]);retained--;}
    const objectKey=`whiteboard-exports/${p.orgId}/${status.jobId}.${extension(status.format)}`;await session.query(`INSERT INTO whiteboard_file_export_jobs(id,org_id,board_id,actor_id,format,background,status,progress,filename,mime_type,object_key) VALUES($1,$2,$3,$4,$5,$6,'queued',0,$7,$8,$9)`,[status.jobId,p.orgId,status.boardId,p.userId,status.format,input.background,status.filename,status.mimeType,objectKey]);});}
  async claimNext(workerId:string,leaseMs:number,concurrency:number):Promise<WhiteboardFileExportClaim|null>{return this.db.withoutTenant(async session=>{const result=await session.query<Row>('SELECT * FROM kernel_claim_whiteboard_file_export($1,$2,$3)',[workerId,leaseMs,concurrency]),row=result.rows[0];if(!row||!row.org_id||!row.actor_id||!row.background||!row.object_key||!row.lease_owner)return null;return{principal:{orgId:toOrgId(row.org_id),userId:row.actor_id},input:C.BoardFileExportInput.parse({format:row.format,background:row.background}),status:record(row).status,objectKey:row.object_key,leaseOwner:row.lease_owner};});}
  async renew(claim:WhiteboardFileExportClaim,progress:number,leaseMs:number):Promise<boolean>{return this.db.withTenant(claim.principal.orgId,async session=>{const result=await session.query(`UPDATE whiteboard_file_export_jobs j SET progress=GREATEST(j.progress,$5),lease_expires_at=clock_timestamp()+$6*interval '1 millisecond',updated_at=clock_timestamp() FROM whiteboards b LEFT JOIN whiteboard_members m ON m.org_id=b.org_id AND m.board_id=b.id AND m.user_id=$2 WHERE j.org_id=$1 AND j.actor_id=$2 AND j.id=$3 AND j.status='running' AND j.lease_owner=$4 AND b.org_id=j.org_id AND b.id=j.board_id AND (b.owner_id=$2 OR m.user_id IS NOT NULL) RETURNING j.id`,[claim.principal.orgId,claim.principal.userId,claim.status.jobId,claim.leaseOwner,progress,leaseMs]);return Boolean(result.rows[0]);});}
  async complete(claim:WhiteboardFileExportClaim,status:C.BoardFileExportStatus,sha256:string):Promise<boolean>{return this.db.withTenant(claim.principal.orgId,async session=>{const result=await session.query(`UPDATE whiteboard_file_export_jobs j SET status='done',progress=100,object_count=$5,page_order=$6::jsonb,losses=$7::jsonb,size_bytes=$8,error_code=NULL,sha256=$9,artifact_state='referenced',lease_owner=NULL,lease_expires_at=NULL,updated_at=now() FROM whiteboards b LEFT JOIN whiteboard_members m ON m.org_id=b.org_id AND m.board_id=b.id AND m.user_id=$2 WHERE j.org_id=$1 AND j.actor_id=$2 AND j.id=$3 AND j.lease_owner=$4 AND j.status='running' AND b.org_id=j.org_id AND b.id=j.board_id AND (b.owner_id=$2 OR m.user_id IS NOT NULL) RETURNING j.board_id`,[claim.principal.orgId,claim.principal.userId,status.jobId,claim.leaseOwner,status.objectCount,JSON.stringify(status.pageOrder),JSON.stringify(status.losses),status.sizeBytes,sha256]);if(!result.rows[0])return false;await this.audit(session,claim.principal,status,'done');return true;});}
  async finish(claim:WhiteboardFileExportClaim,status:C.BoardFileExportStatus):Promise<void>{await this.db.withTenant(claim.principal.orgId,async session=>{const result=await session.query(`UPDATE whiteboard_file_export_jobs SET status=$5,progress=$6,object_count=$7,page_order=$8::jsonb,losses=$9::jsonb,size_bytes=NULL,error_code=$10,artifact_state='cleanup_pending',cleanup_after=GREATEST(COALESCE(lease_expires_at,clock_timestamp()),clock_timestamp()+interval '30 seconds'),lease_owner=NULL,lease_expires_at=NULL,updated_at=now() WHERE org_id=$1 AND actor_id=$2 AND id=$3 AND lease_owner=$4 AND status='running' RETURNING board_id`,[claim.principal.orgId,claim.principal.userId,status.jobId,claim.leaseOwner,status.status,status.progress,status.objectCount,JSON.stringify(status.pageOrder),JSON.stringify(status.losses),status.errorCode]);if(result.rows[0])await this.audit(session,claim.principal,status,status.status as 'failed'|'cancelled');});}
  private async audit(session:TenantSession,p:Principal,status:C.BoardFileExportStatus,outcome:'done'|'failed'|'cancelled'):Promise<void>{await session.query(`INSERT INTO whiteboard_transfer_audit(org_id,board_id,actor_id,action,object_count,format,outcome,job_id,loss_report) VALUES($1,$2,$3,'export',$4,$5,$6,$7,$8::jsonb)`,[p.orgId,status.boardId,p.userId,status.objectCount,status.format,outcome,status.jobId,JSON.stringify(status.losses)]);}
  async find(p:Principal,jobId:string):Promise<WhiteboardFileExportRecord|null>{return this.db.withTenant(p.orgId,async session=>{const result=await session.query<Row>(`SELECT ${columns} FROM whiteboard_file_export_jobs j JOIN whiteboards b ON b.org_id=j.org_id AND b.id=j.board_id LEFT JOIN whiteboard_members m ON m.org_id=b.org_id AND m.board_id=b.id AND m.user_id=$2 WHERE j.org_id=$1 AND j.actor_id=$2 AND j.id=$3 AND NOT j.retention_evicted AND (b.owner_id=$2 OR m.user_id IS NOT NULL)`,[p.orgId,p.userId,jobId]);return result.rows[0]?record(result.rows[0]):null;});}
  async cancel(p:Principal,jobId:string):Promise<C.BoardFileExportStatus|null>{return this.db.withTenant(p.orgId,async session=>{const result=await session.query<Row>(`UPDATE whiteboard_file_export_jobs j SET status='cancelled',error_code=NULL,artifact_state='cleanup_pending',cleanup_after=GREATEST(COALESCE(j.lease_expires_at,clock_timestamp()),clock_timestamp()+interval '30 seconds'),updated_at=now() FROM whiteboards b LEFT JOIN whiteboard_members m ON m.org_id=b.org_id AND m.board_id=b.id AND m.user_id=$2 WHERE j.org_id=$1 AND j.actor_id=$2 AND j.id=$3 AND NOT j.retention_evicted AND j.status IN ('queued','running') AND b.org_id=j.org_id AND b.id=j.board_id AND (b.owner_id=$2 OR m.user_id IS NOT NULL) RETURNING ${columns}`,[p.orgId,p.userId,jobId]);if(result.rows[0]){const status=record(result.rows[0]).status;await this.audit(session,p,status,'cancelled');return status;}const existing=await session.query<Row>(`SELECT ${columns} FROM whiteboard_file_export_jobs j JOIN whiteboards b ON b.org_id=j.org_id AND b.id=j.board_id LEFT JOIN whiteboard_members m ON m.org_id=b.org_id AND m.board_id=b.id AND m.user_id=$2 WHERE j.org_id=$1 AND j.actor_id=$2 AND j.id=$3 AND NOT j.retention_evicted AND (b.owner_id=$2 OR m.user_id IS NOT NULL)`,[p.orgId,p.userId,jobId]);return existing.rows[0]?record(existing.rows[0]).status:null;});}
  async claimCleanup(workerId:string):Promise<WhiteboardFileExportCleanup|null>{return this.db.withoutTenant(async session=>{const result=await session.query<{id:string;object_key:string;cleanup_owner:string}>('SELECT * FROM kernel_claim_whiteboard_file_export_cleanup($1)',[workerId]);const row=result.rows[0];return row?{jobId:row.id,objectKey:row.object_key,cleanupOwner:row.cleanup_owner}:null;});}
  async finishCleanup(cleanup:WhiteboardFileExportCleanup,deleted:boolean):Promise<void>{await this.db.withoutTenant(async session=>{await session.query('SELECT kernel_finish_whiteboard_file_export_cleanup($1,$2,$3)',[cleanup.jobId,cleanup.cleanupOwner,deleted]);});}
}
