import { whiteboardFileExport as C } from '@repo/contracts';
import type { Principal } from '../../domain/principal';
import type { DatabasePort, TenantSession } from '../../application/ports/database.port';
import { WhiteboardFileExportError as Fault, type WhiteboardFileExportRecord, type WhiteboardFileExportRepository } from '../../application/whiteboard/file-export-ports';

type Row={id:string;board_id:string;format:C.BoardFileExportFormat;status:C.BoardFileExportStatus['status'];progress:number;filename:string;mime_type:string;object_count:number;page_order:unknown;losses:unknown;size_bytes:string|null;error_code:C.BoardFileExportStatus['errorCode'];object_key:string|null;sha256:string|null};
function record(row:Row):WhiteboardFileExportRecord{return{status:C.BoardFileExportStatus.parse({jobId:row.id,boardId:row.board_id,format:row.format,status:row.status,progress:row.progress,filename:row.filename,mimeType:row.mime_type,objectCount:row.object_count,pageOrder:row.page_order,losses:row.losses,sizeBytes:row.size_bytes===null?null:Number(row.size_bytes),errorCode:row.error_code}),objectKey:row.object_key,sha256:row.sha256};}
const columns=`id,board_id,format,status,progress,filename,mime_type,object_count,page_order,losses,size_bytes,error_code,object_key,sha256`;

export class PgWhiteboardFileExportRepository implements WhiteboardFileExportRepository {
  constructor(private readonly db:DatabasePort){}
  private async access(session:TenantSession,p:Principal,jobId:string):Promise<boolean>{const result=await session.query(`SELECT 1 FROM whiteboard_file_export_jobs j JOIN whiteboards b ON b.org_id=j.org_id AND b.id=j.board_id LEFT JOIN whiteboard_members m ON m.org_id=b.org_id AND m.board_id=b.id AND m.user_id=$2 WHERE j.org_id=$1 AND j.actor_id=$2 AND j.id=$3 AND (b.owner_id=$2 OR m.user_id IS NOT NULL)`,[p.orgId,p.userId,jobId]);return Boolean(result.rows[0]);}
  async create(p:Principal,status:C.BoardFileExportStatus,input:C.BoardFileExportInput):Promise<void>{await this.db.withTenant(p.orgId,async session=>{const result=await session.query(`INSERT INTO whiteboard_file_export_jobs(id,org_id,board_id,actor_id,format,background,status,progress,filename,mime_type) SELECT $1,$2,b.id,$4,$5,$6,'queued',0,$7,$8 FROM whiteboards b LEFT JOIN whiteboard_members m ON m.org_id=b.org_id AND m.board_id=b.id AND m.user_id=$4 WHERE b.org_id=$2 AND b.id=$3 AND (b.owner_id=$4 OR m.user_id IS NOT NULL) RETURNING id`,[status.jobId,p.orgId,status.boardId,p.userId,status.format,input.background,status.filename,status.mimeType]);if(!result.rows[0])throw new Fault('NOT_FOUND');});}
  async running(p:Principal,jobId:string,progress:number):Promise<void>{await this.db.withTenant(p.orgId,async session=>{if(!await this.access(session,p,jobId))throw new Fault('NOT_FOUND');const result=await session.query(`UPDATE whiteboard_file_export_jobs SET status='running',progress=GREATEST(progress,$4),updated_at=now() WHERE org_id=$1 AND actor_id=$2 AND id=$3 AND status IN ('queued','running') RETURNING id`,[p.orgId,p.userId,jobId,progress]);if(!result.rows[0])throw new Fault('NOT_FOUND');});}
  async complete(p:Principal,status:C.BoardFileExportStatus,objectKey:string,sha256:string):Promise<void>{await this.db.withTenant(p.orgId,async session=>{if(!await this.access(session,p,status.jobId))throw new Fault('NOT_FOUND');const result=await session.query(`UPDATE whiteboard_file_export_jobs SET status='done',progress=100,object_count=$4,page_order=$5::jsonb,losses=$6::jsonb,size_bytes=$7,error_code=NULL,object_key=$8,sha256=$9,updated_at=now() WHERE org_id=$1 AND actor_id=$2 AND id=$3 AND status='running' RETURNING board_id`,[p.orgId,p.userId,status.jobId,status.objectCount,JSON.stringify(status.pageOrder),JSON.stringify(status.losses),status.sizeBytes,objectKey,sha256]);if(!result.rows[0])throw new Fault('NOT_FOUND');await this.audit(session,p,status,'done');});}
  async finish(p:Principal,status:C.BoardFileExportStatus):Promise<void>{await this.db.withTenant(p.orgId,async session=>{if(!await this.access(session,p,status.jobId))throw new Fault('NOT_FOUND');const result=await session.query(`UPDATE whiteboard_file_export_jobs SET status=$4,progress=$5,object_count=$6,page_order=$7::jsonb,losses=$8::jsonb,size_bytes=NULL,error_code=$9,updated_at=now() WHERE org_id=$1 AND actor_id=$2 AND id=$3 AND status IN ('queued','running') RETURNING board_id`,[p.orgId,p.userId,status.jobId,status.status,status.progress,status.objectCount,JSON.stringify(status.pageOrder),JSON.stringify(status.losses),status.errorCode]);if(result.rows[0])await this.audit(session,p,status,status.status as 'failed'|'cancelled');});}
  private async audit(session:TenantSession,p:Principal,status:C.BoardFileExportStatus,outcome:'done'|'failed'|'cancelled'):Promise<void>{await session.query(`INSERT INTO whiteboard_transfer_audit(org_id,board_id,actor_id,action,object_count,format,outcome,job_id,loss_report) VALUES($1,$2,$3,'export',$4,$5,$6,$7,$8::jsonb)`,[p.orgId,status.boardId,p.userId,status.objectCount,status.format,outcome,status.jobId,JSON.stringify(status.losses)]);}
  async find(p:Principal,jobId:string):Promise<WhiteboardFileExportRecord|null>{return this.db.withTenant(p.orgId,async session=>{if(!await this.access(session,p,jobId))return null;const stale=await session.query<Row>(`UPDATE whiteboard_file_export_jobs SET status='failed',error_code='GENERATION_FAILED',updated_at=now() WHERE org_id=$1 AND actor_id=$2 AND id=$3 AND status IN ('queued','running') AND updated_at<now()-interval '2 minutes' RETURNING ${columns}`,[p.orgId,p.userId,jobId]);if(stale.rows[0])await this.audit(session,p,record(stale.rows[0]).status,'failed');const result=await session.query<Row>(`SELECT ${columns} FROM whiteboard_file_export_jobs WHERE org_id=$1 AND actor_id=$2 AND id=$3`,[p.orgId,p.userId,jobId]);return result.rows[0]?record(result.rows[0]):null;});}
  async cancel(p:Principal,jobId:string):Promise<C.BoardFileExportStatus|null>{return this.db.withTenant(p.orgId,async session=>{if(!await this.access(session,p,jobId))return null;const result=await session.query<Row>(`UPDATE whiteboard_file_export_jobs SET status='cancelled',error_code=NULL,updated_at=now() WHERE org_id=$1 AND actor_id=$2 AND id=$3 AND status IN ('queued','running') RETURNING ${columns}`,[p.orgId,p.userId,jobId]);if(result.rows[0]){const status=record(result.rows[0]).status;await this.audit(session,p,status,'cancelled');return status;}const existing=await session.query<Row>(`SELECT ${columns} FROM whiteboard_file_export_jobs WHERE org_id=$1 AND actor_id=$2 AND id=$3`,[p.orgId,p.userId,jobId]);return existing.rows[0]?record(existing.rows[0]).status:null;});}
}
