import { WhiteboardCheckpointManifest, type WhiteboardCollaborationEvent } from "@repo/contracts/whiteboard-collaboration";
import type { DatabasePort, TenantSession } from "../../application/ports/database.port";
import type { WhiteboardCollaborationStore } from "../../application/whiteboard/collaboration-ports";
import { WhiteboardRecoveryError, type WhiteboardRecoveryMetadata, type WhiteboardSnapshotSource } from "../../application/whiteboard/recovery-service";
import type { Principal } from "../../domain/principal";
import { discloseDecided,guard,isDisclosed } from "../../application/security/permission-filter";
import { decideWhiteboardAccess } from "../../domain/whiteboard/access-decision";

function disclose<T>(boardId:string,role:"owner"|"editor"|"commenter"|"viewer",action:"read"|"write",payload:T):T {const result=discloseDecided(guard({kind:"whiteboard",id:boardId},payload),decideWhiteboardAccess({decisionId:`whiteboard:${boardId}:${action}`,role,action}));if(!isDisclosed(result))throw new WhiteboardRecoveryError("FORBIDDEN");return result.payload;}
type RestoreResponse={epoch:number;seq:0;event:WhiteboardCollaborationEvent;auditEvents?:WhiteboardCollaborationEvent[]};
const normalizeRestore=(response:RestoreResponse)=>({...response,auditEvents:response.auditEvents??[]});

export class PgWhiteboardRecoveryAdapter implements WhiteboardRecoveryMetadata,WhiteboardSnapshotSource {
  constructor(private readonly db:DatabasePort,private readonly collaboration:WhiteboardCollaborationStore){}
  private async access(session:TenantSession,p:Principal,boardId:string){const result=await session.query<{owner_id:string;archived:boolean;role:string|null}>(`SELECT b.owner_id,b.archived,CASE WHEN b.owner_id=$3 THEN 'owner' ELSE m.role END AS role FROM whiteboards b LEFT JOIN whiteboard_members m ON m.org_id=b.org_id AND m.board_id=b.id AND m.user_id=$3 WHERE b.org_id=$1 AND b.id=$2 FOR UPDATE OF b`,[p.orgId,boardId,p.userId]);const row=result.rows[0];if(!row||!row.role)throw new WhiteboardRecoveryError("NOT_FOUND");return{role:row.role as "owner"|"editor"|"commenter"|"viewer",archived:row.archived};}
  async head(p:Principal,boardId:string){return this.db.withTenant(p.orgId,async session=>{const access=await this.access(session,p,boardId),doc=await session.query<{epoch:number;seq:string}>(`SELECT epoch,seq FROM whiteboard_documents WHERE org_id=$1 AND board_id=$2`,[p.orgId,boardId]),row=disclose(boardId,access.role,"read",doc.rows[0]);return{...access,epoch:row?.epoch??1,seq:Number(row?.seq??0)};});}
  async snapshot(p:Principal,boardId:string,epoch:number,seq:number){const state=await this.collaboration.load(p,boardId);if(state.epoch!==epoch||state.seq!==seq)throw new WhiteboardRecoveryError("STALE_HEAD");return state.update;}
  async saveCheckpoint(p:Principal,manifest:WhiteboardCheckpointManifest,requestId:string,event:WhiteboardCollaborationEvent){return this.db.withTenant(p.orgId,async session=>{const access=await this.access(session,p,manifest.boardId);const replay=await session.query<{manifest:unknown}>(`SELECT manifest FROM whiteboard_checkpoints WHERE org_id=$1 AND board_id=$2 AND actor_id=$3 AND request_id=$4`,[p.orgId,manifest.boardId,p.userId,requestId]);if(replay.rows[0])return{manifest:disclose(manifest.boardId,access.role,"write",replay.rows[0]).manifest as WhiteboardCheckpointManifest,replayed:true};await session.query(`INSERT INTO whiteboard_checkpoints(org_id,board_id,checkpoint_id,actor_id,request_id,manifest) VALUES($1,$2,$3,$4,$5,$6::jsonb)`,[p.orgId,manifest.boardId,manifest.checkpointId,p.userId,requestId,JSON.stringify(manifest)]);await session.query(`INSERT INTO whiteboard_collaboration_events(org_id,board_id,event_id,actor_id,event_type,payload) VALUES($1,$2,$3,$4,$5,$6::jsonb)`,[p.orgId,manifest.boardId,event.eventId,p.userId,event.type,JSON.stringify(event)]);return{manifest,replayed:false};});}
  async getCheckpoint(p:Principal,boardId:string,checkpointId:string){return this.db.withTenant(p.orgId,async session=>{const access=await this.access(session,p,boardId);const result=await session.query<{manifest:unknown}>(`SELECT manifest FROM whiteboard_checkpoints WHERE org_id=$1 AND board_id=$2 AND checkpoint_id=$3`,[p.orgId,boardId,checkpointId]),row=disclose(boardId,access.role,"read",result.rows[0]);return(row?.manifest as WhiteboardCheckpointManifest|undefined)??null;});}
  async findCheckpointRequest(p:Principal,boardId:string,requestId:string){return this.db.withTenant(p.orgId,async session=>{const access=await this.access(session,p,boardId);const result=await session.query<{manifest:unknown}>(`SELECT manifest FROM whiteboard_checkpoints WHERE org_id=$1 AND board_id=$2 AND actor_id=$3 AND request_id=$4`,[p.orgId,boardId,p.userId,requestId]),row=disclose(boardId,access.role,"read",result.rows[0]);return(row?.manifest as WhiteboardCheckpointManifest|undefined)??null;});}
  async findRestore(p:Principal,boardId:string,requestId:string){return this.db.withTenant(p.orgId,async session=>{const access=await this.access(session,p,boardId);const result=await session.query<{response:RestoreResponse}>(`SELECT response FROM whiteboard_restore_requests WHERE org_id=$1 AND board_id=$2 AND actor_id=$3 AND request_id=$4`,[p.orgId,boardId,p.userId,requestId]),row=disclose(boardId,access.role,"read",result.rows[0]);return row?.response?normalizeRestore(row.response):null;});}
  async recoveryCandidates(p:Principal,boardId:string,epoch:number,beforeSeq:number){return this.db.withTenant(p.orgId,async session=>{const access=await this.access(session,p,boardId);const result=await session.query<{manifest:unknown}>(`SELECT manifest FROM whiteboard_checkpoints WHERE org_id=$1 AND board_id=$2 AND (manifest->>'epoch')::integer=$3 AND (manifest->>'seq')::bigint<$4 ORDER BY (manifest->>'seq')::bigint DESC,created_at DESC`,[p.orgId,boardId,epoch,beforeSeq]);return disclose(boardId,access.role,"read",result.rows).map(row=>WhiteboardCheckpointManifest.parse(row.manifest));});}
  async updatesBetween(p:Principal,boardId:string,epoch:number,afterSeq:number,throughSeq:number){return this.db.withTenant(p.orgId,async session=>{const access=await this.access(session,p,boardId);const result=await session.query<{seq:string;update:Buffer}>(`SELECT seq,update FROM whiteboard_updates WHERE org_id=$1 AND board_id=$2 AND epoch=$3 AND seq>$4 AND seq<=$5 ORDER BY seq`,[p.orgId,boardId,epoch,afterSeq,throughSeq]);return disclose(boardId,access.role,"read",result.rows).map(row=>({seq:Number(row.seq),update:new Uint8Array(row.update)}));});}
  async commitRestore(p:Principal,input:Parameters<WhiteboardRecoveryMetadata["commitRestore"]>[1]){return this.db.withTenant(p.orgId,async session=>{const access=await this.access(session,p,input.boardId);if(access.role!=="owner"||access.archived)throw new WhiteboardRecoveryError("FORBIDDEN");const replay=await session.query<{response:RestoreResponse}>(`SELECT response FROM whiteboard_restore_requests WHERE org_id=$1 AND board_id=$2 AND actor_id=$3 AND request_id=$4`,[p.orgId,input.boardId,p.userId,input.requestId]);if(replay.rows[0])return{...normalizeRestore(disclose(input.boardId,access.role,"write",replay.rows[0]).response),replayed:true};const doc=await session.query<{epoch:number;seq:string}>(`SELECT epoch,seq FROM whiteboard_documents WHERE org_id=$1 AND board_id=$2 FOR UPDATE`,[p.orgId,input.boardId]),head=disclose(input.boardId,access.role,"write",doc.rows[0]);if(head?.epoch!==input.expectedEpoch||Number(head?.seq)!==input.expectedSeq)throw new WhiteboardRecoveryError("STALE_HEAD");await session.query(`UPDATE whiteboard_documents SET epoch=$3,seq=0,snapshot=$4,updated_at=now() WHERE org_id=$1 AND board_id=$2`,[p.orgId,input.boardId,input.newEpoch,Buffer.from(input.snapshot)]);for(const audit of [...input.auditEvents,input.event])await session.query(`INSERT INTO whiteboard_collaboration_events(org_id,board_id,event_id,actor_id,event_type,payload) VALUES($1,$2,$3,$4,$5,$6::jsonb)`,[p.orgId,input.boardId,audit.eventId,p.userId,audit.type,JSON.stringify(audit)]);const response={epoch:input.newEpoch,seq:0 as const,event:input.event,auditEvents:input.auditEvents};await session.query(`INSERT INTO whiteboard_restore_requests(org_id,board_id,actor_id,request_id,response) VALUES($1,$2,$3,$4,$5::jsonb)`,[p.orgId,input.boardId,p.userId,input.requestId,JSON.stringify(response)]);return{epoch:response.epoch,seq:response.seq,replayed:false,auditEvents:response.auditEvents};});}
}
