'use client';
import { useState } from 'react';
import { MoreHorizontal } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from '@/components/ui/dropdown-menu';
export type Tag = { id: string; name: string };
export function BoardMenu({ id, name, onAction }: { id: string; name: string; onAction: (action: 'rename' | 'tags' | 'duplicate' | 'delete') => void }) {
 return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className="h-12 w-12" aria-label={`${name}的更多操作`} data-testid={`workspace-menu-${id}`}><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end">{(['rename', 'tags', 'duplicate', 'delete'] as const).map(action => <DropdownMenuItem key={action} data-testid={`workspace-${action}-${id}`} onSelect={() => onAction(action)}>{({ rename: '重命名', tags: '编辑标签', duplicate: '复制画板', delete: '删除画板' })[action]}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>;
}
export function TagManager({ tags, selected, onToggle, onChange, onDelete, onClose }: { tags: Tag[]; selected?: string[]; onToggle?: (id: string) => void; onChange: (tag: Tag) => void; onDelete: (id: string) => void; onClose: () => void }) {
 const [editing, setEditing] = useState<string | null>(null); const [name, setName] = useState(''); const [error, setError] = useState(''); const [deleting, setDeleting] = useState<string | null>(null);
 const save = () => { const trimmed = name.trim(); if (!trimmed || tags.some(t => t.id !== editing && t.name.toLocaleLowerCase() === trimmed.toLocaleLowerCase())) { setError('请输入不重复的标签名称'); return; } onChange({ id: editing || crypto.randomUUID(), name: trimmed }); setName(''); setEditing(null); setError(''); };
 return <Dialog open onOpenChange={value => { if (!value) onClose(); }}><DialogContent data-testid="workspace-tags-dialog"><DialogHeader><DialogTitle>{selected ? '画板标签' : '管理标签'}</DialogTitle><DialogDescription>{selected ? '选择标签绑定到当前画板。标签名称修改对所有画板生效。' : '创建和整理当前页面的标签。刷新会重置演示数据。'}</DialogDescription></DialogHeader><div className="max-h-64 overflow-auto">{tags.map(tag => <div key={tag.id} className="flex flex-wrap items-center gap-2 border-b py-2">{onToggle ? <Button variant={selected?.includes(tag.id) ? 'secondary' : 'outline'} aria-pressed={selected?.includes(tag.id)} data-testid={`workspace-bind-${tag.id}`} className="min-h-12" onClick={() => onToggle(tag.id)}>{tag.name}</Button> : <span className="mr-auto">{tag.name}</span>}<Button variant="ghost" data-testid={`workspace-tag-rename-${tag.id}`} onClick={() => { setEditing(tag.id); setName(tag.name); }}>重命名</Button><Button variant="ghost" data-testid={`workspace-tag-delete-${tag.id}`} onClick={() => setDeleting(tag.id)}>删除</Button>{deleting === tag.id && <div className="w-full rounded-lg bg-muted p-3"><p>删除“{tag.name}”会从所有画板解绑，不删除画板内容。</p><Button data-testid="workspace-tag-delete-confirm" variant="destructive" onClick={() => { onDelete(tag.id); setDeleting(null); }}>确认删除标签</Button><Button data-testid="workspace-tag-delete-cancel" variant="ghost" onClick={() => setDeleting(null)}>取消</Button></div>}</div>)}</div><Input aria-label="标签名称" data-testid="workspace-tag-name" maxLength={40} value={name} onChange={e => setName(e.target.value)} /><Button data-testid="workspace-tag-save" onClick={save}>{editing ? '保存标签名称' : '新建标签'}</Button>{error && <p role="alert">{error}</p>}<Button data-testid="workspace-tags-done" variant="outline" onClick={onClose}>完成</Button></DialogContent></Dialog>;
}
