'use client';
import { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import { ArrowLeft, Plus, Search, MousePointer2, StickyNote, Shapes, Pencil, MoveUpRight, Trash2, PenLine } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import type { Tool } from './canvas';
const Surface = dynamic(() => import('./canvas').then(m => m.WorkspaceCanvas), { ssr: false });
const colors = ['#fff1a8', '#f8c9dc', '#d8e8ff', '#d4edd8', '#292929'] as const;
const tools = [{ id: 'select', label: '选择', icon: MousePointer2 }, { id: 'sticky', label: '便利贴', icon: StickyNote }, { id: 'shape', label: '图形', icon: Shapes }, { id: 'draw', label: '画笔', icon: Pencil }, { id: 'connector', label: '连线', icon: MoveUpRight }] as const;
type Board = { id: string; name: string; detail: string };
const initial: Board[] = [{ id: 'one', name: '团队创意工作坊', detail: '今天更新' }, { id: 'two', name: '新产品体验地图', detail: '昨天更新' }, { id: 'three', name: '下一季，我们一起做什么？', detail: '3 天前更新' }, { id: 'four', name: '研究发现与用户声音', detail: '上周更新' }];
export function BoardWorkspacePreview() {
  const [state, setState] = useState('default'); const [boards, setBoards] = useState(initial); const [active, setActive] = useState<Board | null>(null); const [query, setQuery] = useState('');
  const [tool, setTool] = useState<Tool>('select'); const [color, setColor] = useState<string>(colors[0]); const [shape, setShape] = useState('rounded'); const [width, setWidth] = useState(4);
  const [modal, setModal] = useState<'create' | 'rename' | 'delete' | null>(null); const [target, setTarget] = useState<Board | null>(null); const [name, setName] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { const s = new URLSearchParams(window.location.search).get('state') || 'default'; setState(s); if (s === 'empty') setBoards([]); if (s === 'readonly' || s === 'editor') setActive(initial[0] ?? null); if (s === 'validation') { setModal('create'); setError('请输入画板名称'); } if (s === 'success') setNotice('画板已创建（演示）'); }, []);
  const readonly = state === 'readonly';
  const open = (action: 'create' | 'rename' | 'delete', board?: Board) => { setTarget(board || null); setName(board?.name || ''); setError(''); setModal(action); };
  const save = () => { if (modal !== 'delete' && !name.trim()) { setError('请输入画板名称'); return; } if (modal === 'create') setBoards(b => [{ id: crypto.randomUUID(), name: name.trim(), detail: '刚刚更新' }, ...b]); if (modal === 'rename') setBoards(b => b.map(item => item.id === target?.id ? { ...item, name: name.trim() } : item)); if (modal === 'delete') setBoards(b => b.filter(item => item.id !== target?.id)); setNotice(modal === 'delete' ? '已从演示列表删除' : '画板已更新（演示）'); setModal(null); };
  return <main className="min-h-screen bg-background text-foreground" data-testid="board-workspace-preview">
    <style>{`.board-dock-tool{transition:transform 180ms ease,background 180ms ease}.board-dock-tool:hover{transform:translateY(-4px)}.board-dock-tool[aria-pressed=true]{transform:translateY(-6px)}@media(prefers-reduced-motion:reduce){.board-dock-tool{transition:none!important;transform:none!important}}`}</style>
    {active ? <section className="fixed inset-0 bg-background" data-testid="workspace-editor">
      <Surface options={{ tool, color, shape, width, readonly }} />
      <header className="absolute left-3 right-3 top-3 flex items-center justify-between gap-2 rounded-xl border bg-background/95 p-2 shadow-sm">
        <div className="flex min-w-0 items-center gap-2"><Button variant="ghost" className="h-12 w-12 shrink-0" aria-label="返回画板浏览" data-testid="workspace-back" onClick={() => setActive(null)}><ArrowLeft /></Button><div className="min-w-0"><h1 className="truncate font-semibold">{active.name}</h1><p className="text-xs text-muted-foreground">{readonly ? '只读预览' : '交互预览 · 刷新后重置'}</p></div></div><span className="hidden pr-3 text-sm text-muted-foreground sm:block">一起把想法画出来</span>
      </header>
      <div className="absolute bottom-6 left-1/2 z-10 w-max max-w-full -translate-x-1/2 px-2" data-testid="workspace-dock">
        {tool !== 'select' && !readonly && <div className="mb-5 flex flex-wrap items-center justify-center gap-2 rounded-2xl border bg-background p-3 shadow-lg" role="group" aria-label="工具选项" data-testid="workspace-tool-options">
          {colors.map((value, index) => <Button key={value} aria-label={`颜色 ${index + 1}`} aria-pressed={color === value} data-testid={`workspace-color-${index}`} variant="outline" className="h-12 w-12 rounded-full p-2" onClick={() => setColor(value)}><span className="h-7 w-7 rounded-full border" style={{ background: value }} /></Button>)}
          {tool === 'shape' && ['rectangle', 'rounded', 'circle'].map(value => <Button data-testid={`workspace-shape-${value}`} key={value} variant={shape === value ? 'primary' : 'outline'} className="h-12" onClick={() => setShape(value)}>{value === 'circle' ? '圆形' : value === 'rounded' ? '圆角' : '矩形'}</Button>)}
          {(tool === 'draw' || tool === 'connector') && [2, 4, 8].map(value => <Button data-testid={`workspace-width-${value}`} key={value} aria-label={`线宽 ${value}`} variant={width === value ? 'primary' : 'outline'} className="h-12 w-12" onClick={() => setWidth(value)}><span className="w-6 rounded-full bg-current" style={{ height: value }} /></Button>)}
          {tool === 'connector' && <Button data-testid="workspace-connector-style" className="h-12" variant="outline" onClick={() => setShape(shape === 'dashed' ? 'straight' : 'dashed')}>{shape === 'dashed' ? '虚线' : '实线'}</Button>}
        </div>}
        <div className="flex items-end justify-center gap-1 rounded-2xl border bg-background px-2 py-3 shadow-xl" role="toolbar" aria-label="白板工具">
          {tools.map(({ id, label, icon: Icon }) => <Button key={id} disabled={readonly && id !== 'select'} aria-pressed={tool === id} aria-label={label} data-testid={`workspace-tool-${id}`} variant={tool === id ? 'secondary' : 'ghost'} className="board-dock-tool flex h-16 min-w-12 flex-col gap-1 rounded-xl px-3 sm:min-w-16" onClick={() => { setTool(id); if (id === 'draw' || id === 'connector') setColor(colors[4]); }}><Icon className="h-7 w-7" /><span className="text-xs">{label}</span></Button>)}
        </div><p className="mt-2 text-center text-xs text-muted-foreground">{readonly ? '只读模式，无法编辑' : tool === 'connector' ? '在画布上拖动，画出连线' : tool === 'draw' ? '在画布上拖动画笔' : tool === 'select' ? '拖动选择 · 双击文字编辑' : '轻触画布，放下一个新想法'}</p>
      </div>
    </section> : <div className="mx-auto max-w-6xl px-5 py-12 sm:px-10">
      <header className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-3xl font-semibold">画板</h1><p className="mt-2 text-muted-foreground">从一个想法开始，和团队一起展开。</p></div><Button className="h-12 gap-2" data-testid="workspace-create" onClick={() => open('create')}><Plus />新建画板</Button></header>
      <p className="mb-5 rounded-lg bg-muted px-4 py-2 text-sm text-muted-foreground">交互预览：数据仅保留在当前页面，刷新重置。尚未连接保存与多人协作。</p>
      <div className="relative mb-8 max-w-sm"><Search className="absolute left-3 top-3 h-5 w-5 text-muted-foreground" /><Input className="h-12 pl-10" aria-label="搜索画板" data-testid="workspace-search" placeholder="搜索画板" value={query} onChange={e => setQuery(e.target.value)} /></div>
      {notice && <p role="status" className="mb-4 text-sm" data-testid="workspace-success">{notice}</p>}
      {state === 'loading' ? <div data-testid="loading" role="status" className="grid gap-5 sm:grid-cols-2">{[1,2,3,4].map(i => <div key={i} className="h-56 animate-pulse rounded-xl bg-muted motion-reduce:animate-none" />)}<span className="sr-only">正在加载画板</span></div> : state === 'error' ? <div role="alert" data-testid="err-dependency" className="rounded-xl border p-8"><h2>画板暂时无法加载</h2><p className="my-3 text-muted-foreground">请重试，现有画板不会丢失。</p><Button data-testid="workspace-retry" onClick={() => setState('default')}>重试</Button></div> : state === 'forbidden' ? <p data-testid="workspace-forbidden">你没有访问这些画板的权限，请联系管理员。</p> : <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3" data-testid="workspace-board-grid">
        {boards.filter(b => b.name.includes(query)).map((board, index) => <article className="overflow-hidden rounded-xl border" key={board.id}>
          <button className="block w-full bg-muted/40 p-5 text-left transition-colors hover:bg-muted focus-visible:ring-2 focus-visible:ring-ring" data-testid={`workspace-open-${board.id}`} onClick={() => setActive(board)} aria-label={`打开 ${board.name}`}><div className="relative h-32" aria-hidden="true"><span className="absolute left-2 top-2 h-20 w-20 rotate-6 shadow-sm" style={{ background: colors[index % 4] }} /><span className="absolute left-24 top-8 h-20 w-24 -rotate-3 shadow-sm" style={{ background: colors[(index + 1) % 4] }} /><span className="absolute left-8 top-8 text-sm">灵感</span><span className="absolute left-28 top-14 text-sm">下一步</span></div><h2 className="mt-3 truncate font-semibold">{board.name}</h2><p className="mt-1 text-xs text-muted-foreground">{board.detail}</p></button>
          <div className="flex justify-end gap-1 border-t px-2"><Button variant="ghost" className="h-12 w-12" data-testid={`workspace-rename-${board.id}`} aria-label={`重命名 ${board.name}`} onClick={() => open('rename', board)}><PenLine className="h-4 w-4" /></Button><Button variant="ghost" className="h-12 w-12" data-testid={`workspace-delete-${board.id}`} aria-label={`删除 ${board.name}`} onClick={() => open('delete', board)}><Trash2 className="h-4 w-4" /></Button></div>
        </article>)}
        {!boards.filter(b => b.name.includes(query)).length && <div data-testid="empty" className="col-span-full rounded-xl border border-dashed p-12 text-center"><h2 className="font-semibold">{query ? '没有找到匹配的画板' : '第一张画板，从这里开始'}</h2><p className="mt-2 text-muted-foreground">{query ? '试试其他关键词。' : '创建画板，放下你的第一个想法。'}</p></div>}
      </div>}
    </div>}
    <Dialog open={modal !== null} onOpenChange={value => { if (!value) setModal(null); }}><DialogContent data-testid="workspace-dialog"><DialogHeader><DialogTitle>{modal === 'delete' ? '删除这张画板？' : modal === 'rename' ? '重命名画板' : '新建画板'}</DialogTitle><DialogDescription>{modal === 'delete' ? `将从演示列表删除“${target?.name}”。此预览不删除服务器数据，刷新即可恢复。` : '给团队一个容易找到的名字。此操作仅用于预览。'}</DialogDescription></DialogHeader>{modal !== 'delete' && <Input data-testid="workspace-name" aria-label="画板名称" maxLength={120} value={name} onChange={e => setName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.nativeEvent.isComposing) save(); }} />}{error && <p role="alert" data-testid="err-form" className="text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button data-testid="workspace-cancel" variant="outline" className="h-12" onClick={() => setModal(null)}>取消</Button><Button data-testid="workspace-confirm" variant={modal === 'delete' ? 'destructive' : 'primary'} className="h-12" onClick={save}>{modal === 'delete' ? '确认删除' : '保存'}</Button></div></DialogContent></Dialog>
  </main>;
}
