/** Only synthetic material; this lane never selects an existing user attachment. */
export const SKILL_BATCH_SCENARIOS = {
 S001:{stableName:'knowledge-grounded-answer',packId:'standard-context',inputName:'policy.txt',input:'合成政策 AX-17：试用期为14天。退款规则尚未确定。\nSynthetic policy AX-17: trial lasts 14 days. Refund policy is undecided.\n',output:'answer.md',prompt:'根据当前线程授权资料回答AX-17试用多久、能否退款。请选择适合的技能，实际搜索和读取知识来源，保留来源ID和原句，未知不得编造。生成answer.md并发布。'},
 S002:{stableName:'web-research',packId:'standard-web',inputName:'research.txt',input:'Research topic: official LangChain overview. No private information.\n',output:'research.md',prompt:'研究LangChain官方资料中LangGraph和Deep Agents的关系。请选择适合的技能，实际搜索并读取官方网页，区分引用与推断，生成research.md并发布。'},
 S003:{stableName:'docx-create',packId:'office',inputName:'brief.txt',input:'合成项目晨星：目标是测试文档。里程碑：需求确认、原型验证。预算未知。\nSynthetic project Morning Star: document testing. Milestones: confirm requirements; validate prototype. Budget unknown.\n',output:'report.docx',prompt:'按附件合成项目简报生成中英双语两页Word文档report.docx，页眉为晨星测试，包含里程碑表格和预算未知说明。选择适合技能，实际渲染并验证文件。发布原件及PDF/页面PNG预览，不能把未知预算编造为数字。'},
 S004:{stableName:'xlsx-create',packId:'office',inputName:'sales.csv',input:'team,amount\nA,10\nA,20\nB,12\n',output:'sales.xlsx',prompt:'根据附件合成CSV创建sales.xlsx，中英双语表头；保存3条原始记录、按团队汇总A=30和B=12，总计42必须有SUM公式并保存正确缓存结果。选择适合技能，实际渲染及验证，发布工作簿和预览。'},
 S005:{stableName:'pptx-create',packId:'office',inputName:'brief.txt',input:'合成项目晨星：目标是测试演示。事实：3次实验，2次通过，1次待复核。没有预算和交付日期。\nSynthetic Morning Star: 3 experiments; 2 passed; 1 awaiting review. No budget or delivery date.\n',output:'slides.pptx',prompt:'根据附件合成资料创建3页中英双语slides.pptx：目标、实验结果、下一步。2次通过和1次待复核不能写成全部成功；预算和交付日期未知。选择适合技能，实际渲染核验，发布PPTX及PDF/页面PNG。'},
 S006:{stableName:'pdf-create',packId:'office',inputName:'brief.txt',input:'合成PDF第一页：ALPHA 中文甲。第二页：BETA 中文乙。第三页：GAMMA 中文丙。\n',output:'selected.pdf',prompt:'选择PDF技能，先按附件创建3页source.pdf，再用包内已有PDF页选择脚本只保留第1和第3页为selected.pdf。确保中文可读且BETA不在选中PDF中，实际读回/渲染验证，发布selected.pdf和页面PNG。不声称进行了安全涂黑。'},
 S007:{stableName:'data-analysis',packId:'data-workflows',inputName:'data.csv',input:'team,amount\nA,10\nA,20\nB,12\nB,\nA,10\n',output:'analysis.md',prompt:'分析附件合成CSV，选择适合技能。共有5条记录、1个金额空值、1条完全重复记录；不得无依据删除重复行。按保留重复且金额空值不计的口径，A合计40、B合计12、总计52。实际执行计算并保存可复跑代码和结果表；说明分母与缺失值，不推断因果。生成analysis.md并发布报告、代码和结果。'},
 S008:{stableName:'meeting-preparation',packId:'standard-context',inputName:'meeting.txt',input:'合成会议准备：晨星项目要讨论原型验证方案。已知风险是样本只有3人，预算和会议时间未确定。\nSynthetic meeting: discuss prototype validation. Sample size is 3. Budget and meeting time unknown.\n',output:'preparation.md',prompt:'为附件合成晨星项目准备原型验证会议，选择适合技能。从当前线程授权知识搜索读取事实，形成背景、目标、议程、关键问题与待补项，引用真实来源ID；预算、时间未知，不编造参会人，不发送邀请。生成preparation.md并发布。'},
} as const;
export type SkillBatchId=keyof typeof SKILL_BATCH_SCENARIOS;
