const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {verifyPlan,probe}=require('./cn-bootstrap-baseline.cjs');
const h=x=>crypto.createHash('sha256').update(x).digest('hex'),j=x=>h(JSON.stringify(x));
const source='a'.repeat(40),baseline='b'.repeat(40),now=Date.now(),old=Buffer.from('CREATE TABLE agents(id text);'),next=Buffer.from('CREATE TABLE candidate_fields(answer_spans jsonb);');
const files={'old.sql':old,'next.sql':next},oldFiles={'old.sql':old};
function plan(){const ledger=[{name:'old.sql',checksum:h(old)}],pending=[{name:'next.sql',checksum:h(next),risk:'additive'}],inventory=Object.entries(files).sort(([a],[b])=>a<b?-1:1).map(([name,b])=>({name,checksum:h(b)}));const body={schemaVersion:1,targetSha:source,baselineSha:baseline,baselineLedgerSha256:j(ledger),sourceInventorySha256:j(inventory),pendingSha256:j(pending.map(({name,checksum})=>({name,checksum}))),snapshotEvidence:{snapshotSha256:'c'.repeat(64),sourceBindingSha256:'d'.repeat(64),fullResponseSha256:'e'.repeat(64),ledgerSha256:j(ledger),independentSqlCount:1,capturedAt:new Date(now).toISOString()},ledger,pending,drift:[],blockers:[],ready:true,scope:'read-only-plan',productionMigrationAuthorized:false};return {...body,planSha256:j(body)};}
function client(options={}){const queries=[];return {queries,async query(sql){queries.push(sql);if(sql.startsWith('SHOW'))return {rows:[{transaction_read_only:options.guard??'on'}]};if(sql.includes('pg_roles'))return {rows:[{unsafe:options.unsafe??false}]};if(sql.startsWith('SELECT name'))return {rows:options.rows??plan().ledger};if(sql.includes('pg_class'))return {rows:[{unsafe:false}]};return {rows:[]};}};}
test('old schema without candidate fields admits only build against exact plan',async()=>{const db=client();const result=await probe(db,plan(),source,baseline,files,oldFiles,async()=>({baselineSchemaContract:true,schemaSha256:'d'.repeat(64)}));assert.equal(result.buildAdmissionOnly,true);assert.equal(result.candidateSchemaContract,false);assert.equal(db.queries.some(x=>x.includes('answer_spans')),false);assert.equal(db.queries.at(-1),'ROLLBACK');assert.equal(db.queries[0],'BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY');});
test('baseline source checksum drift rejects',async()=>assert.rejects(probe(client(),plan(),source,baseline,files,{'old.sql':Buffer.from('changed')}),/BASELINE_SCHEMA/));
test('unsafe role rejects and rolls back',async()=>{const db=client({unsafe:true});await assert.rejects(probe(db,plan(),source,baseline,files,oldFiles,async()=>({baselineSchemaContract:true,schemaSha256:'d'.repeat(64)})),/PERMISSION/);assert.equal(db.queries.at(-1),'ROLLBACK');});
test('ledger drift rejects and rolls back',async()=>assert.rejects(probe(client({rows:[]}),plan(),source,baseline,files,oldFiles,async()=>({baselineSchemaContract:true,schemaSha256:'d'.repeat(64)})),/LEDGER_DRIFT/));
test('read-only guard rejects',async()=>assert.rejects(probe(client({guard:'off'}),plan(),source,baseline,files,oldFiles,async()=>({baselineSchemaContract:true,schemaSha256:'d'.repeat(64)})),/READ_ONLY/));
for(const [label,change] of [['hash',p=>p.planSha256='f'.repeat(64)],['target',p=>p.targetSha=baseline],['baseline',p=>p.baselineSha=source],['write approval',p=>p.productionMigrationAuthorized=true],['expired snapshot',p=>p.snapshotEvidence.capturedAt=new Date(now-3600001).toISOString()],['blocked risk',p=>{p.ready=false;p.blockers=['pending_destructive:next.sql'];}],['missing snapshot',p=>delete p.snapshotEvidence]])test(`reject ${label} before SQL`,async()=>{const p=plan();change(p);if(label!=='hash'){const {planSha256,...body}=p;p.planSha256=j(body);}const db=client();await assert.rejects(probe(db,p,source,baseline,files,oldFiles,async()=>({baselineSchemaContract:true,schemaSha256:'d'.repeat(64)})));assert.deepEqual(db.queries,[]);});
const {candidateEnvironment}=require('./cn-bootstrap-baseline.cjs');
const env={PGDATABASE:'workspacex',PGHOST:'private-endpoint',PGSSLMODE:'verify-full',PGSSLROOTCERT:'/run/certs/ca.pem',APP_DB_PASSWORD:'fixture-only'};
function target(){return {schemaVersion:1,scope:'isolated-post-migration',attemptId:'attempt',sourceSha:source,baselineSha:baseline,migrationPlanSha256:plan().planSha256,imageDigest:'sha256:'+'f'.repeat(64),database:'wsx_shadow_'+source.slice(0,12)+'_'+h('attempt').slice(0,16),issuedAt:new Date(now).toISOString(),expiresAt:new Date(now+3600000).toISOString()};}
test('candidate probe selects isolated migrated DB, preserves endpoint and credentials',()=>{const t=target(),result=candidateEnvironment(t,plan(),env,source,baseline,t.imageDigest,'attempt',now);assert.equal(result.PGHOST,env.PGHOST);assert.equal(result.APP_DB_PASSWORD,env.APP_DB_PASSWORD);assert.notEqual(result.PGDATABASE,env.PGDATABASE);});
for(const [name,change] of [['production DB',t=>t.database='workspacex'],['unbound plan',t=>t.migrationPlanSha256='e'.repeat(64)],['wrong image',t=>t.imageDigest='sha256:'+'e'.repeat(64)],['expired',t=>t.expiresAt=new Date(now).toISOString()],['override endpoint',t=>t.PGHOST='other']])test('reject candidate '+name,()=>{const t=target();change(t);assert.throws(()=>candidateEnvironment(t,plan(),env,source,baseline,'sha256:'+'f'.repeat(64),'attempt',now));});

test('cross attempt target rejected',()=>assert.throws(()=>candidateEnvironment(target(),plan(),env,source,baseline,target().imageDigest,'another',now)));
