import { generateKeyPairSync, sign } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { validateEnvelope, validateDevapp, digest, collectGovernance, collectDevapp, evidenceWindow } from './cn-controlled-evidence.mjs';
import { validateGovernanceReceipt } from './cn-frozen-release-identity.mjs';
const source='a'.repeat(40),attempt='gha-123-1',now=Date.parse('2026-10-01T00:30:00Z');
const key=generateKeyPairSync('ed25519');
const wrap=(v:any)=>{const b=Buffer.from(JSON.stringify(v));return {payload:b.toString('base64'),signature:sign(null,b,key.privateKey).toString('base64')}};
const envelopeValue=(kind='devapp')=>({schemaVersion:1,kind,repository:'boardx/workspacex',sourceSha:source,attemptId:attempt,observedAt:'2026-10-01T00:00:00Z',expiresAt:'2026-10-01T01:00:00Z'});
const raw=()=>({run:{id:123,run_attempt:2,repository:{full_name:'boardx/workspacex'},head_repository:{full_name:'boardx/workspacex'},path:'.github/workflows/real-model-chat-evidence.yml',head_sha:source,status:'completed',conclusion:'success',created_at:'2026-10-01T00:00:00Z',run_started_at:'2026-10-01T00:00:00Z'},artifact:{created_at:'2026-10-01T00:10:00Z',name:'real-model-chat-evidence',expired:false,workflow_run:{id:123,head_sha:source},digest:'sha256:'+digest(Buffer.from('archive'))},archive:Buffer.from('archive').toString('base64'),browser:{context:{generatedAt:'2026-10-01T00:05:00Z',lane:'devapp',baseUrl:'https://devapp.boardx.us',threadId:'real-thread',runStartObserved:true},assertions:[...'①②③④⑤⑥⑦⑧'].map(name=>({name,ok:true})),pageErrors:[]},runtime:Object.fromEntries(['api','web','agent','sandbox'].map(k=>[k,{running:true,sourceSha:source,imageId:'sha256:'+'b'.repeat(64),containerId:k,startedAt:'2026-09-30T00:00:00Z'}]))});
describe('controlled signed evidence boundary',()=>{
 it('verifies pinned signature with exact attempt/source and one-hour TTL',()=>{const e=wrap(envelopeValue());expect(validateEnvelope(e,key.publicKey,source,attempt,'devapp',now).sourceSha).toBe(source);for(const [s,a,k,t] of [['b'.repeat(40),attempt,'devapp',now],[source,'other','devapp',now],[source,attempt,'governance',now],[source,attempt,'devapp',now+3600000]] as any[])expect(()=>validateEnvelope(e,key.publicKey,s,a,k,t)).toThrow();expect(()=>validateEnvelope({...e,payload:wrap({...envelopeValue(),sourceSha:'b'.repeat(40)}).payload},key.publicKey,source,attempt,'devapp',now)).toThrow();expect(()=>validateEnvelope(e,generateKeyPairSync('ed25519').publicKey,source,attempt,'devapp',now)).toThrow()});
 it('derives acceptance only from run, artifact bytes, complete browser and running service evidence',()=>{expect(validateDevapp(raw(),source).browserAccepted).toBe(true);for(const mutate of [(r:any)=>r.run.conclusion='failure',(r:any)=>r.run.head_sha='b'.repeat(40),(r:any)=>r.artifact.workflow_run.id=122,(r:any)=>r.archive='tampered',(r:any)=>r.browser.assertions.pop(),(r:any)=>r.browser.assertions[5].ok=false,(r:any)=>r.browser.pageErrors.push({}),(r:any)=>r.runtime.api.sourceSha='b'.repeat(40),(r:any)=>r.runtime.web.running=false,(r:any)=>r.runtime.agent.startedAt='2026-10-01T00:01:00Z']){const r=raw();mutate(r);expect(()=>validateDevapp(r,source)).toThrow()}});
 it('reads inherited organization rules at their owner and refuses invisible bypass actors',()=>{const called:string[]=[];const summaries=[{id:4,target:'tag',enforcement:'active',source_type:'Organization',source:'boardx'}];const read=(p:string)=>{called.push(p);return p.includes('rulesets')?{bypass_actors:[]}:{}},list=(p:string)=>p.includes('rulesets')?summaries:[];collectGovernance(read,list);expect(called).toContain('orgs/boardx/rulesets/4');expect(()=>collectGovernance(()=>({}),list)).toThrow('CONTROLLED_RULE_WRITE_VISIBILITY_REQUIRED');expect(()=>collectGovernance(read,()=>[{...summaries[0],source:'other'}])).toThrow()});
 it('executes controlled collector with mocked API/runtime and refuses corrupted archive or changed runtime',()=>{
  const fixture=raw();let corrupt=false,wrongRuntime=false;
  const ports={api:()=>fixture.run,pages:()=>[fixture.artifact],protectedRead:()=>Buffer.from(JSON.stringify({containers:Object.fromEntries(['api','web','agent','sandbox'].map(k=>[k,k]))})),exec:(cmd:string,args:string[])=>{
   if(cmd==='gh')return Buffer.from(corrupt?'wrong':'archive');
   if(cmd==='unzip'){const name=args[2];return JSON.stringify(name==='00-context.json'?fixture.browser.context:name==='10-assertions.json'?fixture.browser.assertions:fixture.browser.pageErrors);}
   if(args[0]==='inspect')return JSON.stringify([{Id:args[1],Image:'sha256:'+'b'.repeat(64),State:{Running:true,StartedAt:'2026-09-30T00:00:00Z'}}]);
   return JSON.stringify([{Config:{Labels:{'org.opencontainers.image.revision':wrongRuntime?'b'.repeat(40):source}}}]);
  }};
  expect(validateDevapp(collectDevapp(123,source,ports),source).workflowRunAttempt).toBe(2);
  corrupt=true;expect(()=>collectDevapp(123,source,ports)).toThrow('CONTROLLED_DEVAPP_ARTIFACT');corrupt=false;wrongRuntime=true;expect(()=>collectDevapp(123,source,ports)).toThrow('CONTROLLED_DEVAPP_RUNTIME');
 });
 it('requires short-lived source/attempt binding even for root-verified governance',()=>{expect(()=>validateGovernanceReceipt(envelopeValue('governance'),{repository:'boardx/workspacex',releaseSourceSha:source,attemptId:attempt},now+3600000)).toThrow('FROZEN_RELEASE_GOVERNANCE_RECEIPT')});
});

it('captures the producer clock once so millisecond advancement cannot exceed signed TTL',()=>{let reads=0;const clock=()=>now+reads++;const times=evidenceWindow(clock);expect(reads).toBe(1);expect(Date.parse(times.expiresAt)-Date.parse(times.observedAt)).toBe(3600000);expect(validateEnvelope(wrap({...envelopeValue('governance'),...times}),key.publicKey,source,attempt,'governance',now).observedAt).toBe(times.observedAt);const longer={...times,expiresAt:new Date(Date.parse(times.expiresAt)+1).toISOString()};expect(()=>validateEnvelope(wrap({...envelopeValue('governance'),...longer}),key.publicKey,source,attempt,'governance',now)).toThrow('CONTROLLED_BINDING_OR_TTL');});
