/* Catalog-only restoration facts. Protected caller owns provider/backup bindings.
 * No production adapter, permission grant, SQL mutation, READY or row-data proof. */
'use strict';
const {createHash}=require('node:crypto');
const hash=x=>createHash('sha256').update(x).digest('hex');
const assert=(x,c)=>{if(!x)throw Error('RESTORE_CATALOG_'+c);};
const USER="n.nspname<>'information_schema' AND n.nspname !~ '^pg_'";
const acl=(field,kind,owner)=>`ARRAY(SELECT jsonb_build_object('grantee',CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END,'grantor',pg_get_userbyid(a.grantor),'privilege',a.privilege_type,'grantable',a.is_grantable) FROM aclexplode(COALESCE(${field},acldefault(${kind.startsWith('CASE')?kind:`'${kind}'`},${owner}))) a)`;
const QUERIES=Object.freeze({
 database:`SELECT pg_encoding_to_char(encoding) encoding,datcollate,datctype,pg_get_userbyid(datdba) owner,${acl('datacl','d','datdba')} acl FROM pg_database WHERE datname=current_database()`,
 namespaces:`SELECT n.nspname name,pg_get_userbyid(n.nspowner) owner,${acl('n.nspacl','n','n.nspowner')} acl FROM pg_namespace n WHERE ${USER}`,
 relations:`SELECT n.nspname schema,c.relname name,c.relkind kind,pg_get_userbyid(c.relowner) owner,c.relrowsecurity rls,c.relforcerowsecurity force_rls,${acl('c.relacl',"CASE WHEN c.relkind='S' THEN 's'::\"char\" ELSE 'r'::\"char\" END",'c.relowner')} acl FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE ${USER} AND c.relkind IN ('r','p','v','m','S','f')`,
 sequences:`SELECT n.nspname schema,c.relname name,pg_catalog.format_type(s.seqtypid,NULL) type,s.seqstart::text start,s.seqincrement::text increment,s.seqmax::text maximum,s.seqmin::text minimum,s.seqcache::text cache,s.seqcycle cycle FROM pg_sequence s JOIN pg_class c ON c.oid=s.seqrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE ${USER}`,
 functions:`SELECT n.nspname schema,p.proname name,pg_get_function_identity_arguments(p.oid) arguments,pg_get_userbyid(p.proowner) owner,p.prosecdef security_definer,p.proconfig,${acl('p.proacl','f','p.proowner')} acl FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE ${USER}`,
 policies:`SELECT n.nspname schema,c.relname relation,p.polname name,p.polcmd command,p.polpermissive permissive,ARRAY(SELECT CASE WHEN r=0 THEN 'PUBLIC' ELSE pg_get_userbyid(r) END FROM unnest(p.polroles) r) roles,pg_get_expr(p.polqual,p.polrelid) using_expression,pg_get_expr(p.polwithcheck,p.polrelid) check_expression FROM pg_policy p JOIN pg_class c ON c.oid=p.polrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE ${USER}`,
 defaultAcl:"SELECT pg_get_userbyid(d.defaclrole) owner,CASE WHEN d.defaclnamespace=0 THEN NULL ELSE n.nspname END schema,d.defaclobjtype kind,ARRAY(SELECT jsonb_build_object('grantee',CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END,'grantor',pg_get_userbyid(a.grantor),'privilege',a.privilege_type,'grantable',a.is_grantable) FROM aclexplode(d.defaclacl) a) acl FROM pg_default_acl d LEFT JOIN pg_namespace n ON n.oid=d.defaclnamespace WHERE d.defaclnamespace=0 OR (n.nspname<>'information_schema' AND n.nspname !~ '^pg_')",
 extensions:"SELECT e.extname name,e.extversion version,n.nspname schema,pg_get_userbyid(e.extowner) owner,e.extrelocatable relocatable FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace",
 roles:"SELECT rolname name,rolsuper superuser,rolinherit inherit,rolcreaterole create_role,rolcreatedb create_db,rolcanlogin login,rolreplication replication,rolbypassrls bypass_rls,rolconnlimit connection_limit,rolvaliduntil::text valid_until,rolconfig FROM pg_roles WHERE rolname=ANY($1::text[])",
 memberships:"SELECT pg_get_userbyid(m.roleid) role,pg_get_userbyid(m.member) member,pg_get_userbyid(m.grantor) grantor,m.admin_option,(to_jsonb(m)->>'inherit_option') inherit_option,(to_jsonb(m)->>'set_option') set_option FROM pg_auth_members m WHERE pg_get_userbyid(m.roleid)=ANY($1::text[]) OR pg_get_userbyid(m.member)=ANY($1::text[])",
 agePresence:"SELECT to_regclass('ag_catalog.ag_graph') IS NOT NULL graphs,to_regclass('ag_catalog.ag_label') IS NOT NULL labels",
 graphs:"SELECT g.name::text name,n.nspname namespace FROM ag_catalog.ag_graph g JOIN pg_namespace n ON n.oid=g.namespace",
 labels:"SELECT l.name::text name,g.name::text graph,l.id::text label_id,l.kind::text kind,(to_jsonb(l)-'graph'-'relation'-'name'-'id'-'kind') metadata,n.nspname relation_schema,c.relname relation_name FROM ag_catalog.ag_label l JOIN ag_catalog.ag_graph g ON g.graphid=l.graph JOIN pg_class c ON c.oid=l.relation JOIN pg_namespace n ON n.oid=c.relnamespace",
});
const identitySql="SELECT current_database() database,current_user username,current_setting('transaction_read_only') readonly,current_setting('transaction_isolation') isolation";
const sqlSha256=hash(JSON.stringify({identitySql,queries:QUERIES}));
function stable(x){if(Array.isArray(x))return x.map(stable).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));if(x&&typeof x==='object')return Object.fromEntries(Object.keys(x).sort().map(k=>[k,stable(x[k])]));return x;}
function canonical(facts){assert(facts&&typeof facts==='object'&&!Array.isArray(facts),'FACTS');const keys=['database','namespaces','relations','sequences','functions','policies','defaultAcl','extensions','roles','memberships','agePresence','graphs','labels'];assert(Object.keys(facts).sort().join('|')===keys.sort().join('|'),'FACT_SCOPE');for(const k of keys)assert(Array.isArray(facts[k]),'FACT_ROWS');assert(facts.database.length===1&&facts.agePresence.length===1,'SINGLETON');return stable(facts);}
function binding(value){assert(value&&typeof value==='object'&&['source','target'].includes(value.side),'BINDING');for(const k of ['attemptId','database','username','instanceId'])assert(typeof value[k]==='string'&&value[k].length>0,'BINDING');for(const k of ['providerBindingSha256','backupReceiptSha256','peerSha256'])assert(/^[a-f0-9]{64}$/.test(value[k]),'HASH_BINDING');assert(value.port===5432,'PORT');return stable(value);}
const configHash=rows=>rows.map(row=>{const result={...row};for(const k of ['rolconfig','proconfig'])if(k in result){result[k+'Sha256']=hash(JSON.stringify(stable(result[k])));delete result[k];}return result;});
function namedRoles(facts,seeds){const roles=new Set(seeds);const walk=x=>{if(Array.isArray(x))return x.forEach(walk);if(x&&typeof x==='object')for(const [k,v] of Object.entries(x)){if(['owner','grantee','grantor'].includes(k)&&typeof v==='string'&&v!=='PUBLIC')roles.add(v);else if(k==='roles'&&Array.isArray(v))v.filter(r=>r!=='PUBLIC').forEach(r=>roles.add(r));else walk(v);}};walk(facts);return [...roles].sort();}
/** An already authenticated pg Client is supplied by the protected caller.
 * Read transport before BEGIN and verify SQL identity inside the transaction.
 * No credentials enter output; role/function config values are digest-only. */
async function capture(client,expected,requiredRoles){const b=binding(expected);assert(Array.isArray(requiredRoles)&&requiredRoles.length>0&&requiredRoles.every(r=>typeof r==='string'&&r.length>0),'ROLE_SCOPE');const peer=client.connection?.stream;assert(peer&&hash(String(peer.remoteAddress).replace(/^::ffff:/,''))===b.peerSha256&&peer.remotePort===b.port,'TRANSPORT');let begun=false;try{await client.query('BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY');begun=true;const rows=(await client.query(identitySql)).rows;assert(rows.length===1&&rows[0].database===b.database&&rows[0].username===b.username&&rows[0].readonly==='on'&&rows[0].isolation==='repeatable read','SQL_IDENTITY');const facts={};for(const name of ['database','namespaces','relations','sequences','functions','policies','defaultAcl','extensions','agePresence'])facts[name]=configHash((await client.query(QUERIES[name])).rows);assert(facts.agePresence.length===1&&typeof facts.agePresence[0].graphs==='boolean'&&typeof facts.agePresence[0].labels==='boolean','AGE_PRESENCE');assert(facts.agePresence[0].graphs===facts.agePresence[0].labels,'AGE_PARTIAL');facts.graphs=facts.agePresence[0].graphs?(await client.query(QUERIES.graphs)).rows:[];facts.labels=facts.agePresence[0].labels?(await client.query(QUERIES.labels)).rows:[];let scope=namedRoles(facts,requiredRoles);for(let round=0;;round++){assert(round<100,'ROLE_CLOSURE_BOUND');const memberships=(await client.query(QUERIES.memberships,[scope])).rows;const next=[...new Set([...scope,...memberships.flatMap(m=>[m.role,m.member,m.grantor])])].sort();if(JSON.stringify(next)===JSON.stringify(scope)){facts.memberships=memberships;break;}scope=next;}facts.roles=configHash((await client.query(QUERIES.roles,[scope])).rows);assert(facts.roles.length===scope.length&&scope.every(r=>facts.roles.some(x=>x.name===r)),'ROLE_MISSING');const normalized=canonical(facts);await client.query('ROLLBACK');begun=false;return {schemaVersion:1,binding:b,bindingSha256:hash(JSON.stringify(b)),sqlSha256,facts:normalized,catalogSha256:hash(JSON.stringify(normalized)),readOnly:true,rollbackComplete:true};}finally{if(begun)await client.query('ROLLBACK');}}
function verifyCapture(x,expected,expectedHash){assert(x&&x.schemaVersion===1&&x.readOnly===true&&x.rollbackComplete===true&&x.sqlSha256===sqlSha256,'CAPTURE');const b=binding(expected);assert(JSON.stringify(x.binding)===JSON.stringify(b)&&x.bindingSha256===hash(JSON.stringify(b)),'CAPTURE_BINDING');const facts=canonical(x.facts);const digest=hash(JSON.stringify(facts));assert(digest===x.catalogSha256&&digest===expectedHash,'CAPTURE_HASH');return facts;}
function compare(source,target,expected){assert(expected&&expected.source.side==='source'&&expected.target.side==='target'&&expected.source.attemptId===expected.target.attemptId&&expected.source.backupReceiptSha256===expected.target.backupReceiptSha256&&expected.source.instanceId!==expected.target.instanceId,'PAIR_BINDING');const mapping=expected.databaseMapping;assert(mapping&&mapping.source===expected.source.database&&mapping.target===expected.target.database,'DATABASE_MAPPING');const s=verifyCapture(source,expected.source,expected.sourceCatalogSha256),t=verifyCapture(target,expected.target,expected.targetCatalogSha256);assert(JSON.stringify(s)===JSON.stringify(t),'MISMATCH');return {schemaVersion:1,scope:'restore-catalog-only',attemptId:expected.source.attemptId,backupReceiptSha256:expected.source.backupReceiptSha256,sourceBindingSha256:source.bindingSha256,targetBindingSha256:target.bindingSha256,sourceCatalogSha256:source.catalogSha256,targetCatalogSha256:target.catalogSha256,sqlSha256,catalogEquivalent:true,rowDataVerified:false,productionMutationAuthorized:false};}
module.exports={QUERIES,identitySql,sqlSha256,capture,compare,canonical,hash,binding};
