'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const helper=require('./role-scope-law.cjs'),copy=x=>JSON.parse(JSON.stringify(x));
const fixtures=JSON.parse(fs.readFileSync(__dirname+'/fixtures/isolated-canonical-historical/role-scope-laws.json'));
const laws={};for(const[name,law]of Object.entries(fixtures)){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.resolve(__dirname,'../../../apps/api/migrations',name))).digest('hex'),law.sqlSha256);assert.equal(crypto.createHash('sha256').update(JSON.stringify(law.body)).digest('hex'),law.lawSha256);laws[name]=law.body;}
const base={};for(const t of helper.TABLES)base[t]={columns:[{num:1,name:'id',type:'text',notnull:true,default_expr:null},{num:2,name:'org_id',type:'text',notnull:true,default_expr:null}],constraints:[{name:t+'_pkey',type:'p',validated:true,keys:[1],deferrable:false,deferred:false,local:true,inherited:0,noinherit:true,expression:null,definition:'PRIMARY KEY (id)'}],policies:[{name:'tenant',cmd:'*',permissive:true,roles:['PUBLIC'],using_expr:'org_id = current_org()',check_expr:'org_id = current_org()'},{name:'freeze',cmd:'w',permissive:false,roles:['PUBLIC'],using_expr:null,check_expr:'kernel_org_is_writable(org_id)'}],acl:[{owner:'migration_admin',enabled:true,forced:true,grantee:'app_rw',grantor:'migration_admin',privilege:'SELECT',grantable:false}],maxnum:[{maxnum:5}],legacyIds:['legacy-a','legacy-b']};
function afterCatalog(){const a=copy(base);const extra={agent_versions:{num:6,name:'pending_skill_bindings',type:'jsonb',notnull:true,default_expr:"'[]'::jsonb"},agent_runs:{num:6,name:'skill_scope',type:'text',notnull:false,default_expr:null},thread_message_queue:{num:6,name:'explicit_agent',type:'boolean',notnull:false,default_expr:null}};const checks={agent_versions:['agent_versions_pending_skill_bindings_array',"(jsonb_typeof(pending_skill_bindings) = 'array'::text)"],agent_runs:['agent_runs_skill_scope_check',"((skill_scope IS NULL) OR (skill_scope = ANY (ARRAY['agent_pins'::text, 'general'::text])))"]};for(const t of helper.TABLES){a[t].columns.push(extra[t]);a[t].maxnum=[{maxnum:6}];if(checks[t])a[t].constraints.push({name:checks[t][0],type:'c',validated:true,keys:[6],deferrable:false,deferred:false,local:true,inherited:0,noinherit:false,expression:checks[t][1],definition:'CHECK ('+checks[t][1]+')'});}return a;}
function mock(catalog,mutateRows){const calls=[];return {calls,query:async(sql,params)=>{calls.push({sql,params});const t=helper.TABLES.find(t=>sql.includes("'public."+t+"'::regclass")||sql.includes('public."'+t+'"'));assert(t,'SQL table must be one of exact three');for(const kind of ['columns','constraints','policies','acl','maxnum'])if(sql===helper.queryFor(t,kind))return {rows:copy(catalog[t][kind])};if(sql.startsWith('SELECT id::text id FROM ONLY ')){assert(sql.includes('agent_id')&&sql.includes('NOT IN')&&sql.endsWith('ORDER BY id::text LIMIT 100001'));return {rows:base[t].legacyIds.map(id=>({id}))};}assert(sql.startsWith('SELECT count(*)::text total,count(*) FILTER (WHERE '));assert(sql.endsWith('WHERE id::text=ANY($1::text[])'));assert.equal(JSON.stringify(params),JSON.stringify([base[t].legacyIds]));const column={agent_versions:'pending_skill_bindings',agent_runs:'skill_scope',thread_message_queue:'explicit_agent'}[t];assert(sql.includes(t==='agent_versions'?"pending_skill_bindings IS DISTINCT FROM '[]'::jsonb":column+' IS NOT NULL'));const rows=base[t].legacyIds.map(id=>({id,value:t==='agent_versions'?[]:null}));rows.push({id:'canonical-owned-new',value:t==='agent_versions'?['new-gap']:t==='agent_runs'?'general':true});if(mutateRows)mutateRows(t,rows);const cohort=rows.filter(r=>params[0].includes(r.id));return {rows:[{total:String(cohort.length),changed:String(cohort.filter(r=>JSON.stringify(r.value)!==JSON.stringify(t==='agent_versions'?[]:null)).length)}]};}};}
const source=fs.readFileSync(__dirname+'/conservation-engine.cjs','utf8'),bytes=fs.readFileSync(__dirname+'/role-scope-law.cjs','utf8'),digest=crypto.createHash('sha256').update(bytes).digest('hex');
function embedded(s,b){const marker='const roleScopeValidators=(function(){const module={exports:{}};\n';const start=s.indexOf(marker);assert(start>=0);assert.equal(s.slice(start+marker.length,s.indexOf('\nreturn module.exports;})();',start)),b);assert(s.includes("roleScopeValidatorSha256==='"+crypto.createHash('sha256').update(b).digest('hex')+"'"));}
embedded(source,bytes);assert.throws(()=>embedded(source,bytes+'// drift'));assert.throws(()=>embedded(source.replace('roleScopeValidatorSha256','wrongField'),bytes));
const sandbox={Buffer,TextDecoder,module:{exports:{}},process:{env:{}},require:n=>n==='pg'?{Client:class{constructor(){throw Error('NO_REAL_SQL')}}}:require(n)};vm.runInNewContext(source,sandbox);const engine=sandbox.module.exports;
(async()=>{const captureClient=mock(base);const captured=await helper.captureRoleScopeBaseline(captureClient,async t=>base[t].legacyIds.map(id=>({id})));assert.deepEqual(captured,base);const after=afterCatalog();assert((await helper.validateRoleScope(mock(after),laws,captured)).catalogLawVerified);assert((await helper.validateRoleScope(mock(after),laws,captured)).catalogLawVerified);let negatives=0;
for(const table of helper.TABLES){for(const mutate of [x=>x.columns[0].type='integer',x=>x.columns.at(-1).num=3,x=>x.columns.at(-1).type='integer',x=>x.columns.at(-1).notnull=!x.columns.at(-1).notnull,x=>x.columns.at(-1).default_expr="'fabricated'",x=>x.columns.push({name:'unreviewed'}),x=>x.maxnum[0].maxnum=7,x=>x.constraints[0].definition='CHECK (true)',x=>x.policies[0].using_expr='true',x=>x.policies[1].permissive=true,x=>x.acl[0].grantable=true,x=>x.acl[0].owner='app_rw',x=>x.acl[0].forced=false,x=>x.acl.push({...x.acl[0],grantee:'PUBLIC'})]){const bad=copy(after);mutate(bad[table]);await assert.rejects(helper.validateRoleScope(mock(bad),laws,captured));negatives++;}
await assert.rejects(helper.validateRoleScope(mock(after,(t,rows)=>{if(t===table)rows[0].value='fabricated'}),laws,captured));negatives++;await assert.rejects(helper.validateRoleScope(mock(after,(t,rows)=>{if(t===table)rows.splice(0,1)}),laws,captured));negatives++;}
for(const table of ['agent_versions','agent_runs'])for(const mutate of [c=>c.expression+=' OR true',c=>c.definition+=' OR true',c=>c.validated=false,c=>c.keys=[1],c=>c.deferrable=true,c=>c.deferred=true,c=>c.local=false,c=>c.inherited=1,c=>c.noinherit=true,c=>c.type='u']){const bad=copy(after);mutate(bad[table].constraints.at(-1));await assert.rejects(helper.validateRoleScope(mock(bad),laws,captured));negatives++;}
for(const t of helper.TABLES){const pre=copy(base);pre[t].columns.push(after[t].columns.at(-1));await assert.rejects(helper.captureRoleScopeBaseline(mock(pre),async n=>base[n].legacyIds.map(id=>({id}))),/PREEXISTING_COLUMN/);negatives++;}
for(const t of ['agent_versions','agent_runs']){const pre=copy(base);pre[t].constraints.push({...after[t].constraints.at(-1),definition:'CHECK (id IS NOT NULL)',expression:'id IS NOT NULL',keys:[1]});await assert.rejects(helper.captureRoleScopeBaseline(mock(pre),async n=>base[n].legacyIds.map(id=>({id}))),/PREEXISTING_CHECK/);negatives++;}
for(const ids of [['duplicate','duplicate'],[''],Array(100001).fill('too-many')]){const bad=copy(captured);bad.agent_versions.legacyIds=ids;await assert.rejects(helper.validateRoleScope(mock(after),laws,bad),/COHORT_REQUIRED/);negatives++;}
const missing=copy(captured);delete missing.agent_runs;await assert.rejects(helper.validateRoleScope(mock(after),laws,missing),/BASELINE_REQUIRED/);negatives++;
const plan={roleScopeValidatorSha256:digest,migrationLawBindings:Object.fromEntries(Object.entries(fixtures).map(([n,l])=>[n,{...l,reviewed:true}]))};const tables=helper.TABLES.map(table=>({schema:'public',table,columns:['id','org_id','agent_id','run_id']}));const before=await engine.roleScopeProof(mock(base),'before',plan,tables);assert(before.roleScopeCatalogBaseline);const first=await engine.roleScopeProof(mock(after),'after',plan,tables,before),repeat=await engine.roleScopeProof(mock(after),'after',plan,tables,before);assert.deepEqual(first,repeat);assert(first.roleScopeCatalogProof.catalogLawVerified);await assert.rejects(engine.roleScopeProof(mock(after),'before',plan,tables),/PREEXISTING_COLUMN/);await assert.rejects(engine.roleScopeProof(mock(after),'after',{...plan,roleScopeValidatorSha256:'0'.repeat(64)},tables,before),/VALIDATOR_HASH/);const unreviewed=copy(plan);Object.values(unreviewed.migrationLawBindings)[0].reviewed=false;await assert.rejects(engine.roleScopeProof(mock(after),'after',unreviewed,tables,before),/REVIEW_REQUIRED/);await assert.rejects(engine.roleScopeProof(mock(after),'after',plan,tables,{}),/BASELINE_REQUIRED/);for(const c of [...helper.SAFE_CODES,'ROLE_SCOPE_VALIDATOR_HASH','ROLE_SCOPE_REVIEW_REQUIRED','ROLE_SCOPE_BASELINE_TABLES'])assert.equal(engine.failureCode(c),c);assert.equal(engine.failureCode('password=private'),'QUERY_FAILED');
for(const table of tables){assert.equal(engine.projection(table,'before'),engine.projection(table,'after'));assert(!engine.projection(table,'after').includes('pending_skill_bindings'));}
console.log(`role scope actual-query/engine positive, repeat + ${negatives} catalog/cohort negatives PASS; no SQL`);
})().catch(e=>{console.error(e);process.exitCode=1});
