'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const helper=require('./role-scope-law.cjs'),copy=x=>JSON.parse(JSON.stringify(x));
const fixtures=JSON.parse(fs.readFileSync(__dirname+'/fixtures/isolated-canonical-historical/role-scope-laws.json'));
const laws={};for(const[name,law]of Object.entries(fixtures)){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.resolve(__dirname,'../../../apps/api/migrations',name))).digest('hex'),law.sqlSha256);assert.equal(crypto.createHash('sha256').update(JSON.stringify(law.body)).digest('hex'),law.lawSha256);laws[name]=law.body;}
const base={};for(const t of helper.TABLES)base[t]={columns:[{num:1,name:'id',type:'text',notnull:true,default_expr:null},{num:2,name:'org_id',type:'text',notnull:true,default_expr:null}],constraints:[{name:t+'_pkey',type:'p',validated:true,keys:[1],deferrable:false,deferred:false,local:true,inherited:0,noinherit:true,expression:null,definition:'PRIMARY KEY (id)'}],policies:[{name:'tenant',cmd:'*',permissive:true,roles:['PUBLIC'],using_expr:'org_id = current_org()',check_expr:'org_id = current_org()'},{name:'freeze',cmd:'w',permissive:false,roles:['PUBLIC'],using_expr:null,check_expr:'kernel_org_is_writable(org_id)'}],acl:[{owner:'migration_admin',enabled:true,forced:true,grantee:'app_rw',grantor:'migration_admin',privilege:'SELECT',grantable:false}],maxnum:[{maxnum:5}],legacyIds:['legacy-a','legacy-b']};
// Combined fixture: original 255-ledger catalog plus all pending 391 and new two SQL.
// Descriptor literals remain independent of the validator; source hashes below bind the actual SQL.
base.agent_versions.columns.push({num:3,name:'tool_policy',type:'jsonb',notnull:true,default_expr:null});
const constraint=(name,keys,expression)=>({name,type:'c',validated:true,keys,deferrable:false,deferred:false,local:true,inherited:0,noinherit:false,expression,definition:'CHECK ('+expression+')'});
base.agent_versions.constraints.push(constraint('agent_versions_tool_policy_check',[3],"((jsonb_typeof(tool_policy) = 'array'::text) AND (jsonb_array_length(tool_policy) = 0))"));
for(const[name,sha]of Object.entries(helper.PRIOR_SQL))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.resolve(__dirname,'../../../apps/api/migrations',name))).digest('hex'),sha);
function afterCatalog(){const a=copy(base);
 const prior=[['avatar','jsonb',false,null],['role_category','text',false,null],['catalog_source','text',true,"'org'::text"],['workflow_allowlist','text[]',true,"'{}'::text[]"],['delegation_policy','jsonb',true,'\'{"maxDepth": 0, "allowedTargets": [], "requireApproval": true}\'::jsonb'],['escalation_policy','jsonb',true,'\'{"rules": []}\'::jsonb'],['kpi','jsonb',true,"'[]'::jsonb"],['tags','text[]',true,"'{}'::text[]"],['pending_skill_bindings','jsonb',true,"'[]'::jsonb"]];
 a.agent_versions.columns.push(...prior.map(([name,type,notnull,default_expr],i)=>({num:6+i,name,type,notnull,default_expr})));a.agent_versions.maxnum=[{maxnum:14}];
 a.agent_versions.constraints=a.agent_versions.constraints.filter(c=>c.name!=='agent_versions_tool_policy_check');
 a.agent_versions.constraints.push(
 constraint('agent_versions_role_category_check',[7],"((role_category IS NULL) OR (role_category = ANY (ARRAY['research'::text, 'product'::text, 'sales'::text, 'design'::text, 'general'::text, 'executive'::text, 'customer_success'::text, 'operations'::text])))"),
 constraint('agent_versions_catalog_source_check',[8],"(catalog_source = ANY (ARRAY['official'::text, 'org'::text]))"),
 constraint('agent_versions_role_fields_ok',[6,9,10,11,12],'agent_role_fields_ok(avatar, workflow_allowlist, delegation_policy, escalation_policy, kpi)'),
 constraint('agent_versions_tags_ok',[13],'((cardinality(tags) <= 10) AND (array_position(tags, NULL::text) IS NULL))'),
 constraint('agent_versions_tool_policy_check',[3],'agent_tool_policy_ok(tool_policy)'),
 constraint('agent_versions_pending_skill_bindings_array',[14],"(jsonb_typeof(pending_skill_bindings) = 'array'::text)"));
 a.agent_runs.columns.push({num:6,name:'cited_sources',type:'jsonb',notnull:true,default_expr:"'[]'::jsonb"},{num:7,name:'skill_scope',type:'text',notnull:false,default_expr:null});a.agent_runs.maxnum=[{maxnum:7}];a.agent_runs.constraints.push(constraint('agent_runs_skill_scope_check',[7],"((skill_scope IS NULL) OR (skill_scope = ANY (ARRAY['agent_pins'::text, 'general'::text])))"));
 a.thread_message_queue.columns.push({num:6,name:'explicit_agent',type:'boolean',notnull:false,default_expr:null});a.thread_message_queue.maxnum=[{maxnum:6}];return a;
}
function mock(catalog,mutateRows){const calls=[];return {calls,query:async(sql,params)=>{calls.push({sql,params});const t=helper.TABLES.find(t=>sql.includes("'public."+t+"'::regclass")||sql.includes('public."'+t+'"'));assert(t,'SQL table must be one of exact three');for(const kind of ['columns','constraints','policies','acl','maxnum'])if(sql===helper.queryFor(t,kind))return {rows:copy(catalog[t][kind])};if(sql.startsWith('SELECT id::text id FROM ONLY ')){assert(sql.includes('agent_id')&&sql.includes('NOT IN')&&sql.endsWith('ORDER BY id::text LIMIT 100001'));return {rows:base[t].legacyIds.map(id=>({id}))};}assert(sql.startsWith('SELECT count(*)::text total,count(*) FILTER (WHERE '));assert(sql.endsWith('WHERE id::text=ANY($1::text[])'));assert.equal(JSON.stringify(params),JSON.stringify([base[t].legacyIds]));const column={agent_versions:'pending_skill_bindings',agent_runs:'skill_scope',thread_message_queue:'explicit_agent'}[t];assert(sql.includes(t==='agent_versions'?"pending_skill_bindings IS DISTINCT FROM '[]'::jsonb":column+' IS NOT NULL'));if(t==='agent_versions')for(const token of ['avatar IS NOT NULL','role_category IS NOT NULL',"catalog_source IS DISTINCT FROM 'org'::text","workflow_allowlist IS DISTINCT FROM '{}'::text[]",'delegation_policy IS DISTINCT FROM','escalation_policy IS DISTINCT FROM',"kpi IS DISTINCT FROM '[]'::jsonb","tags IS DISTINCT FROM '{}'::text[]"])assert(sql.includes(token));if(t==='agent_runs')assert(sql.includes("cited_sources IS DISTINCT FROM '[]'::jsonb"));const rows=base[t].legacyIds.map(id=>({id,value:t==='agent_versions'?[]:null}));rows.push({id:'canonical-owned-new',value:t==='agent_versions'?['new-gap']:t==='agent_runs'?'general':true});if(mutateRows)mutateRows(t,rows);const cohort=rows.filter(r=>params[0].includes(r.id));return {rows:[{total:String(cohort.length),changed:String(cohort.filter(r=>r.priorValueDrift||JSON.stringify(r.value)!==JSON.stringify(t==='agent_versions'?[]:null)).length)}]};}};}
const source=fs.readFileSync(__dirname+'/conservation-engine.cjs','utf8'),bytes=fs.readFileSync(__dirname+'/role-scope-law.cjs','utf8'),digest=crypto.createHash('sha256').update(bytes).digest('hex');
function embedded(s,b){const marker='const roleScopeValidators=(function(){const module={exports:{}};\n';const start=s.indexOf(marker);assert(start>=0);assert.equal(s.slice(start+marker.length,s.indexOf('\nreturn module.exports;})();',start)),b);assert(s.includes("roleScopeValidatorSha256==='"+crypto.createHash('sha256').update(b).digest('hex')+"'"));}
embedded(source,bytes);assert.throws(()=>embedded(source,bytes+'// drift'));assert.throws(()=>embedded(source.replace('roleScopeValidatorSha256','wrongField'),bytes));
const sandbox={Buffer,TextDecoder,module:{exports:{}},process:{env:{}},require:n=>n==='pg'?{Client:class{constructor(){throw Error('NO_REAL_SQL')}}}:require(n)};vm.runInNewContext(source,sandbox);const engine=sandbox.module.exports;
(async()=>{const captureClient=mock(base);const captured=await helper.captureRoleScopeBaseline(captureClient,async t=>base[t].legacyIds.map(id=>({id})));assert.deepEqual(captured,base);const after=afterCatalog();assert((await helper.validateRoleScope(mock(after),laws,captured)).catalogLawVerified);assert((await helper.validateRoleScope(mock(after),laws,captured)).catalogLawVerified);let negatives=0;
for(const table of helper.TABLES){for(const mutate of [x=>x.columns[0].type='integer',x=>x.columns.at(-1).num=3,x=>x.columns.at(-1).type='integer',x=>x.columns.at(-1).notnull=!x.columns.at(-1).notnull,x=>x.columns.at(-1).default_expr="'fabricated'",x=>x.columns.push({name:'unreviewed'}),x=>x.maxnum[0].maxnum++,x=>x.constraints[0].definition='CHECK (true)',x=>x.policies[0].using_expr='true',x=>x.policies[1].permissive=true,x=>x.acl[0].grantable=true,x=>x.acl[0].owner='app_rw',x=>x.acl[0].forced=false,x=>x.acl.push({...x.acl[0],grantee:'PUBLIC'})]){const bad=copy(after);mutate(bad[table]);await assert.rejects(helper.validateRoleScope(mock(bad),laws,captured));negatives++;}
await assert.rejects(helper.validateRoleScope(mock(after,(t,rows)=>{if(t===table)rows[0].value='fabricated'}),laws,captured));negatives++;await assert.rejects(helper.validateRoleScope(mock(after,(t,rows)=>{if(t===table)rows.splice(0,1)}),laws,captured));negatives++;}
for(const table of ['agent_versions','agent_runs'])for(const mutate of [c=>c.expression+=' OR true',c=>c.definition+=' OR true',c=>c.validated=false,c=>c.keys=[1],c=>c.deferrable=true,c=>c.deferred=true,c=>c.local=false,c=>c.inherited=1,c=>c.noinherit=true,c=>c.type='u']){const bad=copy(after);mutate(bad[table].constraints.at(-1));await assert.rejects(helper.validateRoleScope(mock(bad),laws,captured));negatives++;}
for(const t of helper.TABLES){const pre=copy(base);pre[t].columns.push(after[t].columns.at(-1));await assert.rejects(helper.captureRoleScopeBaseline(mock(pre),async n=>base[n].legacyIds.map(id=>({id}))),/PREEXISTING_COLUMN/);negatives++;}
for(const t of ['agent_versions','agent_runs']){const pre=copy(base);pre[t].constraints.push({...after[t].constraints.at(-1),definition:'CHECK (id IS NOT NULL)',expression:'id IS NOT NULL',keys:[1]});await assert.rejects(helper.captureRoleScopeBaseline(mock(pre),async n=>base[n].legacyIds.map(id=>({id}))),/PREEXISTING_CHECK/);negatives++;}
for(const ids of [['duplicate','duplicate'],[''],Array(100001).fill('too-many')]){const bad=copy(captured);bad.agent_versions.legacyIds=ids;await assert.rejects(helper.validateRoleScope(mock(after),laws,bad),/COHORT_REQUIRED/);negatives++;}
for(const table of ['agent_versions','agent_runs']){await assert.rejects(helper.validateRoleScope(mock(after,(t,rows)=>{if(t===table)rows[0].priorValueDrift=true}),laws,captured),/LEGACY_VALUES_DRIFT/);negatives++;}
for(const table of ['agent_versions','agent_runs'])for(const column of after[table].columns.slice(base[table].columns.length,-1)){const bad=copy(after);bad[table].columns.find(c=>c.name===column.name).default_expr="'unreviewed'";await assert.rejects(helper.validateRoleScope(mock(bad),laws,captured),/COLUMN_DELTA/);negatives++;}
for(const c of after.agent_versions.constraints.filter(c=>!base.agent_versions.constraints.some(b=>b.name===c.name)&&c.name!=='agent_versions_pending_skill_bindings_array')){const bad=copy(after);bad.agent_versions.constraints.find(x=>x.name===c.name).validated=false;await assert.rejects(helper.validateRoleScope(mock(bad),laws,captured),/PRIOR_CATALOG/);negatives++;}
const incompatible=copy(base);incompatible.agent_versions.constraints.find(c=>c.name==='agent_versions_tool_policy_check').expression='true';await assert.rejects(helper.captureRoleScopeBaseline(mock(incompatible),async t=>base[t].legacyIds.map(id=>({id}))),/PRIOR_CATALOG/);negatives++;
const wrongPrior=copy(laws);Object.values(wrongPrior)[0].priorCatalogSqlChecksums[Object.keys(helper.PRIOR_SQL)[0]]='0'.repeat(64);await assert.rejects(helper.validateRoleScope(mock(after),wrongPrior,captured),/PRIOR_LAW/);negatives++;
const missing=copy(captured);delete missing.agent_runs;await assert.rejects(helper.validateRoleScope(mock(after),laws,missing),/BASELINE_REQUIRED/);negatives++;
const plan={fullSqlChecksums:{...helper.PRIOR_SQL},pendingSqlChecksums:{...helper.PRIOR_SQL},roleScopeValidatorSha256:digest,migrationLawBindings:Object.fromEntries(Object.entries(fixtures).map(([n,l])=>[n,{...l,reviewed:true}]))};const tables=helper.TABLES.map(table=>({schema:'public',table,columns:['id','org_id','agent_id','run_id']}));const before=await engine.roleScopeProof(mock(base),'before',plan,tables);assert(before.roleScopeCatalogBaseline);const first=await engine.roleScopeProof(mock(after),'after',plan,tables,before),repeat=await engine.roleScopeProof(mock(after),'after',plan,tables,before);assert.deepEqual(first,repeat);assert(first.roleScopeCatalogProof.catalogLawVerified);await assert.rejects(engine.roleScopeProof(mock(after),'before',plan,tables),/PREEXISTING_COLUMN/);await assert.rejects(engine.roleScopeProof(mock(after),'after',{...plan,roleScopeValidatorSha256:'0'.repeat(64)},tables,before),/VALIDATOR_HASH/);const alreadyApplied=copy(plan);delete alreadyApplied.pendingSqlChecksums[Object.keys(helper.PRIOR_SQL)[0]];await assert.rejects(engine.roleScopeProof(mock(base),'before',alreadyApplied,tables),/PRIOR_LAW/);const priorDrift=copy(plan);priorDrift.fullSqlChecksums[Object.keys(helper.PRIOR_SQL)[0]]='0'.repeat(64);await assert.rejects(engine.roleScopeProof(mock(base),'before',priorDrift,tables),/PRIOR_LAW/);const unreviewed=copy(plan);Object.values(unreviewed.migrationLawBindings)[0].reviewed=false;await assert.rejects(engine.roleScopeProof(mock(after),'after',unreviewed,tables,before),/REVIEW_REQUIRED/);await assert.rejects(engine.roleScopeProof(mock(after),'after',plan,tables,{}),/BASELINE_REQUIRED/);for(const c of [...helper.SAFE_CODES,'ROLE_SCOPE_VALIDATOR_HASH','ROLE_SCOPE_REVIEW_REQUIRED','ROLE_SCOPE_BASELINE_TABLES'])assert.equal(engine.failureCode(c),c);assert.equal(engine.failureCode('password=private'),'QUERY_FAILED');
for(const table of tables){assert.equal(engine.projection(table,'before'),engine.projection(table,'after'));assert(!engine.projection(table,'after').includes('pending_skill_bindings'));}
console.log(`role scope actual-query/engine positive, repeat + ${negatives} catalog/cohort negatives PASS; no SQL`);
})().catch(e=>{console.error(e);process.exitCode=1});
