'use strict';
const fs=require('node:fs'),{createHash}=require('node:crypto');
const SOURCE='pgm-uf6rg214cp381l49';
const ROLES=['app_diag_ro','app_rw','graph_owner','memory_owner','memory_rw','migration_owner'];
const OWNER_MAP={workspacex:'migration_owner',workspacex_agent:'graph_owner',workspacex_memory:'memory_owner'};
function validate(x){
 const b=x.binding,m=x.secret,s=b.sourceDatabaseSpec;
 if(!/^pgm-[a-z0-9]+$/.test(b.targetInstanceId)||b.targetInstanceId===SOURCE||m.targetInstanceId!==b.targetInstanceId||m.attemptId!==b.attemptId||m.host!==b.host||m.peer!==b.peer||m.port!==5432||m.user!=='migration_admin')throw Error('TARGET_BINDING_INVALID');
 if(b.host!==b.targetInstanceId+'.rwlb.rds.aliyuncs.com'||createHash('sha256').update(b.peer).digest('hex')!==b.peerSha256)throw Error('PEER_BINDING_INVALID');
 if(s.rdsInstanceId!==SOURCE||s.readOnly!==true||s.rollbackConfirmed!==true||!Array.isArray(s.databases)||s.databases.length!==3)throw Error('SOURCE_SCOPE_INVALID');
 const age=Date.now()-Date.parse(s.observedUtc);if(!Number.isFinite(age)||age<0||age>3600000)throw Error('SOURCE_SPEC_EXPIRED');
 const names=new Set();for(const d of s.databases){if(names.has(d.name)||OWNER_MAP[d.name]!==d.owner||d.encoding!=='UTF8'||d.collate!=='C'||d.ctype!=='en_US.utf8'||d.acl!==null)throw Error('SOURCE_DB_SPEC_INVALID');names.add(d.name);}
 if(names.size!==3)throw Error('SOURCE_CLOSURE_INVALID');return s.databases;
}
function ident(n){if(!/^[a-z_][a-z_0-9]*$/.test(n))throw Error('IDENTIFIER_INVALID');return '"'+n+'"';}
function createStatement(d){return 'CREATE DATABASE '+ident(d.name)+' OWNER '+ident(d.owner)+" TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'en_US.utf8'";}
async function run(x){const databases=validate(x),m=x.secret;const b=x.binding,{Client}=require('pg');const tls=b.tls.sslmode==='verify-full'?{rejectUnauthorized:true,ca:fs.readFileSync('/run/ca.pem','utf8')}:false;if(!tls&&b.tls.approvedException!=='aliyun-postgresql-serverless-no-tls')throw Error('TLS_EXCEPTION_INVALID');const c=new Client({host:m.host,port:m.port,user:m.user,password:m.password,database:'postgres',ssl:tls,connectionTimeoutMillis:10000,options:'-c statement_timeout=15000'});const granted=[],created=[];let tx=false;try{await c.connect();if(createHash('sha256').update(c.connection.stream.remoteAddress.replace(/^::ffff:/,'')).digest('hex')!==b.peerSha256||c.connection.stream.remotePort!==5432)throw Error('TARGET_PEER_INVALID');await c.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');tx=true;const id=(await c.query("SELECT current_database() AS db,current_user AS username,current_setting('transaction_read_only') AS readonly")).rows[0];if(id.db!=='postgres'||id.username!=='migration_admin'||id.readonly!=='on')throw Error('TARGET_IDENTITY_INVALID');const existing=await c.query('SELECT datname FROM pg_database WHERE datname=ANY($1::text[])',[Object.keys(OWNER_MAP)]);if(existing.rowCount)throw Error('TARGET_DATABASE_NOT_EMPTY');const normal=(await c.query('SELECT rolname AS name,rolsuper,rolinherit,rolcreaterole,rolcreatedb,rolcanlogin,rolreplication,rolbypassrls,rolconnlimit,rolconfig FROM pg_roles WHERE rolname=ANY($1::text[])',[ROLES])).rows;if(normal.length!==6||normal.some(r=>!ROLES.includes(r.name)||r.rolsuper||!r.rolinherit||r.rolcreaterole||r.rolcreatedb||!r.rolcanlogin||r.rolreplication||r.rolbypassrls||r.rolconnlimit!==-1||r.rolconfig!==null))throw Error('TARGET_NORMAL_ROLE_ATTRIBUTES_INVALID');const members=await c.query("SELECT r.rolname AS role FROM pg_auth_members a JOIN pg_roles r ON r.oid=a.roleid JOIN pg_roles m ON m.oid=a.member WHERE m.rolname='migration_admin' AND r.rolname=ANY($1::text[])",[ROLES]);if(members.rowCount)throw Error('TARGET_EXISTING_OWNER_MEMBERSHIP_CONFLICT');await c.query('ROLLBACK');tx=false;
// Temporary SET memberships are explicitly part of restore input, never source-fidelity acceptance.
await c.query('BEGIN');tx=true;for(const role of ROLES){const credential=m.roles?.[role];if(credential?.user!==role||credential.targetInstanceId!==b.targetInstanceId||credential.attemptId!==b.attemptId||credential.host!==b.host||credential.peer!==b.peer||!/^Aa1![A-Za-z0-9_-]{32}$/.test(credential.password))throw Error('ROLE_CREDENTIAL_BINDING');await c.query('ALTER ROLE '+ident(role)+" PASSWORD '"+credential.password+"'");await c.query('GRANT '+ident(role)+' TO migration_admin WITH INHERIT FALSE');await c.query('GRANT '+ident(role)+' TO migration_admin WITH SET TRUE');granted.push(role);}await c.query('COMMIT');tx=false;for(const d of databases){await c.query(createStatement(d));created.push(d.name);}const actual=(await c.query('SELECT d.datname AS name,r.rolname AS owner,pg_encoding_to_char(d.encoding) AS encoding,d.datcollate AS collate,d.datctype AS ctype,d.datacl::text AS acl FROM pg_database d JOIN pg_roles r ON r.oid=d.datdba WHERE d.datname=ANY($1::text[]) ORDER BY d.datname COLLATE "C"',[Object.keys(OWNER_MAP)])).rows;if(actual.length!==3||actual.some(d=>d.owner!==OWNER_MAP[d.name]||d.encoding!=='UTF8'||d.collate!=='C'||d.ctype!=='en_US.utf8'||d.acl!==null))throw Error('TARGET_DB_OWNER_ACL_MISMATCH');process.stdout.write(JSON.stringify({schemaVersion:1,targetId:b.targetInstanceId,sourceDistinct:true,observedUtc:new Date().toISOString(),sourceObservedUtc:b.sourceDatabaseSpec.observedUtc,databases:actual,temporaryMembershipRows:(await c.query("SELECT r.rolname AS role,g.rolname AS grantor,a.admin_option,a.inherit_option,a.set_option FROM pg_auth_members a JOIN pg_roles r ON r.oid=a.roleid JOIN pg_roles g ON g.oid=a.grantor JOIN pg_roles m ON m.oid=a.member WHERE m.rolname='migration_admin' AND r.rolname=ANY($1::text[]) ORDER BY r.rolname,g.rolname",[ROLES])).rows,temporarySetRoles:granted,temporaryMembershipsRequireRemovalAfterRestore:true,restorePerformed:false})+'\n');}catch(e){if(tx)try{await c.query('ROLLBACK');}catch{}process.stderr.write('TARGET_DB_PREPARE_FAILED; created_count='+created.length+'; temporary_memberships_count='+granted.length+'\n');throw Error('TARGET_DB_PREPARE_FAILED');}finally{await c.end();}}

async function removeTemporary(x){validate(x);const b=x.binding,m=x.secret,{Client}=require('pg'),proof=x.preparationReceipt;if(proof?.targetId!==b.targetInstanceId||JSON.stringify([...proof.temporarySetRoles].sort())!==JSON.stringify([...ROLES].sort())||!Array.isArray(proof.temporaryMembershipRows)||proof.temporaryMembershipRows.length!==ROLES.length)throw Error('OWNED_MEMBERSHIP_RECEIPT');const tls=b.tls.sslmode==='verify-full'?{rejectUnauthorized:true,ca:fs.readFileSync('/run/ca.pem','utf8'),servername:b.host}:false;const c=new Client({host:m.host,port:5432,database:'postgres',user:m.user,password:m.password,ssl:tls,connectionTimeoutMillis:5000});let tx=false;try{await c.connect();if(createHash('sha256').update(c.connection.stream.remoteAddress.replace(/^::ffff:/,'')).digest('hex')!==b.peerSha256||c.connection.stream.remotePort!==5432)throw Error('ACTUAL_PEER');await c.query('BEGIN');tx=true;const actual=(await c.query("SELECT r.rolname AS role,g.rolname AS grantor,a.admin_option,a.inherit_option,a.set_option FROM pg_auth_members a JOIN pg_roles r ON r.oid=a.roleid JOIN pg_roles g ON g.oid=a.grantor JOIN pg_roles m ON m.oid=a.member WHERE m.rolname='migration_admin' AND r.rolname=ANY($1::text[]) ORDER BY r.rolname,g.rolname",[ROLES])).rows;if(JSON.stringify(actual)!==JSON.stringify(proof.temporaryMembershipRows))throw Error('MEMBERSHIP_CHANGED');for(const row of actual){if(!ROLES.includes(row.role))throw Error('MEMBERSHIP_SCOPE');await c.query('REVOKE '+ident(row.role)+' FROM migration_admin GRANTED BY '+ident(row.grantor)+' RESTRICT');}if((await c.query("SELECT a.roleid FROM pg_auth_members a JOIN pg_roles r ON r.oid=a.roleid JOIN pg_roles m ON m.oid=a.member WHERE m.rolname='migration_admin' AND r.rolname=ANY($1::text[])",[ROLES])).rowCount)throw Error('MEMBERSHIP_NOT_REMOVED');await c.query('COMMIT');tx=false;process.stdout.write(JSON.stringify({temporaryMembershipsRemoved:true,targetId:b.targetInstanceId,attemptId:b.attemptId})+'\n');}finally{if(tx)await c.query('ROLLBACK').catch(()=>{});await c.end();}}
if(require.main===module||process.argv[1]===undefined){const x=JSON.parse(fs.readFileSync(0,'utf8'));if(x.operation==='remove-temporary-memberships')removeTemporary(x).catch(()=>{process.exitCode=1;});else run(x).catch(()=>{process.exitCode=1;});}module.exports={validate,createStatement,removeTemporary};
