'use strict';
const assert=require('node:assert/strict');const {capturePendingAttachmentBaseline,validatePendingAttachment}=require('./pending-attachment-law.cjs');
const baseline={columns:[{name:'message_id',type:'text',notnull:false,default_expr:null},{name:'file_id',type:'text',notnull:true,default_expr:null}],constraints:[{name:'oldpk',type:'p',validated:true,definition:'PRIMARY KEY (file_id)'}],policies:[{name:'tenant',cmd:'*',permissive:true,roles:['PUBLIC'],using_expr:'org_id = current_org()',check_expr:'org_id = current_org()'},{name:'org_frozen',cmd:'d',permissive:false,roles:['PUBLIC'],using_expr:'kernel_org_is_writable(org_id)',check_expr:null}],acl:[{owner:'migration_admin',enabled:true,forced:true,grantee:'app_rw',grantor:'migration_admin',privilege:'SELECT',grantable:false}]};
const after=[ [...baseline.columns,{name:'uploaded_by',type:'text',notnull:false,default_expr:null},{name:'cancelled_at',type:'timestamp with time zone',notnull:false,default_expr:null}], [...baseline.constraints,{name:'chat_attachment_cancel_pending',type:'c',validated:true,definition:'CHECK ((cancelled_at IS NULL) OR (message_id IS NULL))'}], [...baseline.policies,{name:'chat_attachment_delete_pending',cmd:'d',permissive:false,roles:['app_rw'],using_expr:'(message_id IS NULL)',check_expr:null}], [...baseline.acl,{...baseline.acl[0],privilege:'DELETE'}],[{total:'2',changed:'0'}] ];
const copy=x=>JSON.parse(JSON.stringify(x));const client=rows=>{let i=0;return {query:async()=>({rows:rows[i++]})}};const fsSource=require('node:fs'),pathSource=require('node:path'),cryptoSource=require('node:crypto');const fixture=JSON.parse(fsSource.readFileSync(__dirname+'/fixtures/isolated-canonical-historical/pending-attachment-law.json'));const migration=fsSource.readFileSync(pathSource.resolve(__dirname,'../../../apps/api/migrations',fixture.migrationName));assert.equal(cryptoSource.createHash('sha256').update(migration).digest('hex'),fixture.sqlSha256);assert.equal(cryptoSource.createHash('sha256').update(JSON.stringify(fixture.body)).digest('hex'),fixture.lawSha256);const law=fixture.body;
(async()=>{assert.deepEqual(await capturePendingAttachmentBaseline(client([baseline.columns,baseline.constraints,baseline.policies,baseline.acl])),baseline);assert((await validatePendingAttachment(client(after),law,baseline)).catalogLawVerified);let negatives=0;
for(const mutate of [r=>r[0][0].type='integer',r=>r[0].push({name:'unreviewed'}),r=>r[0][2].notnull=true,r=>r[0][2].default_expr="'unknown'",r=>r[0][3].type='timestamp without time zone',r=>r[1][1].definition+=' OR true',r=>r[1][1].validated=false,r=>r[1][0].definition='CHECK (true)',r=>r[2][2].cmd='*',r=>r[2][2].permissive=true,r=>r[2][2].roles=['PUBLIC'],r=>r[2][2].using_expr='true',r=>r[2][2].check_expr='true',r=>r[2].push(r[2][2]),r=>r[2][0].using_expr='true',r=>r[2].splice(1,1),r=>r[3][1].grantable=true,r=>r[3][1].grantee='PUBLIC',r=>r[3][1].privilege='UPDATE',r=>r[3][1].grantor='other',r=>r[3][1].forced=false,r=>r[3].splice(0,1),r=>r[4][0].changed='1']){const rows=copy(after);mutate(rows);await assert.rejects(validatePendingAttachment(client(rows),law,baseline));negatives++;}
const bad=copy(baseline);bad.columns.push(after[0][2]);await assert.rejects(capturePendingAttachmentBaseline(client([bad.columns,bad.constraints,bad.policies,bad.acl])));negatives++;
// A repeated normal migration applies zero SQL; verify the post-catalog again against
// the same first-before baseline. Never recapture already migrated columns.
assert((await validatePendingAttachment(client(after),law,baseline)).catalogLawVerified);
await assert.rejects(capturePendingAttachmentBaseline(client(after.slice(0,4))));
const badSecond=copy(after);badSecond[2][2].permissive=true;await assert.rejects(validatePendingAttachment(client(badSecond),law,baseline));
// Real authoritative existing projection compares all original attachment columns,
// keeping message_id/file_id changes detectable while new null columns use above law.
const vm=require('node:vm'),fs=require('node:fs');const sandbox={Buffer,TextDecoder,module:{exports:{}},process:{env:{}},require:n=>n==='pg'?{Client:class{constructor(){throw Error('TEST_SQL_FORBIDDEN')}}}:require(n)};const source=fs.readFileSync(__dirname+'/conservation-engine.cjs','utf8');vm.runInNewContext(source+'\nmodule.exports.Multiset=Multiset;module.exports.setTestSpool=p=>{spool=p;};',sandbox);const {projection}=sandbox.module.exports;const table={schema:'public',table:'chat_message_attachments',columns:baseline.columns.map(c=>c.name)};
assert.equal(projection(table,'before'),projection(table,'after'));assert.equal(projection(table,'after'),'ROW("message_id","file_id")::text');
const helperBytes=fs.readFileSync(__dirname+'/pending-attachment-law.cjs','utf8');function assertEmbedded(actualSource,bytes){const marker='const attachmentValidators=(function(){const module={exports:{}};\n';const begin=actualSource.indexOf(marker);assert(begin>=0);const embedded=actualSource.slice(begin+marker.length,actualSource.indexOf('\nreturn module.exports;})();',begin));assert.equal(embedded,bytes);const digest=cryptoSource.createHash('sha256').update(bytes).digest('hex');assert(actualSource.includes("pendingAttachmentValidatorSha256==='"+digest+"'"));}assertEmbedded(source,helperBytes);assert.throws(()=>assertEmbedded(source,helperBytes+'// stale embedded'));assert.throws(()=>assertEmbedded(source.replace('pendingAttachmentValidatorSha256','wrongHashField'),helperBytes));for(const code of require('./pending-attachment-law.cjs').SAFE_CODES)assert.equal(sandbox.module.exports.failureCode(code),code);assert.equal(sandbox.module.exports.failureCode('password=private-value'), 'QUERY_FAILED');assert.equal(sandbox.module.exports.failureCode('ATTACHMENT_VALIDATOR_HASH'),'ATTACHMENT_VALIDATOR_HASH');
const tmp=fs.mkdtempSync(require('node:path').join(require('node:os').tmpdir(),'wsx-attachment-multiset-'));try{sandbox.module.exports.setTestSpool(tmp);const digest=(name,rows)=>{const m=new sandbox.module.exports.Multiset(name);rows.forEach(r=>m.add(r));return m.finish()};const original=digest('before',['(,file1)','(msg2,file2)']);assert.deepEqual(digest('unchanged',['(msg2,file2)','(,file1)']),original);assert.notEqual(digest('mutated',['(,file1)','(msg9,file2)']).multisetSha256,original.multisetSha256);assert.notEqual(digest('deleted',['(,file1)']).multisetSha256,original.multisetSha256);assert.notEqual(digest('duplicated',['(,file1)','(msg2,file2)','(msg2,file2)']).multisetSha256,original.multisetSha256);}finally{fs.rmSync(tmp,{recursive:true,force:true})}
console.log(`pending attachment catalog positive + ${negatives} negatives PASS; actual engine original-column projection verified; no SQL`);
})().catch(e=>{console.error(e);process.exitCode=1});
