"""Canonical input semantics shared by offline admission and actual stage producers.
The authoritative table/ledger derivation stays in canonical_plan_factory. No SQL,
Docker, provider access, credentials or accepted rehearsal receipt is created here.
"""
import hashlib,json,re
from isolated_canonical_plan_factory import derive

DATABASES=('workspacex_agent','workspacex_memory')
SOURCE_FILES=('memory_deployment.py','postgres_checkpointer.py','self_hosted_runtime.py')
EXPECTED_SOURCE_PATHS=frozenset('apps/deep-agent-service/src/deep_agent_service/'+n for n in SOURCE_FILES)|{'apps/deep-agent-service/pyproject.toml','apps/deep-agent-service/uv.lock'}
def reject(code):raise ValueError(code)
def digest(raw):return hashlib.sha256(raw).hexdigest()
def json_bytes(value):
 # Canonical plans are generated by the same derive() with stable string keys and
 # integer ledger values. Compact UTF-8 also matches bind_request/Node stringify.
 return json.dumps(value,separators=(',',':'),ensure_ascii=False,allow_nan=False).encode('utf8')
def read_json(ref,reader):
 raw=reader(ref)
 if not isinstance(raw,bytes) or digest(raw)!=ref.get('sha256'):reject('CANONICAL_INPUT_BYTES_HASH')
 value=json.loads(raw)
 if not isinstance(value,dict):reject('CANONICAL_INPUT_OBJECT')
 return value,raw

def validate_canonical_inputs(spec,binding,reader):
 """reader(ref)->verified actual immutable bytes; caller owns root/path policy."""
 candidate=binding['candidateSha'];conservation=spec['conservationPlan'];canonical=spec['stages']['canonical-setup']
 resources=canonical.get('resources',{})
 if set(resources)!={'exact','probe'} or set(resources['probe'])!={'canonical-source-manifest.json','canonical-extractor.json','python-runtime-manifest.json'}:reject('CANONICAL_RESOURCE_SETS')
 probe=resources['probe'];source,source_raw=read_json(probe['canonical-source-manifest.json'],reader);extractor,extractor_raw=read_json(probe['canonical-extractor.json'],reader);runtime,runtime_raw=read_json(probe['python-runtime-manifest.json'],reader)
 if source.get('schemaVersion')!=1 or source.get('sourceSha')!=candidate or type(source.get('sourceQueriesAttempted')) is not int or source['sourceQueriesAttempted']!=0 or type(source.get('networkConnectionsAttempted')) is not int or source['networkConnectionsAttempted']!=0:reject('CANONICAL_SOURCE_IDENTITY')
 files=source.get('filesSha256',{});exact=resources['exact'];versions=source.get('expectedPackageVersions')
 if set(files)!=EXPECTED_SOURCE_PATHS or set(exact)!=EXPECTED_SOURCE_PATHS:reject('CANONICAL_EXACT_SOURCE_SET')
 if not isinstance(versions,dict) or set(versions)!={'psycopg','langgraph','langgraph-checkpoint-postgres'} or any(not isinstance(v,str) or not v for v in versions.values()):reject('CANONICAL_LOCK_PACKAGE_VERSIONS')
 for relative,expected in files.items():
  if not re.fullmatch('[a-f0-9]{64}',expected) or exact[relative].get('sha256')!=expected or digest(reader(exact[relative]))!=expected:reject('CANONICAL_EXACT_SOURCE_BYTES')
 expected_names={n:files['apps/deep-agent-service/src/deep_agent_service/'+n] for n in SOURCE_FILES};expected_names['pyproject.toml']=files['apps/deep-agent-service/pyproject.toml']
 if conservation.get('canonicalSourceSha')!=candidate or conservation.get('canonicalSourceFiles')!=expected_names:reject('CANONICAL_CONSERVATION_SOURCE_BINDING')
 uvhash=files['apps/deep-agent-service/uv.lock']
 for name,value in [('extractor',extractor),('runtime',runtime)]:
  if value.get('schemaVersion')!=1 or value.get('candidateSha')!=candidate or value.get('candidateUvLockSha256')!=uvhash or value.get('packageVersions')!=versions or type(value.get('sourceQueriesAttempted')) is not int or value['sourceQueriesAttempted']!=0 or type(value.get('networkConnectionsAttempted')) is not int or value['networkConnectionsAttempted']!=0:reject('CANONICAL_'+name.upper()+'_IDENTITY')
 rows=runtime.get('distributions')
 if not isinstance(rows,list) or not rows or runtime.get('distributionCount')!=len(rows):reject('CANONICAL_RUNTIME_DISTRIBUTIONS')
 names=[]
 for row in rows:
  if not isinstance(row,dict) or set(row)!={'name','normalizedName','version'} or not isinstance(row['name'],str) or not row['name'] or not isinstance(row['version'],str) or not row['version'] or row['normalizedName']!=re.sub(r'[-_.]+','-',row['name']).lower():reject('CANONICAL_RUNTIME_DISTRIBUTION_SHAPE')
  names.append(row['normalizedName'])
 if names!=sorted(names) or len(names)!=len(set(names)):reject('CANONICAL_RUNTIME_DISTRIBUTION_ORDER')
 if runtime.get('distributionsCanonicalSha256')!=digest(json.dumps(rows,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False).encode()):reject('CANONICAL_RUNTIME_DISTRIBUTION_HASH')
 actual_versions={row['normalizedName']:row['version'] for row in rows}
 if any(actual_versions.get(name)!=value for name,value in versions.items()):reject('CANONICAL_RUNTIME_LOCK_DRIFT')
 image=canonical['immutableRuntimeId']
 if not re.fullmatch('sha256:[a-f0-9]{64}',image) or not re.fullmatch('[a-f0-9]{40}',canonical.get('runtimeSourceSha','')):reject('CANONICAL_RUNTIME_IMAGE_SHAPE')
 # Authoritative factory validates actual ordered migration SQL bytes/checksums,
 # package setup identities and derives complete expected tables/ledger versions.
 try:expected=derive(source,extractor,runtime,digest(source_raw),digest(extractor_raw),digest(runtime_raw),image)
 except (AssertionError,KeyError,TypeError,ValueError) as error:raise ValueError('CANONICAL_FACTORY_DERIVATION') from error
 hashes=conservation.get('canonicalSchemaPlanHashes',{})
 if set(hashes)!=set(DATABASES):reject('CANONICAL_PLAN_DATABASE_HASH_SET')
 plans={}
 for stage in ('before','after'):
  for database in DATABASES:
   ref=spec['stages'][stage][database]['canonicalPlan'];plan,raw=read_json(ref,reader)
   expected_raw=json_bytes(expected[database]);expected_hash=digest(expected_raw)
   if raw!=expected_raw or plan!=expected[database] or ref['sha256']!=expected_hash or hashes[database]!=expected_hash:reject('CANONICAL_PLAN_DERIVED_BYTES_BINDING')
   plans[database]=expected_hash
 return {'candidateSha':candidate,'sourceManifestSha256':digest(source_raw),'extractorSha256':digest(extractor_raw),'runtimeManifestSha256':digest(runtime_raw),'canonicalPlanSha256':plans,'inputSemanticsVerified':True,'prepared':False}
