'use strict';
// Source integration fixtures only: no process, container, root operation or PG.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {EventEmitter}=require('node:events'),{PassThrough}=require('node:stream');
const catalog=require('./cn-production-recovery-catalog.cjs');
const kernel=require('./existing_session_restore.cjs');
const lifetime=require('./offline_restore_pipeline.cjs');
const sha=x=>require('node:crypto').createHash('sha256').update(x).digest('hex');
function load(fidelity){const module={exports:{}};vm.runInNewContext(fs.readFileSync(__dirname+'/retained_session_recovery.cjs','utf8'),{module,exports:module.exports,require:name=>name==='./cn-production-recovery-fidelity.cjs'?fidelity:require(name),Buffer,process,setTimeout,clearTimeout});return module.exports;}
const identity={sourceRevision:'9b25bfa65662b96c0826fe67506b562ea46aa6d0',baselineRevision:'ba6343199f3c834d6a198f83d0c771614292c82b',migrationPlanSha256:'a'.repeat(64),attemptId:'test'};
function child(){const c=new EventEmitter();c.exitCode=null;c.signalCode=null;c.stdout=new PassThrough();c.stdin=new PassThrough();c.kills=[];c.finished=false;c.finish=(code=0,signal=null)=>{if(c.finished)return;c.finished=true;c.exitCode=code;c.signalCode=signal;c.emit('close',code,signal);};c.kill=signal=>{c.kills.push(signal);c.stdout.destroy();c.stdin.destroy();queueMicrotask(()=>c.finish(null,signal));};return c;}
async function fixture(fault){
 let status='I',readOnly=false,currentExtra=false;const queries=[],events=[],opened=[],closed=[],spawns=[],live=[];
 const roles=[{name:'migration_admin',superuser:false,inherit:true,create_role:false,create_db:false,login:false,replication:false,bypass_rls:true,connection_limit:-1,valid_until:null,rolconfig:null},{name:'app_diag_ro',superuser:false,inherit:true,create_role:false,create_db:false,login:true,replication:false,bypass_rls:false,connection_limit:-1,valid_until:null,rolconfig:null}];
 const facts=name=>name==='database'?[{encoding:'UTF8',datcollate:'C',datctype:'C',owner:'migration_admin',acl:[]}]:name==='agePresence'?[{graphs:false,labels:false}]:name==='roles'?roles:name==='namespaces'&&currentExtra?[{name:'unexpected_candidate_schema',owner:'migration_admin',acl:[]}]:[];
 const stream=new EventEmitter();Object.assign(stream,{remoteAddress:'10.0.0.1',remotePort:5432,encrypted:true,authorized:true,destroy:()=>events.push('control-destroyed')});
 const client={connection:{stream},connectionParameters:{query_timeout:10000},connect(){throw Error('NO_NEW_CLIENT');},end(){throw Error('NO_CLIENT_END');},async query(sql,params){queries.push(sql);if(sql.startsWith('BEGIN')){status='T';readOnly=sql.includes('READ ONLY');return {rows:[]};}if(sql==='ROLLBACK'||sql==='COMMIT'){status='I';events.push(sql);return {rows:[]};}if(sql===catalog.identitySql)return {rows:[{database:'workspacex',username:'migration_admin',readonly:readOnly?'on':'off',isolation:'repeatable read'}]};const name=Object.keys(catalog.QUERIES).find(k=>catalog.QUERIES[k]===sql);if(name)return {rows:facts(name)};if(sql.includes('diagnosticPrivileges'))return {rows:[{value:{currentRole:params[0],diagnosticPrivileges:{databaseWrite:fault==='diagnostic-write',schemaWrite:false,tableWrite:false,sequenceWrite:false,definerExecute:false,privilegedMembership:false},roles:[{name:'app_diag_ro',login:true,superuser:false,createRole:false,createDb:false,replication:false,bypassRls:false}]}}]};if(sql==='SELECT 1;'&&fault==='sql')throw Error('private SQL error');return {rows:[]};}};
 const binding={peer:{database:'workspacex',serverAddr:'10.0.0.1',serverPort:5432,systemIdentifier:'42'},role:'migration_admin',pid:101,backendStart:'fixed',tls:{ssl:true},socket:{authorized:true}};
 const backup='b'.repeat(64),provider='c'.repeat(64),peer=sha('10.0.0.1');
 const sourceBinding={side:'source',attemptId:'prior-capture',database:'workspacex',username:'migration_admin',instanceId:'pgm-uf6rg214cp381l49',providerBindingSha256:provider,backupReceiptSha256:backup,peerSha256:peer,port:5432};
 const capture=await catalog.capture(client,sourceBinding,['migration_admin','app_diag_ro']);const sourceRaw=Buffer.from(JSON.stringify(capture));queries.length=0;events.length=0;currentExtra=fault==='extra-object';
 const now=Date.now()/1000,ref=name=>({path:'/sealed/'+name,sha256:sha(name)}),image='sha256:'+'d'.repeat(64);
 const item={database:'workspacex',sourceRdsInstanceId:'pgm-uf6rg214cp381l49',baselineRevision:identity.baselineRevision,dumpExitCode:0,encryptionExitCode:0,dumpBytes:fault==='archive-length'?8:7,recipientCertificateSha256:ref('cert').sha256,ciphertext:{...ref('archive'),bytes:10},sourceCatalog:{path:'/sealed/catalog',sha256:sha(sourceRaw)},sourceCatalogSha256:capture.catalogSha256,backupReceiptSha256:backup,completeClusterRoleNames:['migration_admin','app_diag_ro']};
 const plan={identity,toolRevision:'e'.repeat(40),production:{instanceId:'pgm-uf6rg214cp381l49',hostname:'rds.internal',providerBindingSha256:provider,databasePeers:{workspacex:binding.peer},transportPeers:{workspacex:{peerAddressSha256:peer,port:5432}}},authorization:{identity,productionInstanceId:'pgm-uf6rg214cp381l49',action:'replace-three-production-databases-with-exact-baseline',notBefore:now-10,expiresAt:now+600},recipientCertificate:ref('cert'),recipientKey:ref('key'),clientImage:image,clientImageLabels:{source:'fixed'},databases:{workspacex:item,workspacex_agent:{},workspacex_memory:{}}};
 const raw=Buffer.from(JSON.stringify(plan));const auth={schemaVersion:1,kind:'exact-9b-retained-session-recovery',identity,toolRevision:plan.toolRevision,planPath:'/etc/workspacex-cn/maintenance-recovery/'+identity.sourceRevision+'/test/recovery-plan.json',planSha256:sha(raw),librarySha256:'f'.repeat(64),opensslSha256:'1'.repeat(64),dockerSha256:'2'.repeat(64),operationTimeoutMs:10000,maxCopyBytes:1048576,notBefore:now-10,expiresAt:now+600};
 const context={client,Query:function(){},binding,mode:'control',identityBinding:identity,toolRevision:plan.toolRevision,diagnosticRole:'app_diag_ro',identity:async()=>binding,transactionStatus:()=>status};
 let calls=0;
 const module=load({async mainExistingSession(input,existing){assert.equal(existing.client,client);assert.equal(existing.Query,context.Query);assert.equal(status,'T');let text='';for await(const b of input)text+=b;const request=JSON.parse(text.split('\n')[0]);assert.equal(request.attemptId,identity.attemptId);assert.equal(request.targetSecret.user,'migration_admin');assert(!('password' in request.targetSecret));calls++;if(fault==='fidelity')throw Error('private row error');return {dataFidelityVerified:true};}});
 const io={assertHost:()=>events.push('host-checked'),readPinned:r=>r.path===auth.planPath?raw:r.path===item.sourceCatalog.path?sourceRaw:Buffer.from('pinned'),openPinned:r=>{const fd=100+opened.length;opened.push({fd,path:r.path});return fd;},close:fd=>closed.push(fd),execFileSync(file,args,options){assert.equal(file,'/proc/self/fd/3');assert.equal(options.stdio[3],101);assert.deepEqual(Array.from(args.slice(0,4)),['--config','/nonexistent','--host','unix:///var/run/docker.sock']);if(args[4]==='image')return JSON.stringify([{Id:image,Os:'linux',Architecture:'amd64',Config:{Labels:plan.clientImageLabels}}]);if(args[4]==='ps')return '';throw Error('unexpected daemon action');},spawn(file,args,options){spawns.push({file,args:Array.from(args),stdio:Array.from(options.stdio)});if(fault==='second-spawn'&&spawns.length===2)throw Error('spawn rejected');const c=child();live.push(c);if(file==='/proc/self/fd/5'){assert.equal(options.stdio[5],100);queueMicrotask(()=>c.stdout.end(Buffer.from('archive')));c.stdout.once('end',()=>c.finish());}else{assert.equal(file,'/proc/self/fd/3');assert.equal(options.stdio[3],101);assert(args.includes('none')&&args.includes('--read-only')&&args.includes('--pull')&&args.includes('never'));assert(!args.some(x=>String(x).includes('PGPASSWORD')));let outputDone=false,inputDone=false;c.stdin.resume();const finish=()=>{if(outputDone&&inputDone)c.finish(fault==='decoder-exit'?1:0);};c.stdin.once('finish',()=>{inputDone=true;finish();});c.stdout.once('end',()=>{outputDone=true;finish();});const command=args[args.length-1];queueMicrotask(()=>c.stdout.end(Buffer.from(command.includes('--list')?'; TOC\n':command.includes('--data-only')?'SET standard_conforming_strings = on;\n':'SELECT 1;\n')));}return c;}};
 return {module,context,auth,io,queries,events,opened,closed,spawns,live,calls:()=>calls};
}
(async()=>{let count=0;
 const ok=await fixture();const result=await ok.module.recoverExistingSession(ok.context,ok.auth,ok.io);assert.equal(result.restoreCommitted,true);assert.equal(result.precommitFidelityVerified,true);assert.equal(ok.calls(),1);assert.equal(ok.queries.filter(q=>q==='COMMIT').length,1);assert.equal(ok.context.client.connectionParameters.query_timeout,10000);assert.equal(ok.spawns.length,6);const archiveFds=ok.opened.filter(x=>x.path==='/sealed/archive').map(x=>x.fd);assert.equal(new Set(archiveFds).size,3);assert.equal(ok.closed.length,ok.opened.length);assert(ok.live.every(c=>c.finished));count++;
 for(const fault of ['sql','fidelity','diagnostic-write','second-spawn','decoder-exit','extra-object','archive-length']){const f=await fixture(fault);await assert.rejects(f.module.recoverExistingSession(f.context,f.auth,f.io));assert(!f.queries.includes('COMMIT'));assert.equal(f.closed.length,f.opened.length);assert(f.live.every(c=>c.finished));if(fault==='extra-object'){assert.equal(f.spawns.length,0);assert(!f.queries.includes('SELECT 1;'));}count++;}
 const denied=await fixture();denied.auth.expiresAt=1;await assert.rejects(denied.module.recoverExistingSession(denied.context,denied.auth,denied.io));assert.equal(denied.spawns.length,0);count++;
 console.log(`${count} retained host source integration assertions PASS; mocked process/daemon/fidelity; real restore NOT RUN`);
})().catch(e=>{console.error(e);process.exitCode=1;});
