'use strict';
const { test } = require('node:test'); const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { ControlSession, ID_SQL } = require('./control_connection.cjs');
function fixture() {
 const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wsx-control-fixture-')); const ca = path.join(dir, 'ca'); fs.writeFileSync(ca, 'fixture');
 const binding = { peer: { database: 'db' }, tls: { ssl: true }, role: 'admin', pid: 123, backendStart: 'fixed', clientAddr: 'local' };
 const driver = { queries: [], connectCount: 0, on() {}, async connect() { this.connectCount++; }, async query(sql) { this.queries.push(sql); if(sql.includes('catalog_lock_authority'))return {rows:[{catalog_lock_authority:true,alter_role_authority:true}]}; return { rows: [{ identity: structuredClone(binding) }] }; }, async end() {} };
 const session = new ControlSession(() => driver, () => ({ databases: { db: { database: 'db', ssl: { rejectUnauthorized: true, caFile: ca } } } }));
 const connect = { sequence: 1, roleTargets:['admin'], mode:'control', operation: 'connect', database: 'db', serviceFile: '/fixture', caFile: ca, sslMode: 'verify-full', applicationName: 'wsx-maintenance-control-test', identity: { attemptId: 'test' } };
 return { session, driver, connect, binding, cleanup: () => fs.rmSync(dir, { recursive: true }) };
}
test('LOGIN close and restore retain a single pg Client', async () => { const f = fixture(); try { await f.session.handle(f.connect); await f.session.handle({ sequence: 2, operation: 'execute', sql: 'close fixture' }); await f.session.handle({ sequence: 3, operation: 'execute', sql: 'restore fixture' }); assert.equal(f.driver.connectCount, 1); assert.equal(f.driver.queries.filter(x => x !== ID_SQL && !x.includes('catalog_lock_authority')).length, 2); } finally { f.cleanup(); } });
test('changed backend rejected before mutation', async () => { const f = fixture(); try { await f.session.handle(f.connect); f.binding.pid++; await assert.rejects(f.session.handle({ sequence: 2, operation: 'execute', sql: 'must not run' })); assert(!f.driver.queries.includes('must not run')); } finally { f.cleanup(); } });
test('duplicate sequence and false TLS reject', async () => { const f = fixture(); try { await f.session.handle(f.connect); await assert.rejects(f.session.handle({ sequence: 1, operation: 'execute', sql: 'no' })); const g = fixture(); try { g.binding.tls.ssl = false; await assert.rejects(g.session.handle(g.connect)); } finally { g.cleanup(); } } finally { f.cleanup(); } });
test('diagnostic keeps one client and runs only fixed read-only SQL', async () => { const f=fixture(); try { f.connect.mode='diagnostic';f.connect.applicationName='wsx-maintenance-diagnostic-test';const original=f.driver.query.bind(f.driver);f.driver.query=async sql=>sql===ID_SQL?original(sql):{rows:[{value:{fixed:true}}]};await f.session.handle(f.connect);const reply=await f.session.handle({sequence:2,operation:'query',queryId:'roles'});assert.deepEqual(reply.value,{fixed:true});assert.equal(f.driver.connectCount,1);await assert.rejects(f.session.handle({sequence:3,operation:'execute',sql:'UPDATE forbidden'})); } finally {f.cleanup();} });
test('diagnostic arbitrary query ID fails closed', async () => {const f=fixture();try {f.connect.mode='diagnostic';f.connect.applicationName='wsx-maintenance-diagnostic-test';await f.session.handle(f.connect);await assert.rejects(f.session.handle({sequence:2,operation:'query',queryId:'DELETE arbitrary'}));assert.equal(f.driver.queries.length,1);}finally{f.cleanup();}});
test('insufficient catalog lock capability rejects control before LOGIN mutation',async()=>{const f=fixture();try{const original=f.driver.query.bind(f.driver);f.driver.query=async sql=>sql.includes('catalog_lock_authority')?{rows:[{catalog_lock_authority:false,alter_role_authority:true}]}:original(sql);await assert.rejects(f.session.handle(f.connect));assert(!f.driver.queries.some(sql=>sql.includes('ALTER ROLE')));}finally{f.cleanup();}});
