'use strict';
const { test } = require('node:test'); const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { ControlSession, ID_SQL } = require('./control_connection.cjs');
function fixture() {
 const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wsx-control-fixture-')); const ca = path.join(dir, 'ca'); fs.writeFileSync(ca, 'fixture');
 const binding = { peer: { database: 'db' }, tls: { ssl: true }, role: 'admin', pid: 123, backendStart: 'fixed', clientAddr: 'local' };
 const driver = {connection:{on(name,callback){this.ready=callback;},stream:{remoteAddress:'10.0.0.1',remotePort:5432,localAddress:'10.0.0.2',localPort:1234,encrypted:true,authorized:true}}, queries: [], connectCount: 0, on() {}, async connect() { this.connectCount++; }, async query(sql) { this.connection.ready?.({status:this.txStatus??'I'});this.queries.push(sql); if(sql.includes('catalog_lock_authority'))return {rows:[{catalog_lock_authority:true,alter_role_authority:true}]}; return { rows: [{ identity: structuredClone(binding) }] }; }, async end() {} };
 const session = new ControlSession(() => driver, () => ({ databases: { db: { database: 'db', ssl: { rejectUnauthorized: true, caFile: ca } } } }));
 const connect = { sequence: 1, roleTargets:['admin'], mode:'control', operation: 'connect', database: 'db', serviceFile: '/fixture', caFile: ca, sslMode: 'verify-full', applicationName: 'wsx-maintenance-control-test', identity: { attemptId: 'test' } };
 connect.toolRevision='c'.repeat(40);connect.originalPlanReference={path:'/etc/workspacex-cn/test-original.json',sha256:'a'.repeat(64)};
 session.originalAuthorityLoader=()=>({authority:{identity:structuredClone(connect.identity),toolRevision:connect.toolRevision,sourcePlanPath:connect.originalPlanReference.path,sourcePlanSha256:connect.originalPlanReference.sha256,sourcePlan:{recoveryAuthorization:structuredClone(connect.recoveryAuthorization??null),backupHostReference:structuredClone(connect.backupHostReference??null),diagnosticRole:connect.diagnosticRole,databaseWriterRoles:{[connect.database]:connect.roleTargets??null},controlProbe:{serviceFile:connect.serviceFile,caFile:connect.caFile},databaseProbe:{serviceFile:connect.serviceFile,caFile:connect.caFile},migrationAuthorization:structuredClone(connect.migrationAuthorization??null)}},assert(){}});
 return { session, driver, connect, binding, cleanup: () => fs.rmSync(dir, { recursive: true }) };
}
test('LOGIN close and restore retain a single pg Client', async () => { const f = fixture(); try { await f.session.handle(f.connect); await f.session.handle({ sequence: 2, operation: 'execute', sql: 'close fixture' }); await f.session.handle({ sequence: 3, operation: 'execute', sql: 'restore fixture' }); assert.equal(f.driver.connectCount, 1); assert.equal(f.driver.queries.filter(x => x !== ID_SQL && !x.includes('catalog_lock_authority')).length, 2); } finally { f.cleanup(); } });
test('changed backend rejected before mutation', async () => { const f = fixture(); try { await f.session.handle(f.connect); f.binding.pid++; await assert.rejects(f.session.handle({ sequence: 2, operation: 'execute', sql: 'must not run' })); assert(!f.driver.queries.includes('must not run')); } finally { f.cleanup(); } });
test('duplicate sequence and false TLS reject', async () => { const f = fixture(); try { await f.session.handle(f.connect); await assert.rejects(f.session.handle({ sequence: 1, operation: 'execute', sql: 'no' })); const g = fixture(); try { g.binding.tls.ssl = false; await assert.rejects(g.session.handle(g.connect)); } finally { g.cleanup(); } } finally { f.cleanup(); } });
test('diagnostic keeps one client and runs only fixed read-only SQL', async () => { const f=fixture(); try { f.connect.mode='diagnostic';f.connect.applicationName='wsx-maintenance-diagnostic-test';const original=f.driver.query.bind(f.driver);f.driver.query=async sql=>sql===ID_SQL?original(sql):{rows:[{value:{fixed:true}}]};await f.session.handle(f.connect);const reply=await f.session.handle({sequence:2,operation:'query',queryId:'roles'});assert.deepEqual(reply.value,{fixed:true});assert.equal(f.driver.connectCount,1);await assert.rejects(f.session.handle({sequence:3,operation:'execute',sql:'UPDATE forbidden'})); } finally {f.cleanup();} });
test('diagnostic arbitrary query ID fails closed', async () => {const f=fixture();try {f.connect.mode='diagnostic';f.connect.applicationName='wsx-maintenance-diagnostic-test';await f.session.handle(f.connect);await assert.rejects(f.session.handle({sequence:2,operation:'query',queryId:'DELETE arbitrary'}));assert.equal(f.driver.queries.length,1);}finally{f.cleanup();}});
test('insufficient catalog lock capability rejects control before LOGIN mutation',async()=>{const f=fixture();try{const original=f.driver.query.bind(f.driver);f.driver.query=async sql=>sql.includes('catalog_lock_authority')?{rows:[{catalog_lock_authority:false,alter_role_authority:true}]}:original(sql);await assert.rejects(f.session.handle(f.connect));assert(!f.driver.queries.some(sql=>sql.includes('ALTER ROLE')));}finally{f.cleanup();}});
const {validateMigrationAuthorization,READ_QUERIES}=require('./control_connection.cjs');
function migrationFixture(){
 const f=fixture();const identity={sourceRevision:'9b25bfa65662b96c0826fe67506b562ea46aa6d0',baselineRevision:'ba6343199f3c834d6a198f83d0c771614292c82b',migrationPlanSha256:'a'.repeat(64),attemptId:'test'};
 const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);const hash=v=>require('node:crypto').createHash('sha256').update(canonical(v)).digest('hex');
 const rows=[{name:'0001.sql',checksum:'b'.repeat(64)}];const auth={schemaVersion:1,kind:'exact-9b-existing-session-migration',identity,toolRevision:'c'.repeat(40),checkout:'/var/lib/workspacex-cn/releases/'+identity.sourceRevision,gitExecutableSha256:'d'.repeat(64),canonicalMigratorSha256:'e'.repeat(64),librarySha256:'f'.repeat(64),sourceInventory:rows,sourceInventorySha256:hash(rows),pending:rows,pendingSha256:hash(rows),baselineLedger:[],baselineLedgerSha256:hash([]),lockTimeoutMs:10000,operationTimeoutMs:300000,migrationSource:{user:'admin'},sourceEvidence:{fixture:true}};
 f.connect.identity=identity;f.connect.database='workspacex';f.connect.toolRevision=auth.toolRevision;f.connect.migrationAuthorization=auth;f.binding.peer.database='workspacex';f.session.load=()=>({databases:{workspacex:{database:'workspacex',user:'admin',ssl:{rejectUnauthorized:true,caFile:f.connect.caFile}}}});
 const query=f.driver.query.bind(f.driver);f.driver.query=async sql=>sql.startsWith('SELECT name,checksum FROM')?{rows:[]}:query(sql);
 let calls=0;f.session.checkoutVerifier=value=>{assert.equal(value.checkout,auth.checkout);};f.session.migrationLibraryLoader=()=>({async migrateExistingSession(client,cfg,source,evidence,exception,dir,timeout){calls++;assert.equal(client,f.driver);assert.equal(cfg.database,'workspacex');assert.equal(dir,auth.checkout+'/apps/api/migrations');assert.equal(timeout,10000);return {applied:['0001.sql'],skipped:[]};}});
 const python="import sys,json;from datetime import datetime,timezone,timedelta;sys.path.insert(0,'.agents/skills/workspacex-cn-release/scripts');from test_validate_preflight import fixture;from validate_preflight import validate;v=fixture();i=json.loads(sys.argv[1]);v.update(sourceSha=i['sourceRevision'],baselineSha=i['baselineRevision'],attemptId=i['attemptId']);v['checks']['source.exact_sha']['metadata']={k:i['sourceRevision'] for k in ['requestedSha','repositoryHead','mirrorHead']};v['checks']['runtime.release_lock']['metadata']['attemptId']=i['attemptId'];v['checks']['config.release_manifest']['metadata']['sourceSha']=i['sourceRevision'];v['checks']['build.affected_services']['metadata'].update(sourceSha=i['sourceRevision'],baselineSha=i['baselineRevision']);v['checks']['bootstrap.compatibility']['metadata'].update(baselineSha=i['baselineRevision'],migrationPlanSha256=i['migrationPlanSha256']);n=datetime.now(timezone.utc);v.update(issuedAt=(n-timedelta(seconds=1)).strftime('%Y-%m-%dT%H:%M:%SZ'),expiresAt=(n+timedelta(minutes=10)).strftime('%Y-%m-%dT%H:%M:%SZ'));print(json.dumps({'evidence':v,'validated':validate(v)}))";
 const real=require('node:child_process').execFileSync('python3',['-c',python,JSON.stringify(identity)],{cwd:require('node:path').resolve(__dirname,'../../..'),env:{...process.env,PYTHONPYCACHEPREFIX:'/tmp/wsx-stage-pycache'},encoding:'utf8'});
 const admission=JSON.parse(real);f.session.migrationAdmissionReader=path=>Buffer.from(JSON.stringify(path.endsWith('/prebuild.validated.json')?admission.validated:admission.evidence));
 return {...f,auth,identity,hash,admission,calls:()=>calls};
}
test('exact migration reuses original connected pg Client and fixed library operation',async()=>{const f=migrationFixture();try{await f.session.handle(f.connect);const result=await f.session.handle({sequence:2,operation:'migrate-exact-plan',identity:f.identity});assert.deepEqual(result.value,{applied:['0001.sql'],skipped:[]});assert.equal(f.driver.connectCount,1);assert.equal(f.calls(),1);}finally{f.cleanup();}});
test('missing authorization and stale inventory cannot reach migration library',async()=>{for(const corrupt of [f=>{delete f.connect.migrationAuthorization;},f=>{f.auth.pending=[];f.auth.pendingSha256=f.hash([]);},f=>{f.auth.sourceInventorySha256='0'.repeat(64);}]){const f=migrationFixture();try{corrupt(f);await f.session.handle(f.connect);await assert.rejects(f.session.handle({sequence:2,operation:'migrate-exact-plan',identity:f.identity}));assert.equal(f.calls(),0);}finally{f.cleanup();}}});
test('still-open prior transaction cannot begin migration',async()=>{const f=migrationFixture();try{await f.session.handle(f.connect);f.session.transactionStatus='T';await assert.rejects(f.session.handle({sequence:2,operation:'migrate-exact-plan',identity:f.identity}));assert.equal(f.calls(),0);}finally{f.cleanup();}});
test('LOGIN CAS must leave protocol idle before another operation',async()=>{const f=fixture();try{await f.session.handle(f.connect);f.driver.txStatus='T';await assert.rejects(f.session.handle({sequence:2,operation:'execute',sql:'fixture transaction still open'}));assert.equal(f.session.failed,true);}finally{f.cleanup();}});
test('diagnostic ledger query is compiled read-only and cannot receive caller SQL',()=>{assert(READ_QUERIES['migration-ledger'].startsWith('BEGIN TRANSACTION READ ONLY;'));assert(READ_QUERIES['migration-ledger'].endsWith('ROLLBACK;'));assert(READ_QUERIES.roles.includes('diagnosticPrivileges'));});
const {validateAuthority}=require('./retained_session_recovery.cjs');
function recoveryFixture(){const f=migrationFixture();const now=Date.now()/1000;const auth={schemaVersion:1,kind:'exact-9b-retained-session-recovery',identity:f.identity,toolRevision:f.auth.toolRevision,planPath:'/etc/workspacex-cn/maintenance-recovery/'+f.identity.sourceRevision+'/test/recovery-plan.json',planSha256:'a'.repeat(64),librarySha256:'b'.repeat(64),opensslSha256:'c'.repeat(64),dockerSha256:'d'.repeat(64),operationTimeoutMs:300000,maxCopyBytes:1048576,notBefore:now-10,expiresAt:now+600};f.connect.recoveryAuthorization=auth;f.connect.diagnosticRole='app_diag_ro';f.session.Query=function(){};let recoveries=0;f.session.recoveryLibraryLoader=()=>({validateAuthority,async recoverExistingSession(ctx,value){recoveries++;assert.equal(ctx.client,f.driver);assert.equal(ctx.Query,f.session.Query);assert.deepEqual(value,auth);assert.equal(ctx.diagnosticRole,'app_diag_ro');return {database:'workspacex',existingSession:true,decoderJoined:true,dataFidelityVerified:true,ready:false};}});return {...f,recoveryAuth:auth,recoveries:()=>recoveries};}
test('sealed recovery dispatch reuses the existing client and never accepts plan/SQL from request',async()=>{const f=recoveryFixture();try{await f.session.handle(f.connect);const r=await f.session.handle({sequence:2,operation:'recover-existing-session',identity:f.identity});assert.equal(r.value.existingSession,true);assert.equal(f.driver.connectCount,1);assert.equal(f.recoveries(),1);await assert.rejects(f.session.handle({sequence:3,operation:'recover-existing-session',identity:f.identity}));assert.equal(f.recoveries(),1);}finally{f.cleanup();}});
test('recovery rejects absent/expired/foreign authority, active transactions and caller overrides',async()=>{for(const corrupt of [f=>delete f.connect.recoveryAuthorization,f=>f.recoveryAuth.expiresAt=1,f=>f.recoveryAuth.identity={...f.identity,sourceRevision:'0'.repeat(40)},f=>f.session.transactionStatus='T',f=>f.extra={sql:'DROP DATABASE workspacex'},f=>{f.connect.mode='diagnostic';f.connect.applicationName='wsx-maintenance-diagnostic-test';}]){const f=recoveryFixture();try{if(corrupt.toString().includes('transactionStatus')){await f.session.handle(f.connect);corrupt(f);}else{corrupt(f);await f.session.handle(f.connect);}await assert.rejects(f.session.handle({sequence:2,operation:'recover-existing-session',identity:f.identity,...f.extra}));assert.equal(f.recoveries(),0);assert.equal(f.driver.connectCount,1);}finally{f.cleanup();}}});

for(const name of ['missing','artifact','expired','wrong-plan','tampered','missing-schema'])test('direct persistent SQL protocol rejects '+name+' baseline evidence before DDL',async()=>{const f=migrationFixture();try{await f.session.handle(f.connect);const e=f.admission.evidence;if(name==='missing')f.session.migrationAdmissionReader=()=>{throw Error('receipt-missing');};else{if(name==='artifact')e.phase='artifact-build';if(name==='expired')e.expiresAt=e.issuedAt;if(name==='wrong-plan')e.checks['bootstrap.compatibility'].metadata.migrationPlanSha256='0'.repeat(64);if(name==='missing-schema')delete e.checks['bootstrap.compatibility'].metadata.baselineSchemaSha256;if(name!=='tampered')f.admission.validated.receiptSha256=f.hash(e);else f.admission.validated.receiptSha256='0'.repeat(64);}await assert.rejects(f.session.handle({sequence:2,operation:'migrate-exact-plan',identity:f.identity}),/CONTROL_PROTOCOL_REJECTED/);assert.equal(f.calls(),0);}finally{f.cleanup();}});

test('candidate backend query is fixed read-only and includes exact client port',async()=>{const {READ_QUERIES}=require('./control_connection.cjs');assert.ok(READ_QUERIES['candidate-sessions'].startsWith('BEGIN TRANSACTION READ ONLY;'));assert.ok(READ_QUERIES['candidate-sessions'].endsWith('ROLLBACK;'));assert.ok(READ_QUERIES['candidate-sessions'].includes("'clientPort',client_port"));const f=fixture();try{f.connect.mode='diagnostic';f.connect.applicationName='wsx-maintenance-diagnostic-test';const original=f.driver.query.bind(f.driver);f.driver.query=async sql=>sql===ID_SQL?original(sql):{rows:[{value:{sessions:[]}}]};await f.session.handle(f.connect);assert.deepEqual((await f.session.handle({sequence:2,operation:'query',queryId:'candidate-sessions'})).value,{sessions:[]});}finally{f.cleanup();}});

test('a1 retained connect accepts independently admitted authority and rejects identity/raw/tool drift before client',async()=>{
 for(const bad of [null,'identity','raw','tool']){const f=fixture();try{
 f.connect.identity={sourceRevision:'a1cb4c7683768566b0cf38ffe6a27b0a8c13f4f0',baselineRevision:'ba6343199f3c834d6a198f83d0c771614292c82b',migrationPlanSha256:'d'.repeat(64),attemptId:'test'};
 const authority={identity:structuredClone(f.connect.identity),toolRevision:f.connect.toolRevision,sourcePlanPath:f.connect.originalPlanReference.path,sourcePlanSha256:f.connect.originalPlanReference.sha256,sourcePlan:{recoveryAuthorization:null,backupHostReference:null,diagnosticRole:f.connect.diagnosticRole,databaseWriterRoles:{[f.connect.database]:f.connect.roleTargets},controlProbe:{serviceFile:f.connect.serviceFile,caFile:f.connect.caFile}}};
 f.session.originalAuthorityLoader=()=>({authority,assert(){}});
 if(bad==='identity')f.connect.identity.sourceRevision='0'.repeat(40);if(bad==='raw')f.connect.originalPlanReference.sha256='0'.repeat(64);if(bad==='tool')f.connect.toolRevision='0'.repeat(40);
 if(bad){await assert.rejects(f.session.handle(f.connect));assert.equal(f.driver.connectCount,0);}else{await f.session.handle(f.connect);assert.equal(f.driver.connectCount,1);}
 }finally{f.cleanup();}}
});

test('same identity cannot substitute retained recovery backup diagnostic or role authority',async()=>{
 for(const field of ['recoveryAuthorization','backupHostReference','diagnosticRole','roleTargets']){const f=fixture();try{
 const issued=f.session.originalAuthorityLoader();f.session.originalAuthorityLoader=()=>issued;
 f.connect[field]=field==='roleTargets'?['unapproved-role']:field==='diagnosticRole'?'unapproved-role':{path:'/etc/workspacex-cn/unapproved.json',sha256:'0'.repeat(64)};
 await assert.rejects(f.session.handle(f.connect));assert.equal(f.driver.connectCount,0);assert.equal(f.driver.queries.length,0);
 }finally{f.cleanup();}}
});
