'use strict';
const { test } = require('node:test'); const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { ControlSession, ID_SQL } = require('./control_connection.cjs');
function fixture() {
 const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wsx-control-fixture-')); const ca = path.join(dir, 'ca'); fs.writeFileSync(ca, 'fixture');
 const binding = { peer: { database: 'db' }, tls: { ssl: true }, role: 'admin', pid: 123, backendStart: 'fixed', clientAddr: 'local' };
 const driver = {connection:{on(name,callback){this.ready=callback;},stream:{remoteAddress:'10.0.0.1',remotePort:5432,localAddress:'10.0.0.2',localPort:1234,encrypted:true,authorized:true}}, queries: [], connectCount: 0, on() {}, async connect() { this.connectCount++; }, async query(sql) { this.connection.ready?.({status:this.txStatus??'I'});this.queries.push(sql); if(sql.includes('catalog_lock_authority'))return {rows:[{catalog_lock_authority:true,alter_role_authority:true}]}; return { rows: [{ identity: structuredClone(binding) }] }; }, async end() {} };
 const session = new ControlSession(() => driver, () => ({ databases: { db: { database: 'db', ssl: { rejectUnauthorized: true, caFile: ca } } } }));
 const connect = { sequence: 1, roleTargets:['admin'], mode:'control', operation: 'connect', database: 'db', serviceFile: '/fixture', caFile: ca, sslMode: 'verify-full', applicationName: 'wsx-maintenance-control-test', identity: { attemptId: 'test' } };
 return { session, driver, connect, binding, cleanup: () => fs.rmSync(dir, { recursive: true }) };
}
test('LOGIN close and restore retain a single pg Client', async () => { const f = fixture(); try { await f.session.handle(f.connect); await f.session.handle({ sequence: 2, operation: 'execute', sql: 'close fixture' }); await f.session.handle({ sequence: 3, operation: 'execute', sql: 'restore fixture' }); assert.equal(f.driver.connectCount, 1); assert.equal(f.driver.queries.filter(x => x !== ID_SQL && !x.includes('catalog_lock_authority')).length, 2); } finally { f.cleanup(); } });
test('changed backend rejected before mutation', async () => { const f = fixture(); try { await f.session.handle(f.connect); f.binding.pid++; await assert.rejects(f.session.handle({ sequence: 2, operation: 'execute', sql: 'must not run' })); assert(!f.driver.queries.includes('must not run')); } finally { f.cleanup(); } });
test('duplicate sequence and false TLS reject', async () => { const f = fixture(); try { await f.session.handle(f.connect); await assert.rejects(f.session.handle({ sequence: 1, operation: 'execute', sql: 'no' })); const g = fixture(); try { g.binding.tls.ssl = false; await assert.rejects(g.session.handle(g.connect)); } finally { g.cleanup(); } } finally { f.cleanup(); } });
test('diagnostic keeps one client and runs only fixed read-only SQL', async () => { const f=fixture(); try { f.connect.mode='diagnostic';f.connect.applicationName='wsx-maintenance-diagnostic-test';const original=f.driver.query.bind(f.driver);f.driver.query=async sql=>sql===ID_SQL?original(sql):{rows:[{value:{fixed:true}}]};await f.session.handle(f.connect);const reply=await f.session.handle({sequence:2,operation:'query',queryId:'roles'});assert.deepEqual(reply.value,{fixed:true});assert.equal(f.driver.connectCount,1);await assert.rejects(f.session.handle({sequence:3,operation:'execute',sql:'UPDATE forbidden'})); } finally {f.cleanup();} });
test('diagnostic arbitrary query ID fails closed', async () => {const f=fixture();try {f.connect.mode='diagnostic';f.connect.applicationName='wsx-maintenance-diagnostic-test';await f.session.handle(f.connect);await assert.rejects(f.session.handle({sequence:2,operation:'query',queryId:'DELETE arbitrary'}));assert.equal(f.driver.queries.length,1);}finally{f.cleanup();}});
test('insufficient catalog lock capability rejects control before LOGIN mutation',async()=>{const f=fixture();try{const original=f.driver.query.bind(f.driver);f.driver.query=async sql=>sql.includes('catalog_lock_authority')?{rows:[{catalog_lock_authority:false,alter_role_authority:true}]}:original(sql);await assert.rejects(f.session.handle(f.connect));assert(!f.driver.queries.some(sql=>sql.includes('ALTER ROLE')));}finally{f.cleanup();}});
const {validateMigrationAuthorization,READ_QUERIES}=require('./control_connection.cjs');
function migrationFixture(){
 const f=fixture();const identity={sourceRevision:'9b25bfa65662b96c0826fe67506b562ea46aa6d0',baselineRevision:'ba6343199f3c834d6a198f83d0c771614292c82b',migrationPlanSha256:'a'.repeat(64),attemptId:'test'};
 const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);const hash=v=>require('node:crypto').createHash('sha256').update(canonical(v)).digest('hex');
 const rows=[{name:'0001.sql',checksum:'b'.repeat(64)}];const auth={schemaVersion:1,kind:'exact-9b-existing-session-migration',identity,toolRevision:'c'.repeat(40),checkout:'/var/lib/workspacex-cn/releases/'+identity.sourceRevision,gitExecutableSha256:'d'.repeat(64),canonicalMigratorSha256:'e'.repeat(64),librarySha256:'f'.repeat(64),sourceInventory:rows,sourceInventorySha256:hash(rows),pending:rows,pendingSha256:hash(rows),baselineLedger:[],baselineLedgerSha256:hash([]),lockTimeoutMs:10000,operationTimeoutMs:300000,migrationSource:{user:'admin'},sourceEvidence:{fixture:true}};
 f.connect.identity=identity;f.connect.database='workspacex';f.connect.toolRevision=auth.toolRevision;f.connect.migrationAuthorization=auth;f.binding.peer.database='workspacex';f.session.load=()=>({databases:{workspacex:{database:'workspacex',user:'admin',ssl:{rejectUnauthorized:true,caFile:f.connect.caFile}}}});
 const query=f.driver.query.bind(f.driver);f.driver.query=async sql=>sql.startsWith('SELECT name,checksum FROM')?{rows:[]}:query(sql);
 let calls=0;f.session.checkoutVerifier=value=>{assert.equal(value.checkout,auth.checkout);};f.session.migrationLibraryLoader=()=>({async migrateExistingSession(client,cfg,source,evidence,exception,dir,timeout){calls++;assert.equal(client,f.driver);assert.equal(cfg.database,'workspacex');assert.equal(dir,auth.checkout+'/apps/api/migrations');assert.equal(timeout,10000);return {applied:['0001.sql'],skipped:[]};}});
 return {...f,auth,identity,hash,calls:()=>calls};
}
test('exact migration reuses original connected pg Client and fixed library operation',async()=>{const f=migrationFixture();try{await f.session.handle(f.connect);const result=await f.session.handle({sequence:2,operation:'migrate-exact-plan',identity:f.identity});assert.deepEqual(result.value,{applied:['0001.sql'],skipped:[]});assert.equal(f.driver.connectCount,1);assert.equal(f.calls(),1);}finally{f.cleanup();}});
test('missing authorization and stale inventory cannot reach migration library',async()=>{for(const corrupt of [f=>{delete f.connect.migrationAuthorization;},f=>{f.auth.pending=[];f.auth.pendingSha256=f.hash([]);},f=>{f.auth.sourceInventorySha256='0'.repeat(64);}]){const f=migrationFixture();try{corrupt(f);await f.session.handle(f.connect);await assert.rejects(f.session.handle({sequence:2,operation:'migrate-exact-plan',identity:f.identity}));assert.equal(f.calls(),0);}finally{f.cleanup();}}});
test('still-open prior transaction cannot begin migration',async()=>{const f=migrationFixture();try{await f.session.handle(f.connect);f.session.transactionStatus='T';await assert.rejects(f.session.handle({sequence:2,operation:'migrate-exact-plan',identity:f.identity}));assert.equal(f.calls(),0);}finally{f.cleanup();}});
test('LOGIN CAS must leave protocol idle before another operation',async()=>{const f=fixture();try{await f.session.handle(f.connect);f.driver.txStatus='T';await assert.rejects(f.session.handle({sequence:2,operation:'execute',sql:'fixture transaction still open'}));assert.equal(f.session.failed,true);}finally{f.cleanup();}});
test('diagnostic ledger query is compiled read-only and cannot receive caller SQL',()=>{assert(READ_QUERIES['migration-ledger'].startsWith('BEGIN TRANSACTION READ ONLY;'));assert(READ_QUERIES['migration-ledger'].endsWith('ROLLBACK;'));assert(READ_QUERIES.roles.includes('diagnosticPrivileges'));});
