'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto'),path=require('node:path');
const {ControlSession,ID_SQL}=require('./control_connection.cjs');
const library=require('./cn-maintenance-migrator.cjs');
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const hash=v=>crypto.createHash('sha256').update(v).digest('hex');
function fixture(){
 const evidence=JSON.parse(fs.readFileSync(path.join(__dirname,'../../../deploy/aliyun/cn-release-existing-rds-transport.json'))),now=Date.now()/1000;
 const identity={sourceRevision:'9b25bfa65662b96c0826fe67506b562ea46aa6d0',baselineRevision:'ba6343199f3c834d6a198f83d0c771614292c82b',migrationPlanSha256:'a'.repeat(64),attemptId:'source-fixture'};
 const exception={kind:'aliyun-postgresql-serverless-no-tls',allowedCidrs:['192.168.100.40/32']};
 // Synthetic protected file/STS, never a live credential or approval receipt.
 const raw=Buffer.from(JSON.stringify({environment:{profile:'production',ecsInstanceId:'i-uf6ga92ewloganobbln6',rdsInstanceId:'pgm-uf6rg214cp381l49',rdsTlsException:exception}})),configurationSha256=hash(raw),host='pgm-uf6rg214cp381l49.rwlb.rds.aliyuncs.com';
 const sourceEvidence={request:{regionId:'cn-shanghai',dbInstanceId:'pgm-uf6rg214cp381l49'},configuration:{sha256:configurationSha256,endpointSha256:hash(host+':5432'),regionId:'cn-shanghai',rdsInstanceId:'pgm-uf6rg214cp381l49',host,port:5432,database:'workspacex',user:'app_diag_ro',sslMode:'disable',rdsTlsException:exception},stsResponse:{RequestId:'source-fixture-not-live',AccountId:'1177216024653153'},attributeResponse:evidence.attribute,netInfoResponse:evidence.network};
 const source={accountId:'1177216024653153',regionId:'cn-shanghai',dbInstanceId:'pgm-uf6rg214cp381l49',database:'workspacex',user:'app_diag_ro',endpointSha256:hash(host+':5432'),serverAddressSha256:null,port:null,identityLane:'aliyun-private-endpoint',clientPeerAddressSha256:hash('192.168.100.44'),clientPeerPort:5432,configurationSha256,providerEvidenceSha256:hash(canonical({request:sourceEvidence.request,stsResponse:sourceEvidence.stsResponse,attributeResponse:sourceEvidence.attributeResponse,netInfoResponse:sourceEvidence.netInfoResponse})),sslMode:'disable',clientEncrypted:false,clientTlsAuthorized:false};
 const auth={schemaVersion:1,kind:'existing-production-maintenance-transport',identity,toolRevision:'b'.repeat(40),librarySha256:'c'.repeat(64),source,sourceEvidence,approvedRdsTlsException:exception,sslResponse:evidence.ssl,allowlistResponse:evidence.allowlist,notBefore:now-10,expiresAt:now+600,configurationPath:`/etc/workspacex-cn/maintenance-host/${identity.sourceRevision}/${identity.attemptId}/approved-baseline-deployment.json`,configurationSha256};
 const profile={toolRevision:auth.toolRevision,installedFilesSha256:{'/usr/local/lib/workspacex-cn/cn-maintenance-migrator.cjs':auth.librarySha256},existingProductionTransport:{configurationSha256,ecsInstanceId:'i-uf6ga92ewloganobbln6',rdsInstanceId:'pgm-uf6rg214cp381l49',privateAddress:'192.168.100.44',allowedCidrs:exception.allowedCidrs}};
 const binding={peer:{database:'workspacex',serverAddr:null,serverPort:5432},role:'app_diag_ro',pid:123,backendStart:'fixture',clientAddr:'192.168.100.40',tls:{ssl:false}};
 const stream={remoteAddress:'192.168.100.44',remotePort:5432,localAddress:'192.168.100.40',localPort:12345,encrypted:false,authorized:false};
 const driver={connection:{stream,on(){}},queries:[],connectCount:0,on(){},async connect(){this.connectCount++;},async query(sql){this.queries.push(sql);return sql===ID_SQL?{rows:[{identity:structuredClone(binding)}]}:{rows:[{value:{fixture:true}}]};},async end(){}};
 let options,factoryCount=0,configRaw=raw;
 const session=new ControlSession(value=>{options=value;factoryCount++;return driver;},()=>({databases:{workspacex:{database:'workspacex',user:'app_diag_ro',host,port:5432,ssl:false}}}),undefined,undefined,undefined,undefined,()=>library,p=>p==='/etc/workspacex-cn/trusted-tool-binding.json'?Buffer.from(JSON.stringify(profile)):configRaw);
 const connect={sequence:1,operation:'connect',database:'workspacex',mode:'diagnostic',diagnosticRole:'app_diag_ro',toolRevision:auth.toolRevision,serviceFile:'/fixture',sslMode:'disable',applicationName:'wsx-maintenance-diagnostic-'+identity.attemptId,identity,connectionTransport:auth};
 connect.originalPlanReference={path:'/etc/workspacex-cn/fixture-original.json',sha256:'e'.repeat(64)};const original={identity:structuredClone(identity),toolRevision:auth.toolRevision,sourcePlanPath:connect.originalPlanReference.path,sourcePlanSha256:connect.originalPlanReference.sha256,sourcePlan:{diagnosticRole:connect.diagnosticRole,databaseWriterRoles:{[connect.database]:connect.roleTargets??null},databaseProbe:{serviceFile:connect.serviceFile,caFile:connect.caFile},connectionTransportAuthorizations:{workspacex:{diagnostic:structuredClone(auth)}}}};session.originalAuthorityLoader=()=>({authority:original,assert(){}});
 return {auth,profile,connect,session,driver,binding,stream,factoryCount:()=>factoryCount,options:()=>options,changeConfig:()=>{configRaw=Buffer.from('changed');}};
}
test('existing exception pins preconnect private IP and verifies original client each operation',async()=>{const f=fixture();const hello=await f.session.handle(f.connect);assert.equal(f.options().host,'192.168.100.44');assert.equal(f.options().ssl,false);assert.equal(f.session.options.host,f.auth.sourceEvidence.configuration.host);assert.equal(hello.connection.transport.configurationSha256,f.auth.configurationSha256);await f.session.handle({sequence:2,operation:'query',queryId:'roles'});assert.equal(f.driver.connectCount,1);});
test('unapproved/expired/profile/config/provider exceptions reject before client construction',async()=>{for(const edit of [f=>delete f.connect.connectionTransport,f=>f.auth.expiresAt=1,f=>f.auth.notBefore-=400,f=>delete f.profile.existingProductionTransport,f=>f.profile.existingProductionTransport.configurationSha256='0'.repeat(64),f=>f.profile.existingProductionTransport.allowedCidrs=['0.0.0.0/0'],f=>f.changeConfig(),f=>f.auth.sslResponse.SSLEnabled='on']){const f=fixture();edit(f);await assert.rejects(f.session.handle(f.connect));assert.equal(f.factoryCount(),0);}});
test('observed plaintext peer/source/role drift or postconnect config/profile expiry blocks next SQL',async()=>{for(const edit of [f=>f.stream.localAddress='192.168.100.41',f=>f.stream.remoteAddress='192.168.100.45',f=>f.binding.role='migration_admin',f=>f.changeConfig(),f=>f.profile.toolRevision='0'.repeat(40),f=>f.session.connectionTransport.expiresAt=1]){const f=fixture();await f.session.handle(f.connect);edit(f);await assert.rejects(f.session.handle({sequence:2,operation:'query',queryId:'roles'}));assert(f.driver.queries.every(q=>q===ID_SQL));}});
test('fresh live provider verification reuses retained diagnostic client and rejects SSL drift',async()=>{const f=fixture();await f.session.handle(f.connect);const provider=JSON.parse(fs.readFileSync(path.join(__dirname,'../../../deploy/aliyun/cn-release-existing-rds-transport.json'),'utf8'));const live={attribute:provider.attribute,ssl:provider.ssl,allowlist:provider.allowlist,network:provider.network};const reply=await f.session.handle({sequence:2,operation:'verify-live-transport',provider:live});assert.equal(reply.value.kind,'existing-production-maintenance-transport-verified');assert.deepEqual(reply.value.identity,f.auth.identity);assert.deepEqual(reply.value.peer,f.binding.peer);assert.match(reply.value.proof.providerEvidenceSha256,/^[a-f0-9]{64}$/);assert.equal(f.driver.connectCount,1);const g=fixture();await g.session.handle(g.connect);live.ssl.SSLEnabled='on';await assert.rejects(g.session.handle({sequence:2,operation:'verify-live-transport',provider:live}));});
