#!/usr/bin/env node
/**
 * build-js.mjs — joins the page's ES modules into one file.
 *
 * The sources stay split by concern (motion, diagrams, cases, …) because that
 * is how they are edited. The page loaded them as a module graph: main.js,
 * then the eight it imports, then the four diagrams.js imports — nine
 * requests, three round trips deep before the diagram labels could arrive.
 * On the slow-3G profile the last one landed ~2.6 s after the page did. This
 * is the same move build-css made for the stylesheets.
 *
 * It is not a general bundler, and it refuses what it does not understand:
 *   - imports must be relative, named (`import { a, b } from './x.js'`) or a
 *     default (`import X from './x.js'`) — no `as`, no namespace imports;
 *   - every module shares one scope, so two modules declaring the same
 *     top-level name is an error, not a silent shadow;
 *   - comments are removed only when they start a line, so nothing inside a
 *     string or a regular expression can be touched.
 * Each module is marked `/* module: name *\/` in the output, which the
 * degradation suite uses to break one on purpose.
 *
 *   node scripts/build-js.mjs            write assets/js/site.js
 *   node scripts/build-js.mjs --check    fail if it is out of date
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'assets/js');
const ENTRY = 'main.js';
const TARGET = 'site.js';
const CHECK = process.argv.includes('--check');

const IMPORT = /^import\s+(?:\{([^}]*)\}|([A-Za-z_$][\w$]*))\s+from\s+'\.\/([\w-]+\.js)';\s*$/gm;

const fail = (msg) => { console.error(`✗ build-js: ${msg}`); process.exit(1); };

/* ---- the graph, dependencies first -------------------------------------- */
const order = [];
const seen = new Set();
const sources = new Map();
const visit = (name, trail = []) => {
  if (seen.has(name)) return;
  if (trail.includes(name)) fail(`import cycle: ${[...trail, name].join(' → ')}`);
  const src = readFileSync(join(dir, name), 'utf8');
  sources.set(name, src);
  if (/^\s*import\s/m.test(src.replace(IMPORT, ''))) fail(`${name}: an import this script does not understand`);
  for (const m of src.matchAll(IMPORT)) {
    if (m[1] && /\bas\b/.test(m[1])) fail(`${name}: "import { … as … }" is not supported`);
    visit(m[3], [...trail, name]);
  }
  seen.add(name);
  order.push(name);
};
visit(ENTRY);

/* ---- one scope ---------------------------------------------------------- */
const defaultName = (file) => `__default_${file.replace(/\W/g, '_')}`;
const declared = new Map();
const parts = order.map((name) => {
  let src = sources.get(name);
  const aliases = [];
  src = src.replace(IMPORT, (whole, named, def, from) => {
    if (def) aliases.push(`const ${def} = ${defaultName(from)};`);
    return '';
  });
  src = src.replace(/^export default\s+/m, `const ${defaultName(name)} = `);
  src = src.replace(/^export\s+(?=(?:async\s+)?function\b|const\b|let\b|class\b)/gm, '');
  if (/^export\b/m.test(src)) fail(`${name}: an export this script does not understand`);

  for (const m of src.matchAll(/^(?:async\s+)?(?:function\*?|const|let|class)\s+([A-Za-z_$][\w$]*)/gm)) {
    if (declared.has(m[1])) fail(`"${m[1]}" is declared at the top of both ${declared.get(m[1])} and ${name}`);
    declared.set(m[1], name);
  }
  /* Comments that begin a line: block comments spanning lines, and // lines.
     A comment after code on the same line is left alone. */
  src = src
    .replace(/^[ \t]*\/\*[\s\S]*?\*\/[ \t]*\n/gm, '')
    .replace(/^[ \t]*\/\/.*\n/gm, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
  return `/* module: ${name} */\n${aliases.join('\n')}${aliases.length ? '\n' : ''}${src}\n`;
});

const banner = `/* GENERATED by scripts/build-js.mjs from ${order.length} modules. Edit the sources, not this. */\n`;
const bundle = banner + parts.join('\n');
const target = join(dir, TARGET);

if (CHECK) {
  let current = '';
  try { current = readFileSync(target, 'utf8'); } catch { /* missing */ }
  if (current !== bundle) fail(`assets/js/${TARGET} is out of date — run: node scripts/build-js.mjs`);
  console.log(`✓ ${TARGET} matches its ${order.length} modules`);
} else {
  writeFileSync(target, bundle);
  const raw = order.reduce((n, f) => n + sources.get(f).length, 0);
  console.log(`✓ wrote assets/js/${TARGET} — ${(bundle.length / 1024).toFixed(1)} KB from ${(raw / 1024).toFixed(1)} KB in ${order.length} modules (${order.join(', ')})`);
}
