#!/usr/bin/env node
/**
 * build-brand.mjs — writes the brand mark into every document that needs it.
 *
 * Sources: scripts/brand.mjs for the geometry, assets/css/base.css for the
 * colour. Targets: the sprite in index.html and privacy.html, the inline mark
 * in the social card, and assets/img/favicon.svg.
 *
 * The first three can name CSS variables, so they do. The favicon cannot — a
 * browser fetches it as a standalone document with no stylesheet — so it gets
 * the resolved hexes, read out of base.css at build time rather than typed in.
 * That is why the favicon is generated instead of hand-edited: a hand-edited
 * one is a fifth declaration of the palette waiting to drift.
 *
 *   node scripts/build-brand.mjs            rewrite the four documents
 *   node scripts/build-brand.mjs --check    fail if any is out of date
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { lobes, gradient, VIEWBOX } from './brand.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(join(root, p), 'utf8');
const check = process.argv.includes('--check');

/* ---- colour, read from the token block ---------------------------------- */
const base = read('assets/css/base.css');
const hexes = [1, 2, 3].map((n) => {
  const m = base.match(new RegExp(`--c-${n}-rgb:\\s*([0-9]+)\\s+([0-9]+)\\s+([0-9]+)`));
  if (!m) throw new Error(`base.css declares no --c-${n}-rgb`);
  return '#' + m.slice(1, 4).map((v) => (+v).toString(16).padStart(2, '0')).join('');
});

/* ---- the sprite the two pages share ------------------------------------- */
const sprite =
`<svg width="0" height="0" style="position:absolute" aria-hidden="true" focusable="false">
  <defs>
    ${gradient('bm', (i) => `style="stop-color:var(--c-${i + 1})"`)}
    <symbol id="mark" viewBox="${VIEWBOX}">
${lobes('url(#bm)', '      ')}
    </symbol>
  </defs>
</svg>`;

/* ---- the card's own copy, same geometry, its own gradient id ------------- */
const card =
`<svg viewBox="${VIEWBOX}" aria-hidden="true"><defs>
    ${gradient('g', (i) => `style="stop-color:var(--c-${i + 1})"`)}
    </defs>
${lobes('url(#g)', '    ')}
    </svg>`;

/* ---- the favicon, which has no stylesheet to read ----------------------- */
const favicon =
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${VIEWBOX}">
  <!-- Generated by scripts/build-brand.mjs. Do not edit: the geometry comes
       from scripts/brand.mjs and the colours from base.css. -->
  <defs>
    ${gradient('g', (i) => `stop-color="${hexes[i]}"`)}
  </defs>
  <rect width="32" height="32" rx="7" fill="#08070b"/>
  <g transform="translate(16 16) scale(0.82) translate(-16 -16)">
${lobes('url(#g)', '    ')}
  </g>
</svg>
`;

/* ---- the manifest, so an installed icon is not a screenshot -------------
   Its name comes out of the page's own <title> and its colours out of the
   token block, because a manifest is the classic place for a brand to be
   restated by hand and then quietly disagree with the site. It sits beside
   the assets so build-i18n's depth rewriting carries it into /zh/ unchanged,
   and its icon paths resolve relative to itself. */
const bg = base.match(/--bg:\s*(#[0-9a-f]{3,8})/i)[1];
const meta = (page) => {
  const html = read(page);
  return {
    title: html.match(/<title>([^<]*)<\/title>/)[1],
    description: html.match(/<meta name="description" content="([^"]*)"/)[1],
    lang: html.match(/<html lang="([^"]*)"/)[1],
  };
};
/* One manifest per language. A single shared one meant a Chinese visitor who
   installed the site got an English name and an English description on their
   home screen — the one place the install prompt shows text at all, and the
   one page of the site that had no Chinese version of it. Both are read from
   the page they describe rather than typed here. */
const manifest = (page, start) => {
  const m = meta(page);
  return JSON.stringify({
    name: m.title,
    short_name: 'WorkspaceX',
    description: m.description,
    lang: m.lang,
    start_url: start,
    display: 'standalone',
    background_color: bg,
    theme_color: bg,
    icons: [
      { src: 'img/favicon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
      { src: 'img/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
    ],
  }, null, 2) + '\n';
};

const SPRITE_RE = /<svg width="0" height="0" style="position:absolute"[\s\S]*?<\/svg>/;
const CARD_RE = /<svg viewBox="0 0 32 32"[\s\S]*?<\/svg>/;

const targets = [
  ['index.html', SPRITE_RE, sprite],
  ['privacy.html', SPRITE_RE, sprite],
  ['scripts/og-card.html', CARD_RE, card],
  ['assets/img/favicon.svg', null, favicon],
  ['assets/site.webmanifest', null, manifest('index.html', '/')],
  ['assets/site.zh.webmanifest', null, manifest('zh/index.html', '/zh/')],
];

let stale = 0;
for (const [file, re, block] of targets) {
  /* A generated file may not exist yet — on a first run, or after someone
     deletes it. Missing counts as stale, not as a crash. */
  let before;
  try { before = read(file); } catch { before = ''; }
  const after = re ? before.replace(re, () => block) : block;
  if (re && !re.test(before)) {
    console.error(`✗ ${file}: no brand block found — the marker pattern moved`);
    process.exitCode = 1;
    continue;
  }
  if (after === before) continue;
  if (check) { console.error(`✗ ${file} is out of date with the brand source`); stale++; continue; }
  writeFileSync(join(root, file), after);
  console.log(`✓ wrote ${file}`);
}

if (check) {
  if (stale) { console.error(`\n${stale} file(s) stale — run node scripts/build-brand.mjs`); process.exit(1); }
  console.log(`✓ brand mark and manifest match their sources — ${targets.length} documents`);
}
