#!/usr/bin/env node
/**
 * build-i18n.mjs — generates the prerendered Chinese page.
 *
 * Client-side language switching left the Chinese site unindexable, unlinkable
 * and unshareable: one URL, one language in the markup, and no way to send
 * somebody the Chinese page. Language belongs in the URL.
 *
 *   index.html      English, at /
 *   zh/index.html   Chinese, at /zh/   — generated from index.html + zh.js
 *
 * `--check` re-generates in memory and fails if the committed file differs, so
 * editing the English page or the dictionary without regenerating is caught
 * rather than silently shipping a stale translation.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

const SITE = 'https://workspacex.boardx.us';
const META = {
  zh: {
    title: 'WorkspaceX — 面向人与 AI 的开放协作运行空间',
    description: 'WorkspaceX 是把上下文、智能体、行动、证据与记忆连成一条链的运行层——让意图变成工作，让工作留下证据。',
    ogTitle: 'WorkspaceX — 面向人与 AI 的开放协作运行空间',
    ogDescription: '不是另一个协作工具，而是人与 AI 真正一起把工作完成的运行层：共享上下文、可验证的行动、属于组织的记忆。',
  },
};

const escapeHtml = (s) => s
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

function build() {
  const html = readFileSync(join(root, 'index.html'), 'utf8');
  const zhSource = readFileSync(join(root, 'assets/js/zh.js'), 'utf8');

  // Read the dictionary without importing it, so this stays a pure text
  // transform with no module cache to invalidate.
  const dict = {};
  for (const m of zhSource.matchAll(/^\s*'([\w.]+)':\s*'((?:[^'\\]|\\.)*)'/gm)) {
    dict[m[1]] = m[2].replace(/\\'/g, "'");
  }

  let out = html;

  // 1. swap every translatable node
  out = out.replace(
    /(<([a-z0-9]+)\b[^>]*\sdata-i18n="([\w.]+)"[^>]*>)([\s\S]*?)(<\/\2>)/g,
    (whole, open, tag, key, _body, close) =>
      (dict[key] === undefined ? whole : `${open}${escapeHtml(dict[key])}${close}`),
  );
  out = out.replace(
    /(<([a-z0-9]+)\b[^>]*\sdata-i18n-html="([\w.]+)"[^>]*>)([\s\S]*?)(<\/\2>)/g,
    (whole, open, tag, key, _body, close) =>
      (dict[key] === undefined ? whole : `${open}${dict[key]}${close}`),
  );

  // 2. document language
  out = out.replace('<html lang="en"', '<html lang="zh-Hans"');

  // 3. head: title, description, og
  out = out.replace(/<title>[\s\S]*?<\/title>/, `<title>${escapeHtml(META.zh.title)}</title>`);
  out = out.replace(/(<meta name="description" content=")[^"]*(")/, `$1${escapeHtml(META.zh.description)}$2`);
  out = out.replace(/(<meta property="og:title" content=")[^"]*(")/, `$1${escapeHtml(META.zh.ogTitle)}$2`);
  out = out.replace(/(<meta property="og:description" content=")[^"]*(")/, `$1${escapeHtml(META.zh.ogDescription)}$2`);
  out = out.replace('<meta property="og:locale" content="en">', '<meta property="og:locale" content="zh_Hans">');
  out = out.replace('<meta property="og:locale:alternate" content="zh_Hans">', '<meta property="og:locale:alternate" content="en">');
  out = out.replace(`<link rel="canonical" href="${SITE}/">`, `<link rel="canonical" href="${SITE}/zh/">`);
  out = out.replace(`<meta property="og:url" content="${SITE}/">`, `<meta property="og:url" content="${SITE}/zh/">`);

  // 4. which language button is the current one
  out = out.replace(/(<a class="langswitch__btn" href="\/" )aria-current="true"/, '$1');
  out = out.replace(/(<a class="langswitch__btn" href="\/zh\/" )/, '$1aria-current="true" ');

  // 5. the Chinese card, not the English one
  out = out.replace(/og\.png/g, 'og-zh.png');

  // 6. relative asset paths move one level down
  out = out.replace(/(href|src)="(assets\/)/g, '$1="../$2');

  // 7. mark it, so nobody edits the generated file by hand
  out = out.replace('<head>', '<head>\n<!-- GENERATED by scripts/build-i18n.mjs from index.html + assets/js/zh.js. Do not edit; run the script. -->');

  return out;
}

const generated = build();
const target = join(root, 'zh/index.html');

if (CHECK) {
  let current = '';
  try { current = readFileSync(target, 'utf8'); } catch { /* missing */ }
  if (current !== generated) {
    console.error('\n✗ zh/index.html is out of date — run: node scripts/build-i18n.mjs');
    process.exit(1);
  }
  console.log('✓ zh/index.html matches index.html + zh.js');
} else {
  mkdirSync(join(root, 'zh'), { recursive: true });
  writeFileSync(target, generated);
  console.log(`✓ wrote zh/index.html (${(generated.length / 1024).toFixed(1)} KB)`);
}
