#!/usr/bin/env node
/**
 * build-css.mjs — concatenates the stylesheets into one.
 *
 * The sources stay split by concern, because that is how they are edited. The
 * page loads one file, because that is how it is fetched: six render-blocking
 * stylesheets on a high-latency link means six round trips before anything can
 * paint, and measured on slow 3G nothing rendered at all until 6.2 seconds.
 *
 * `--check` fails if the bundle is stale, so editing a source without
 * rebuilding cannot ship.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

/* Order matters: tokens before the rules that read them, and the per-section
   layer last so it can override the shared components. print.css stays out —
   it is `media="print"` and must not become render-blocking. */
const SOURCES = [
  'fonts.css', 'base.css', 'layout.css', 'components.css',
  'sections.css', 'motion.css', 'diagrams.css',
];

/* The sources are heavily commented on purpose — most of them record why a
   value is what it is, which is the part that gets lost otherwise. None of
   that needs to travel to a browser, and on a 400 kbps link it is seconds. */
const strip = (css) => css
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/\n{3,}/g, '\n\n')
  .replace(/[ \t]+$/gm, '')
  .trim();

const parts = SOURCES.map((name) => {
  const body = readFileSync(join(root, 'assets/css', name), 'utf8');
  return `/* ${name} */\n${strip(body)}\n`;
});

const banner = `/* GENERATED by scripts/build-css.mjs. Edit the sources, not this. */\n`;
const bundle = banner + parts.join('\n');
const target = join(root, 'assets/css/site.css');

if (CHECK) {
  let current = '';
  try { current = readFileSync(target, 'utf8'); } catch { /* missing */ }
  if (current !== bundle) {
    console.error('✗ assets/css/site.css is out of date — run: node scripts/build-css.mjs');
    process.exit(1);
  }
  console.log(`✓ site.css matches its ${SOURCES.length} sources`);
} else {
  writeFileSync(target, bundle);
  const raw = SOURCES.reduce((n, f) => n + readFileSync(join(root, 'assets/css', f), 'utf8').length, 0);
  console.log(`✓ wrote assets/css/site.css — ${(bundle.length / 1024).toFixed(1)} KB from ${(raw / 1024).toFixed(1)} KB of sources`);
}
