import {createHash,randomUUID} from 'node:crypto';
import {expect,type Page,type APIRequestContext} from '@playwright/test';
import {FULLSTACK_E2E as F} from '../fullstack-smoke-fixture';
import {SESSION_TOKEN_STORAGE_KEY} from '../../lib/api-client';

export function origin(){const value=process.env.WHITEBOARD_API_URL??(process.env.WORKSPACEX_API_PORT?`http://127.0.0.1:${process.env.WORKSPACEX_API_PORT}`:undefined);if(!value)throw new Error('WHITEBOARD_API_URL required');return value;}
export async function call(api:APIRequestContext,token:string,method:string,path:string,data?:unknown){const r=await api.fetch(`${origin()}${path}`,{method,headers:{Authorization:`Bearer ${token}`},data});expect(r.ok(),`${method} ${path}: ${r.status()}`).toBe(true);return r;}
export async function login(page:Page,peer=false){await page.goto('/login');await page.getByTestId('login-email').fill(peer?F.leadEmail:F.adminEmail);await page.getByTestId('login-password').fill(peer?F.leadPassword:F.adminPassword);await page.getByTestId('login-submit').click();await expect(page).toHaveURL(/\/(?:home|projects)$/);return(await page.evaluate(key=>localStorage.getItem(key),SESSION_TOKEN_STORAGE_KEY))!;}
export async function canonical(api:APIRequestContext,token:string,id:string){const result=await(await call(api,token,'POST',`/whiteboards/${id}/imports/standard-export`,{requestId:randomUUID()})).json();const downloaded=await(await call(api,token,'GET',result.downloadPath)).json();const bytes=Buffer.from(downloaded.contentBase64,'base64');expect(createHash('sha256').update(bytes).digest('hex')).toBe(downloaded.sha256);return JSON.parse(bytes.toString()) as {board:{epoch:number;seq:number};objects:Array<{kind:string;extensionData?:{contentObject?:Record<string,unknown>}}>};}
export type Evidence={created:string[];revoked:string[];loaded:Array<{url:string;width:number;height:number}>};
export async function observe(page:Page){await page.addInitScript(()=>{const state={created:[] as string[],revoked:[] as string[],loaded:[] as Array<{url:string;width:number;height:number}>};(window as unknown as {__images:typeof state}).__images=state;const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=blob=>{const url=create(blob);state.created.push(url);return url;};URL.revokeObjectURL=url=>{state.revoked.push(url);revoke(url);};const descriptor=Object.getOwnPropertyDescriptor(HTMLImageElement.prototype,'src')!;Object.defineProperty(HTMLImageElement.prototype,'src',{...descriptor,set(value:string){if(value.startsWith('blob:'))this.addEventListener('load',()=>state.loaded.push({url:value,width:this.naturalWidth,height:this.naturalHeight}),{once:true});descriptor.set!.call(this,value);}});});}
export async function painted(page:Page){await expect.poll(()=>page.evaluate(()=>(window as unknown as {__images:Evidence}).__images.loaded.some(image=>image.width===64&&image.height===48))).toBe(true);await expect.poll(()=>page.locator('canvas.lower-canvas').evaluateAll(canvases=>canvases.some(element=>{const canvas=element as HTMLCanvasElement,ctx=canvas.getContext('2d');if(!ctx)return false;const bytes=ctx.getImageData(0,0,canvas.width,canvas.height).data;let matching=0;for(let i=0;i<bytes.length;i+=4)if(bytes[i]===231&&bytes[i+1]===29&&bytes[i+2]===73&&bytes[i+3]===255)matching++;return matching>100;}))).toBe(true);}

