import {it,expect,vi} from 'vitest';
import {readFile} from 'node:fs/promises';
import {BackupMaintenanceService,BackupMaintenanceError,type MaintenanceState,type BackupMaintenancePort,type MaintenanceReceipt} from '../../src/application/whiteboard/backup-maintenance';
import {backupHash,backupTenant,validateBackupManifest} from '../../src/application/whiteboard/board-backup';
import {toOrgId} from '../../src/domain/org-id';
import {ObjectExistsError} from '../../src/application/artifact/ports';
const p={orgId:toOrgId('maint-unit'),userId:'owner'},board='10000000-0000-4000-8000-000000000001',backup='20000000-0000-4000-8000-000000000001',requestId='30000000-0000-4000-8000-000000000001',now=new Date('2026-09-27T00:00:00Z');
function store(){const values=new Map<string,{bytes:Uint8Array;mime:string}>();return {values,putOnce:vi.fn(async(key:string,bytes:Uint8Array,mime:string)=>{if(values.has(key))throw new ObjectExistsError(key);values.set(key,{bytes:bytes.slice(),mime});}),get:async(key:string)=>values.get(key)?.bytes??null,head:async(key:string)=>{const item=values.get(key);return item?{sizeBytes:item.bytes.length,mime:item.mime}:null;}};}
function fixture(){const primary=store(),archive=store(),bytes=new Uint8Array([0,0]),hash=backupHash(bytes),key=`whiteboards/tenants/${backupTenant(p.orgId)}/boards/${board}/snapshot.yjs`;
 const manifest=validateBackupManifest({version:1,backupId:backup,orgId:p.orgId,capturedAt:'2026-08-01T00:00:00Z',board:{id:board,name:'Synthetic',ownerId:'owner',createdAt:'2026-08-01T00:00:00Z',updatedAt:'2026-08-01T00:00:00Z',archived:false,lifecycleRevision:0,tagsRevision:0,members:[],tags:[]},revision:{epoch:1,seq:2},snapshot:{key,hash,bytes:2,mime:'application/vnd.yjs-update'},images:[],comments:[]});
 const manifestBytes=Buffer.from(JSON.stringify(manifest)),prefix=`board-backups/${backupTenant(p.orgId)}/${backup}`;
 archive.values.set(`${prefix}/manifest.json`,{bytes:manifestBytes,mime:'application/json'});archive.values.set(`${prefix}/blobs/${hash}`,{bytes,mime:'application/vnd.yjs-update'});
 const state:MaintenanceState={backup:{manifest,status:'verified',manifestHash:backupHash(manifestBytes)},createdAt:new Date('2026-08-01'),activePins:3,activeRestores:0,snapshot:{epoch:1,seq:2,manifestVersion:1,key,hash,bytes:2,inline:false},receipt:null};
 const release=vi.fn<BackupMaintenancePort['release']>(async(_p,r,_hash,_cutoff,requestHash)=>{const result:MaintenanceReceipt={action:r.action,requestId:r.requestId,backupId:backup,boardId:null,requestHash,releasedPins:3,objectKey:null};state.receipt=result;return result;});
 const recover=vi.fn<BackupMaintenancePort['recover']>(async(_p,r,_hash,ref,requestHash)=>{const result:MaintenanceReceipt={action:r.action,requestId:r.requestId,backupId:backup,boardId:board,requestHash,releasedPins:0,objectKey:ref.key};state.receipt=result;return result;});
 const inspect=vi.fn(async()=>state),repo:BackupMaintenancePort={inspect,release,recover};return {state,primary,archive,repo,service:new BackupMaintenanceService(repo,primary,archive,()=>now)};
}
const releaseRequest={action:'release-pins',backupId:backup,requestId,retentionDays:30};
const recoveryRequest={action:'recover-manifest',backupId:backup,requestId,boardId:board,expectedEpoch:1,expectedSeq:2,targetVersion:1};
it('defaults to verified dry-run without releasing pins or writing files',async()=>{const f=fixture();expect(await f.service.run(p,releaseRequest)).toMatchObject({mode:'dry-run',eligible:true,activePins:3});expect(f.repo.release).not.toHaveBeenCalled();expect(f.primary.putOnce).not.toHaveBeenCalled();});
it('verifies archive before releasing and replays an identical metadata receipt',async()=>{const f=fixture();expect(await f.service.run(p,releaseRequest,true)).toMatchObject({releasedPins:3,replayed:false});expect(await f.service.run(p,releaseRequest,true)).toMatchObject({releasedPins:3,replayed:true});expect(f.repo.release).toHaveBeenCalledOnce();await expect(f.service.run(p,{...releaseRequest,retentionDays:31},true)).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});});
it.each(['missing','corrupt'] as const)('refuses %s archive without dropping pins or writing primary files',async mode=>{const f=fixture(),key=[...f.archive.values.keys()].find(key=>key.includes('/blobs/'))!;if(mode==='missing')f.archive.values.delete(key);else f.archive.values.get(key)!.bytes=new Uint8Array([9,9]);await expect(f.service.run(p,releaseRequest,true)).rejects.toMatchObject({code:'BACKUP_INTEGRITY_FAILED'});expect(f.repo.release).not.toHaveBeenCalled();expect(f.primary.values.size).toBe(0);});
it.each(['restore','young','unverified'] as const)('refuses unsafe retention state: %s',async mode=>{const f=fixture();if(mode==='restore')f.state.activeRestores=1;if(mode==='young')f.state.createdAt=now;if(mode==='unverified')f.state.backup.status='failed_pending_cleanup';await expect(f.service.run(p,releaseRequest,true)).rejects.toBeInstanceOf(BackupMaintenanceError);expect(f.repo.release).not.toHaveBeenCalled();});
it('recovers only the same logical revision into a fresh verified FS pointer',async()=>{const f=fixture();await f.service.run(p,recoveryRequest);expect(f.primary.values.size).toBe(0);const result=await f.service.run(p,recoveryRequest,true);expect(result).toMatchObject({mode:'execute',releasedPins:0});expect(f.primary.values.size).toBe(1);expect([...f.primary.values.keys()][0]).toContain('/recovered/');expect(f.repo.recover).toHaveBeenCalledOnce();expect(JSON.stringify(result)).not.toContain('snapshot');});
it.each(['newer','hash','inline','format'] as const)('refuses incompatible in-place recovery: %s',async mode=>{const f=fixture();if(mode==='newer')f.state.snapshot!.seq=3;if(mode==='hash')f.state.snapshot!.hash='0'.repeat(64);if(mode==='inline')f.state.snapshot!.inline=true;if(mode==='format')f.state.snapshot!.manifestVersion=2;await expect(f.service.run(p,recoveryRequest,true)).rejects.toBeInstanceOf(BackupMaintenanceError);expect(f.primary.values.size).toBe(0);expect(f.repo.recover).not.toHaveBeenCalled();});
it('does not overwrite a concurrent logical edit after the verified file copy',async()=>{const f=fixture();vi.mocked(f.repo.recover).mockRejectedValue(new BackupMaintenanceError('CURRENT_CONTENT_CHANGED'));await expect(f.service.run(p,recoveryRequest,true)).rejects.toMatchObject({code:'CURRENT_CONTENT_CHANGED'});expect(f.primary.values.size).toBe(1);expect(f.state.receipt).toBeNull();expect(f.state.snapshot!.seq).toBe(2);});
it('rechecks authorization before an old successful receipt can be replayed',async()=>{const f=fixture();await f.service.run(p,releaseRequest,true);vi.mocked(f.repo.inspect).mockRejectedValue(new BackupMaintenanceError('NOT_FOUND'));await expect(f.service.run(p,releaseRequest,true)).rejects.toMatchObject({code:'NOT_FOUND'});expect(f.repo.release).toHaveBeenCalledOnce();});
it('retains every live root family while excluding only released backup pins',async()=>{const sql=await readFile(new URL('../../migrations/20260928010000_whiteboard_backup_maintenance.sql',import.meta.url),'utf8');for(const table of ['whiteboard_documents','whiteboard_updates','whiteboard_checkpoints','whiteboard_imports','whiteboard_exports','whiteboard_asset_refs','whiteboard_comment_threads','whiteboard_comment_requests'])expect(sql).toContain(`FROM ${table}`);expect(sql).toContain('whiteboard_backup_pins WHERE org_id=p_org AND object_key=p_key AND released_at IS NULL');expect(sql).not.toContain('DELETE FROM');});

it('cannot release backup pins while a captured history blob is missing',async()=>{
 const f=fixture(),bytes=Buffer.from('AI undo body'),hash=backupHash(bytes);
 f.state.backup.manifest.sourceHistory=[{key:`whiteboards/tenants/${backupTenant(p.orgId)}/boards/${board}/proposal-bodies/${hash}.json`,hash,bytes:bytes.length,mime:'application/json'}];
 const manifestBytes=Buffer.from(JSON.stringify(f.state.backup.manifest));f.state.backup.manifestHash=backupHash(manifestBytes);
 f.archive.values.set(`board-backups/${backupTenant(p.orgId)}/${backup}/manifest.json`,{bytes:manifestBytes,mime:'application/json'});
 await expect(f.service.run(p,releaseRequest,true)).rejects.toMatchObject({code:'BACKUP_INTEGRITY_FAILED'});
 expect(f.repo.release).not.toHaveBeenCalled();
});
