import { describe,expect,it } from 'vitest';
import { WhiteboardObjectGarbageCollector,WhiteboardObjectSweeper,type WhiteboardObjectRetentionRepository,type WhiteboardStoredObject,type WhiteboardObjectSweepRepository } from '../../src/application/whiteboard/object-retention';
import { PgWhiteboardObjectRetentionRepository } from '../../src/infrastructure/whiteboard/pg-object-retention';
import type { DatabasePort,TenantSession } from '../../src/application/ports/database.port';
import { mkdtemp,rm } from 'node:fs/promises';import { tmpdir } from 'node:os';import { join } from 'node:path';
import { FsObjectStore } from '../../src/infrastructure/storage/fs-object-store';import { FsPhysicalPurge } from '../../src/infrastructure/storage/fs-physical-purge';
import { WhiteboardGcRuntime } from '../../src/infrastructure/whiteboard/object-gc-runtime';
const day=86_400_000,base=new Date('2026-09-27T00:00:00.000Z'),tenant='a'.repeat(32),prefix=`whiteboards/tenants/${tenant}/`;
function fixture(roots:string[],objects:WhiteboardStoredObject[],marks:Map<string,Date>=new Map()){const calls={marked:[] as string[],unmarked:[] as string[],swept:[] as string[],audits:[] as unknown[]};const repository:WhiteboardObjectRetentionRepository={roots:async()=>roots.map((key,index)=>({key,kind:index%2?'asset':'document'})),tombstones:async()=>marks,mark:async(_o,value)=>{calls.marked.push(value.key)},unmark:async(_o,keys)=>{calls.unmarked.push(...keys)},sweep:async(_o,value)=>{calls.swept.push(value.key)},audit:async(_o,_r,result)=>{calls.audits.push(result)}};const inventory={head:async()=>null,list:async(_prefix:string,cursor?:string)=>cursor?{objects:objects.slice(2)}:{objects:objects.slice(0,2),cursor:objects.length>2?'next':undefined}};return{gc:new WhiteboardObjectGarbageCollector(repository,inventory,day,()=>base),calls};}
describe('whiteboard object retention',()=>{
  it('marks unreachable old objects, preserves roots and recent uploads, and audits the run',async()=>{const root=`${prefix}boards/b/doc.yjs`,old=`${prefix}boards/b/orphan.yjs`,recent=`${prefix}boards/b/recent.yjs`,f=fixture([root],[{key:root,lastModified:new Date(base.getTime()-3*day),sizeBytes:1,versionTag:'v1'},{key:old,lastModified:new Date(base.getTime()-3*day),sizeBytes:2,versionTag:'v2'},{key:recent,lastModified:new Date(base.getTime()-1000),sizeBytes:3,versionTag:'v3'}]);const result=await f.gc.collect('org',tenant,'run');expect(result).toEqual({roots:1,scanned:3,marked:1,swept:0,retained:2,candidateBytes:0});expect(f.calls.marked).toEqual([old]);expect(f.calls.audits).toEqual([result]);});
  it('sweeps only after a second grace window and rescues a tombstone that became reachable',async()=>{const rescued=`${prefix}boards/b/rescued.yjs`,orphan=`${prefix}boards/b/orphan.yjs`,marks=new Map([[rescued,new Date(base.getTime()-2*day)],[orphan,new Date(base.getTime()-2*day)]]),f=fixture([rescued],[{key:rescued,lastModified:new Date(base.getTime()-4*day),sizeBytes:4,versionTag:'v4'},{key:orphan,lastModified:new Date(base.getTime()-4*day),sizeBytes:8,versionTag:'v8'}],marks);const result=await f.gc.collect('org',tenant,'run');expect(f.calls.unmarked).toEqual([rescued]);expect(f.calls.swept).toEqual([orphan]);expect(result).toMatchObject({swept:1,candidateBytes:8});});
  it('fails closed if inventory crosses the tenant prefix',async()=>{const f=fixture([],[{key:'whiteboards/tenants/evil/boards/b/x',lastModified:new Date(0),sizeBytes:1,versionTag:'v1'}]);await expect(f.gc.collect('org',tenant,'run')).rejects.toThrow('WHITEBOARD_GC_SCOPE_VIOLATION');expect(f.calls.marked).toEqual([]);});
  it('returns document, update, checkpoint, import source, and asset roots from the database root boundary',async()=>{const rows=['document','update','checkpoint','import','asset'].map((kind,index)=>({object_key:`key-${index}`,kind}));const session:TenantSession={query:async<R>()=>({rows:rows as R[]})};const db:DatabasePort={withTenant:async(_org,fn)=>fn(session),withoutTenant:async()=>{throw new Error('no')},close:async()=>{}};expect((await new PgWhiteboardObjectRetentionRepository(db).roots('org')).map(root=>root.kind)).toEqual(['document','update','checkpoint','import','asset']);});
  it('physically purges only the exact claimed generation and records an idempotent receipt',async()=>{const finished:unknown[]=[],claim={objectKey:`${prefix}orphan`,generation:2,sizeBytes:9,objectLastModified:new Date(0),versionTag:'etag-2',receiptId:'receipt'};const repository:WhiteboardObjectSweepRepository={retryable:async()=>[{objectKey:claim.objectKey,objectLastModified:claim.objectLastModified}],claim:async()=>claim,confirm:async()=>true,finish:async(_org,_claim,outcome)=>{finished.push(outcome)}};const purged:string[]=[];const sweeper=new WhiteboardObjectSweeper(repository,{head:async()=>({sizeBytes:9,mime:'x',versionTag:'etag-2'})},{purgeAll:async()=>[],purgeExact:async(objectKey)=>{purged.push(objectKey);return{objectKey,deleted:true,versionMatched:true};}});await expect(sweeper.run('org')).resolves.toEqual([{status:'deleted',receiptId:'receipt'}]);expect(purged).toEqual([claim.objectKey]);expect(finished).toEqual([{deleted:true}]);});
  it('fails closed before physical purge when the object-store generation changed',async()=>{const finished:unknown[]=[],claim={objectKey:`${prefix}orphan`,generation:2,sizeBytes:9,objectLastModified:new Date(0),versionTag:'etag-2',receiptId:'receipt'},repository:WhiteboardObjectSweepRepository={retryable:async()=>[],claim:async()=>claim,confirm:async()=>true,finish:async(_org,_claim,outcome)=>{finished.push(outcome)}};let called=false;const result=await new WhiteboardObjectSweeper(repository,{head:async()=>({sizeBytes:9,mime:'x',versionTag:'etag-3'})},{purgeAll:async()=>[],purgeExact:async objectKey=>{called=true;return{objectKey,deleted:true,versionMatched:true};}}).purgeOne('org',claim.objectKey,claim.objectLastModified);expect(result.status).toBe('rescued');expect(called).toBe(false);expect(finished).toEqual([{deleted:false,error:'OBJECT_VERSION_CHANGED'}]);});
  it('filesystem conditional purge refuses a stale version tag and deletes the exact generation',async()=>{const root=await mkdtemp(join(tmpdir(),'wb-gc-')),key='whiteboards/tenants/a/object';try{const store=new FsObjectStore(root),purge=new FsPhysicalPurge(root);await store.putOnce(key,new Uint8Array([1,2,3]),'x/test');const head=await store.head(key);expect(head?.versionTag).toBeTruthy();await expect(purge.purgeExact(key,'stale')).resolves.toMatchObject({deleted:false,versionMatched:false});expect(await store.get(key)).toEqual(new Uint8Array([1,2,3]));await expect(purge.purgeExact(key,head!.versionTag!)).resolves.toMatchObject({deleted:true,versionMatched:true});expect(await store.get(key)).toBeNull();}finally{await rm(root,{recursive:true,force:true});}});
  it('production runtime scopes scheduled maintenance to configured tenants and prevents overlap',async()=>{const queries:string[]=[];const session:TenantSession={query:async<R>(sql:string)=>{queries.push(sql);return{rows:[] as R[]}}},db:DatabasePort={withTenant:async(_org,fn)=>fn(session),withoutTenant:async()=>{throw new Error('no')},close:async()=>{}};const runtime=new WhiteboardGcRuntime(db,{head:async()=>null},{purgeAll:async()=>[],purgeExact:async objectKey=>({objectKey,deleted:true,versionMatched:true})},{WHITEBOARD_GC_TENANTS:'org-a,org-a,org-b'});expect(runtime.tenants()).toEqual(['org-a','org-b']);await Promise.all([runtime.tick(),runtime.tick()]);expect(queries.filter(sql=>sql.includes('UPDATE whiteboard_asset_refs')).length).toBe(2);expect(queries.filter(sql=>sql.includes('whiteboard_object_tombstones')).length).toBe(2);});
});
