import { describe,expect,it } from 'vitest';
import { WhiteboardObjectGarbageCollector,WhiteboardObjectSweeper,type WhiteboardObjectRetentionRepository,type WhiteboardStoredObject,type WhiteboardObjectSweepRepository } from '../../src/application/whiteboard/object-retention';
import { PgWhiteboardObjectRetentionRepository } from '../../src/infrastructure/whiteboard/pg-object-retention';
import type { DatabasePort,TenantSession } from '../../src/application/ports/database.port';
const day=86_400_000,base=new Date('2026-09-27T00:00:00.000Z'),tenant='a'.repeat(32),prefix=`whiteboards/tenants/${tenant}/`;
function fixture(roots:string[],objects:WhiteboardStoredObject[],marks:Map<string,Date>=new Map()){const calls={marked:[] as string[],unmarked:[] as string[],swept:[] as string[],audits:[] as unknown[]};const repository:WhiteboardObjectRetentionRepository={roots:async()=>roots.map((key,index)=>({key,kind:index%2?'asset':'document'})),tombstones:async()=>marks,mark:async(_o,value)=>{calls.marked.push(value.key)},unmark:async(_o,keys)=>{calls.unmarked.push(...keys)},sweep:async(_o,value)=>{calls.swept.push(value.key)},audit:async(_o,_r,result)=>{calls.audits.push(result)}};const inventory={head:async()=>null,list:async(_prefix:string,cursor?:string)=>cursor?{objects:objects.slice(2)}:{objects:objects.slice(0,2),cursor:objects.length>2?'next':undefined}};return{gc:new WhiteboardObjectGarbageCollector(repository,inventory,day,()=>base),calls};}
describe('whiteboard object retention',()=>{
  it('marks unreachable old objects, preserves roots and recent uploads, and audits the run',async()=>{const root=`${prefix}boards/b/doc.yjs`,old=`${prefix}boards/b/orphan.yjs`,recent=`${prefix}boards/b/recent.yjs`,f=fixture([root],[{key:root,lastModified:new Date(base.getTime()-3*day),sizeBytes:1,versionTag:'v1'},{key:old,lastModified:new Date(base.getTime()-3*day),sizeBytes:2,versionTag:'v2'},{key:recent,lastModified:new Date(base.getTime()-1000),sizeBytes:3,versionTag:'v3'}]);const result=await f.gc.collect('org',tenant,'run');expect(result).toEqual({roots:1,scanned:3,marked:1,swept:0,retained:2,candidateBytes:0});expect(f.calls.marked).toEqual([old]);expect(f.calls.audits).toEqual([result]);});
  it('sweeps only after a second grace window and rescues a tombstone that became reachable',async()=>{const rescued=`${prefix}boards/b/rescued.yjs`,orphan=`${prefix}boards/b/orphan.yjs`,marks=new Map([[rescued,new Date(base.getTime()-2*day)],[orphan,new Date(base.getTime()-2*day)]]),f=fixture([rescued],[{key:rescued,lastModified:new Date(base.getTime()-4*day),sizeBytes:4,versionTag:'v4'},{key:orphan,lastModified:new Date(base.getTime()-4*day),sizeBytes:8,versionTag:'v8'}],marks);const result=await f.gc.collect('org',tenant,'run');expect(f.calls.unmarked).toEqual([rescued]);expect(f.calls.swept).toEqual([orphan]);expect(result).toMatchObject({swept:1,candidateBytes:8});});
  it('fails closed if inventory crosses the tenant prefix',async()=>{const f=fixture([],[{key:'whiteboards/tenants/evil/boards/b/x',lastModified:new Date(0),sizeBytes:1,versionTag:'v1'}]);await expect(f.gc.collect('org',tenant,'run')).rejects.toThrow('WHITEBOARD_GC_SCOPE_VIOLATION');expect(f.calls.marked).toEqual([]);});
  it('discovers document, update, checkpoint, import source, and asset roots',async()=>{const sql:string[]=[];const session:TenantSession={query:async<R>(query:string)=>{sql.push(query);return{rows:[] as R[]}}};const db:DatabasePort={withTenant:async(_org,fn)=>fn(session),withoutTenant:async()=>{throw new Error('no')},close:async()=>{}};await new PgWhiteboardObjectRetentionRepository(db).roots('org');for(const kind of ['document','update','checkpoint','import','asset'])expect(sql[0]).toContain(`'${kind}'`);expect(sql[0]).toContain('whiteboard_asset_refs');});
  it('physically purges only the exact claimed generation and records an idempotent receipt',async()=>{const finished:unknown[]=[],claim={objectKey:`${prefix}orphan`,generation:2,sizeBytes:9,objectLastModified:new Date(0),versionTag:'etag-2',receiptId:'receipt'};const repository:WhiteboardObjectSweepRepository={retryable:async()=>[{objectKey:claim.objectKey,objectLastModified:claim.objectLastModified}],claim:async()=>claim,confirm:async()=>true,finish:async(_org,_claim,outcome)=>{finished.push(outcome)}};const purged:string[]=[];const sweeper=new WhiteboardObjectSweeper(repository,{head:async()=>({sizeBytes:9,mime:'x',versionTag:'etag-2'})},{purgeAll:async keys=>{purged.push(...keys);return keys.map(objectKey=>({objectKey,deleted:true}));}});await expect(sweeper.run('org')).resolves.toEqual([{status:'deleted',receiptId:'receipt'}]);expect(purged).toEqual([claim.objectKey]);expect(finished).toEqual([{deleted:true}]);});
  it('fails closed before physical purge when the object-store generation changed',async()=>{const finished:unknown[]=[],claim={objectKey:`${prefix}orphan`,generation:2,sizeBytes:9,objectLastModified:new Date(0),versionTag:'etag-2',receiptId:'receipt'},repository:WhiteboardObjectSweepRepository={retryable:async()=>[],claim:async()=>claim,confirm:async()=>true,finish:async(_org,_claim,outcome)=>{finished.push(outcome)}};let called=false;const result=await new WhiteboardObjectSweeper(repository,{head:async()=>({sizeBytes:9,mime:'x',versionTag:'etag-3'})},{purgeAll:async()=>{called=true;return[]}}).purgeOne('org',claim.objectKey,claim.objectLastModified);expect(result.status).toBe('rescued');expect(called).toBe(false);expect(finished).toEqual([{deleted:false,error:'OBJECT_VERSION_CHANGED'}]);});
});
