import { describe,it,expect } from 'vitest';
import * as Y from 'yjs';
import { randomUUID } from 'node:crypto';
import { CommentBodyStorage } from '../../src/infrastructure/whiteboard/comment-body-storage';
import { createWhiteboardDocument,executeCommands,WhiteboardCommentService } from '@repo/whiteboard-core';
import { BoardBackupService,backupHash,backupTenant,validateBackupManifest,type BoardBackupManifest,type BoardBackupRepository,type BackupRecord } from '../../src/application/whiteboard/board-backup';
import { ObjectExistsError } from '../../src/application/artifact/ports';
import { toOrgId } from '../../src/domain/org-id';
const p={orgId:toOrgId('backup-unit'),userId:'owner'},board='10000000-0000-4000-8000-000000000001',backup='20000000-0000-4000-8000-000000000001',restore='30000000-0000-4000-8000-000000000001';
function objectStore(){const values=new Map<string,{bytes:Uint8Array;mime:string}>();return{values,putOnce:async(key:string,bytes:Uint8Array,mime:string)=>{if(values.has(key))throw new ObjectExistsError(key);values.set(key,{bytes:new Uint8Array(bytes),mime});},get:async(key:string)=>values.get(key)?.bytes??null,head:async(key:string)=>{const v=values.get(key);return v?{sizeBytes:v.bytes.byteLength,mime:v.mime}:null;}};}
function fixture(){const primary=objectStore(),secondary=objectStore(),doc=createWhiteboardDocument();executeCommands(doc,[{type:'create',object:{id:'note',schemaVersion:1,kind:'sticky',text:'real note',parentId:null,orderKey:'a',style:{},geometry:{x:0,y:0,width:100,height:100,rotation:0}}}],'test');const bytes=Y.encodeStateAsUpdate(doc);doc.destroy();
  const key=`whiteboards/tenants/${backupTenant(p.orgId)}/boards/${board}/epochs/1/snapshot.yjs`,hash=backupHash(bytes);
  primary.values.set(key,{bytes,mime:'application/vnd.yjs-update'});
  const manifest:BoardBackupManifest={version:1,backupId:backup,orgId:p.orgId,capturedAt:'2026-09-27T00:00:00.000Z',board:{id:board,name:'Ideas',ownerId:p.userId,createdAt:'2026-09-27T00:00:00.000Z',updatedAt:'2026-09-27T00:00:00.000Z',archived:false,lifecycleRevision:1,tagsRevision:0,members:[],tags:[]},revision:{epoch:1,seq:1},snapshot:{key,hash,bytes:bytes.byteLength,mime:'application/vnd.yjs-update'},images:[],comments:[]};
  let record:BackupRecord={manifest,status:'preparing',manifestHash:null},published=0,prepared=0,denied=false;const order:string[]=[];
  const repo:BoardBackupRepository={capture:async()=>{if(denied)throw Error('NOT_FOUND');order.push('pins-committed');return record;},read:async()=>{if(denied)throw Error('NOT_FOUND');return record;},verified:async(_p,_b,manifestHash)=>{order.push('verified');record={...record,status:'verified',manifestHash};},failed:async()=>{record={...record,status:'failed_pending_cleanup'};},prepareRestore:async()=>{prepared++;return{completed:published>0};},publishRestore:async()=>{published++;}};
  const service=new BoardBackupService(repo,primary,secondary);
  return{service,repo,manifest,primary,secondary,order,get record(){return record},get published(){return published},get prepared(){return prepared},deny(){denied=true}};
}
async function withComment(f:ReturnType<typeof fixture>,objectId='note'){
  const comment=new WhiteboardCommentService(board,{objectExists:()=>true,isMentionable:()=>true,now:()=>new Date('2026-09-27T00:00:00Z'),uuid:randomUUID});
  const result=comment.dispatch({actorId:p.userId,role:'owner'},{type:'create-comment',requestId:randomUUID(),threadId:randomUUID(),commentId:randomUUID(),objectId,worldPosition:null,body:'PRIVATE COMMENT BODY',mentions:[],expectedRevision:0}),thread=result.threads[0]!;
  const stored=await new CommentBodyStorage(f.primary).split(p,board,thread);
  f.manifest.comments.push({id:thread.id,objectId:thread.objectId,status:thread.status,revision:thread.revision,...stored});return stored;
}
describe('Board joint metadata and body backup',()=>{
  it('keeps comment text out of the manifest and copies verified body bytes to the restored board',async()=>{const f=fixture();const c=await withComment(f);expect(JSON.stringify(f.manifest)).not.toContain('PRIVATE COMMENT BODY');await f.service.backup(p,board,backup);f.primary.values.clear();await f.service.restore(p,backup,restore);const key=`whiteboards/tenants/${backupTenant(p.orgId)}/boards/${restore}/comment-bodies/${c.blob.hash}.json`;expect(Buffer.from((await f.primary.get(key))!).toString()).toContain('PRIVATE COMMENT BODY');expect(f.published).toBe(1);});
  it('rejects live comments anchored to an absent object before publishing an archive',async()=>{const f=fixture();await withComment(f,'missing');await expect(f.service.backup(p,board,backup)).rejects.toThrow('COMMENT_OBJECT_MISSING');expect(f.secondary.values.size).toBe(0);});
  it('rejects comment body sneaked into bodyless PG metadata',async()=>{const f=fixture();await withComment(f);const raw=structuredClone(f.manifest) as any;raw.comments[0].metadata.comments[0].body='hidden';expect(()=>validateBackupManifest(raw)).toThrow();});

  it('publishes manifest last, restores after loss of primary bytes, and replays the restore receipt',async()=>{const f=fixture();const put=f.secondary.putOnce;f.secondary.putOnce=async(...args)=>{expect(f.order[0]).toBe('pins-committed');f.order.push(args[0].endsWith('manifest.json')?'manifest':'blob');return put(...args);};await f.service.backup(p,board,backup);expect(f.order).toEqual(['pins-committed','blob','manifest','verified']);f.primary.values.clear();expect(await f.service.restore(p,backup,restore)).toEqual({boardId:restore,replayed:false});expect(f.published).toBe(1);expect([...f.primary.values.keys()][0]).toContain(`/boards/${restore}/`);expect(await f.service.restore(p,backup,restore)).toEqual({boardId:restore,replayed:true});expect(f.published).toBe(1);});
  it.each(['missing','tampered'] as const)('rejects %s archive bytes before target pin or publication',async mode=>{const f=fixture();await f.service.backup(p,board,backup);const key=[...f.secondary.values.keys()].find(k=>k.includes('/blobs/'))!;if(mode==='missing')f.secondary.values.delete(key);else f.secondary.values.get(key)!.bytes[0]=f.secondary.values.get(key)!.bytes[0]!^255;await expect(f.service.restore(p,backup,restore)).rejects.toThrow('BACKUP_INTEGRITY_FAILED');expect(f.prepared).toBe(0);expect(f.published).toBe(0);});
  it('does not publish failed copy or release persistent source pins',async()=>{const f=fixture();f.secondary.putOnce=async()=>{throw Error('offline');};await expect(f.service.backup(p,board,backup)).rejects.toThrow('offline');expect(f.record.status).toBe('failed_pending_cleanup');expect(f.order).toEqual(['pins-committed']);expect(f.published).toBe(0);});
  it('rejects cross-tenant, mismatched backup ID and fresh access revocation',async()=>{const f=fixture();await f.service.backup(p,board,backup);await expect(f.service.restore({...p,orgId:toOrgId('other')},backup,restore)).rejects.toThrow('NOT_FOUND');await expect(f.service.restore(p,restore,restore)).rejects.toThrow('NOT_FOUND');f.deny();await expect(f.service.restore(p,backup,restore)).rejects.toThrow('NOT_FOUND');expect(f.prepared).toBe(0);});
  it('rejects restoring onto the source identity',async()=>{const f=fixture();await f.service.backup(p,board,backup);await expect(f.service.restore(p,backup,board)).rejects.toThrow('TARGET_MUST_BE_NEW');expect(f.prepared).toBe(0);});
  it('rejects unknown manifest fields and out-of-tenant refs',()=>{const f=fixture();expect(()=>validateBackupManifest({...f.manifest,body:'hidden'})).toThrow();expect(()=>validateBackupManifest({...f.manifest,snapshot:{...f.manifest.snapshot,key:'outside'}})).toThrow('BACKUP_INTEGRITY_FAILED');});
});
