import { createHash,randomUUID } from 'node:crypto';
import JSZip from 'jszip';
import { describe,expect,it } from 'vitest';
import type { Principal } from '../../src/domain/principal';
import { toOrgId } from '../../src/domain/org-id';
import { ObjectExistsError } from '../../src/application/artifact/ports';
import { WhiteboardImportService,type WhiteboardImportRecord,type WhiteboardImportRepository } from '../../src/application/whiteboard/import-service';
import type { WhiteboardRepository } from '../../src/application/whiteboard/ports';
import type { WhiteboardCollaborationStore,WhiteboardCommandsInput } from '../../src/application/whiteboard/collaboration-ports';

const principal:Principal={orgId:toOrgId('import-service-org'),userId:'owner'},boardId='20000000-0000-4000-8000-000000000001';
const digest=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
const crc32=(bytes:Uint8Array)=>{let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^(crc&1?0xedb88320:0);}return(crc^0xffffffff)>>>0;};
const png=()=>{const bytes=new Uint8Array(45),view=new DataView(bytes.buffer);bytes.set(Buffer.from('89504e470d0a1a0a','hex'));view.setUint32(8,13);bytes.set(new TextEncoder().encode('IHDR'),12);view.setUint32(16,32);view.setUint32(20,24);bytes[24]=8;bytes[25]=6;view.setUint32(29,crc32(bytes.subarray(12,29)));bytes.set(new TextEncoder().encode('IEND'),37);view.setUint32(41,crc32(bytes.subarray(37,41)));return bytes;};
class Imports implements WhiteboardImportRepository{
  value:WhiteboardImportRecord|null=null;
  async create(_p:Principal,record:WhiteboardImportRecord){if(!this.value){this.value=structuredClone(record);return{record:structuredClone(record),replayed:false,conflict:false};}const conflict=this.value.sha256!==record.sha256;return{record:structuredClone(this.value),replayed:!conflict,conflict};}
  async get(){return this.value?structuredClone(this.value):null;}
  async savePreflight(_p:Principal,_r:WhiteboardImportRecord,_id:string,report:WhiteboardImportRecord['report']){this.value={...this.value!,stage:'preflighted',counts:report!.counts,report:report!,updatedAt:new Date().toISOString()};return structuredClone(this.value);}
  async claimExecution(_p:Principal,_r:WhiteboardImportRecord,input:{requestId:string;requestHash:string}){if(this.value!.executeRequestId)return{record:structuredClone(this.value!),conflict:this.value!.executeRequestId!==input.requestId||this.value!.executeRequestHash!==input.requestHash};this.value={...this.value!,executeRequestId:input.requestId,executeRequestHash:input.requestHash};return{record:structuredClone(this.value),conflict:false};}
  async releaseExecution(_p:Principal,_r:WhiteboardImportRecord,input:{requestId:string;requestHash:string}){if(this.value?.executeRequestId===input.requestId&&this.value.executeRequestHash===input.requestHash&&this.value.completedSeq===null)this.value={...this.value,executeRequestId:null,executeRequestHash:null};}
  async complete(_p:Principal,_r:WhiteboardImportRecord,input:{requestId:string;requestHash:string;epoch:number;seq:number;report:NonNullable<WhiteboardImportRecord['report']>;assetRefs:Array<{objectKey:string;contentHash:string;byteSize:number}>}){this.value={...this.value!,stage:'completed',counts:input.report.counts,report:input.report,completedEpoch:input.epoch,completedSeq:input.seq};return structuredClone(this.value);}
}
function fixture(failure?:'STALE_EPOCH'){const blobs=new Map<string,Uint8Array>(),imports=new Imports(),writes:WhiteboardCommandsInput[]=[];const objects={putOnce:async(key:string,bytes:Uint8Array)=>{if(blobs.has(key))throw new ObjectExistsError(key);blobs.set(key,new Uint8Array(bytes));},get:async(key:string)=>blobs.get(key)??null,head:async(key:string)=>blobs.has(key)?{sizeBytes:blobs.get(key)!.byteLength,mime:'application/octet-stream'}:null};const boards={get:async(p:Principal,id:string)=>p.orgId===principal.orgId&&id===boardId?{id:boardId,name:'Board',ownerId:'owner',role:'owner',archived:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}:null} as unknown as WhiteboardRepository;const collaboration={writeCommands:async(_p:Principal,_b:string,input:WhiteboardCommandsInput)=>{writes.push(input);if(failure){const error=Object.assign(new Error(failure),{code:failure});failure=undefined;throw error;}return{epoch:input.epoch,seq:1,updateId:input.requestId,replayed:writes.length>1,update:new Uint8Array([0,0])};}} as unknown as WhiteboardCollaborationStore;return{service:new WhiteboardImportService(boards,imports,collaboration,objects,()=>new Date('2026-09-26T00:00:00.000Z')),imports,blobs,writes};}
async function upload(service:WhiteboardImportService,bytes:Uint8Array,mime:'application/json'|'text/csv'|'application/zip'='application/json',source:'miro'|'mural'='miro',requestId=randomUUID(),sourceRevision:string=requestId){return service.upload(principal,boardId,{requestId,source,sourceBoardId:`${source}-source-board`,sourceRevision,fileName:`export.${mime==='application/zip'?'zip':'json'}`,mimeType:mime,sizeBytes:bytes.byteLength,sha256:digest(bytes),contentBase64:Buffer.from(bytes).toString('base64')});}
describe('whiteboard import orchestration',()=>{
  it('preflights and executes one canonical command transaction, then replays safely',async()=>{const f=fixture(),bytes=new TextEncoder().encode(JSON.stringify({widgets:[{id:'a',type:'sticker',text:'Idea'},{id:'b',type:'shape',shape:'diamond',text:'Decide'},{id:'e',type:'connector',startWidget:{id:'a'},endWidget:{id:'b'}}]})),created=await upload(f.service,bytes),preflightId=randomUUID();const report=await f.service.preflight(principal,boardId,created.importId,{requestId:preflightId});expect(report).toMatchObject({executable:true,counts:{discovered:3,accepted:3,unsupported:0}});const executeId=randomUUID(),first=await f.service.execute(principal,boardId,created.importId,{requestId:executeId,expectedEpoch:1});expect(first.status.stage).toBe('completed');expect(f.writes).toHaveLength(1);expect(f.writes[0]?.commands).toHaveLength(3);const replay=await f.service.execute(principal,boardId,created.importId,{requestId:executeId,expectedEpoch:1});expect(replay.replayed).toBe(true);expect(f.writes).toHaveLength(1);await expect(f.service.execute(principal,boardId,created.importId,{requestId:randomUUID(),expectedEpoch:1})).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});});
  it('stores ZIP image bytes separately and canonical content contains only the object ref',async()=>{const f=fixture(),zip=new JSZip(),image=png();zip.file('board.json',JSON.stringify({widgets:[{id:'image',type:'image',fileName:'assets/p.png'}]}));zip.file('assets/p.png',image);const bytes=await zip.generateAsync({type:'uint8array'}),created=await upload(f.service,bytes,'application/zip');await f.service.execute(principal,boardId,created.importId,{requestId:randomUUID(),expectedEpoch:1});const serialized=JSON.stringify(f.writes[0]?.commands);expect(serialized).toContain('/assets/');expect(serialized).not.toContain(Buffer.from(image).toString('base64'));expect([...f.blobs.keys()].filter(key=>key.includes('/assets/'))).toHaveLength(1);});
  it('reports unsupported records instead of silently dropping them and closes integrity/tenant failures',async()=>{const f=fixture(),bytes=new TextEncoder().encode(JSON.stringify({items:[{id:'ok',type:'sticky note',text:'Keep'},{id:'x',type:'video',text:'Unsupported'}]})),created=await upload(f.service,bytes,'application/json','mural');const report=await f.service.preflight(principal,boardId,created.importId,{requestId:randomUUID()});expect(report.counts).toMatchObject({discovered:2,accepted:1,unsupported:1});expect(report.issues).toMatchObject([{code:'UNSUPPORTED_ITEM',sourceId:'x'}]);f.blobs.set(f.imports.value!.sourceObjectKey,new Uint8Array([1]));await expect(f.service.execute(principal,boardId,created.importId,{requestId:randomUUID(),expectedEpoch:1})).rejects.toMatchObject({code:'INTEGRITY_FAILED'});await expect(f.service.getStatus({...principal,orgId:toOrgId('other-org')},boardId,created.importId)).rejects.toMatchObject({code:'NOT_FOUND'});});
  it('rejects a mismatched upload digest before publishing metadata',async()=>{const f=fixture(),bytes=new TextEncoder().encode('{}');await expect(f.service.upload(principal,boardId,{requestId:randomUUID(),source:'miro',sourceBoardId:'source-board',sourceRevision:'r1',fileName:'x.json',mimeType:'application/json',sizeBytes:bytes.byteLength,sha256:'0'.repeat(64),contentBase64:Buffer.from(bytes).toString('base64')})).rejects.toMatchObject({code:'INVALID_UPLOAD'});expect(f.imports.value).toBeNull();});
  it('deduplicates retries by source board and revision even with a new request id',async()=>{const f=fixture(),bytes=new TextEncoder().encode(JSON.stringify({widgets:[]})),revision='rev-42',first=await upload(f.service,bytes,'application/json','miro',randomUUID(),revision),second=await upload(f.service,bytes,'application/json','miro',randomUUID(),revision);expect(second.importId).toBe(first.importId);expect(second.sourceBoardId).toBe('miro-source-board');expect(second.sourceRevision).toBe(revision);});
  it('releases a stale-head claim so the user can retry at the new epoch',async()=>{const f=fixture('STALE_EPOCH'),bytes=new TextEncoder().encode(JSON.stringify({widgets:[{id:'a',type:'sticker',text:'Idea'}]})),created=await upload(f.service,bytes);await expect(f.service.execute(principal,boardId,created.importId,{requestId:randomUUID(),expectedEpoch:1})).rejects.toMatchObject({code:'STALE_HEAD'});expect(f.imports.value?.executeRequestId).toBeNull();await expect(f.service.execute(principal,boardId,created.importId,{requestId:randomUUID(),expectedEpoch:2})).resolves.toMatchObject({epoch:2});});
});
