import { createHash,randomUUID } from 'node:crypto';
import JSZip from 'jszip';
import sharp from 'sharp';
import { WhiteboardImageAssets } from '../../src/application/whiteboard/image-assets';
import { SharpBoardImageVerifier } from '../../src/infrastructure/whiteboard/image-verifier';
import { describe,expect,it } from 'vitest';
import * as Y from 'yjs';
import type { Principal } from '../../src/domain/principal';
import { toOrgId } from '../../src/domain/org-id';
import { ObjectExistsError } from '../../src/application/artifact/ports';
import { WhiteboardImportService,type WhiteboardExportRecord,type WhiteboardExportRepository,type WhiteboardImportRecord,type WhiteboardImportRepository } from '../../src/application/whiteboard/import-service';
import type { WhiteboardRepository } from '../../src/application/whiteboard/ports';
import type { WhiteboardCollaborationStore,WhiteboardCommandsInput } from '../../src/application/whiteboard/collaboration-ports';
import { createWhiteboardDocument,executeCommands } from '@repo/whiteboard-core';

const principal:Principal={orgId:toOrgId('import-service-org'),userId:'owner'},boardId='20000000-0000-4000-8000-000000000001';
const digest=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
const png=()=>sharp({create:{width:32,height:24,channels:4,background:'#4488ff'}}).png().toBuffer();
class Imports implements WhiteboardImportRepository{
  value:WhiteboardImportRecord|null=null;
  async create(_p:Principal,record:WhiteboardImportRecord){if(!this.value){this.value=structuredClone(record);return{record:structuredClone(record),replayed:false,conflict:false};}const conflict=this.value.sha256!==record.sha256;return{record:structuredClone(this.value),replayed:!conflict,conflict};}
  async get(){return this.value?structuredClone(this.value):null;}
  async savePreflight(_p:Principal,_r:WhiteboardImportRecord,_id:string,report:WhiteboardImportRecord['report']){this.value={...this.value!,stage:'preflighted',counts:report!.counts,report:report!,updatedAt:new Date().toISOString()};return structuredClone(this.value);}
  async claimExecution(_p:Principal,_r:WhiteboardImportRecord,input:{requestId:string;requestHash:string}){if(this.value!.executeRequestId)return{record:structuredClone(this.value!),conflict:this.value!.executeRequestId!==input.requestId||this.value!.executeRequestHash!==input.requestHash};this.value={...this.value!,executeRequestId:input.requestId,executeRequestHash:input.requestHash};return{record:structuredClone(this.value),conflict:false};}
  async releaseExecution(_p:Principal,_r:WhiteboardImportRecord,input:{requestId:string;requestHash:string}){if(this.value?.executeRequestId===input.requestId&&this.value.executeRequestHash===input.requestHash&&this.value.completedSeq===null)this.value={...this.value,executeRequestId:null,executeRequestHash:null};}
  async reserveAssets(){}
  async releaseExpiredAssets(){return 0;}
  async complete(_p:Principal,_r:WhiteboardImportRecord,input:{requestId:string;requestHash:string;epoch:number;seq:number;report:NonNullable<WhiteboardImportRecord['report']>;assetRefs:Array<{objectKey:string;contentHash:string;byteSize:number}>}){this.value={...this.value!,stage:'completed',counts:input.report.counts,report:input.report,completedEpoch:input.epoch,completedSeq:input.seq};return structuredClone(this.value);}
}
class Exports implements WhiteboardExportRepository{
  readonly values=new Map<string,WhiteboardExportRecord>();
  async create(_p:Principal,record:WhiteboardExportRecord){const value=this.values.get(record.exportId);if(!value){this.values.set(record.exportId,structuredClone(record));return{record:structuredClone(record),replayed:false,conflict:false};}const conflict=value.requestHash!==record.requestHash||value.actorId!==record.actorId;return{record:structuredClone(value),replayed:!conflict,conflict};}
  async get(_p:Principal,_boardId:string,exportId:string){const value=this.values.get(exportId);return value?structuredClone(value):null;}
}
function fixture(failure?:'STALE_EPOCH',options:{archived?:boolean;role?:'owner'|'editor'|'viewer';update?:Uint8Array}={}){const blobs=new Map<string,Uint8Array>(),mimes=new Map<string,string>(),imports=new Imports(),exports=new Exports(),writes:WhiteboardCommandsInput[]=[];const objects={putOnce:async(key:string,bytes:Uint8Array,mime:string)=>{if(blobs.has(key))throw new ObjectExistsError(key);blobs.set(key,new Uint8Array(bytes));mimes.set(key,mime);},get:async(key:string)=>blobs.get(key)??null,head:async(key:string)=>blobs.has(key)?{sizeBytes:blobs.get(key)!.byteLength,mime:mimes.get(key)??'application/octet-stream'}:null};const boards={get:async(p:Principal,id:string)=>p.orgId===principal.orgId&&id===boardId?{id:boardId,name:'Board',ownerId:'owner',role:options.role??'owner',archived:options.archived??false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}:null} as unknown as WhiteboardRepository;const collaboration={load:async()=>{const doc=new Y.Doc(),update=options.update??Y.encodeStateAsUpdate(doc);doc.destroy();return{epoch:1,seq:0,update,role:options.role??'owner',archived:options.archived??false};},writeCommands:async(_p:Principal,_b:string,input:WhiteboardCommandsInput)=>{writes.push(input);if(failure){const error=Object.assign(new Error(failure),{code:failure});failure=undefined;throw error;}return{epoch:input.epoch,seq:1,updateId:input.requestId,replayed:writes.length>1,update:new Uint8Array([0,0])};}} as unknown as WhiteboardCollaborationStore;return{service:new WhiteboardImportService(boards,imports,collaboration,objects,exports,()=>new Date('2026-09-26T00:00:00.000Z'),new WhiteboardImageAssets(boards,{save:async()=>{},get:async()=>null},objects,new SharpBoardImageVerifier())),imports,exports,blobs,writes};}
async function upload(service:WhiteboardImportService,bytes:Uint8Array,mime:'application/json'|'text/csv'|'application/zip'='application/json',source:'miro'|'mural'='miro',requestId=randomUUID()){return service.upload(principal,boardId,{requestId,source,fileName:`export.${mime==='application/zip'?'zip':'json'}`,mimeType:mime,sizeBytes:bytes.byteLength,sha256:digest(bytes),contentBase64:Buffer.from(bytes).toString('base64')});}
describe('whiteboard import orchestration',()=>{
  it('preflights and executes one canonical command transaction, then replays safely',async()=>{const f=fixture(),bytes=new TextEncoder().encode(JSON.stringify({widgets:[{id:'a',type:'sticker',text:'Idea'},{id:'b',type:'shape',shape:'diamond',text:'Decide'},{id:'e',type:'connector',startWidget:{id:'a'},endWidget:{id:'b'}}]})),created=await upload(f.service,bytes),preflightId=randomUUID();const report=await f.service.preflight(principal,boardId,created.importId,{requestId:preflightId});expect(report).toMatchObject({executable:true,counts:{discovered:3,accepted:3,unsupported:0}});const executeId=randomUUID(),first=await f.service.execute(principal,boardId,created.importId,{requestId:executeId,expectedEpoch:1});expect(first.status.stage).toBe('completed');expect(f.writes).toHaveLength(1);expect(f.writes[0]?.commands).toHaveLength(3);const replay=await f.service.execute(principal,boardId,created.importId,{requestId:executeId,expectedEpoch:1});expect(replay.replayed).toBe(true);expect(f.writes).toHaveLength(1);await expect(f.service.execute(principal,boardId,created.importId,{requestId:randomUUID(),expectedEpoch:1})).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});});
  it('stores ZIP image bytes separately and canonical content contains only the object ref',async()=>{const f=fixture(),zip=new JSZip(),image=await png();zip.file('board.json',JSON.stringify({widgets:[{id:'image',type:'image',fileName:'assets/p.png'}]}));zip.file('assets/p.png',image);const bytes=await zip.generateAsync({type:'uint8array'}),created=await upload(f.service,bytes,'application/zip');await f.service.execute(principal,boardId,created.importId,{requestId:randomUUID(),expectedEpoch:1});const serialized=JSON.stringify(f.writes[0]?.commands);expect(serialized).toContain('board-image-');expect(serialized).toContain('sha256:');expect(serialized).toContain('"intrinsicWidth":32');expect(serialized).toContain('"intrinsicHeight":24');expect(serialized).not.toContain(Buffer.from(image).toString('base64'));expect([...f.blobs.keys()].filter(key=>key.includes('/assets/'))).toHaveLength(1);});
  it('reports a header-only PNG as missing instead of publishing ready content',async()=>{const f=fixture(),zip=new JSZip(),image=(await png()).subarray(0,45);zip.file('board.json',JSON.stringify({widgets:[{id:'image',type:'image',fileName:'assets/p.png'}]}));zip.file('assets/p.png',image);const created=await upload(f.service,await zip.generateAsync({type:'uint8array'}),'application/zip');const report=await f.service.preflight(principal,boardId,created.importId,{requestId:randomUUID()});expect(report.executable).toBe(false);expect(report.counts.accepted).toBe(0);expect([...f.blobs.keys()].filter(key=>key.includes('/assets/'))).toHaveLength(0);});
  it('reports unsupported records instead of silently dropping them and closes integrity/tenant failures',async()=>{const f=fixture(),bytes=new TextEncoder().encode(JSON.stringify({items:[{id:'ok',type:'sticky note',text:'Keep'},{id:'x',type:'video',text:'Unsupported'}]})),created=await upload(f.service,bytes,'application/json','mural');const report=await f.service.preflight(principal,boardId,created.importId,{requestId:randomUUID()});expect(report.counts).toMatchObject({discovered:2,accepted:1,unsupported:1});expect(report.issues).toEqual(expect.arrayContaining([expect.objectContaining({code:'UNSUPPORTED_ITEM',sourceId:'x'}),expect.objectContaining({code:'VALUE_NORMALIZED',sourceId:'ok'})]));expect(report.items.find(item=>item.sourceId==='x')).toMatchObject({outcome:'skipped',reasonCode:'UNSUPPORTED_ITEM'});f.blobs.set(f.imports.value!.sourceObjectKey,new Uint8Array([1]));await expect(f.service.execute(principal,boardId,created.importId,{requestId:randomUUID(),expectedEpoch:1})).rejects.toMatchObject({code:'INTEGRITY_FAILED'});await expect(f.service.getStatus({...principal,orgId:toOrgId('other-org')},boardId,created.importId)).rejects.toMatchObject({code:'NOT_FOUND'});});
  it('rejects a mismatched upload digest before publishing metadata',async()=>{const f=fixture(),bytes=new TextEncoder().encode('{}');await expect(f.service.upload(principal,boardId,{requestId:randomUUID(),source:'miro',fileName:'x.json',mimeType:'application/json',sizeBytes:bytes.byteLength,sha256:'0'.repeat(64),contentBase64:Buffer.from(bytes).toString('base64')})).rejects.toMatchObject({code:'INVALID_UPLOAD'});expect(f.imports.value).toBeNull();});
  it('deduplicates retries by server-derived source identity even with a new request id',async()=>{const f=fixture(),bytes=new TextEncoder().encode(JSON.stringify({board:{id:'miro-source-board'},version:'rev-42',widgets:[]})),first=await upload(f.service,bytes),second=await upload(f.service,bytes);expect(second.importId).toBe(first.importId);expect(second.sourceBoardId).toBe('miro-source-board');expect(second.sourceRevision).toBe('rev-42');});
  it('releases a stale-head claim so the user can retry at the new epoch',async()=>{const f=fixture('STALE_EPOCH'),bytes=new TextEncoder().encode(JSON.stringify({widgets:[{id:'a',type:'sticker',text:'Idea'}]})),created=await upload(f.service,bytes);await expect(f.service.execute(principal,boardId,created.importId,{requestId:randomUUID(),expectedEpoch:1})).rejects.toMatchObject({code:'STALE_HEAD'});expect(f.imports.value?.executeRequestId).toBeNull();await expect(f.service.execute(principal,boardId,created.importId,{requestId:randomUUID(),expectedEpoch:2})).resolves.toMatchObject({epoch:2});});
  it('persists a digest-verifiable export pointer and round-trips through its download path',async()=>{const doc=createWhiteboardDocument();executeCommands(doc,[{type:'create',object:{id:'roundtrip',schemaVersion:1,kind:'sticky',text:'Round trip',style:{},parentId:null,orderKey:'',geometry:{x:1,y:2,width:120,height:80,rotation:0}}}],{});const f=fixture(undefined,{update:Y.encodeStateAsUpdate(doc)}),requestId=randomUUID(),result=await f.service.standardExport(principal,boardId,{requestId});doc.destroy();expect(result).toMatchObject({exportId:requestId,objectKey:expect.stringContaining('/exports/'),downloadPath:`/whiteboards/${boardId}/imports/standard-export/${requestId}`,replayed:false});expect(result.contentBase64).toBeUndefined();expect(f.exports.values.get(requestId)).toMatchObject({sha256:result.sha256,sizeBytes:result.sizeBytes,objectKey:result.objectKey});const replay=await f.service.standardExport(principal,boardId,{requestId});expect(replay.replayed).toBe(true);const download=await f.service.downloadStandardExport(principal,boardId,requestId),body=Buffer.from(download.contentBase64,'base64');expect(digest(body)).toBe(result.sha256);const packageBody=JSON.parse(body.toString());expect(packageBody).toMatchObject({format:'workspacex.board.v1',board:{id:boardId,epoch:1,seq:0},objects:[{id:'roundtrip',text:'Round trip'}]});const imported=await upload(fixture().service,body);expect(imported.sourceBoardId).toBe(boardId);});
  it('rejects export idempotency conflicts and corrupted stored bytes',async()=>{const f=fixture(),requestId=randomUUID(),first=await f.service.standardExport(principal,boardId,{requestId});f.exports.values.get(requestId)!.requestHash='0'.repeat(64);await expect(f.service.standardExport(principal,boardId,{requestId})).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});f.exports.values.get(requestId)!.requestHash=createHash('sha256').update(JSON.stringify({boardId,epoch:1,seq:0,sha256:first.sha256})).digest('hex');f.blobs.set(first.objectKey,new Uint8Array([1]));await expect(f.service.downloadStandardExport(principal,boardId,requestId)).rejects.toMatchObject({code:'INTEGRITY_FAILED'});});
  it('enforces export ACL and archived-board policy',async()=>{const input={requestId:randomUUID()};await expect(fixture(undefined,{role:'viewer'}).service.standardExport(principal,boardId,input)).rejects.toMatchObject({code:'FORBIDDEN'});await expect(fixture(undefined,{archived:true}).service.standardExport(principal,boardId,input)).rejects.toMatchObject({code:'ARCHIVED'});await expect(fixture().service.standardExport({...principal,orgId:toOrgId('outside')},boardId,input)).rejects.toMatchObject({code:'NOT_FOUND'});});
});

it('rejects an oversized migration as a whole before canonical writes',async()=>{
 const f=fixture(),bytes=Buffer.from(JSON.stringify({items:Array.from({length:201},(_,index)=>({id:`n${index}`,type:'sticky_note',text:'keep'}))}));
 const created=await upload(f.service,bytes),report=await f.service.preflight(principal,boardId,created.importId,{requestId:randomUUID()});
 expect(report).toMatchObject({executable:false,counts:{discovered:201,accepted:0,unsupported:201},items:[],issues:[{code:'OBJECT_LIMIT'}]});
 await expect(f.service.execute(principal,boardId,created.importId,{requestId:randomUUID(),expectedEpoch:1})).rejects.toMatchObject({code:'UNSUPPORTED_FORMAT'});
 expect(f.writes).toHaveLength(0);
});
