import { randomUUID } from 'node:crypto';
import { describe,expect,it } from 'vitest';
import { ObjectExistsError } from '../../src/application/artifact/ports';
import type { DatabasePort,TenantSession } from '../../src/application/ports/database.port';
import type { WhiteboardUpdateValidator } from '../../src/application/whiteboard/collaboration-ports';
import { PgWhiteboardCollaborationStore } from '../../src/infrastructure/whiteboard/pg-collaboration-store';
import { toOrgId } from '../../src/domain/org-id';
const p={orgId:toOrgId('object-manifest-org'),userId:'owner'},boardId=randomUUID();
const validator:WhiteboardUpdateValidator={objects:async()=>[],objectIds:async()=>[],diff:async snapshot=>snapshot,commands:async()=>({snapshot:new Uint8Array([0,1,2]),update:new Uint8Array([1,2])}),validate:async()=>({snapshot:new Uint8Array([0,1,2]),update:new Uint8Array([1,2])})};
function fixture(readback:'ok'|'missing'|'tampered'='ok'){const queries:{sql:string;params:readonly unknown[]}[]=[],blobs=new Map<string,Uint8Array>();const session:TenantSession={async query<R>(sql:string,params:readonly unknown[]=[]){queries.push({sql,params});const rows=sql.startsWith('SELECT owner_id')?[{owner_id:p.userId,archived:false}]:sql.startsWith('SELECT epoch,seq,snapshot')?[{epoch:1,seq:'0',snapshot:Buffer.from([0,0]),object_key:null,content_hash:null,byte_size:null}]:sql.startsWith('SELECT count')?[{count:'0'}]:[];return{rows:rows as R[]};}};const db:DatabasePort={withTenant:async(_org,fn)=>fn(session),withoutTenant:async()=>{throw new Error('no')},close:async()=>{}};const objects={putOnce:async(key:string,bytes:Uint8Array)=>{if(blobs.has(key))throw new ObjectExistsError(key);blobs.set(key,new Uint8Array(bytes));},get:async(key:string)=>readback==='missing'?null:readback==='tampered'?new Uint8Array([9]):blobs.get(key)??null,head:async(key:string)=>blobs.has(key)?{sizeBytes:blobs.get(key)!.byteLength,mime:'application/vnd.yjs-update'}:null};return{store:new PgWhiteboardCollaborationStore(db,validator,120,objects),queries,blobs};}
describe('object-backed whiteboard manifests',()=>{
  it('verifies immutable readback before publishing refs and writes no body to PG',async()=>{const f=fixture(),ack=await f.store.writeCommands(p,boardId,{epoch:1,requestId:randomUUID(),commands:[{type:'delete',id:'note'}]});expect(ack.seq).toBe(1);expect(f.blobs.size).toBe(2);const insert=f.queries.find(query=>query.sql.startsWith('INSERT INTO whiteboard_updates('))!;expect(insert.sql).toContain('update_object_key');expect(insert.sql).toContain('VALUES($1,$2,$3,$4,$5,$6,$7,NULL');expect(insert.params.some(value=>Buffer.isBuffer(value))).toBe(false);const update=f.queries.find(query=>query.sql.startsWith('UPDATE whiteboard_documents SET seq'))!;expect(update.sql).toContain('snapshot=NULL');expect(update.params.some(value=>Buffer.isBuffer(value))).toBe(false);for(const key of f.blobs.keys())expect(key).toMatch(/^whiteboards\/tenants\/[a-f0-9]{32}\/boards\//);});
  it.each(['missing','tampered'] as const)('fails closed when object-store readback is %s',async mode=>{const f=fixture(mode);await expect(f.store.writeCommands(p,boardId,{epoch:1,requestId:randomUUID(),commands:[{type:'delete',id:'note'}]})).rejects.toMatchObject({code:'INTEGRITY_FAILED'});expect(f.queries.some(query=>query.sql.startsWith('INSERT INTO whiteboard_updates'))).toBe(false);});
});
