import { createHash,randomUUID } from 'node:crypto';
import { describe,expect,it } from 'vitest';
import { ObjectExistsError } from '../../src/application/artifact/ports';
import type { DatabasePort,TenantSession } from '../../src/application/ports/database.port';
import type { WhiteboardUpdateValidator } from '../../src/application/whiteboard/collaboration-ports';
import { PgWhiteboardCollaborationStore } from '../../src/infrastructure/whiteboard/pg-collaboration-store';
import { toOrgId } from '../../src/domain/org-id';
const p={orgId:toOrgId('object-manifest-org'),userId:'owner'},boardId=randomUUID();
const validator:WhiteboardUpdateValidator={objects:async()=>[],objectIds:async()=>[],diff:async snapshot=>snapshot,commands:async()=>({objectIds:[],snapshot:new Uint8Array([0,1,2]),update:new Uint8Array([1,2])}),validate:async()=>({objectIds:[],snapshot:new Uint8Array([0,1,2]),update:new Uint8Array([1,2])})};
function fixture(readback:'ok'|'missing'|'tampered'='ok',withObjects=true,legacyReplay?:{id:string;hash:string;bytes:Uint8Array}){const queries:{sql:string;params:readonly unknown[]}[]=[],blobs=new Map<string,Uint8Array>();let doc={epoch:1,seq:'0',snapshot:Buffer.from([0,0]) as Buffer|null,object_key:null as string|null,content_hash:null as string|null,byte_size:null as string|null};let replay=legacyReplay?{seq:'1',request_hash:legacyReplay.hash,update:Buffer.from(legacyReplay.bytes) as Buffer|null,update_object_key:null as string|null,update_hash:null as string|null,update_size:null as string|null}:null;const session:TenantSession={async query<R>(sql:string,params:readonly unknown[]=[]){queries.push({sql,params});let rows:unknown[]=sql.startsWith('SELECT owner_id')?[{owner_id:p.userId,archived:false}]:sql.startsWith('SELECT epoch,seq,snapshot')?[{...doc}]:sql.startsWith('SELECT epoch,seq::text,actor_id')&&legacyReplay&&replay?[{epoch:1,actor_id:p.userId,update_id:legacyReplay.id,...replay}]:sql.startsWith('SELECT object_key,content_hash')?[{...doc}]:sql.startsWith('SELECT seq,request_hash')&&legacyReplay&&params[4]===legacyReplay.id&&replay?[{...replay}]:sql.startsWith('SELECT count')?[{count:'0'}]:[];if(sql.startsWith('UPDATE whiteboard_documents SET snapshot=NULL,manifest_version=1')&&sql.includes('AND seq=$7')){doc={...doc,snapshot:null,object_key:String(params[3]),content_hash:String(params[4]),byte_size:String(params[5])};rows=[{object_key:doc.object_key,content_hash:doc.content_hash,byte_size:doc.byte_size,snapshot:null}];}if(sql.startsWith('UPDATE whiteboard_updates SET update=NULL')&&replay){replay={...replay,update:null,update_object_key:String(params[5]),update_hash:String(params[6]),update_size:String(params[7])};rows=[{object_key:replay.update_object_key,content_hash:replay.update_hash,byte_size:replay.update_size,snapshot:null}];}if(sql.startsWith('UPDATE whiteboard_documents SET seq=$3'))doc={...doc,seq:String(params[2]),snapshot:null,object_key:String(params[3]),content_hash:String(params[4]),byte_size:String(params[5])};return{rows:rows as R[]};}};const db:DatabasePort={withTenant:async(_org,fn)=>fn(session),withoutTenant:async()=>{throw new Error('no')},close:async()=>{}};const objects={putOnce:async(key:string,bytes:Uint8Array)=>{if(blobs.has(key))throw new ObjectExistsError(key);blobs.set(key,new Uint8Array(bytes));},get:async(key:string)=>readback==='missing'?null:readback==='tampered'?new Uint8Array([9]):blobs.get(key)??null,head:async(key:string)=>blobs.has(key)?{sizeBytes:blobs.get(key)!.byteLength,mime:'application/vnd.yjs-update'}:null};return{store:new PgWhiteboardCollaborationStore(db,validator,120,withObjects?objects:undefined),queries,blobs,get doc(){return doc},get replay(){return replay}};}
describe('object-backed whiteboard manifests',()=>{
  it('read-through migrates legacy bytes, verifies readback, and publishes only refs for new writes',async()=>{const f=fixture();await expect(f.store.load(p,boardId)).resolves.toMatchObject({epoch:1,seq:0});expect(f.doc).toMatchObject({snapshot:null,object_key:expect.any(String),content_hash:expect.stringMatching(/^[a-f0-9]{64}$/),byte_size:'2'});const ack=await f.store.writeCommands(p,boardId,{epoch:1,requestId:randomUUID(),commands:[{type:'delete',id:'note'}]});expect(ack.seq).toBe(1);expect(f.blobs.size).toBe(3);const insert=f.queries.find(query=>query.sql.startsWith('INSERT INTO whiteboard_updates('))!;expect(insert.sql).toContain('update_object_key');expect(insert.sql).toContain('VALUES($1,$2,$3,$4,$5,$6,$7,NULL');expect(insert.params.some(value=>Buffer.isBuffer(value))).toBe(false);const update=f.queries.find(query=>query.sql.startsWith('UPDATE whiteboard_documents SET seq'))!;expect(update.sql).toContain('snapshot=NULL');expect(update.params.some(value=>Buffer.isBuffer(value))).toBe(false);for(const key of f.blobs.keys())expect(key).toMatch(/^whiteboards\/tenants\/[a-f0-9]{32}\/boards\//);});
  it.each(['missing','tampered'] as const)('fails closed when object-store readback is %s',async mode=>{const f=fixture(mode);await expect(f.store.writeCommands(p,boardId,{epoch:1,requestId:randomUUID(),commands:[{type:'delete',id:'note'}]})).rejects.toMatchObject({code:'INTEGRITY_FAILED'});expect(f.queries.some(query=>query.sql.startsWith('INSERT INTO whiteboard_updates'))).toBe(false);});
  it('allows legacy reads but refuses every new write when ObjectStore is not composed',async()=>{const f=fixture('ok',false);await expect(f.store.load(p,boardId)).resolves.toMatchObject({update:new Uint8Array([0,0])});await expect(f.store.writeCommands(p,boardId,{epoch:1,requestId:randomUUID(),commands:[{type:'delete',id:'note'}]})).rejects.toMatchObject({code:'DEPENDENCY_UNAVAILABLE'});expect(f.queries.some(query=>query.sql.startsWith('INSERT INTO whiteboard_updates'))).toBe(false);});
  it('read-through migrates a legacy idempotency update before replaying it',async()=>{const id=randomUUID(),bytes=new Uint8Array([7,8]),hash=createHash('sha256').update(Buffer.concat([Buffer.from('update:'),Buffer.from(bytes)])).digest('hex'),f=fixture('ok',true,{id,hash,bytes});const ack=await f.store.append(p,boardId,{epoch:1,updateId:id,gestureId:id,update:bytes});expect(ack).toMatchObject({replayed:true,update:bytes});expect(f.replay).toMatchObject({update:null,update_object_key:expect.any(String),update_hash:expect.stringMatching(/^[a-f0-9]{64}$/),update_size:'2'});expect(f.blobs.size).toBe(1);});
  it('exposes a bounded tenant-scoped backfill hook for legacy updates that are never replayed',async()=>{const id=randomUUID(),bytes=new Uint8Array([4,5]),f=fixture('ok',true,{id,hash:'unused',bytes});await expect(f.store.backfillLegacyBoard(p,boardId,100)).resolves.toEqual({migrated:1,remaining:0});expect(f.replay).toMatchObject({update:null,update_object_key:expect.any(String)});expect(f.queries.some(query=>query.sql.includes('update IS NOT NULL ORDER BY epoch,seq LIMIT'))).toBe(true);});
});
