import type {ModelCallInput} from '../../src/application/agent-run/ports';
import {describe,expect,it,vi} from 'vitest';
import * as Y from 'yjs';
import {createWhiteboardDocument,executeCommands,readObjects} from '@repo/whiteboard-core';
import type {WhiteboardCommand,WhiteboardObject} from '@repo/contracts/whiteboard-document';
import {clusterCommands,WhiteboardOrganizeService} from '../../src/application/whiteboard/organize-service';
import {inverse} from '../../src/application/whiteboard/proposal-service';
import {toOrgId} from '../../src/domain/org-id';
const notes:WhiteboardObject[]=Array.from({length:30},(_,i)=>({id:`note-${i}`,schemaVersion:1,kind:'sticky',text:i<15?'新人不知道第一步':'产品响应太慢',style:{},parentId:null,orderKey:String(i),geometry:{x:i*20,y:0,width:180,height:180,rotation:0}}));
const groups={clusters:[{label:'入门引导',objectIds:notes.slice(0,15).map(o=>o.id)},{label:'性能体验',objectIds:notes.slice(15).map(o=>o.id)}]};
function deps(){const doc=createWhiteboardDocument();executeCommands(doc,notes.map(object=>({type:'create',object})),{});const update=Y.encodeStateAsUpdate(doc);doc.destroy();
  const session={query:vi.fn()},db={withTenant:vi.fn(async(_org:unknown,fn:(s:unknown)=>Promise<unknown>)=>fn(session))},audit={lockHead:vi.fn(async()=>({epoch:1,seq:1,actorRole:'owner'})),resolveActor:vi.fn(async()=>({actorId:'agent',kind:'ai',delegatedBy:'user',scopes:['board:read','board:write'],model:'configured/model',skill:'skill-v1'}))};
  const collaboration={load:vi.fn(async()=>({epoch:1,seq:1,update}))},proposals={create:vi.fn(async(_p:unknown,_b:string,value:{action:{type:string;labels:string[];commands:WhiteboardCommand[]}})=>value)},agents={resolvePublished:vi.fn(async()=>({agentId:'agent',agentVersionId:'agent-v1',skillVersionIds:['skill-v1'],modelProvider:'configured',modelId:'model',instructions:'Use semantic topics'}))},skills={readPinnedSkills:vi.fn(async()=>[{versionId:'skill-v1',stableName:'cluster',name:'Cluster',content:'Read all notes and name meaningful groups.'}])},model={complete:vi.fn(async(_input:ModelCallInput)=>({text:JSON.stringify(groups)}))},directory={list:vi.fn(async()=>['agent'])};
  const service=new WhiteboardOrganizeService(db as never,audit as never,collaboration as never,proposals as never,agents,skills,model,directory);
  return{service,audit,model,proposals,agents,skills};}
const principal={userId:'user',orgId:toOrgId('org')},input={requestId:'00000000-0000-4000-8000-000000000001',actorId:'agent',objectIds:notes.map(o=>o.id),expectedRevision:{epoch:1,seq:1}};
describe('real organize orchestration with a UNIT model double',()=>{
 it('reads authoritative text, calls routed pinned model and previews atomic reversible commands',async()=>{const d=deps();await d.service.organize(principal,'board',input);expect(d.model.complete).toHaveBeenCalledTimes(1);expect(d.model.complete.mock.calls[0]?.[0]).toMatchObject({modelProvider:'configured',modelId:'model',executionMode:'text-only'});expect(JSON.parse(d.model.complete.mock.calls[0]![0]!.user).notes).toEqual(notes.map(o=>({id:o.id,text:o.text})).sort((a,b)=>a.id.localeCompare(b.id)));const proposal=d.proposals.create.mock.calls[0]![2]!;expect(proposal.action.type).toBe('cluster');expect(proposal.action.labels).toEqual(['入门引导','性能体验']);
 const doc=createWhiteboardDocument();executeCommands(doc,notes.map(object=>({type:'create',object})),{});const before=readObjects(doc);executeCommands(doc,proposal.action.commands,{});expect(readObjects(doc).filter(o=>o.kind==='frame')).toHaveLength(2);executeCommands(doc,inverse(proposal.action.commands,new Map(before.map(o=>[o.id,o]))),{});expect(readObjects(doc)).toEqual(before);doc.destroy();});
 it.each(['unknown','duplicate','missing'])('rejects %s model memberships without a proposal',async(kind)=>{const d=deps(),value=structuredClone(groups);if(kind==='unknown')value.clusters[0]!.objectIds[0]='not-selected';if(kind==='duplicate')value.clusters[0]!.objectIds[1]=value.clusters[0]!.objectIds[0]!;if(kind==='missing')value.clusters[0]!.objectIds.pop();d.model.complete.mockResolvedValue({text:JSON.stringify(value)});await expect(d.service.organize(principal,'board',input)).rejects.toMatchObject({code:'VALIDATION_FAILED'});expect(d.proposals.create).not.toHaveBeenCalled();});
 it('denies viewer before reading or sending notes to model',async()=>{const d=deps();d.audit.lockHead.mockResolvedValue({epoch:1,seq:1,actorRole:'viewer'});await expect(d.service.organize(principal,'board',input)).rejects.toMatchObject({code:'FORBIDDEN'});expect(d.model.complete).not.toHaveBeenCalled();});
 it('rejects mismatched registered model and unavailable pinned skill',async()=>{const d=deps();d.agents.resolvePublished.mockResolvedValue({...await d.agents.resolvePublished(),modelId:'different'});await expect(d.service.organize(principal,'board',input)).rejects.toMatchObject({code:'DEPENDENCY_UNAVAILABLE'});expect(d.model.complete).not.toHaveBeenCalled();});
 it('rejects stale source revision and model errors with no preview mutation',async()=>{const d=deps();await expect(d.service.organize(principal,'board',{...input,expectedRevision:{epoch:1,seq:0}})).rejects.toMatchObject({code:'STALE_REVISION'});expect(d.model.complete).not.toHaveBeenCalled();d.model.complete.mockRejectedValue(new Error('secret provider error'));await expect(d.service.organize(principal,'board',input)).rejects.toMatchObject({code:'DEPENDENCY_UNAVAILABLE'});expect(d.proposals.create).not.toHaveBeenCalled();});
 it('validates cluster membership independently of model transport',()=>{expect(()=>clusterCommands(notes,{clusters:[]})).toThrow();});
});

it('rejects skill switch within same published agent version after inference',async()=>{const d=deps();d.agents.resolvePublished.mockResolvedValue({...await d.agents.resolvePublished(),skillVersionIds:['skill-v1','skill-v2']});d.model.complete.mockImplementation(async()=>{d.audit.resolveActor.mockResolvedValue({...await d.audit.resolveActor(),skill:'skill-v2'});return{text:JSON.stringify(groups)};});await expect(d.service.organize(principal,'board',input)).rejects.toMatchObject({code:'STALE_REVISION'});expect(d.proposals.create).not.toHaveBeenCalled();});
