/** Real PostgreSQL, filesystem object-store, fresh-connection and 5k-object growth lane. */
import './collaboration-persistence.test';

import { randomUUID } from 'node:crypto';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { PgDatabase } from '../../src/infrastructure/db/pg-database';
import { appConfig } from '../../src/infrastructure/db/pg-config';
import { PgWhiteboardRepository } from '../../src/infrastructure/whiteboard/pg-whiteboard-repository';
import { PgWhiteboardImportRepository } from '../../src/infrastructure/whiteboard/pg-import-repository';
import { toOrgId } from '../../src/domain/org-id';
import { addOrgMember,ensureDatabase,migrateOnce,resetOrgs,seedOrg } from '../support/db';
const fenceOrg=toOrgId('wb-gc-fence-real'),fenceOwner={orgId:fenceOrg,userId:'gc-owner'};let fenceDb:PgDatabase;
beforeAll(async()=>{ensureDatabase();await migrateOnce();await resetOrgs(fenceOrg);await seedOrg({orgId:fenceOrg,projectId:'gc-fence-project'});await addOrgMember(fenceOrg,fenceOwner.userId,'consultant',null);fenceDb=new PgDatabase(appConfig());});
afterAll(async()=>{await fenceDb?.close();await resetOrgs(fenceOrg);});
describe('real PostgreSQL object-key purge fence',()=>{it('rejects a new root while the same key is purging and permits replay after a failed purge',async()=>{const board=await new PgWhiteboardRepository(fenceDb).create(fenceOwner,{requestId:randomUUID(),name:'GC fence'}),key=`whiteboards/tenants/fence/boards/${board.id}/asset`,receipt=randomUUID();await fenceDb.withTenant(fenceOrg,async session=>{await session.query(`INSERT INTO whiteboard_object_tombstones(org_id,object_key,size_bytes,object_last_modified,version_tag,marked_at,swept_at) VALUES($1,$2,1,now(),'v1',now(),now())`,[fenceOrg,key]);await session.query(`INSERT INTO whiteboard_object_purge_receipts(org_id,object_key,generation,receipt_id,status,attempts) VALUES($1,$2,1,$3,'purging',1)`,[fenceOrg,key,receipt]);});await expect(fenceDb.withTenant(fenceOrg,session=>session.query(`INSERT INTO whiteboard_asset_refs(org_id,board_id,object_key,content_hash,byte_size,state) VALUES($1,$2,$3,$4,1,'active')`,[fenceOrg,board.id,key,'a'.repeat(64)]))).rejects.toThrow(/WHITEBOARD_OBJECT_PURGE_FENCED/);await fenceDb.withTenant(fenceOrg,session=>session.query(`UPDATE whiteboard_object_purge_receipts SET status='failed' WHERE org_id=$1 AND object_key=$2`,[fenceOrg,key]));await expect(fenceDb.withTenant(fenceOrg,session=>session.query(`INSERT INTO whiteboard_asset_refs(org_id,board_id,object_key,content_hash,byte_size,state) VALUES($1,$2,$3,$4,1,'active')`,[fenceOrg,board.id,key,'a'.repeat(64)]))).resolves.toBeDefined();});
it('leases pending assets, safely releases expired roots, and allows retry to reacquire them',async()=>{const board=await new PgWhiteboardRepository(fenceDb).create(fenceOwner,{requestId:randomUUID(),name:'Lease'}),repo=new PgWhiteboardImportRepository(fenceDb),id=randomUUID(),now=new Date().toISOString(),record={importId:id,boardId:board.id,source:'miro' as const,sourceBoardId:'source',sourceRevision:'r1',fileName:'b.json',mimeType:'application/json' as const,sizeBytes:2,sha256:'b'.repeat(64),stage:'uploaded' as const,counts:null,createdAt:now,updatedAt:now,sourceObjectKey:`whiteboards/tenants/fence/boards/${board.id}/imports/${id}/source`,actorId:fenceOwner.userId,report:null,executeRequestId:null,executeRequestHash:null,completedEpoch:null,completedSeq:null};await repo.create(fenceOwner,record);const asset={objectKey:`whiteboards/tenants/fence/boards/${board.id}/imports/${id}/asset`,contentHash:'c'.repeat(64),byteSize:1};await repo.reserveAssets(fenceOwner,record,[asset]);await fenceDb.withTenant(fenceOrg,session=>session.query(`UPDATE whiteboard_asset_refs SET lease_expires_at=now()-interval '1 second' WHERE org_id=$1 AND object_key=$2`,[fenceOrg,asset.objectKey]));expect(await repo.releaseExpiredAssets(fenceOwner,new Date())).toBe(1);await repo.reserveAssets(fenceOwner,record,[asset]);const state=await fenceDb.withTenant(fenceOrg,session=>session.query<{released:boolean;leased:boolean}>(`SELECT released_at IS NULL AS released,lease_expires_at>now() AS leased FROM whiteboard_asset_refs WHERE org_id=$1 AND object_key=$2`,[fenceOrg,asset.objectKey]));expect(state.rows[0]).toEqual({released:true,leased:true});});});
