import {expect,it,vi} from 'vitest';
import {WhiteboardProposalService} from '../../src/application/whiteboard/proposal-service';
import {WhiteboardOperationError} from '../../src/application/whiteboard/operation-service';
const proposalId='00000000-0000-4000-8000-000000000002',boardId='00000000-0000-4000-8000-000000000003',undoId='00000000-0000-4000-8000-000000000004';
const commands=[{type:'geometry',id:'note',geometry:{x:0,y:0,width:180,height:180,rotation:0}}];
function fixture(){const executeInTransaction=vi.fn(async()=>({revision:{epoch:1,seq:8}}));const service=new WhiteboardProposalService({withTenant:async(_org:unknown,fn:(s:unknown)=>unknown)=>fn({})} as never,{} as never,{lockHead:async()=>({epoch:1,seq:7,actorRole:'owner'})} as never,{lock:async()=>({ownerUserId:'user',proposal:{status:'confirmed',undoReceipt:{undoId,expectedRevision:{epoch:1,seq:7},commands},provenance:{inputObjectIds:['note']}}})} as never,{executeInTransaction} as never);return{service,executeInTransaction};}
const principal={orgId:'org',userId:'user'} as never;
it('uses server stored inverse and stable undo key, never caller commands',async()=>{const d=fixture();await d.service.undo(principal,boardId,proposalId,{requestId:proposalId,expectedRevision:{epoch:1,seq:7}});expect(d.executeInTransaction).toHaveBeenCalledWith(expect.anything(),principal,boardId,expect.objectContaining({requestId:undoId,commands,expectedRevision:{epoch:1,seq:7}}));await expect(d.service.undo(principal,boardId,proposalId,{requestId:proposalId,expectedRevision:{epoch:1,seq:7},commands:[]})).rejects.toThrow();expect(d.executeInTransaction).toHaveBeenCalledTimes(1);});
it('rejects changed revision and propagates authoritative CAS conflicts',async()=>{const d=fixture();await expect(d.service.undo(principal,boardId,proposalId,{requestId:proposalId,expectedRevision:{epoch:1,seq:8}})).rejects.toMatchObject({code:'STALE_REVISION'});expect(d.executeInTransaction).not.toHaveBeenCalled();d.executeInTransaction.mockRejectedValue(new WhiteboardOperationError('STALE_REVISION'));await expect(d.service.undo(principal,boardId,proposalId,{requestId:proposalId,expectedRevision:{epoch:1,seq:7}})).rejects.toMatchObject({code:'STALE_REVISION'});});

it.each(['read','cancel','undo'] as const)('fresh board ACL denies revoked owner %s before reading stored preview',async(method)=>{
 const lock=vi.fn(),setStatus=vi.fn(),executeInTransaction=vi.fn();
 const service=new WhiteboardProposalService({withTenant:async(_org:unknown,fn:(s:unknown)=>unknown)=>fn({})} as never,{} as never,{lockHead:async()=>null} as never,{lock,setStatus} as never,{executeInTransaction} as never);
 await expect(method==='read'?service.read(principal,boardId,proposalId):service[method](principal,boardId,proposalId,{requestId:proposalId,expectedRevision:{epoch:1,seq:7}})).rejects.toMatchObject({code:'NOT_FOUND'});
 expect(lock).not.toHaveBeenCalled();expect(setStatus).not.toHaveBeenCalled();expect(executeInTransaction).not.toHaveBeenCalled();
});

it('undo acquires board before proposal lock',async()=>{const order:string[]=[];const d=fixture();const service=new WhiteboardProposalService({withTenant:async(_org:unknown,fn:(s:unknown)=>unknown)=>fn({})} as never,{} as never,{lockHead:async()=>{order.push('board');return{epoch:1,seq:7};}} as never,{lock:async()=>{order.push('proposal');return{ownerUserId:'user',proposal:{status:'confirmed',undoReceipt:{undoId,expectedRevision:{epoch:1,seq:7},commands},provenance:{inputObjectIds:[]}}};}} as never,{executeInTransaction:d.executeInTransaction} as never);await service.undo(principal,boardId,proposalId,{requestId:proposalId,expectedRevision:{epoch:1,seq:7}});expect(order).toEqual(['board','proposal']);});
it('revoked create replay cannot read existing stored proposal',async()=>{const lock=vi.fn();const service=new WhiteboardProposalService({withTenant:async(_org:unknown,fn:(s:unknown)=>unknown)=>fn({})} as never,{} as never,{lockHead:async()=>null} as never,{lock} as never,{} as never);await expect(service.create(principal,boardId,{proposalId,actorId:'agent',baseRevision:{epoch:1,seq:7},action:{type:'arrange',objectIds:['note'],layout:'grid',commands},provenance:{source:'ai-proposal',model:'m',skill:'s'}})).rejects.toMatchObject({code:'NOT_FOUND'});expect(lock).not.toHaveBeenCalled();});
it('confirmation rejects changed pinned skill before mutation',async()=>{const executeInTransaction=vi.fn();const service=new WhiteboardProposalService({withTenant:async(_org:unknown,fn:(s:unknown)=>unknown)=>fn({})} as never,{} as never,{lockHead:async()=>({epoch:1,seq:7}),resolveActor:async()=>({model:'p/m',skill:'B'})} as never,{lock:async()=>({ownerUserId:'user',proposal:{status:'preview',createdBy:{actorId:'agent'},runtimePin:{model:'p/m',skill:'A',agentVersionId:'v1'}}})} as never,{executeInTransaction} as never,undefined,{resolvePublished:async()=>({agentVersionId:'v1',modelProvider:'p',modelId:'m',skillVersionIds:['A','B']})} as never);await expect(service.confirmWithUndo(principal,boardId,proposalId,{requestId:proposalId,expectedRevision:{epoch:1,seq:7}})).rejects.toMatchObject({code:'STALE_REVISION'});expect(executeInTransaction).not.toHaveBeenCalled();});
