import {expect,it,vi} from 'vitest';
import {WhiteboardProposalService} from '../../src/application/whiteboard/proposal-service';
import {WhiteboardOperationError} from '../../src/application/whiteboard/operation-service';
const proposalId='00000000-0000-4000-8000-000000000002',boardId='00000000-0000-4000-8000-000000000003',undoId='00000000-0000-4000-8000-000000000004';
const commands=[{type:'geometry',id:'note',geometry:{x:0,y:0,width:180,height:180,rotation:0}}];
function fixture(){const executeInTransaction=vi.fn(async()=>({revision:{epoch:1,seq:8}}));const service=new WhiteboardProposalService({withTenant:async(_org:unknown,fn:(s:unknown)=>unknown)=>fn({})} as never,{} as never,{} as never,{lock:async()=>({ownerUserId:'user',proposal:{status:'confirmed',undoReceipt:{undoId,expectedRevision:{epoch:1,seq:7},commands},provenance:{inputObjectIds:['note']}}})} as never,{executeInTransaction} as never);return{service,executeInTransaction};}
const principal={orgId:'org',userId:'user'} as never;
it('uses server stored inverse and stable undo key, never caller commands',async()=>{const d=fixture();await d.service.undo(principal,boardId,proposalId,{requestId:proposalId,expectedRevision:{epoch:1,seq:7}});expect(d.executeInTransaction).toHaveBeenCalledWith(expect.anything(),principal,boardId,expect.objectContaining({requestId:undoId,commands,expectedRevision:{epoch:1,seq:7}}));await expect(d.service.undo(principal,boardId,proposalId,{requestId:proposalId,expectedRevision:{epoch:1,seq:7},commands:[]})).rejects.toThrow();expect(d.executeInTransaction).toHaveBeenCalledTimes(1);});
it('rejects changed revision and propagates authoritative CAS conflicts',async()=>{const d=fixture();await expect(d.service.undo(principal,boardId,proposalId,{requestId:proposalId,expectedRevision:{epoch:1,seq:8}})).rejects.toMatchObject({code:'STALE_REVISION'});expect(d.executeInTransaction).not.toHaveBeenCalled();d.executeInTransaction.mockRejectedValue(new WhiteboardOperationError('STALE_REVISION'));await expect(d.service.undo(principal,boardId,proposalId,{requestId:proposalId,expectedRevision:{epoch:1,seq:7}})).rejects.toMatchObject({code:'STALE_REVISION'});});
