import { randomUUID } from 'node:crypto';
import { describe,expect,it } from 'vitest';
import type { DatabasePort,TenantSession } from '../../src/application/ports/database.port';
import { PgWhiteboardRecoveryMetadata } from '../../src/infrastructure/whiteboard/pg-recovery-metadata';
import { toOrgId } from '../../src/domain/org-id';
import type { WhiteboardCheckpointManifest,WhiteboardCollaborationEvent } from '@repo/contracts/whiteboard-collaboration';
const p={orgId:toOrgId('recovery-metadata-org'),userId:'owner'},boardId='20000000-0000-4000-8000-000000000001';
function fixture(){let checkpoint:WhiteboardCheckpointManifest|null=null,head={epoch:2,seq:7},receipt:{request_hash:string;new_epoch:number}|null=null;const queries:{sql:string;params:readonly unknown[]}[]=[];const session:TenantSession={async query<R>(sql:string,params:readonly unknown[]=[]){queries.push({sql,params});let rows:unknown[]=[];if(sql.startsWith('SELECT owner_id'))rows=[{owner_id:p.userId,archived:false}];else if(sql.includes('FROM whiteboard_checkpoints'))rows=checkpoint?[{checkpoint_id:checkpoint.checkpointId,board_id:checkpoint.boardId,version:1,epoch:checkpoint.epoch,seq:String(checkpoint.seq),object_key:checkpoint.objectKey,content_hash:checkpoint.contentHash,byte_size:String(checkpoint.byteSize),created_by:checkpoint.createdBy,created_at:checkpoint.createdAt}]:[];else if(sql.startsWith('INSERT INTO whiteboard_checkpoints'))checkpoint={checkpointId:String(params[2]),boardId:String(params[1]),version:1,epoch:Number(params[4]),seq:Number(params[5]),objectKey:String(params[6]),contentHash:String(params[7]),byteSize:Number(params[8]),createdBy:String(params[9]),createdAt:String(params[10])};else if(sql.startsWith('SELECT request_hash'))rows=receipt?[receipt]:[];else if(sql.startsWith('SELECT epoch,seq::text FROM whiteboard_documents'))rows=[{epoch:head.epoch,seq:String(head.seq)}];else if(sql.startsWith('UPDATE whiteboard_documents'))head={epoch:Number(params[2]),seq:0};else if(sql.startsWith('INSERT INTO whiteboard_restore_receipts'))receipt={request_hash:String(params[3]),new_epoch:Number(params[6])};return{rows:rows as R[]};}};const db:DatabasePort={withTenant:async(_org,fn)=>fn(session),withoutTenant:async()=>{throw new Error('no')},close:async()=>{}};return{repo:new PgWhiteboardRecoveryMetadata(db),queries,get head(){return head}};}
const manifest=(id=randomUUID()):WhiteboardCheckpointManifest=>({checkpointId:id,boardId,version:1,epoch:2,seq:7,objectKey:`whiteboards/tenants/abc/boards/${boardId}/checkpoints/${id}.yjs`,contentHash:`sha256:${'a'.repeat(64)}`,byteSize:12,createdBy:p.userId,createdAt:'2026-09-26T00:00:00.000Z'});
describe('PostgreSQL recovery metadata adapter',()=>{
  it('stores only immutable checkpoint metadata and replays exact checkpoint ids',async()=>{const f=fixture(),value=manifest();const first=await f.repo.saveCheckpoint(p,value,value.checkpointId),second=await f.repo.saveCheckpoint(p,value,value.checkpointId);expect(first.replayed).toBe(false);expect(second.replayed).toBe(true);const insert=f.queries.find(query=>query.sql.startsWith('INSERT INTO whiteboard_checkpoints'))!;expect(insert.params).not.toContainEqual(expect.any(Uint8Array));expect(insert.sql).not.toContain('snapshot');});
  it('publishes a restore manifest by CAS and replays before testing the changed head',async()=>{const f=fixture(),checkpoint=manifest();await f.repo.saveCheckpoint(p,checkpoint,checkpoint.checkpointId);const requestId=randomUUID(),event:WhiteboardCollaborationEvent={type:'BoardRestored',eventId:requestId,operationId:requestId,boardId,checkpointId:checkpoint.checkpointId,previousEpoch:2,epoch:3,actorId:p.userId,occurredAt:'2026-09-26T00:01:00.000Z'};const input={boardId,checkpoint,newEpoch:3,expectedEpoch:2,expectedSeq:7,requestId,event};expect(await f.repo.commitRestore(p,input)).toEqual({epoch:3,seq:0,replayed:false});expect(f.head).toEqual({epoch:3,seq:0});expect(await f.repo.commitRestore(p,input)).toEqual({epoch:3,seq:0,replayed:true});const update=f.queries.find(query=>query.sql.startsWith('UPDATE whiteboard_documents'))!;expect(update.sql).toContain('snapshot=NULL');expect(update.params).not.toContainEqual(expect.any(Uint8Array));});
});
