import {it,expect,vi} from 'vitest';
import {runStorageBackfill,type StorageBackfillPort,StorageBackfillError} from '../../src/application/whiteboard/storage-backfill';
import {lockBoardStorageMaintenance} from '../../src/infrastructure/whiteboard/storage-maintenance-access';
import {PgStorageBackfill} from '../../src/infrastructure/whiteboard/pg-storage-backfill';
import type {Principal} from '../../src/domain/principal';
import {toOrgId} from '../../src/domain/org-id';
import type {TenantSession,DatabasePort} from '../../src/application/ports/database.port';
const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002',empty={snapshots:0,updates:0,commentThreads:0,commentReceipts:0},scope=[{orgId:'org',actorId:'actor',boardIds:[a,b]}];
function port(){return {list:vi.fn(async(_p:Principal,_after:string|null,_limit:number)=>[] as string[]),inspect:vi.fn(async(_p:Principal,_id:string)=>({archived:false,remaining:{...empty,updates:3}})),migrate:vi.fn(async(_p:Principal,_id:string,_rows:number)=>({archived:false,migrated:1,remaining:empty}))};}
it('defaults to dry-run and cannot reuse its cursor for execute or another scope',async()=>{const p=port(),result=await runStorageBackfill(p,scope,{boardLimit:1});expect(result.mode).toBe('dry-run');expect(p.migrate).not.toHaveBeenCalled();expect(p.inspect).toHaveBeenCalledOnce();expect(result.cursor).not.toBeNull();await expect(runStorageBackfill(p,scope,{execute:true,cursor:result.cursor!})).rejects.toMatchObject({code:'INVALID_CURSOR'});await expect(runStorageBackfill(p,[{...scope[0],actorId:'other'}],{cursor:result.cursor!})).rejects.toMatchObject({code:'INVALID_CURSOR'});});
it('resumes a partially migrated board before advancing and passes a hard row budget',async()=>{const p=port();p.migrate.mockResolvedValueOnce({archived:true,migrated:1,remaining:{...empty,commentThreads:1}});const first=await runStorageBackfill(p,scope,{execute:true,rowLimit:1});expect(first.boards.map(row=>row.boardId)).toEqual([a]);const second=await runStorageBackfill(p,scope,{execute:true,rowLimit:1,cursor:first.cursor!,delayMs:0});expect(p.migrate.mock.calls.map(call=>call[1])).toEqual([a,a]);const third=await runStorageBackfill(p,scope,{execute:true,rowLimit:1,cursor:second.cursor!,delayMs:0});expect(p.migrate.mock.calls.map(call=>call[1])).toEqual([a,a,b]);const end=await runStorageBackfill(p,scope,{execute:true,rowLimit:1,cursor:third.cursor!,delayMs:0});expect(p.migrate).toHaveBeenCalledWith(expect.anything(),a,1);expect(end.cursor).toBeNull();expect(end.failureCount).toBe(0);});
it('paces boards, keeps a sanitized failure list, and continues across explicit tenants',async()=>{const p=port(),sleep=vi.fn(async()=>{});p.migrate.mockRejectedValueOnce(Object.assign(new Error('private body/token'),{code:'INTEGRITY_FAILED'}));const result=await runStorageBackfill(p,[...scope,{orgId:'other-org',actorId:'other-owner',boardIds:[a]}],{execute:true,delayMs:20},sleep);expect(result.failures).toEqual([{orgId:'org',boardId:a,code:'INTEGRITY_FAILED'}]);expect(result.failureCount).toBe(1);expect(result.batchMigrated).toBe(false);expect(sleep).toHaveBeenCalledTimes(2);expect(JSON.stringify(result)).not.toContain('private');});
it('never drops previous failure count on cursor continuation',async()=>{const p=port();p.migrate.mockRejectedValueOnce(new Error('secret'));const first=await runStorageBackfill(p,scope,{execute:true,boardLimit:1});const second=await runStorageBackfill(p,scope,{execute:true,cursor:first.cursor!,delayMs:0});expect(second.failureCount).toBe(1);expect(second.scanComplete).toBe(true);});
it('all-board scopes enumerate only through the explicitly authorized tenant port',async()=>{const p=port();p.list.mockResolvedValueOnce([a]).mockResolvedValueOnce([]);await runStorageBackfill(p,[{orgId:'org',actorId:'admin',allBoards:true}],{});expect(p.list).toHaveBeenCalledWith({orgId:'org',userId:'admin'},null,20);expect(p.migrate).not.toHaveBeenCalled();});
function access(role:string|null,owner='owner',archived=true){const calls:string[]=[];const session:TenantSession={async query<R>(sql:string){calls.push(sql);return {rows:(sql.includes('org_memberships')?(role?[{org_role:role}]:[]):[{owner_id:owner,archived}]) as R[]};}};return {session,calls};}
it('locks current organization membership before board, permits archived maintenance only to owner/admin',async()=>{for(const [role,actor,allow] of [['consultant','owner',true],['admin','admin-user',true],['consultant','editor',false],['lead','lead',false],[null,'owner',false]] as const){const f=access(role);const operation=lockBoardStorageMaintenance(f.session,{orgId:toOrgId('org'),userId:actor},a);if(allow){expect(await operation).toEqual({archived:true});expect(f.calls[0]).toContain('org_memberships');expect(f.calls[0]).toContain('FOR SHARE');expect(f.calls[1]).toContain('FOR UPDATE');}else await expect(operation).rejects.toBeInstanceOf(StorageBackfillError);}});
it('rejects owner-only all-board enumeration and revocation before touching a board',async()=>{const f=access('consultant');await expect(lockBoardStorageMaintenance(f.session,{orgId:toOrgId('org'),userId:'owner'})).rejects.toMatchObject({code:'FORBIDDEN'});expect(f.calls).toHaveLength(1);const revoked=access(null);await expect(lockBoardStorageMaintenance(revoked.session,{orgId:toOrgId('org'),userId:'owner'},a)).rejects.toMatchObject({code:'NOT_FOUND'});expect(revoked.calls).toHaveLength(1);});
it('shares one transaction and one total row budget across document and comment hooks',async()=>{const f=access('admin'),original=f.session.query.bind(f.session);f.session.query=async<R>(sql:string,params?:readonly unknown[])=>sql.startsWith('SELECT\n')?{rows:[{snapshots:'0',updates:'0',threads:'0',receipts:'0'}] as R[]}:original<R>(sql,params);const db={withTenant:async(_org,fn)=>fn(f.session)} as DatabasePort;const docs={backfillStorageInTransaction:vi.fn(async()=>2)},comments={backfillStorageInTransaction:vi.fn(async()=>1)};const repository=new PgStorageBackfill(db,docs,comments);expect((await repository.migrate({orgId:toOrgId('org'),userId:'admin'},a,3)).migrated).toBe(3);expect(docs.backfillStorageInTransaction).toHaveBeenCalledWith(f.session,expect.anything(),a,3);expect(comments.backfillStorageInTransaction).toHaveBeenCalledWith(f.session,expect.anything(),a,1);});
it('document maintenance hook migrates a snapshot within the budget without loading archived content',async()=>{
 const {PgWhiteboardCollaborationStore}=await import('../../src/infrastructure/whiteboard/pg-collaboration-store');
 const files=new Map<string,Uint8Array>(),objects={putOnce:async(key:string,bytes:Uint8Array)=>{files.set(key,bytes);},get:async(key:string)=>files.get(key)??null,head:async(key:string)=>files.has(key)?{sizeBytes:files.get(key)!.length,mime:'application/vnd.yjs-update'}:null};
 const calls:string[]=[];let persisted=false;
 const session:TenantSession={async query<R>(sql:string,params:readonly unknown[]=[]){calls.push(sql);let rows:unknown[]=[];
  if(sql.includes('org_memberships'))rows=[{org_role:'admin'}];else if(sql.includes('SELECT owner_id,archived'))rows=[{owner_id:'other',archived:true}];
  else if(sql.startsWith('SELECT epoch,seq,snapshot'))rows=persisted?[]:[{epoch:1,seq:'0',snapshot:Buffer.from([0,0]),object_key:null,content_hash:null,byte_size:null}];
  else if(sql.startsWith('UPDATE whiteboard_documents')){persisted=true;rows=[{object_key:params[3],content_hash:params[4],byte_size:String(params[5]),snapshot:null}];}
  else throw Error('Unexpected query');return {rows:rows as R[]};}};
 const store=new PgWhiteboardCollaborationStore({} as DatabasePort,undefined,120,objects);
 expect(await store.backfillStorageInTransaction(session,{orgId:toOrgId('org'),userId:'admin'},a,1)).toBe(1);expect(files.size).toBe(1);expect(calls.some(sql=>sql.includes('FROM whiteboard_updates'))).toBe(false);expect(calls.some(sql=>sql.includes('archived='))).toBe(false);
});
it('comment maintenance respects its remaining budget even for archived boards',async()=>{
 const {randomUUID}=await import('node:crypto');const {WhiteboardCommentService}=await import('@repo/whiteboard-core');const {PgWhiteboardCommentStore}=await import('../../src/infrastructure/whiteboard/pg-whiteboard-comment-store');
 const core=new WhiteboardCommentService(a,{objectExists:()=>true,isMentionable:()=>true,now:()=>new Date(),uuid:randomUUID});const rows:any[]=[];
 for(let i=0;i<2;i++){const accepted=core.dispatch({actorId:'owner',role:'owner'},{type:'create-comment',requestId:randomUUID(),threadId:randomUUID(),commentId:randomUUID(),objectId:'note',worldPosition:null,body:'Synthetic comment',mentions:[],expectedRevision:0});const thread=accepted.threads.find(thread=>!rows.some(row=>row.id===thread.id))!;rows.push({id:thread.id,object_id:thread.objectId,status:thread.status,revision:thread.revision,payload:thread,body_object_key:null});}
 const files=new Map<string,Uint8Array>(),objects={putOnce:async(key:string,bytes:Uint8Array)=>{files.set(key,bytes);},get:async(key:string)=>files.get(key)??null,head:async(key:string)=>files.has(key)?{sizeBytes:files.get(key)!.length,mime:'application/json'}:null};
 const calls:string[]=[];const session:TenantSession={async query<R>(sql:string,params:readonly unknown[]=[]){calls.push(sql);let found:unknown[]=[];
  if(sql.includes('org_memberships'))found=[{org_role:'admin'}];else if(sql.includes('SELECT owner_id,archived'))found=[{owner_id:'owner',archived:true}];
  else if(sql.startsWith('SELECT')&&sql.includes('whiteboard_comment_threads'))found=rows.filter(row=>!row.body_object_key).slice(0,Number(params[2]));
  else if(sql.startsWith('UPDATE whiteboard_comment_threads'))Object.assign(rows.find(row=>row.id===params[2]),{payload:JSON.parse(String(params[3])),body_object_key:params[4]});else throw Error('Unexpected query');return {rows:found as R[]};}};
 const store=new PgWhiteboardCommentStore({} as DatabasePort,{} as never,undefined,undefined,objects);
 expect(await store.backfillStorageInTransaction(session,{orgId:toOrgId('org'),userId:'admin'},a,1)).toBe(1);expect(rows.filter(row=>row.body_object_key)).toHaveLength(1);expect(files.size).toBe(1);expect(calls.some(sql=>sql.includes('whiteboard_comment_requests'))).toBe(false);
});

it('enforces one invocation row budget across boards and keeps the next board in its cursor',async()=>{
 const p=port();p.migrate.mockResolvedValueOnce({archived:false,migrated:2,remaining:empty}).mockResolvedValueOnce({archived:false,migrated:1,remaining:{...empty,updates:1}});
 const result=await runStorageBackfill(p,scope,{execute:true,rowLimit:3,delayMs:0});
 expect(p.migrate.mock.calls.map(call=>call[2])).toEqual([3,1]);expect(result.boards.reduce((n,row)=>n+row.migrated,0)).toBe(3);
 p.migrate.mockClear().mockResolvedValue({archived:false,migrated:1,remaining:empty});
 await runStorageBackfill(p,scope,{execute:true,rowLimit:3,cursor:result.cursor!,delayMs:0});expect(p.migrate.mock.calls.map(call=>call[1])).toEqual([b]);
});
