import {createHash,createHmac,timingSafeEqual} from 'node:crypto';

export const BOARD_SOAK_REQUIREMENTS={clients:50,writers:20,durationMs:30*60*1000,convergenceP95Ms:300} as const;
export type BoardSoakSample={at:string;clientId:string;writer:boolean;revision:number;stateHash:string;latencyMs:number;chainHash:string};
export type BoardSoakLedger={version:1;sha:string;startedAt:string;finishedAt:string;durationMs:number;clients:number;writers:number;convergenceP95Ms:number;finalStateHash:string;samples:BoardSoakSample[];signature:string};
const canonical=(value:unknown):string=>Array.isArray(value)?`[${value.map(canonical).join(',')}]`:value&&typeof value==='object'?`{${Object.entries(value as Record<string,unknown>).filter(([key])=>key!=='signature').sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${canonical(item)}`).join(',')}}`:JSON.stringify(value);
const digest=(value:string)=>createHash('sha256').update(value).digest('hex');
export function nextBoardChain(previous:string,sample:Omit<BoardSoakSample,'chainHash'>){return digest(`${previous}:${canonical(sample)}`);}
export function signBoardSoakLedger(unsigned:Omit<BoardSoakLedger,'signature'>,key:string):BoardSoakLedger{if(key.length<32)throw new Error('BOARD_LEDGER_KEY_TOO_SHORT');return{...unsigned,signature:createHmac('sha256',key).update(canonical(unsigned)).digest('hex')}}
export function verifyBoardSoakLedger(ledger:BoardSoakLedger,key:string){if(key.length<32)return false;const expected=createHmac('sha256',key).update(canonical(ledger)).digest(),actual=Buffer.from(ledger.signature,'hex');if(actual.length!==expected.length||!timingSafeEqual(actual,expected))return false;if(!/^[a-f0-9]{40}$/.test(ledger.sha)||ledger.clients<BOARD_SOAK_REQUIREMENTS.clients||ledger.writers<BOARD_SOAK_REQUIREMENTS.writers||ledger.durationMs<BOARD_SOAK_REQUIREMENTS.durationMs||ledger.convergenceP95Ms>BOARD_SOAK_REQUIREMENTS.convergenceP95Ms)return false;if(Date.parse(ledger.finishedAt)-Date.parse(ledger.startedAt)<BOARD_SOAK_REQUIREMENTS.durationMs)return false;const ids=new Set(ledger.samples.map(sample=>sample.clientId));if(ids.size!==ledger.clients||new Set(ledger.samples.filter(sample=>sample.writer).map(sample=>sample.clientId)).size!==ledger.writers)return false;let chain=digest(`${ledger.sha}:${ledger.startedAt}`),previousAt=Date.parse(ledger.startedAt);const latest=new Map<string,BoardSoakSample>();for(const sample of ledger.samples){const at=Date.parse(sample.at);if(!Number.isFinite(at)||at<previousAt||at>Date.parse(ledger.finishedAt)||sample.latencyMs<0)return false;previousAt=at;const{chainHash,...body}=sample;chain=nextBoardChain(chain,body);if(chainHash!==chain)return false;latest.set(sample.clientId,sample);}return latest.size===ledger.clients&&[...latest.values()].every(sample=>sample.stateHash===ledger.finalStateHash);}

export type BoardRecoveryLedger={version:1;sha:string;events:Array<{at:string;type:'ack'|'revoke'|'disconnect'|'blob-corrupt'|'restore'|'converged';actorId:string;revision:number;stateHash:string}>;acknowledgedRevisions:number[];restoredRevision:number;finalStateHash:string;signature:string};
export function signBoardRecoveryLedger(unsigned:Omit<BoardRecoveryLedger,'signature'>,key:string):BoardRecoveryLedger{return{...unsigned,signature:createHmac('sha256',key).update(canonical(unsigned)).digest('hex')}}
export function verifyBoardRecoveryLedger(ledger:BoardRecoveryLedger,key:string){if(key.length<32||!ledger.acknowledgedRevisions.length||!/^[a-f0-9]{40}$/.test(ledger.sha))return false;const expected=createHmac('sha256',key).update(canonical(ledger)).digest(),actual=Buffer.from(ledger.signature,'hex');if(actual.length!==expected.length||!timingSafeEqual(actual,expected)||!ledger.events.some(event=>event.type==='revoke')||!ledger.events.some(event=>event.type==='blob-corrupt')||!ledger.events.some(event=>event.type==='restore'))return false;const lastAck=Math.max(...ledger.acknowledgedRevisions),final=ledger.events.at(-1);return ledger.restoredRevision>=lastAck&&final?.type==='converged'&&final.revision>=lastAck&&final.stateHash===ledger.finalStateHash;}
