/**
 * 把**服务端准入表**（`NATIVE_PROFILE_TOOLS` + 它算出的 `interrupt_on`）生成到
 * Python 包里，作为跨语言边界的唯一事实源。
 *
 * ## 为什么必须生成，而不是在 Python 里再写一份名字
 *
 * `native_factory.native_graph_context` 里那句
 * `tools=[tool for tool in [...] if tool.name in interrupt_on]`
 * 是**静默过滤**：Python 侧构造了工具、TS 侧没登记，工具就消失，没有日志、没有异常、
 * 模型也看不见它——`spawn_async_task` 就是这么丢的（#3159）。两侧各写一份手抄清单时，
 * 这种丢失只能靠人眼比对发现，本仓已经因"同一事实两处声明"漂移过七次。
 *
 * 生成物 `native_profile_tools.json` 让 Python 侧的门控（`tests/test_native_tool_admission.py`）
 * 能拿到**真的那张准入表**去比对真实构造出来的工具对象，比对结果是机械的。
 *
 * `--check`：正文与磁盘不一致就抛错（由 `tests/agent-run/native-profile-tools-generated.test.ts`
 * 在每次 vitest 里跑）——改了准入表却没重新生成，会当场红。
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { NATIVE_PROFILE_TOOLS, nativeInterruptOn } from "../src/application/agent-run/native-invocation";

const content = JSON.stringify({
  // 说明写进生成物本身：读到这个文件的人不必回来翻脚本。
  note: "Generated by apps/api/scripts/generate-native-profile-tools.ts. Do not edit by hand.",
  tools: [...NATIVE_PROFILE_TOOLS],
  interruptOn: nativeInterruptOn(),
}, null, 2) + "\n";

const path = resolve(import.meta.dirname, "../../deep-agent-service/src/deep_agent_service/generated/native_profile_tools.json");
if (process.argv.includes("--check")) {
  if (readFileSync(path, "utf8") !== content) {
    throw new Error("native profile tools generated file is stale: run `pnpm --filter @repo/api gen:native-profile-tools`");
  }
} else {
  writeFileSync(path, content);
}
