/** Derived coordinates: matrix membership and immutable starter content remain the authority. */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildOfficialAgentRolePack, officialRoleSkillPacks } from "../src/domain/agent/official-role-packs";
import { skillContentDigest, verifySkillStarterPack } from "../src/domain/skill/starter-pack";

const root = resolve(fileURLToPath(new URL("../../../", import.meta.url)));
const output = resolve(root, "apps/api/src/domain/agent/official-role-skill-coordinates.generated.ts");
const preferred = officialRoleSkillPacks().map((pack) => pack.packId);
const packIds = readdirSync(resolve(root, "skills/starter-packs")).sort((a, b) => {
  const ai = preferred.indexOf(a); const bi = preferred.indexOf(b);
  return (ai < 0 ? preferred.length : ai) - (bi < 0 ? preferred.length : bi) || a.localeCompare(b);
});
const byStableId = new Map<string, { stableId: string; stableName: string; packId: string; packVersion: string; digest: string; displayName: string }>();
for (const packId of packIds) {
  const packVersion = packId === "work-sales" ? "1.1.0" : "1.0.0";
  const filename = resolve(root, `skills/starter-packs/${packId}/${packVersion}.json`);
  const raw = JSON.parse(readFileSync(filename, "utf8"));
  const pack = verifySkillStarterPack(raw, { packId, packVersion });
  for (const skill of pack.skills) {
    const work = skill.manifest.work as { stableId?: string } | undefined;
    if (work?.stableId && !byStableId.has(work.stableId)) byStableId.set(work.stableId, {
      stableId: work.stableId, stableName: skill.stableName, packId, packVersion: pack.packVersion, digest: skillContentDigest(skill),
      displayName: Buffer.from(skill.files.find(file => file.path === "SKILL.md")!.contentBase64, "base64").toString("utf8").match(/^# ([^\r\n]+)$/m)?.[1]?.trim() ?? skill.name,
    });
  }
}
const roles = new Set(buildOfficialAgentRolePack().agents.map((role) => role.roleRef));
const rows: Record<string, unknown[]> = {};
for (const line of readFileSync(resolve(root, "requirements/work-stack-v2/DIGITALHUMAN-COMPOSITION-MATRIX.md"), "utf8").split("\n")) {
  const columns = line.split("|").map((column) => column.trim());
  if (!roles.has(columns[1]!)) continue;
  const ids = columns[4]!.match(/S\d{3}/g) ?? [];
  rows[columns[1]!] = ids.map((id) => {
    const coordinate = byStableId.get(id);
    if (!coordinate) throw new Error(`missing authored starter coordinate: ${id}`);
    return coordinate;
  });
}
if (Object.keys(rows).length !== roles.size) throw new Error("missing official role matrix row");
const source = `// Generated by scripts/generate-official-role-skill-coordinates.ts; do not edit.\nexport const OFFICIAL_ROLE_SKILL_COORDINATES = ${JSON.stringify(rows, null, 2)} as const;\n`;
if (process.argv.includes("--check")) {
  if (readFileSync(output, "utf8") !== source) throw new Error("official role Skill coordinates drift; regenerate");
  console.log("official role Skill coordinates match matrix and immutable starter content");
} else writeFileSync(output, source);
