http_port 3128

acl Safe_ports port 80 443
acl SSL_ports port 443
acl CONNECT method CONNECT
acl blocked_v4 dst 0.0.0.0/8 10.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16
acl blocked_v4 dst 172.16.0.0/12 192.0.0.0/24 192.168.0.0/16 198.18.0.0/15 224.0.0.0/4 240.0.0.0/4
acl blocked_v6 dst ::/128 ::1/128 ::ffff:0:0/96 64:ff9b::/96 fc00::/7 fe80::/10 ff00::/8

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access deny blocked_v4
http_access deny blocked_v6
http_access allow all

cache deny all
forwarded_for delete
via off
request_header_access X-Forwarded-For deny all
request_header_access Proxy-Authorization deny all
reply_header_access Server deny all
access_log stdio:/dev/stdout
cache_log /dev/null
