"use client";
import * as React from "react";
import { CheckCircle2, Copy, Link2, QrCode, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { getPublishBlockers, type SurveyMetrics } from "@/lib/survey/workflow-model";
import type { survey } from "@repo/contracts";
import { SectionTitle } from "./survey-workflow-shell";

export function PublishRecoveryStep({ model, metrics, readonly }: { model: survey.SurveyWorkflowModel; metrics: SurveyMetrics; readonly: boolean }) {
  const [copied, setCopied] = React.useState(false); const blockers = getPublishBlockers(model);
  return <div className="grid gap-4 p-5 xl:grid-cols-[14rem_minmax(34rem,1fr)_28rem]">
    <aside className="rounded-lg border border-border bg-card p-3"><SectionTitle title="发布设置" />{["发布状态","链接设置","受访范围","回收规则","质量控制","完成页"].map((item,index) => <button key={item} type="button" className={`mb-1 w-full rounded-md px-3 py-2 text-left text-12 transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${index===0?"bg-accent text-primary":"hover:bg-muted"}`}>{item}</button>)}</aside>
    <section className="space-y-4"><div className={`rounded-lg border p-5 ${blockers.length ? "border-warning/40 bg-warning/5" : "border-success/40 bg-success/5"}`} data-testid="survey-publish-checks"><div className="flex items-center gap-2"><CheckCircle2 className="h-6 w-6 text-success" /><h2 className="text-18 font-semibold">{blockers.length ? `发布检查发现 ${blockers.length} 项阻断` : "发布检查通过"}</h2></div><p className="mt-2 text-12 text-muted-foreground">问卷 {model.questions.length} 题 · 预计 8 分钟 · {model.reportTemplate.sections.length} 个报告章节</p>{blockers.length > 0 && <ul className="mt-3 space-y-1">{blockers.map((blocker) => <li key={blocker.code} className="text-11 text-warning">• {blocker.label}</li>)}</ul>}</div><div className="rounded-lg border border-border bg-card p-5" data-testid="survey-publish-link"><SectionTitle icon={<Link2 className="h-4 w-4" />} title="问卷链接" description="通过链接或二维码邀请受访者答题" /><div className="grid gap-4 md:grid-cols-[1fr_10rem]"><div><div className="flex rounded-md border border-primary/30 bg-accent p-2"><span className="min-w-0 flex-1 truncate text-12 text-primary">{model.publication.link}</span><Button size="xs" variant="outline" onClick={() => setCopied(true)}><Copy className="h-3 w-3" />复制链接</Button></div>{copied && <p className="mt-2 text-11 text-success">链接已复制；若浏览器禁用剪贴板，可手动选择链接。</p>}<Button className="mt-4" variant="primary" disabled={readonly || blockers.length > 0}><Send className="h-4 w-4" />发布问卷</Button></div><div className="flex aspect-square items-center justify-center rounded-lg border border-border bg-muted"><QrCode className="h-20 w-20" aria-label="二维码占位图" /></div></div></div><div className="divide-y divide-border rounded-lg border border-border bg-card">{[["访问方式","拥有链接的任何人可访问"],["答题身份","匿名"],["每人限答","每人仅可提交一次"],["截止日期","2026-09-01 23:59"],["提醒设置","每 3 天提醒一次，最多 3 次"]].map(([label,value]) => <div key={label} className="grid grid-cols-[9rem_1fr_auto] items-center gap-3 px-5 py-4 text-12"><span className="text-muted-foreground">{label}</span><span>{value}</span>{!readonly && <Button variant="ghost" size="xs">修改</Button>}</div>)}</div></section>
    <aside className="space-y-4"><div className="rounded-lg border border-border bg-card p-5"><SectionTitle title="回收质量规则" />{["必答核心题校验","重复答卷检测","完成时间阈值","开放题最小字数"].map((label) => <div key={label} className="mb-2 flex items-center justify-between rounded-md border border-border p-3 text-11"><span>{label}</span><Badge tone="primary">通过</Badge></div>)}</div><div className="rounded-lg border border-border bg-card p-5" data-testid="survey-publish-quality-summary"><SectionTitle title="回收质量概览" /><div className="grid grid-cols-4 gap-2 text-center"><Metric label="已回收" value={metrics.received} /><Metric label="有效样本" value={metrics.valid} /><Metric label="有效率" value={`${metrics.validRate}%`} /><Metric label="目标进度" value={`${metrics.completionRate}%`} /></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{ width: `${metrics.completionRate}%` }} /></div></div><Button className="w-full" variant="outline"><Send className="h-4 w-4" />发送测试邀请</Button></aside>
  </div>;
}
function Metric({label,value}:{label:string;value:string|number}){return <div><p className="text-10 text-muted-foreground">{label}</p><p className="mt-1 text-18 font-semibold">{value}</p></div>}
