"use client";
import * as React from "react";
import { Download, Flag, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { markResponseForReview, type SurveyMetrics } from "@/lib/survey/workflow-model";
import type { survey } from "@repo/contracts";
import { SectionTitle } from "./survey-workflow-shell";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";

export function ResponseReviewStep({ model, setModel, metrics, readonly }: { model: survey.SurveyWorkflowModel; setModel: React.Dispatch<React.SetStateAction<survey.SurveyWorkflowModel>>; metrics: SurveyMetrics; readonly: boolean }) {
  const [query,setQuery]=React.useState(""); const [selectedId,setSelectedId]=React.useState(model.responses[0]?.id ?? "");
  const rows=model.responses.filter((item)=>item.id.toLowerCase().includes(query.toLowerCase())||(item.submitter??"").includes(query)).slice(0,10); const selected=model.responses.find((item)=>item.id===selectedId)??model.responses[0];
  const roles=["高层管理者","部门负责人","普通员工"];
  return <div className="grid min-h-[calc(100vh-9rem)] grid-cols-1 2xl:grid-cols-[14rem_minmax(40rem,1fr)_24rem]">
    <aside className="border-b border-border bg-card p-4 2xl:border-b-0 2xl:border-r"><SectionTitle title="答卷与数据" /><div className="space-y-1">{[["全部答卷",metrics.received],["今日提交",12],["需复核",metrics.needsReview],["已通过",metrics.valid]].map(([label,count],index)=><button key={label} type="button" className={`flex w-full justify-between rounded-md px-3 py-2 text-12 transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${index===0?"bg-accent text-primary":"hover:bg-muted"}`}><span>{label}</span><span>{count}</span></button>)}</div><p className="mb-2 mt-6 text-11 font-semibold">按职级筛选</p>{roles.map((role)=><label key={role} className="flex items-center justify-between py-1.5 text-11"><span>{role}</span><span>{model.responses.filter((item)=>item.role===role).length}</span></label>)}</aside>
    <section className="p-5"><SectionTitle title="查看答题" /><div className="grid gap-3 sm:grid-cols-4"><Metric label="答卷" value={metrics.received}/><Metric label="完成率" value="100%"/><Metric label="平均用时" value={`${Math.floor(metrics.averageDurationSeconds/60)}分${metrics.averageDurationSeconds%60}秒`}/><Metric label="需复核" value={metrics.needsReview} danger/></div><div className="mt-4 flex flex-wrap gap-2"><div className="relative min-w-60 flex-1"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground" aria-hidden /><Input className="pl-8" aria-label="搜索答卷" placeholder="搜索答卷 ID / 提交者" value={query} onChange={(event)=>setQuery(event.target.value)}/></div>{["全部职级","全部员工规模","全部质量"].map((item)=><Button key={item} variant="outline" size="sm">{item}</Button>)}<Button variant="outline" size="sm">刷新</Button></div><div className="mt-4 overflow-x-auto rounded-lg border border-border" data-testid="survey-response-table"><Table className="w-full min-w-[48rem] text-left text-11"><TableHeader className="bg-muted"><TableRow>{["答卷ID","提交者","职级层级","员工规模","提交时间","用时","质量"].map((head)=><TableHead key={head} className="px-3 py-2 font-medium">{head}</TableHead>)}</TableRow></TableHeader><TableBody className="divide-y divide-border">{rows.map((item)=><TableRow key={item.id} onClick={()=>setSelectedId(item.id)} className={`cursor-pointer transition-colors duration-200 hover:bg-muted ${selectedId===item.id?"bg-accent":""}`}><TableCell className="px-3 py-2 font-medium text-primary">{item.id}</TableCell><TableCell className="px-3 py-2">{item.submitter}</TableCell><TableCell className="px-3 py-2">{item.role}</TableCell><TableCell className="px-3 py-2">{item.companySize}</TableCell><TableCell className="px-3 py-2">{new Date(item.submittedAt).toLocaleString("zh-CN")}</TableCell><TableCell className="px-3 py-2">{Math.floor(item.durationSeconds/60)}分{item.durationSeconds%60}秒</TableCell><TableCell className="px-3 py-2"><Badge tone={item.quality==="normal"?"primary":"warning"}>{item.quality==="normal"?"正常":"需复核"}</Badge></TableCell></TableRow>)}</TableBody></Table></div><div className="mt-4 flex items-center justify-between text-11 text-muted-foreground"><span>共 {model.responses.length} 条 · 每页 10 条</span><div className="flex gap-1"><Button size="xs" variant="primary">1</Button><Button size="xs" variant="ghost">2</Button><Button size="xs" variant="ghost">…</Button><Button size="xs" variant="ghost">7</Button></div></div></section>
    {selected&&<aside className="border-t border-border bg-card p-5 2xl:border-l 2xl:border-t-0" data-testid="survey-response-detail"><SectionTitle title="答卷详情" /><p className="text-10 text-muted-foreground">答卷 ID</p><p className="mt-1 text-18 font-semibold">{selected.id}</p><div className="mt-4 grid grid-cols-2 gap-3 text-11"><div><p className="text-muted-foreground">提交时间</p><p>{new Date(selected.submittedAt).toLocaleString("zh-CN")}</p></div><div><p className="text-muted-foreground">用时</p><p>{Math.floor(selected.durationSeconds/60)}分{selected.durationSeconds%60}秒</p></div></div><div className="mt-5 max-h-[32rem] space-y-2 overflow-y-auto">{selected.answers.slice(0,8).map((answer,index)=><div key={answer.questionId} className="rounded-md border border-border p-3"><p className="text-11 font-medium">{index+1}. {model.questions.find((item)=>item.id===answer.questionId)?.title}</p><p className="mt-1 text-11 text-muted-foreground">{Array.isArray(answer.value)?answer.value.join("、"):answer.value}</p></div>)}</div>{!readonly&&<div className="mt-4 grid grid-cols-2 gap-2"><Button variant="outline" size="sm" onClick={()=>setModel((current)=>markResponseForReview(current,selected.id))}><Flag className="h-3.5 w-3.5" aria-hidden />标记复核</Button><Button variant="outline" size="sm"><Download className="h-3.5 w-3.5" aria-hidden />导出单份</Button></div>}</aside>}
  </div>;
}
function Metric({label,value,danger}:{label:string;value:string|number;danger?:boolean}){return <div className="rounded-lg border border-border bg-card p-4"><p className="text-11 text-muted-foreground">{label}</p><p className={`mt-2 text-24 font-semibold ${danger?"text-destructive":""}`}>{value}</p></div>}
