"use client";
import * as React from "react";
import { GripVertical, Plus, Sparkles, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Toggle } from "@/components/ui/toggle";
import type { survey } from "@repo/contracts";
import { SectionTitle } from "./survey-workflow-shell";

export function SurveyDesignStep({ model, setModel, readonly }: { model: survey.SurveyWorkflowModel; setModel: React.Dispatch<React.SetStateAction<survey.SurveyWorkflowModel>>; readonly: boolean }) {
  const [selectedId, setSelectedId] = React.useState(model.questions[0]?.id ?? "");
  const [prompt, setPrompt] = React.useState("");
  const selected = model.questions.find((question) => question.id === selectedId) ?? model.questions[0]!;
  const update = (patch: Partial<typeof selected>) => setModel((current) => ({ ...current, questions: current.questions.map((question) => question.id === selected.id ? { ...question, ...patch } : question) }));
  return <div className="grid min-h-[calc(100vh-9rem)] grid-cols-1 xl:grid-cols-[22rem_minmax(28rem,1fr)_22rem]">
    <aside className="border-b border-border bg-card p-4 xl:border-b-0 xl:border-r" data-testid="survey-design-question-list"><div className="mb-3 flex items-center justify-between"><h2 className="text-14 font-semibold">问题目录（{model.questions.length}）</h2>{!readonly && <Button size="xs" variant="ghost"><Plus className="h-3 w-3" />新增问题</Button>}</div><ol className="space-y-1">{model.questions.map((question) => <li key={question.id}><button type="button" onClick={() => setSelectedId(question.id)} className={`flex w-full items-center gap-2 rounded-md px-2 py-2 text-left text-11 transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${selectedId === question.id ? "bg-accent text-primary" : "hover:bg-muted"}`}><span className="w-5 font-medium">{question.order}.</span><span className="min-w-0 flex-1 truncate">{question.title}</span><GripVertical className="h-3 w-3 text-muted-foreground" /></button></li>)}</ol></aside>
    <section className="p-5" data-testid="survey-design-question-editor"><SectionTitle title="问题编辑" description={`问题 ID：${selected.id}`} /><div className="rounded-lg border border-border bg-card p-4 shadow-sm"><div className="space-y-4"><div><Label htmlFor="question-title">问题内容</Label><Textarea id="question-title" className="mt-1" value={selected.title} disabled={readonly} onChange={(event) => update({ title: event.target.value })} /></div><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="question-type">题型</Label><Input id="question-type" className="mt-1" value={selected.type === "single" ? "单选" : selected.type === "scale" ? "量表" : "开放题"} readOnly /></div><div><Label htmlFor="question-chapter">所属章节</Label><Input id="question-chapter" className="mt-1" value={selected.chapterId || "未映射"} disabled={readonly} onChange={(event) => update({ chapterId: event.target.value })} /></div></div><div className="flex items-center justify-between rounded-md border border-border-subtle p-3"><span className="text-12">是否必答</span><Toggle checked={selected.required} onCheckedChange={(required) => update({ required })} label="是否必答" disabled={readonly} /></div>{selected.options.length > 0 && <div><Label>选项设置</Label><div className="mt-2 divide-y divide-border rounded-md border border-border">{selected.options.map((option, index) => <div key={`${selected.id}-${index}`} className="flex items-center gap-2 p-2"><span className="h-4 w-4 rounded-full border border-input" /><Input aria-label={`选项 ${index + 1}`} value={option} readOnly={readonly} onChange={(event) => update({ options: selected.options.map((item, itemIndex) => itemIndex === index ? event.target.value : item) })} />{!readonly && <Button size="icon" variant="ghost" aria-label={`删除选项 ${index + 1}`}><Trash2 className="h-3.5 w-3.5" /></Button>}</div>)}</div>{!readonly && <Button className="mt-2" size="xs" variant="ghost"><Plus className="h-3 w-3" />添加选项</Button>}</div>}</div></div></section>
    <aside className="border-t border-border bg-card p-5 xl:border-l xl:border-t-0" data-testid="survey-design-ai-assistant"><SectionTitle icon={<Sparkles className="h-5 w-5 text-primary" />} title="AI 助手" /><div className="rounded-lg bg-ai-tint p-4 text-12"><p className="font-medium">我是您的问卷设计助手</p><p className="mt-2 text-muted-foreground">我会基于行业实践提供可预览、可确认的优化建议，不会自动覆盖题目。</p></div><p className="mt-5 text-12 font-medium">您可以尝试</p><div className="mt-2 space-y-2">{["优化当前问题表述", "检查问卷逻辑与结构", "补充缺失的关键问题"].map((label) => <Button key={label} className="w-full justify-start" variant="outline" size="sm">{label}</Button>)}</div><div className="mt-5"><Label htmlFor="ai-prompt">告诉我您想优化的内容</Label><Textarea id="ai-prompt" className="mt-2" rows={7} placeholder="例如：请优化本章节的结构与问题顺序…" value={prompt} disabled={readonly} onChange={(event) => setPrompt(event.target.value)} /></div>{!readonly && <div className="mt-3 grid grid-cols-2 gap-2"><Button variant="outline" size="sm">重新生成章节</Button><Button variant="primary" size="sm">生成变更预览</Button></div>}</aside>
  </div>;
}
